### ISSUE TITLE
Display required field while logging in

### ISSUE THREAD

**Issue by govindgoel** [spotify/backstage#1002]
## Feature Suggestion
Display the required error message for the Github username and Token field whenever these are empty.
![Screenshot from 2020-05-25 22-26-21](https://user-images.githubusercontent.com/52847415/82831733-dd3a5900-9ed6-11ea-8541-46d3cfa5a464.png)

## Possible Implementation

Display error message whenever the field is empty
## Context
No error message defined to make the field as required

**Comment by BA1RY** [comment]
@stefanalund I'd like to work on this.
Also a question, should the error be displayed on clicking _Authenticate_ button or whenever the field is empty?

**Comment by stefanalund** [comment]
@soapraj @Rugvip can you help answer this?

**Comment by dtuite** [comment]
@BA1RY which method do you tend to prefer when you use the web and why?

If you're fixing this, and if it's not too much scope creep, I would suggest helping users understand what "Token" means. Is it a GitHub user password? Is it a personal access token? How do I get a personal access token? What scopes does it need?

**Comment by BA1RY** [comment]
@dtuite That's a valid point.
I would prefer to check when `onChange` is triggered.
For "Token", it would be better we could provide a hint below(if short) or have a link with "What is Token?" which triggers a popup with description. WDYT?

**Comment by dtuite** [comment]
@BA1RY That sounds good to me. I'd be interested to hear what others think too.

**Comment by soapraj** [comment]
Hi @BA1RY @govindgoel 

Thanks for raising the issue and discussing this.

This UI was a temporary solution to use Github Auth to build demo functionality. We don't plan to use this UI going forward and we have a popup based login flow being built at the moment.

You can follow the progress of our Auth work here https://github.com/spotify/backstage/milestone/8 and very soon we will have end-to-end auth flow working for Google and Github. 

Created a follow-up ticket to remove this page. I'll go ahead and close this issue if there are no other concerns.

**Comment by BA1RY** [comment]
Hi @soapraj . Yes, please go ahead.
