### ISSUE TITLE
Catalog: Convention based / dynamic catalog source location metadata

### ISSUE THREAD

**Issue by andrewthauer** [spotify/backstage#1013]
I've been following the progress of the catalog backend in regards to the `CatalogLocation` concept. I'm wondering if there are plans to have a location source type that can dynamically generate the metadata instead of fetching it directly?

## Context

For instance, my organization currently has a custom built catalog. It has a location map configuration file that points to github repos we want to track. It then has an ingestion process that uses a convention based approach to extract metadata (e.g. project description, codeowners file, etc.). It would be great if we could potentially leverage our existing infrastructure during a potential migration process to backstage.

## Feature Suggestion

Ability to use a convention over configuration model when possible for catalog locations rather then requiring a metadata file.

## Possible Implementation

Nothing concrete, but looking for opinions and/or possible plans that might allow for this sort of scenario / use case. Here are some potential options I've thought about:

- We could create a custom location source type that fetches from our catalogs API to bootstrap the configuration 
- The `GitHubLocationSource` could be updated to support a location to the repo and the queries the for metadata which in turn builds the metadata structure dynamically. The reader could possible support a custom metadata extractor that can be provide custom data.
- A push based model where the location refresh process is offloaded to something that pushes updates to the catalog.

**Comment by freben** [comment]
Hi! Good points - this is indeed on our radar. Let me look at it from a few different angles (some of which you mention yourself):

## New Backing Catalog

When the catalog plugin is started up, you give it a catalog implementation as a parameter. Currently there's only the `DatabaseEntitiesCatalog`. But you could make your own, that reads directly from your own catalog and just transforms the results into the shape that the output needs to be (like `DescriptorEnvelope`s)

## Multiple Backing Catalogs

There used to be - and I will probably reintroduce, now that you mention it - an `AggregatingEntitiesCatalog`, that basically takes a list of other catalogs and fetches them all in parallel and returns the aggregated results.

That way, you could use both the database based store if you want to migrate to that one slowly, and your own.

## Ingestion Into The Database Catalog

You could implement a source of your own that fetches from your catalog, transforms to our shape using any logic of your choice, and inserts it into the database based catalog. You might get a slight delay as changes propagate, but it is likely not a problem.

**Comment by stefanalund** [comment]
As many companies already have some mechanism of tracking software ownership, it should ideally be simple to hook it up to Backstage. Related discussion in https://github.com/spotify/backstage/issues/782

**Comment by dtuite** [comment]
Leaving a custom parser in place for any length of time would mean you have to update your parser to match any schema changes in the official Backstage schema. 

Probably better to write a migrator which ingests the legacy descriptor files and replaces them wholesale with the Backstage format. That way you can migrate once and be done with it. Of course, there is a potential issue there if you have key/value pairs in your legacy descriptor files which are not supported by the Backstage schema.

**Comment by freben** [comment]
The schema permits you to put extra data both directly in the `metadata` object, or in `metadata.labels` and `metadata.annotations`. Theoretically you could put things in the `spec` too, but that comes with a bit greater risk of colliding with official features and should probably be avoided if possible.

**Comment by Rugvip** [comment]
@dtuite That's assuming you don't have infrastructure that depend on the existing files though. Being able to ingest the legacy format could allow for a transition period where existing infra is moved to consume from the Backstage catalog service instead of the legacy descriptor files.

**Comment by dtuite** [comment]
Both good points!

**Comment by andrewthauer** [comment]
I think any of those options could work. As I mentioned in the context, we currently use a convention based approach to extract metadata via the GitHub API. So we do not have descriptor files aside from a single map to where all the service repos live.

On one side this is nice because it doesn't require maintaining additional files in repos. However, it has it's limits for the types of metadata that can be inferred and doesn't work great for monorepos. So moving to a descriptor file approach probably makes most sense in the long run. We also do have some in house tools to mass publish changes across repo's so this wouldn't be a huge lift.

However, for an initial trial / pilot of backstage (e.g. #782), something to bootstrap using our existing setup would be a great benefit. I suspect the custom source location that reads from our existing catalog would probably be the easiest way to get up and running in our case.

**Comment by Rugvip** [comment]
Even though it's a bit different, https://github.com/spotify/backstage/pull/1890 is somewhat related to this

**Comment by andrewthauer** [comment]
@Rugvip - I'm good closing this and re-opening if needed. As I was following the progression of the catalog. I think using conventions alone won't allow us to take full advantage of various features. So will most likely go with a `yaml` file approach anyways. There also seems to be a enough hooks in the API to accomplish various approaches as well if needed.
