### ISSUE TITLE
Extra , rendered on all pages

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#1028]
## Current Behavior

Something introduced an extra , in one of the core components:

<img width="447" alt="Screenshot 2020-05-27 at 10 38 42" src="https://user-images.githubusercontent.com/190856/82997164-508eb880-a006-11ea-9343-3f855706d738.png">

**Comment by Mutugiii** [comment]
@stefanalund I would like to quickly patch this up

**Comment by stefanalund** [comment]
Thanks @Mutugiii -- assigned you!

**Comment by Mutugiii** [comment]
All done @stefanalund
