### ISSUE TITLE
PUBLIC_URL no more resolved with homepage when using bundle command

### ISSUE THREAD

**Issue by o0Djeen0o** [spotify/backstage#1033]
Hi, 
I've migrated to release 0.1.1-alpha6 (with some troubles, as the build has completely changed from previous version ^^), and I'm no more able to start a bundled site. `%PUBLIC_URL%` reference (contained in `index.html` public folder of the package app) was previously using the `homepage` property in `package.json` file (probably coming from create react app, or is it a webpack option ?)

It seems to be no more the case. Now when bundling, property is just replaced by empty string, which leads to a broken site.

## Expected Behavior

`%PUBLIC_URL%` id replaced at bundle time by `homepage` property, or another property documented.

## Current Behavior

No replace, site is broken if not started on root location (`/`)

## Possible Solution

Restore a proper template mechanism for such property, or help find if something changed from previous release

## Your Environment

Using `0.1.1-alpha6`

**Comment by Rugvip** [comment]
It was something that create-react-app was providing. I'd say that the new solution for this will be based on the output of https://github.com/spotify/backstage/issues/1012

Do you need a stopgap solution for now or do you have a workaround?

**Comment by o0Djeen0o** [comment]
Thanks for the update @Rugvip.

Right now I can modify the `index.html` by hand/script, it is not a huge work, but it also depends of the estimated time when a new solution will be proposed for this issue.

**Comment by Rugvip** [comment]
@o0Djeen0o We'll want a solution in place in at most one or two weeks, there's plenty of ongoing work that needs the feature.

**Comment by Rugvip** [comment]
Some more details brought up by in #1106

**Comment by Pajn** [comment]
Sorry for not searching for duplicates first.

It seems like I'm able to workaround this with these two in our pipeline:
```
sed -i "s#publicPath: '/',#publicPath: process.env.PUBLIC_URL || '/',#" node_modules/@backstage/cli/dist/lib/bundler/config.js
sed -i "s#const plugins = new Array()#const plugins = [new webpack_1.default.DefinePlugin({'process.env.PUBLIC_URL': JSON.stringify(process.env.PUBLIC_URL)})]#" node_modules/@backstage/cli/dist/lib/bundler/transforms.js
```

Though I would love a nicer solution :) I'm holding my thumbs that will pass the review as a temporary measure.

As you can see from the replacements, our needs is to set both the `output.publicPath` property in the webpack config and to define an environment variable to be used inside the code (to set up router base path as well as oauth rediects).

**Comment by o0Djeen0o** [comment]
@Rugvip Just a short question: I'm working for a dev tool which can start on any port number, meaning that I don't know final origin url (`http://localhost:3000`), only the base url where ui will be exposed (`/myApp/...`). Will it be OK to only pass the homepage path, like previously with webpack property ?

**Comment by Rugvip** [comment]
@o0Djeen0o The origin will likely be needed for auth to work, but I think either just specifying the path or using a dummy origin should make the rest work.

**Comment by o0Djeen0o** [comment]
@Rugvip Thanks for the hard work! When do you think you may test the modifications with a new alpha release? It will be great to test the feature + some other nice additions from previous release.

**Comment by o0Djeen0o** [comment]
@Rugvip I've successfully migrated to latest release and everything is working as expected. Thanks !
