### ISSUE TITLE
Be able to reuse the database setup in multiple backends

### ISSUE THREAD

**Issue by ljupchokotev** [spotify/backstage#1034]
## Context

Currently, the catalog backend has the functionality to work with a database. This functionality should be refactored so that it can be reused in any backend that requires a database. It should be possible to have a very simple way of getting a connection to the database and possibly run migrations as needed per backend.

**Comment by freben** [comment]
Hi! That could be useful. The feature surface is pretty small at this point; it would probably mainly be about a convention of where to put migration files, that are found and run automatically relative to the package root. Would you agree? The rest of it is in making the actual database connection, which happens in the backend package itself, and that's purely config.

**Comment by ljupchokotev** [comment]
Yes, that should be fine for the migrations as a start. 

As for the database connection, should each backend specify its own connection using Knex or is it better to refactor that out to Backstage core and allow backends to request a database connection from Backstage core when needed? It will be easier if a backend doesn't need to specify anything regarding the database and can just request a connection on demand from core.

**Comment by freben** [comment]
Maybe! Would that work well with how database administrators want to manage things in a stricter org? Each plugin will want to act within their own isolated logical database, and I believe the creation of those will then happen by hand out of band. Is that a reasonable assumption? In that case there needs to be a way for the user to set their backend to somehow map plugin connection requests to the right underlying database.

**Comment by Rugvip** [comment]
Let's continue this discussion in #1598
