### ISSUE TITLE
Make metadata.name mandatory

### ISSUE THREAD

**Issue by freben** [spotify/backstage#1036]
The metadata.name field is optional in the current entity schema. That has also led to the metadata blob being non-mandatory too. This is an unnecessary complication.

Make the metadata blob mandatory, and make the name mandatory. Adjust both the TS types and the validation accordingly.

**Comment by Nek** [comment]
API consumption implementation depends on this one. Let me do it all together. I'm talking about this https://github.com/spotify/backstage/issues/984
