### ISSUE TITLE
Solve sub routing for ComponentPage

### ISSUE THREAD

**Issue by nikek** [spotify/backstage#1042]
We need a mechanism for sub routing on the ComponentPage. Plugins like Builds, Deployments, Monitoring etc. will need a way to register their page components onto the ComponentPage sub router.

Suggest solution below before implementing.

**Comment by Rugvip** [comment]
I think we're confident enough and still API-unstable enough that we can bring in the react-router v6 alpha, as that seems to solve a lot of these problems for us.

**Comment by stefanalund** [comment]
@Rugvip @benjdlambert now that https://github.com/spotify/backstage/pull/1171 has landed, how do you think we should proceed with this issue?

**Comment by benjdlambert** [comment]
I'm not sure of the next steps, I think it would be to create tickets to implement the new tabs and routing for the tab.

**Comment by stefanalund** [comment]
Since this seems to be a bigger topic I'm moving it to post Alpha.

**Comment by shmidt-i** [comment]
Solved by #2076
