### ISSUE TITLE
Auth Frontend: Sidebar to have auth state

### ISSUE THREAD

**Issue by soapraj** [spotify/backstage#1044]
Sidebar should have a place where users can see the different auth options, auth state( if they are logged in or not ) and a link to logout.

**Comment by marcuseide** [comment]
Let's try mimic the way it looks internally for now and work on final design later on.

**Comment by stefanalund** [comment]
Fixed in #1140

**Comment by Rugvip** [comment]
@stefanalund, not quite, we decided to merge the PR and do the rest in a followup :p
