### ISSUE TITLE
Auth Backend: Refactor Google provider to reduce dependency on passport

### ISSUE THREAD

**Issue by soapraj** [spotify/backstage#1054]
PassportJS is a black box when it comes to using it as a middleware and handling errors so refactor to get more control over error flow and reduce dependency on passportJS.

- use passport only for the provider strategy
- remove the need for middlewares in auth-backend/service/router.ts

**Comment by Rugvip** [comment]
I can pick this up!

**Comment by Rugvip** [comment]
:trollface:
