### ISSUE TITLE
Persist User Settings

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1060]
Users should be able to add things to a persistent storage that can be used around backstage for other things. Like starring items for use in the catalog view.

## Feature Suggestion
- Be able to save things in local storage a la backstage internal

## Possible Implementation
- Eventually these things should be stored with the `userId` in a backend service, but right now as we don't have a way to generate a user token to store this with server side, lets just use local storage for most of the implementation. Will just lift and shift the `localStorage` implementation from Backstage internal

Dependant of #990

**Comment by benjdlambert** [comment]
@stefanalund should address https://github.com/spotify/backstage/issues/990#issuecomment-633672981

**Comment by Rugvip** [comment]
Would love to find a good interface for this API that also support async storage. Internally we have this split into sync and async APIs. They're not too different though, and they sync one still supports async updates from other sources. The problem with the async one is page load flickering, so I'm thinking a hybrid approach where you can have async storage with localStorage cache, but making the API fully async.

**Comment by benjdlambert** [comment]
@Rugvip agreed. Hooks give us a lot of flexibility in this sense, as that the API can stay synchronous, but we can re-render components that subscribe to different keys in the store when async data comes in. I've taken a stab at moving across the simple local storage version from internal for now, and we can build upon it
