### ISSUE TITLE
Make DismissibleBanner persistently dismissed

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#1153]
## Feature Suggestion

Use the new storage API to save the dismissed state permanently, so that the same dialog is not shown more than once.

`import { useApi, storageApiRef } from '@backstage/core';`

## Possible Implementation

Example of usage in https://github.com/spotify/backstage/pull/1143/files#diff-6dba8b9dac99065b066d81e6e8e22a98R17

## Context

Clicking this button currently does not permanently dismiss the banner. 

![Screenshot 2020-06-05 at 08 54 23](https://user-images.githubusercontent.com/190856/83846036-3e013700-a70a-11ea-8325-ea03cc62e4ad.png)

**Comment by benjaminr** [comment]
@stefanalund happy to have a go at this one.

**Comment by stefanalund** [comment]
@benjaminr great! I’ve assigned you.

**Comment by stefanalund** [comment]
Closed in https://github.com/spotify/backstage/pull/1168

**Comment by ahmm16** [comment]
Hey guys! 

Do you know how I can make it so that even if the user closes the banner, it appears every time the user logs in again?

**Comment by ahmm16** [comment]
@stefanalund @benjaminr @aizatto @chap
