### ISSUE TITLE
Better catalog example entities

### ISSUE THREAD

**Issue by freben** [spotify/backstage#1167]
The catalog-backend has two example yaml files that can be imported. They are very minimal and mock-like. 

Replace them with one single file that has a believable set of entities, preferably around ten of them. Their names could for example be similar to some system of things inside Spotify, or at least be nicely chosen.

The end result should be that after import, the UI in Backstage is nice to view for example during a demo or when evaluating the catalog or Backstage itself.

**Comment by stefanalund** [comment]
Thanks! This is very important. Maybe we even have an empty state with a button that registers these example components. Let’s treat that as a separate issue in any case.

**Comment by stefanalund** [comment]
Fixed in #1245
