### ISSUE TITLE
[RFC] Documentation structure

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#1174]
## Need

Backstage is currently poorly documented. The existing documentation lacks a clear structure making it hard to get an overview. This RFC outlines a suggested structure for the docs we want to have. It does not propose the actual contents.

## Proposed solution

Suggested TOC:

- What is Backstage?
  - Introduction
  - Main concepts
  - Architecture
- Getting started
  - Installation
  - Running Backstage locally
  - Production deployments
    - Create an App
    - App configuration
      - Configuring App with plugins
      - Customize the look-and-feel of your App
    - Deployment scenarios
- Features
  - Software Catalog
    - System model
    - YAML File Format
    - Extending the model
    - External integrations
  - Scaffolding service
    - Configure templates
    - Adding templates
  - Authentication and identity
- Plugins
  - Creating a new plugin
  - Developing a plugin
  - Backends and APIs
    - Proxying
    - Backstage backend plugin
    - Existing API
  - Designing for Backstage
    - Backstage Design Language System (DLS)
    - Storybook -- reusable UI components
    - Figma resources
  - Testing
  - Publishing
    - Open source and NPM
    - Private/internal (non-open source)
- API references
  - JavaScript/TypeScript API
  - Backend APIs
- Tutorials
  - How to do X
  - How to do Y
- Architectural Decision Records (ADRs)
- Contribute
- Support
- FAQ

## Implementation

These docs should be stored in the `/docs` folder and be published to `backstage.io/docs`.

## Questions

* Should "Service Catalog", "Identity" and "Scaffolding service be grouped together?
* Do we need a more clear separation between frontend and backend?

**Comment by Rugvip** [comment]
I think the identity, catalog, scaffolding etc. bits could use dedicated docs from the point of view of a plugin author, probably under the plugin section. Things like "Associating Plugin Data with Entities in the Catalog" and "Forwarding the User's Identity to a Backend Plugin". Then we can keep the rest of the docs of those things completely focused on the implementation and extension of those services for teams handling the integration of Backstage. And with that also put them in a section of the docs that are focused on running and integrating Backstage as opposed to building plugins.

My hunch regarding separation of frontend and backend is that it fits better to put the separation in sub-sections rather than the top-level.

**Comment by dtuite** [comment]
Also, massive +1 to this idea in general. It honestly took me a few hours of struggling around trying to run the service catalog before I realized there were docs in the `packages/backend/README.md`. The docs are too distributed at the moment (from a user perspective).

**Comment by stefanalund** [comment]
@Rugvip @soapraj think it makes sense to have a specific section for Auth?

**Comment by stefanalund** [comment]
> This part might need expansion. Getting started locally (yarn start...) is quite different than "Getting started with deploying Backstage in my company...". With the latter, you end up doing `backstage/cli create-app` etc.

@dtuite I choose to put these further down in the "Production deployments" section. My thinking is that this step is quite a lot later in the process. The assumption being that one would do that after understanding what Backstage is, and how to build a plugin.

As I'm writing this, however, I'm kind of changing my mind 😄 Even if building plugins is important, I wonder if it's not more important to get people up and running with the built-in features of Backstage? 🤔 In that case explaining the Software Catalog (and how to populate it with components) as well as other things like Identity and Scaffolding may be more important.

In any case, I'm adding a subsection for "Configuring your Backstage with plugins".

**Comment by dtuite** [comment]
> I wonder if it's not more important to get people up and running with the built-in features of Backstage? 🤔 In that case explaining the Software Catalog (and how to populate it with components) as well as other things like Identity and Scaffolding may be more important.

This is my thinking. Reducing the time to value is key. There's no way I'm going to invest hours into building custom plugins if I haven't yet seen how Backstage can provide value for my organization. I want to start with built-in plugins as quickly as possible, see some early value, then start customizing.

**Comment by stefanalund** [comment]
@dtuite thank you -- this was really valuable input 🙏 

I've update the TOC now. The main change is de-emphasising plugin development docs in favour of promoting what I tentatively call "Features". These would be the out-of-the-box features you get once you successfully installed and deployed Backstage. Let me know what you think! 💯

**Comment by EXPErdelfavero** [comment]
Connecting my work Github identity with my Discord comments earlier today. I'm "DelfCo" over there.

Reading the discussion here, I think you're going the right way by walking us through the built-in features before you walk us through building a plugin. I'm a tech writer, been doing Docs as Code for the last 5-6 years, and I'm keenly interested in seeing how `techdocs` works. Am I correct in understanding that it's one of the things you're calling "Features"?

**Comment by brucek9** [comment]
@stefanalund I also think that Release versions should be included in this docs, as well as known issues with Backstage?

With features, does it mean that it is out-of-the-box things which the organization can start to use, develop on top of it right away after deploying Backstage?

**Comment by stefanalund** [comment]
> I'm keenly interested in seeing how techdocs works. Am I correct in understanding that it's one of the things you're calling "Features"?

@EXPErdelfavero yes, we are consider TechDocs as being a core feature of Backstage (even if it is built as a plugin).

> @stefanalund I also think that Release versions should be included in this docs, as well as known issues with Backstage?

@brucek9 I think we will keep using https://github.com/spotify/backstage/releases for releases, but link to it from our docs.

> With features, does it mean that it is out-of-the-box things which the organization can start to use, develop on top of it right away after deploying Backstage?

Yes, exactly.
