### ISSUE TITLE
Add missing metadata fields to header

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#1195]
The catalog entities page should have the following 2 `HeaderLabels`:

* Owner
* Lifecycle

(Not Tier -- that is not yet supported)

![Screenshot 2020-06-08 at 14 19 24](https://user-images.githubusercontent.com/190856/84029710-1e307400-a993-11ea-9852-306013884591.png)

**Comment by benjdlambert** [comment]
This data can be mocked for now, as the real data is currently blocked on work with the identity and catalog stuff.

Something like the following would be good for now I think..

```jsx
<HeaderLabels>
    <HeaderLabel title="Owner" value="tools" />
    <HeaderLabel title="Service Tier" value="Tier 1" />
    <HeaderLabel title="Lifecycle" value="production" />
</HeaderLabels>
```
