### ISSUE TITLE
How to handle svg files ?

### ISSUE THREAD

**Issue by o0Djeen0o** [spotify/backstage#1202]
Hi,

I'm trying to use a third party library which needs its own css file to be loaded. The css is requiring some svg files. However, svg is right now not supported with current cli webpack configuration:

```
my-project: ERROR in <project-path>/node_modules/jsoneditor/dist/img/jsoneditor-icons.svg 1:0
my-project: Module parse failed: Unexpected token (1:0)
my-project: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
my-project: > <?xml version="1.0" encoding="UTF-8" standalone="no"?>
my-project: | <svg
my-project: |    xmlns:dc="http://purl.org/dc/elements/1.1/"
``` 

This is probably due to transform configuration:
https://github.com/spotify/backstage/blob/master/packages/cli/src/lib/bundler/transforms.ts

which would need the https://webpack.js.org/loaders/svg-inline-loader/

## Feature Suggestion

It would be great to have a way to override default cli configuration for such cases.

If not possible, it would be great to have a support for svg files, as we cannot always encapsulate an svg object into a react element.

Also maybe I'm missing some knowledge here regarding a backstage project configuration, or webpack. If it is the case, a pointer to some documentation would help next users to resolve such kind of issues.

Thanks for your helps and best regards.

**Comment by Rugvip** [comment]
We can most likely just add SVGs to the `url-loader` for now. Internally we have some tooling around icons that allows you to import SVG icons directly as MUI `SvgIcon` components, which is pretty handy, and something we want to bring that into this project. I don't think we'll ever not want to support plain SVGs though, so most likely we'll find some separate convention around icons.
