### ISSUE TITLE
RFC: Network Request Mocking with MSW

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1205]
# Context
Network request mocking can be a total pain sometimes, in all different types of tests, unit tests to e2e tests always have their own implementation of mocking these requests.
There's been traction in the outer community towards using this library to mock network requests by using an `express` style declaration for routes. `react-testing-library` suggests using this library instead of mocking `fetch` directly wether this be in a browser or in `node`.

# Proposal
https://github.com/mswjs/msw is a library that helps you mock network requests in a browser using `ServiceWorkers` and has the same implementation for `node` using `interceptors`.

It has great support for `REST` API's, but interestingly provides local `resolvers` for GraphQL.

These mocks that you create can be standalone and re-used for all testing frameworks, which means that we can have a single source of truth for mock data, rather than it being distributed across the repository for different levels of testing.

We could for instance create test data in unit tests, and then re-use this test data in things like Storybook or e2e tests, which ensures that the same data yields the same result regardless of testing level or where you use the components for instance.

# Example
Instead of using `jest-fetch-mock` to mock the `fetch` API, we could move to something more declarative and re-use these definitions.

```ts
import { setupWorker, rest } from 'msw'

const worker = setupWorker(
  rest.get('*/user/:userId', (req, res, ctx) => {
    return res(
      ctx.json({
        firstName: 'John',
        lastName: 'Maverick'
      })
    )
  })
)

// Start the Mock Service Worker
worker.start()
```

See https://testing-library.com/docs/react-testing-library/example-intro#full-example for more usage with `jest` + `react-testing-library`

Thoughts?

**Comment by Rugvip** [comment]
👍  , looks pretty awesome compared to mocking fetch mocks. [Full example](https://testing-library.com/docs/react-testing-library/example-intro#full-example) looks pretty clean, and ofc it's Dodds approved.

Pilot with some tests for the catalog perhaps?

**Comment by benjdlambert** [comment]
@Rugvip interestingly enough I was going to do a comparison with the catalog but there wasn't any tests for the API part so maybe I can give it a go with this and we can see how it looks and behaves!

**Comment by freben** [comment]
Please do, this looks great.

**Comment by benjdlambert** [comment]
Put something together in #1221

**Comment by stefanalund** [comment]
@benjdlambert this is fixed, correct?

**Comment by benjdlambert** [comment]
Yep I just need to create an ADR for this. Can fix this today and and close the ticket

**Comment by benjdlambert** [comment]
Closing in favour of the ADR here: #1630
