### ISSUE TITLE
Update catalog list table columns

### ISSUE THREAD

**Issue by freben** [spotify/backstage#1207]
The catalog list table view needs updating.

See [this blog post](https://backstage.io/blog/2020/05/22/phase-2-service-catalog) for inspiration.

- [ ] Remove the "kind" column
- [ ] Add an "owner" column
- [ ] Add a "lifecycle" column

Use mocked data or empty if #983 is not complete, otherwise read from the entity.

I think we will leave the rest for now. I am unsure about the amount of physical space available for tags, for example.

**Comment by stefanalund** [comment]
Duplicate of https://github.com/spotify/backstage/issues/1206
