### ISSUE TITLE
Add catalog empty state with "add example data" button

### ISSUE THREAD

**Issue by freben** [spotify/backstage#1208]
Make a nicer empty state of the catalog list view. Add a button in it, that lets the user add some example data (i.e., registering a set of entities from github, in the [catalog backend fixtures](https://github.com/spotify/backstage/tree/master/plugins/catalog-backend/fixtures) directory and refreshing the view). This helps users evaluate the product easily without having to resort to curl commands.

**Comment by Timunas** [comment]
Hi @freben does this still apply? I was checking the catalog table when no records exist it shows no records to display message and if one clicks create a component he would be redirected to the scaffolder page where we can register an existing component by pointing to a github component yaml file. Would this be enough or do you have something different in mind?

**Comment by stefanalund** [comment]
@Timunas we were thinking there would be a “Add example components” button instead of just a message. 

Clicking the button would do the equivalent of running the “mock-data” script, i.e. register a list of sample components.

**Comment by twishasaraiya** [comment]
Hi @freben, I would like to take this up and give it a try.

**Comment by freben** [comment]
Sure, thanks! Assigned you now.

**Comment by twishasaraiya** [comment]
Hi @freben, I am thinking of doing the following steps
1. Create a state for `entities`
```ts
  const [entitiesState, setEntitiesState] = useState<Entity[]>([]);
```
2. Add a conditional button(besides `create component` that shows only when `entities` are empty
```ts
<Button
                onClick={addMockData}
                variant="contained"
                color="primary"
              >
                Add Example components
              </Button>
```
3. Define `addMockData` function which does the same a `yarn lerna run mock-data`
     a. Loop through static array
     b. For each, call `catalogApi.addLocation`
     c. Set the `entitiesState`

Let me know if it sounds good. I am new to React, so it would be great if you could point me in the right direction.

**Question**
1. How should I update the `CatalogFilter` card with proper number for `Owned, Starred and All` once the example components get added? 
![Screenshot from 2020-08-03 20-10-59](https://user-images.githubusercontent.com/24837027/89194975-b9c21780-d5c5-11ea-99c4-645be5973eb4.png)

**Comment by stefanalund** [comment]
@twishasaraiya go for it!

**Comment by stefanalund** [comment]
Done
