### ISSUE TITLE
Refine Tech Radar Plugin Code Quality & Style

### ISSUE THREAD

**Issue by NWCalvank** [spotify/backstage#1222]
In [Issue 661](https://github.com/spotify/backstage/issues/661) the Tech Radar component files were updated to use TypeScript & React Hooks.

This transition was done while keeping the code changes to a minimum. As a result, there are a number of code style concerns and somewhat strange typings that have resulted.

The goal of this issue would be to clean those up.

## Feature Suggestion

Review the Tech Radar files to address these style concerns:
- Inconsistent function naming
- Functions that are unnecessarily prefixed with `_`
- Bloated functional components
- Other formatting/stylistic inconsistencies, etc.

Review the Tech Radar files to address these code quality concerns:
- Removing type safety hacks or excessive null checks
- Adding unit tests, where possible

## Possible Implementation

The `Props` type definitions likely need to be narrowed to remove `null`/`undefined` union types. Many of the child components treated these values as always-present prior to the TypeScript migration, so it will be necessary to update the callsites to provide all of the required `Props`.

Removing the presence checks for many of the `Props` will likely go a long way to cleaning up these components.

## Context

[Original Issue for the TypeScript migration](https://github.com/spotify/backstage/issues/661)
[TypeScript Migration PR](https://github.com/spotify/backstage/pull/1080)

**Comment by ayshiff** [comment]
Can I take this one ? 👍

**Comment by stefanalund** [comment]
@ayshiff absolutely, assigning you!
