### ISSUE TITLE
Auth: bad chars in username

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#1229]
## Expected Behavior

International characters are not shown correctly immediately after loggin in:

<img width="224" alt="Screenshot 2020-06-10 at 12 41 38" src="https://user-images.githubusercontent.com/190856/84269151-19052d80-ab29-11ea-9b18-a1657de4835d.png">

After reloading the page it works as intended though:

<img width="310" alt="Screenshot 2020-06-10 at 14 44 42" src="https://user-images.githubusercontent.com/190856/84269153-199dc400-ab29-11ea-9ea8-b871e9685e86.png">

**Comment by daniel-j-davis** [comment]
Is it possible that this is some browser-specific issue, @stefanalund? I was looking into this briefly last night but was having trouble reproducing. 

I'm running:
```
Google Chrome: 83.0.4103.106
OS: macOS Version 10.15.4 (Build 19E287)
```

**Comment by freben** [comment]
@ellieseastream did you do anything special to alleviate this problem that you had in google hangouts as well?

**Comment by ellieseastream** [comment]
> @ellieseastream did you do anything special to alleviate this problem that you had in google hangouts as well?

@freben I just did a renaming in Personal Info Settings on my Google account, that's all.

**Comment by freben** [comment]
@stefanalund Let us know if this still is a problem or if the ticket should be closed.
