### ISSUE TITLE
Add support for Okta SSO

### ISSUE THREAD

**Issue by murtadha** [spotify/backstage#1237]
## Feature Suggestion

We want to be able to use Okta with Backstage since that's the identity provider backing our SSO.

## Possible Implementation

Looks like there are possible modules available that might facilitate this integration:
https://github.com/techstars/passport-okta-oauth
https://github.com/jaredhanson/passport-openid

**Comment by nspirrello** [comment]
I can work on this if it's still available

**Comment by stefanalund** [comment]
Thanks @nspirrello -- assigned you! 💯

**Comment by nspirrello** [comment]
#1455 PR for this feature

**Comment by Rugvip** [comment]
Fixed by #1455!
