### ISSUE TITLE
Bug: GitOps Cluster plugin does not start

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#1259]
<img width="1440" alt="Screenshot 2020-06-11 at 21 00 48" src="https://user-images.githubusercontent.com/190856/84428412-b1350c80-ac26-11ea-99c8-f2f7912e9553.png">

@chanwit this happens when I click the plugin from the /explore page (on localhost).

**Comment by chanwit** [comment]
acked.

I'll take a look.
Did you run the gitops-api backend on port 3008?

**Comment by stefanalund** [comment]
@chanwit no I did not -- which is most definitely the issue here. But nonetheless the plugin should fail a bit more gracefully 😏

**Comment by chanwit** [comment]
@stefanalund yep sure. it should say that it expects the backend to run and probably provides some info how to run it.

I'll work on this fix :-)
