### ISSUE TITLE
Support Go remote module import syntax for catalog locations

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1279]
## Feature Suggestion

Standardize on supporting the [Golang way of importing remote modules](https://golang.org/doc/code.html#ImportingRemote) for catalog locations.

The syntax is more or less: `<host>/<repo-path>/<file-path>`. For example `github.com/spotify/backstage/app-config.yaml`, where `github.com` is the repo hosting provider, `spotify/backstage` is the repo path, and `app-config.yaml` is the file path. We could support this syntax without having to declare an explicit `type` for the location as well, and just determine it based on the host.

## Possible Implementation

We probably end up needing custom logic for each hosting provider, at least it makes sense to start out there. So to begin with we'd only support `github.com` as the host part, and we'd expect the 2 first path components to be the repo path.

I haven't dug into the Go logic for determining the location, but it's possible that there's something there that we can re-use.

## Context

Discussion in https://github.com/spotify/backstage/pull/1276#discussion_r439740243

**Comment by freben** [comment]
With "standardize", do you mean that this would be the normalized form that we always convert to and store, no matter what form the user used originally?

And maybe I'm reading too much into it, but did you mean to stop with the `type` field entirely and instead deduce it based on the target? Because if so, I'm wondering if it'll really work out when a large number of (even close source custom) types of location are added as time goes on.

**Comment by Rugvip** [comment]
Main use-case for this would be to allow it to be entered in manually created Location/LocationRef entities, as the full URLs are a bit tedious to handle. I do think we probably need some normalized form to store too, it's possible that this might be a good candidate. And nah I still think we should have type, but I guess this could be put under a repo/remote/url type or something generic like that. It could also be the default type, so a Location entity would often just have a targets field with a couple of easy to parse (for the eyes) URLs.

I do think it could also be a good starting point for handling different types of input in the register component input field. Atm we assume it's github, but I think we'll have to deduce that based on the host, which will probably use logic similar to this.

**Comment by freben** [comment]
I think the main way of entering the target value - both in the gui and in files - will be to copy the url from a browser.

**Comment by Rugvip** [comment]
Would be about making reading existing files nicer, as well as mixing different types of hosts.

Closing this for now anyway, don't think it's worth adding atm.
