### ISSUE TITLE
Support dense table property in Table component

### ISSUE THREAD

**Issue by alexef** [spotify/backstage#1283]
## Feature Suggestion

The backstage/core Table already supports `padding="dense"`, but when set, it is ignored, the table looks exactly the same.

## Possible Implementation

This might be related to the hardcoded cell styles here: https://github.com/spotify/backstage/blob/master/packages/core/src/components/Table/Table.tsx#L104

## Context

The Table that comes with Backstage is great, but being able to display dense data would be even better.

**Comment by stefanalund** [comment]
Thanks for reporting @alexef

**Comment by marcuseide** [comment]
@ ellieseastream want to pick this up as a good first issue?

**Comment by raihle** [comment]
Seems this doesn't quite work with the "select all" checkbox, which normally has a different size in dense mode but gets overridden by Backstage to always be "normal".
