### ISSUE TITLE
Scaffold Component Template List

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1298]
## Feature Suggestion

![Screenshot 2020-06-15 at 13 40 49](https://user-images.githubusercontent.com/3645856/84653551-ea62ca80-af0d-11ea-9674-84b9c099be7b.png)

Should be update to look something more like the designs.

- Update the card listings with the new waves/headers defined by component type (Service, Website, etc)
- Render the real life data from the backend rather than stubbed data.

## Possible Implementation
![](https://user-images.githubusercontent.com/190856/77178005-c33f5d00-6ac6-11ea-8774-016f3d600a2d.png)

**Comment by wesleyyee** [comment]
@benjdlambert should this ticket include the work of adding in a `scaffolderClient`? Otherwise not much to do here esp since we still need the svg assets

**Comment by benjdlambert** [comment]
Not part of this ticket, but it comes under #725 

Do we not have the SVG assets in Figma for this view. @stefanalund @katz95?
