### ISSUE TITLE
Simple Create Component Wizard for Creating Component

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1299]
We want a simple way to enter user variables in a form and be able to start creation of the scaffolder with the entered user variables.

For an MVP, we agreed that we don't need to implement form validation right now, maybe we just have one step in the wizard right now which would be the `componentName` which would then be passed to the

`/v1/jobs` POST request to the `scaffolder` backend.

## Feature Suggestion
- We need another page which can take a parameter of the `templateId`
- Fetch the template details like name an and description from the Service Catalog
- Render a simple `Component Name` field using `mui`
- POST the simple variables to `/v1/jobs` and take the `id` returned to `poll` for events using `/v1/job/:jobId` until success.
- Once complete, navigate to the service catalog page with the new component

## Possible Implementation
- Route could live at `/create/:templateId`
- Also need to pass through `GITHUB_ACCESS_TOKEN` to the `/v1/job` POST, so that we can create the github repo and push the cookiecutter templating
*design to come*

**Comment by wesleyyee** [comment]
@benjdlambert hey were you looking for someone to pick this up? i have some time today if so

**Comment by benjdlambert** [comment]
Hey - yes go ahead!

@katz95 might have some designs for you - haven't pinged her about this yet.

The backend is still up in the air, so maybe just ignore that part for now and just build the step wizard and simple form for now. Hopefully we will either have a mock backend for you to hook it up with or the real thing in the next few days!

But would be good to get this work started on
