### ISSUE TITLE
GitHubReaderProcessor cannot process branch names with "/" in them

### ISSUE THREAD

**Issue by shmidt-i** [spotify/backstage#1315]
https://github.com/spotify/backstage/blob/0ba4cca3c8dbffe95b8877a2bf14c3704afce02c/plugins/catalog-backend/src/ingestion/processors/GithubReaderProcessor.ts#L63-L95

Currently we are just splitting the URL by "/", need more sophisticated way of getting the raw GitHub URL.

**Comment by daniel-j-davis** [comment]
@shmidt-i I'm interested in this issue. I'm wondering whether or not it's just as simple as using two calls to `.replace` on the string, something like this...

``const githubUrl = 'https://github.com/a/b/blob/master/c.yaml';``
``const rawUrl = githubUrl.replace('/blob/', '/').replace('//github.com/', '//raw.githubusercontent.com/');``

seems to output the correct URL (`https://raw.githubusercontent.com/a/b/master/c.yaml`) for the example provided in the file, but let me know if there's any case where you think this might not work?

**Comment by freben** [comment]
What if the branch name is `blob/blob`? ;) I think some form of a robust regex may work here.

**Comment by Rugvip** [comment]
It also becomes a bit of a non-issue once we start using the API for fetching yamls instead. It's the method that GitHub recommends, but requires authentication.

**Comment by daniel-j-davis** [comment]
From memory, `.replace` only replaces the first instance of the string, and the branch will always come after the `/blob/` that we intend to remove, right? You're right, though, @freben - regex is probably a better approach.

**Comment by Rugvip** [comment]
Should be fine to replace first `/blob/` though I think, unless you're an org called `blob`

**Comment by daniel-j-davis** [comment]
Yeah, I guess the `.replace` solution would fall over if the organisation or repository name was `blob`, probably an edge case but good to account for those things. I'll play around with regex and see if there's a more robust solution.

**Comment by daniel-j-davis** [comment]
Interestingly, it seems like the `blob` that we want to delete will always be between the 5th and the 6th instance of `/` from what I understand. I don't think organisations or repositories can have a `/` in them,  and the branch name will come after that, so maybe it's actually fine to split by `/` (like it currently does), delete the 5th item in the array and then join everything back together by `/`. Any thoughts on that?

**Comment by daniel-j-davis** [comment]
I've been toying with a solution this morning, and this seems to be pretty reliable...

```typescript
const githubUrl = 'https://github.com/a/b/blob/master/c.yaml';
const rawUrl = githubUrl.replace('//github.com/', '//raw.githubusercontent.com/').split('/').filter((_, index) => index !== 5).join('/');
```

I tried it with a regular URL, `blob` as the organisation and/or repository name, and `blob/blob` as the branch name and it still seems to output the intended URL. I can put in a PR, but want to make sure I'm not missing anything with this fix.

**Comment by daniel-j-davis** [comment]
@Rugvip raised a good point in my PR that I didn't realise (took the issue at face value and went straight into 'fixing'), is there actually an issue with branch names that contain a `/`, @shmidt-i? I ran the existing code against a branch called `master/blob/blob/master` and it worked fine.

**Comment by shmidt-i** [comment]
It seems like this wasn't a problem! We had something during the mob session and thought this was an issue, hence the ticket. Could be good though to maybe add tests to cover all of the cases discovered in this discussion? 
Sorry for the confusion @daniel-j-davis  ;-)
