### ISSUE TITLE
Update the Scaffolder Backend to fetch the Repo from the Service Catalog

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1318]
Because of the work completed in #1301, the template definitions live in the Service catalog.

We now need to include support for the `scaffolder` repositories to be able to fetch the location from these service definintions when calling `prepare` so that it will duplicate the local files if they are local definitions.

## Feature Suggestion
- Update the Repository to be able to fetch from the Service Catalog
- Prepare a folder from the source `file:`

**Comment by shmidt-i** [comment]
Should we make this ticket only for `file` type and create another one for the `github`?

**Comment by benjdlambert** [comment]
Yeah maybe that makes sense. Will put up the PR for the file stuff now then.
