### ISSUE TITLE
More flexibility for labels and annotations

### ISSUE THREAD

**Issue by JordiPolo** [spotify/backstage#1328]
I'm testing the json schema and right away found issues trying to describe my service.

I want to add the customer-facing name because that's what everyone outside engineering will call it:
```yaml
  labels:
    product_name: "eLearning Compliance Service"
```

But labels do not allow spaces. which makes this whatever way I try to fix it, pretty weird.

Related problem is using `annotations` to link to other stuff in other systems `:` and `/` are not allowed in the value so can't do https:// ...

Is it possible to make this more flexible?
@freben

**Comment by Rugvip** [comment]
I think any value that needs spaces would really be a non-identifying information, so following the rule in the first section of https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/, it should be an annotation instead.

Afaik annotation values are supposed to be opaque strings that we don't enforce and rules on at all, so if we don't allow `:` or `/` I'd call that a bug.

**Comment by JordiPolo** [comment]
My bad, I've reread the document, the annotation values has no restrictions, will fix the json schema!

**Comment by JordiPolo** [comment]
I think I'm closing this as I can use annotations for all the things
