### ISSUE TITLE
Not able to add Plugin

### ISSUE THREAD

**Issue by abhimanyunagrath** [spotify/backstage#1335]
Hi , 
I am trying to add a plugin sentry to my app.
Command : yarn add @backstage/plugin-sentry
and getting the below-mentioned error :
```
error An unexpected error occurred: "https://registry.npmjs.org/@backstage%2fplugin-sentry: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/batman/Documents/backstage/test-app/packages/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Please help me to fix this. 
Node version: 12.14.0

**Comment by Rugvip** [comment]
Related to #1274, the sentry plugin isn't published right now, but it most likely should be

**Comment by freben** [comment]
Hey, would you like to try this again? We published the packages yesterday and you should be able to add them now.

**Comment by marcuseide** [comment]
Closing this, please let us know or re-open if you still see the issue.
