### ISSUE TITLE
Docker build for backend

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1374]
We have a yarn script for bundling the frontend into a docker container, and we should have one for the example backend as well.

We need to figure out how to depend on the local backend packages, and ideally only install runtime node dependencies for the backend, avoiding CLI deps etc.

**Comment by timurista** [comment]
@Rugvip thanks for tracking this.

**Comment by Niraj-Fonseka** [comment]
Do you guys have any update on this ? Is this something that's being prioritized right now ? We have been trying to dockerize it ourselves but running into some issues. Thanks !

**Comment by timurista** [comment]
@Niraj-Fonseka do you have a public repo to track your issues?
