### ISSUE TITLE
Remove React.FC from codebase

### ISSUE THREAD

**Issue by ayshiff** [spotify/backstage#1376]
## Feature Suggestion

We should remove `React.FC` from the codebase.   
It was removed from the TypeScript template of **create-react-app** to avoid inciting to use it.
More details in the GitHub issue: https://github.com/facebook/create-react-app/pull/8177/

In particular:

- `children` props implicitly added, even when we don't want it
- No support for Generic Type

## Possible Implementation

![carbon (7)](https://user-images.githubusercontent.com/32459935/85135019-accbad80-b23d-11ea-8ca7-462147b99450.png)

**Comment by Rugvip** [comment]
Thank you for highlighting this! I think it would make a good ADR too

**Comment by Rugvip** [comment]
Just clarifying that we want to go with this, and if someone wants to submit an ADR for it before we get around to it, that's fine too :grin:

**Comment by freben** [comment]
Closed by #1506
