### ISSUE TITLE
Site configuration

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#138]
Introduce a site config file ([example](https://github.com/spotify/backstage-microsite/blob/master/website/siteConfig.js)) so that people deploying Backstage can customize things like:

* Site name (everyone may not want to use "Backstage")
* Site logo
* Proxy URLs etc
* Timezones for Homepage headers
* GitHub URL
* ...

**Comment by Rugvip** [comment]
We probably want to expose most of these through APIs in `core`, but also want to identify if there are any parameters that can't be configured there.

Example of a possible solution for how to configure the site name would be

```ts
createApp({
  name: 'Backseat',
})
```

**Comment by andrei-pavel** [comment]
> through APIs

That's written correctly. Maybe fix it in the pretty image in the README too? Sorry, I'll go now, bye!

![image](https://user-images.githubusercontent.com/6838492/77064590-6c635600-69e8-11ea-83bd-825926cf2f23.png)

**Comment by Rugvip** [comment]
Closing this as work done towards #1012 has become the solution for this. If we want to add individual configuration values I think we should open up separate issues where we can discuss those.
