### ISSUE TITLE
Library component missing in UI

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#1408]
After registering this [example component](https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/examples/playback-lib-component.yaml) with `type: library` it should appear under LIBRARIES in the catalog. It does not:

<img width="924" alt="Screenshot 2020-06-22 at 16 40 34" src="https://user-images.githubusercontent.com/190856/85300761-42b64100-b4a7-11ea-90ec-3a735a3dc2e4.png">

**Comment by tudi2d** [comment]
Hello @stefanalund - Just found out about backstage, really love the idea and I want to get started contributing by fixing this bug. Let me know if that is ok :)

**Comment by stefanalund** [comment]
@tudi2d nice to hear, welcome to the Backstage community! This bug was "unfortunately" fixed in https://github.com/spotify/backstage/pull/1409 -- but maybe you can find another good first issue to get started with?

https://github.com/spotify/backstage/labels/good%20first%20issue
