### ISSUE TITLE
[Scaffolder] Define Scope of the Project

### ISSUE THREAD

**Issue by daviddyball** [spotify/backstage#1439]
## Feature Suggestion

What is the scope of the `plugins/scaffolder` and `plugins/scaffolder-backend` projects? In it's most basic form I can assume that it will create a codebase, create a github repo and commit the code... but what about ancillary tasks? How are these implemented in the scaffolder flow?

I'm trying to guage whether or not I need to write my own scaffolder/scaffolder-backend for my specific use-case, or whether it'd be worth contributing to the mainline scaffold plugin if our objectives align.

## Context

In our specific use-case we need to raise (and eventually auto-merge) a number of PRs against various other projects in order for a component to be registered with our platform. Is this something that scaffolder aims to address, or is this something that would need to be done as another plugin?

A few other issues regarding the scaffolder mention a concept of "flows", are these going to be definable? Would it be a case of defining a flow like so:

```
1. Create GH repo for <component>
2. Template Codebase for <component>
3. Push code to <component> repo
4. Create PR on repo-X
5. Create PR on repo-Y
6. POST to service-xyz
```

**Comment by stefanalund** [comment]
@benjaminr can you help answer this?

**Comment by benjdlambert** [comment]
Yep - So I think we mentioned this on Discord, but it would be good to document this down here too.

**Comment by daviddyball** [comment]
Yes, we had a good chat on Discord about what is/isn't in the MVP for scaffold... it might be helpful to have docs for others to understand how it will all be pieced together.

**Comment by benjdlambert** [comment]
We're hoping to have a very basic scaffolding flow done for the end of this week. 

Which means that you can define a template in the Service Catalog, currently we've only written a `templater` which supports `cookiecutter`, but contributions are welcome for other templaters, like yeoman or velocity or something.

It will go grab the template, either from `disk` or `github` repo, run the `templater` (`cookiecutter`),  and then create `github` repo and push the scaffolded content, then add it to the service catalog.

Adding hooks for things like, pre-post prepare a folder, and pre-post templating would also be useful, but they're not in scope right now as `cookiecutter` can provide some of that functionality for us by using shell scripts that `cookiecutter` natively supports.

Would be really good if you could test out some of the stuff we're building right now though once it's finished and I'd love to hear your feedback as to what is good and what is whack that we can fix!

So just to confirm, the basic flow looks like this:
- Prepare (go fetch the skeleton)
- Template (run the templater)
- Store (create remote + push)

**Comment by benjdlambert** [comment]
@daviddyball, yep +1 on docs, once we have a simple MVP together, I will write documentation about how to build templates and add them to the service catalog, and how the scaffolder works and what it supports.

Then i'd love to work with you to maybe abstract away further some of the things we've added if it's not generic enough for some of your use cases.

**Comment by daviddyball** [comment]
Excellent 👍 I'll give the MVP branch a test with some basic use-cases and I'd love to work further on the other things we discussed on Discord.

To save anyone having to dive through Discord history:
* Perhaps implement a concept around a "runner" that allows implementing more complex workflows for scaffolding a service
* Perhaps implement runners for Kubernetes, Tekton, Jenkins, CircleCI etc. (in this scenario `scaffold-backend` would just be polling another tool to see if the task is/isn't complete and would allow a lot of flexibility in what actually happens)
* If "runners" became a thing, then the MVP process would just be encapsulated in a runner (perhaps called `LocalCookiecutterRunner`)

My basic thinking is that, in a lot of cases I already have pipelines that do certain tasks e.g. a Jenkins pipeline that:
* Creates a new GitHub repo for code
* Creates a new GitHub repo for deployment config (kubernetes manifests)
* Populates templated content in code and config repos
* Raise a PR against our internal service catalog repo
* Register it's API tests with another repo via PR

I don't think Backstage should be trying to implement everything-for-everyone .... that'll get very tiring very quickly. By abstracting away which "runner" gets called, you leave the specific implementation details in the operators hands (because they most likely already have a lot of this stuff sorted).

**Comment by benjdlambert** [comment]
@daviddyball - we've made things a little more flexible when creating scaffolding flows.

The latest work defined process of each job based on the entity, so If you wanted to add some more things that suit your purpose I think this leaves the door open to do that pretty easily.

Basically each job is created with a series of stages, or labels with functions. And then the `processor` will just run each one of these stages in series and make sure that they all pass and aggregate logs together.

You can see a simple implementation in the PR: https://github.com/spotify/backstage/pull/1437/files#diff-45922f75d9c8de3a9b3a76ca0f704159R103-R143

**Comment by benjdlambert** [comment]
@daviddyball I'd love to catch up with you soon and get some feedback about what we've built. I've create some docs about the latest API and they live here: https://github.com/spotify/backstage/tree/master/docs/features/software-templates.

Would be good to hear your thoughts and work out what we're missing for different use cases!

**Comment by daviddyball** [comment]
Sounds great @benjdlambert I'm just finishing off the backend side of our service scaffolder now (based around Tekton pipelines and exposed by a microservice). I'll be diving into the Backstage portion of the project shortly, so hopefully I'll be caught-up soon 👍

**Comment by benjdlambert** [comment]
Perfect! sounds awesome!

**Comment by stefanalund** [comment]
@daviddyball we have now announced the first version of Software Templates in Backstage:

https://backstage.io/blog/2020/08/05/announcing-backstage-software-templates

Since this ticket is pretty generic I would appreciate if we either a) closed it or b) repurposed it to describe improvements we would like to see for a Beta release of Software Templates.

**Comment by benjdlambert** [comment]
@stefanalund I'm working with @daviddyball through discord, he's on vacation right now, but we're going to pick it up when he's back. I think we can go ahead and close this ticket, as any new requirements can be added as feature requests rather than having this ticket around.

**Comment by stefanalund** [comment]
Makes sense. Thanks both!
