### ISSUE TITLE
Repeated section in the FAQ

### ISSUE THREAD

**Issue by dufcrule** [spotify/backstage#1441]
The answer to the questions "What is a "plugin" in Backstage?" and "Which plugin is used the most at Spotify?" is exactly the same.

- https://github.com/spotify/backstage/blob/master/docs/FAQ.md#what-is-a-plugin-in-backstage

- https://github.com/spotify/backstage/blob/master/docs/FAQ.md#which-plugin-is-used-the-most-at-spotify

It appears the error is with the first answer: "What is a "plugin" in Backstage?". The text here appears to be incorrect as it answers the question "Which plugin is used the most at Spotify?" rather than detailing what a plugin is.

**Comment by stefanalund** [comment]
Fixed in https://github.com/spotify/backstage/pull/1443
