### ISSUE TITLE
Add Starring on entity pages as well

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#1471]
## Feature Suggestion

It should be possible to Star/Favourite a component from the entity page as well.

Mockup:

![Screenshot 2020-06-26 at 14 14 03](https://user-images.githubusercontent.com/190856/85856091-9f6f6f80-b7b7-11ea-9e73-2adfbc5f78ad.png)

## Possible Implementation

As suggested by @freben -- at this point it is probably a good idea to create a separate Favourite react component that preserves state internally and handles changes, stores it, etc.

## Context

This functionality is currently available in the main catalog table:

![Screenshot 2020-06-26 at 14 14 47](https://user-images.githubusercontent.com/190856/85856117-aeeeb880-b7b7-11ea-82e2-65afd4cdf7e2.png)

**Comment by tudi2d** [comment]
Hello @stefanalund . This looks like a fun first issue. I would like to work on it! 👍

**Comment by stefanalund** [comment]
@tudi2d perfect, I have Assigned you 🙇

**Comment by tudi2d** [comment]
Hey. I added a pull request. It looks like this now:

![aNrRkKIp17](https://user-images.githubusercontent.com/8904624/86007682-07bc8c00-ba18-11ea-9807-1f00d11ca068.gif)

I was a bit confused why the star is behind the Overview/Information label. A suggestion from my side would be to move the star behind the name of the service in the header, as the user wants to star the service and not Overview/Information. It would look something like this:

![image](https://user-images.githubusercontent.com/8904624/86008898-bf05d280-ba19-11ea-98b3-4122d4b8b84a.png)

**Comment by stefanalund** [comment]
Yeah, I agree, putting it in the header makes more sense! Would you be up for changing your PR?
