### ISSUE TITLE
[Plugin] GitHub Actions

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1472]
## Summary

A new plugin for [GitHub Action](https://github.com/features/actions) that is similar to the Circle CI plugin. We likely start out showing the status of builds that are triggered for the master branch and PRs.

Inspiration from the existing Circle CI plugin:

![screenshot-1](https://user-images.githubusercontent.com/5012901/81381716-70207880-910d-11ea-88cb-513f0ba7940b.png)
![screenshot-2](https://user-images.githubusercontent.com/5012901/81381722-7282d280-910d-11ea-864c-5d874be653f0.png)

Inspiration from the internal CI plugin:

![Screenshot 2020-04-28 at 09 34 00](https://user-images.githubusercontent.com/190856/80459970-735c7d00-8933-11ea-8951-5a4adc3d51a2.png)

![image3](https://user-images.githubusercontent.com/190856/80459458-b23e0300-8932-11ea-88ed-c7d5d021b272.png)

## Project website (if applicable)

https://github.com/features/actions

## Context

A CI view is one of the essential and most used plugins inside Spotify. As an example, our CI environment adds deep links into Backstage in the Pull Request view(s) in GitHub. From there engineers can drill down further and follow the status of PRs as they make their way into production.

**Comment by freben** [comment]
#1516

**Comment by Nek** [comment]
Decide on how entities reference the build project https://github.com/spotify/backstage/issues/1524

**Comment by Nek** [comment]
Visualize logs https://github.com/spotify/backstage/issues/1858

**Comment by Nek** [comment]
GitHub Actions: provide a context with an entity to the plugin #1859

**Comment by nikek** [comment]
Missing piece: https://github.com/spotify/backstage/issues/1524
