### ISSUE TITLE
SCSS/SASS no longer working

### ISSUE THREAD

**Issue by mikerhyssmith** [spotify/backstage#1482]
In previous versions (alpha.5) specifically, I was able to import SCSS files into my components as long as I installed node-sass or sass into that plugin, this doesnt seem to be working anymore in the latest (alpha.12) version.

## Expected Behavior

SCSS files should compile correctly

## Current Behavior

Adding a scss file and importing into a component gives the following error:

``` 
ERROR in <path_to_backstage>/plugins/circleci/src/components/PluginHeader/PluginHeader.scss 1:0
 Module parse failed: Unexpected token (1:0)
 You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
 > .something {
 |     color: red;
 | }
```

## Possible Solution

Not too sure, I guess this worked previously becuase the build was based off CRA and CRA has the ability to allow scss just by installing node-sass.

## Steps to Reproduce

In the example app, add a scss file, install node-sass/sass into that plugins node_modules and attempt to run yarn build/start from the root.

## Context

Unable to upgrade from alpha.5 to alpha.12

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): MacOS Catalina

**Comment by mikerhyssmith** [comment]
To add to this, if I run `yarn build` in the plugin that uses scss, it builds correctly. This only happens when running from the root.

**Comment by Rugvip** [comment]
We don't really encourage SCSS/SASS as a tool for styling, as it doesn't give access to the MUI theming. JSS, which MUI uses, does support CSS features such as media queries and animations: https://cssinjs.org/jss-syntax?v=v10.3.0. There should be few reasons, if any, to fall back to separate CSS or SCSS.

That said we want to support SCSS in the build just to make it easier to import existing tools into Backstage.

**Comment by elad-barack** [comment]
@Rugvip did you solve it? I'm experiencing the same when trying to add an external module to my plugin

**Comment by yousifalraheem** [comment]
Can someone please follow-up on this issue? It's just adding a sass loader, shouldn't be that difficult, and we really need this feature 🙏

**Comment by yousifalraheem** [comment]
To whoever is looking for a solution for this issue, you can install `sass` and `sass-loader` and then use this syntax to import sass files:
```typescript
import 'style-loader!css-loader!sass-loader!./styles.scss';
```
