### ISSUE TITLE
Crazy CPU usage while idling on MacBook Pro

### ISSUE THREAD

**Issue by orlade-anz** [spotify/backstage#1485]
## Expected Behavior

~0% CPU at idle.

## Current Behavior

~440% CPU at idle.

## Steps to Reproduce

```
git clone
yarn install
yarn start
```
Open activity monitor

## Context

![image](https://user-images.githubusercontent.com/25187960/85999751-f7c09e80-ba4f-11ea-887c-5fdeb0b3e13f.png)

This makes my MBP so loud that I lose the will to work on Backstage.

## Your Environment

- NodeJS Version (v12): v12.18.1. Also tried v14.4.0.
- Operating System and Version (e.g. Ubuntu 14.04): OS X 10.15.5
- Browser Information: Chrome 83.0.4103.116

**Comment by freben** [comment]
Hey!

I have a pretty much identical setup as you do.

What I'm observing is that after I ctrl+c and then yarn start again, my CPU spikes high for 3-4 seconds while it makes sure to compile the bundle to serve. After that, when the browser can draw the page again, it settles down immediately.

- What page is exhibiting this symptom, are you on just `/` or on some other page when this happens?
- Do you see it continuing to consume that much CPU for an extended period of time?
- Is the website on http://localhost:3000 functional during that time?
- Is the backend started or not in the background while all of this goes on?

**Comment by Rugvip** [comment]
Possibly related to https://github.com/webpack/webpack-dev-server/issues/2140? Is fsevents being installed correctly for you?

**Comment by alexishuxley** [comment]
Chrome 83.0.4103.116? Possibly related to [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964177).

**Comment by shmidt-i** [comment]
I had a similar problem, this comment from https://github.com/webpack/webpack-dev-server/issues/2140  helped me:
> Had the same problem, I had warning about gyp: No Xcode or CLT version when installed npm.
> The solution is in here:
> https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
> reinstall Xcode.

Going to close it now, please let us know if the problem persists!
