### ISSUE TITLE
github-actions: decide on how entities reference the build project

### ISSUE THREAD

**Issue by freben** [spotify/backstage#1524]
To be able to display the build status of a given component, there needs to be a way to find the GitHub project that builds that entity.

Devise a plan for how to go from a full entity JSON blob, to having enough data to identify builds for that entity.

Entities that happen to be sourced out of a `Location` that happens to have the `type` set to `github`, will already produce entities that have a generated metadata annotation `backstage.io/managed-by-location` that has values similar to `github:https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/shuffle-api-component.yaml`. It is possible to extract the org and repo out of that target.

But maybe it will be relevant for users to actually manually point to a github org too. In that case we need to come up with how that pointing happens.

One possibility is to specify another annotation that is intended for end users to write by hand if they want, for example on the form `github.io/project-slug: spotify/backstage` if we want to do something generic that can be used for several purposes (which also has drawbacks!).

Another possibility would be to more specifically annotate `github.io/github-actions-build: spotify/backstage` or similar.

Before embarking on this we need a clear picture of all parameters that are needed to actually uniquely identify a set of builds.

**Comment by Nek** [comment]
The annotation ended up being called ```backstage.io/github-actions-id```. Let's discuss/change it until it's too late 😈.

**Comment by freben** [comment]
I'm thinking maybe it's an `org` specifically, not an `id`

**Comment by Rugvip** [comment]
I'd vote for `github.io/project-slug: spotify/backstage` (or similar) and in general try to standardize annotations. That along with a catalog processors that derive it from the location if available.

Going for one annotation per plugin (use-case?) I think will end up in insanity, and that we can provide a lot of value by providing a standard set of annotations that plugins can rely on.

**Comment by freben** [comment]
Yeah sorry, project, not org - but slug is consistent with gitlab too, sounds sensible

**Comment by Nek** [comment]
I like slug. Any ideas on where to put the annotation key itself? Not to have it hardcoded.

**Comment by freben** [comment]
Having the generic one is of course limiting too - we can't do "feature detection" as easily this way; we'll then perhaps default to showing ALL github related plugins whether they apply or not. Maybe some caching in the graphql layer can help in that regard.

**Comment by benjdlambert** [comment]
Surely `github.com/project-slug: spotify/backstage` not `github.io`?

**Comment by benjdlambert** [comment]
Another issue I'm thinking of, is how do we identify github enterprise projects with this? Then the domain entirely falls apart.

Maybe we do something like `github.com/project-slug: https://mygithub.mycompany.com/spotify/backstage` in that case?

**Comment by swiftdiaries** [comment]
> Another issue I'm thinking of, is how do we identify github enterprise projects with this? Then the domain entirely falls apart.
> 
> Maybe we do something like `github.com/project-slug: https://mygithub.mycompany.com/spotify/backstage` in that case?

Like @benjdlambert pointed out, this limits the annotation to non-Enterprise projects.
Suggestion:
```
annotations:
  github.com/project-slug: 'spotify/backstage'
  # Optional annotation for GitHub Enterprise projects
  github.com/host-name: 'https://mygithub.mycompany.com'  
```
