### ISSUE TITLE
[Catalog] Support importing private GitHub repositories

### ISSUE THREAD

**Issue by andrewthauer** [spotify/backstage#1525]
Currently it is not possible to populate the service catalog with component spec files in private repositories. There are ways around this, but they all require custom code and other tooling.

## Feature Suggestion

Have some official way to import catalog spec files from a private GitHub repo.

## Possible Implementation

The GitHub official API does allow downloading files from private repos with an API token. This could must likely work, but the URL or mechanism to do so may be different then the current URL approach.

Some other initial suggestions from @freben (on discord):

- Make your own `EntitiesCatalog` subclass instead of the database based one, that reads directly off of your catalog, no Locations or database or anything involved at all
- Make your own `LocationProcessor` subclass that reads off a custom location of yours e.g. to ingest from an external source into the database catalog
- Improve on the existing `LocationProcessors` and chain on your own together with the ones that come included
- Make completely external refresh loops in another service, that push things to the database catalog via HTTP POST
- A combination of the above

## Context

Some other context can be found in #1013.

**Comment by stefanalund** [comment]
Can this be closed?

**Comment by andrewthauer** [comment]
This was resolved in #1560

**Comment by andrewthauer** [comment]
This was resolved in #1560
