### ISSUE TITLE
Move @backstage/cli create-app to separate package

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1537]
## Feature Suggestion

The `create-app` and similar commands should live in a different packages than the `@backstage/cli`. It would be similar to the split between `create-react-app` and `react-scripts`.

## Possible Implementation

Move the `create-app` command to a separate and much more lightweight `@backstage/create` package. The package probably doesn't have templates baked into it either, just the logic for downloading and executing templates.

## Context

When running `npx @backstage/cli create-app`, all dependencies of the CLI are downloaded just to execute a simple template. All of these dependencies are then thrown away as we create the actual app and download all dependencies again. We effectively download all dependencies of the CLI twice when creating an app, which makes it very slow.

**Comment by ayshiff** [comment]
Can I work on this one @Rugvip ?

**Comment by Rugvip** [comment]
@ayshiff Sure, Thanks!

**Comment by ayshiff** [comment]
I will need some help @Rugvip 👍 
In fact, I was wondering if you could give me some explanations about the way the cli package is working. I don't want to have misunderstandings on important parts of the code.

**Comment by Rugvip** [comment]
@ayshiff Sure! Can start with a brief overview and you can ask about specific bits here or come by discord! :grin:

The CLI lives inside `packages/cli` and the entrypoint, i.e. the root script executed by `node`, is `./bin/backstage-cli`. It's used both when running a packaged version of the CLI and local development, but for local development it registers `ts-node` for transpilation.

The CLI implementation itself is split up into two major parts: `./src/commands` and `./src/lib`. The commands contain the implementation of each CLI command, and the goal is to keep that bit as lean as possible. The lib contains the building blocks that make up the different commands, which is where most of the implementation goes.

One important part of lib is the `paths` module, which make it possible to look up different paths. "target" paths refer to paths relative to the package where the CLI is executed, for example a plugin directory. "targetRoot" refers to the root of the monorepo of the target, or the target itself if it's not a monorepo. "own" refers to the CLI directory itself, either as it exists inside this repo, i.e. `packages/cli`, or where it's installed as a dependency, .e.g. `node_modules/@backstage/cli`. "own" is used to look up for example the config and templates that ship with the CLI.
