### ISSUE TITLE
github-actions: List all builds with mocked data using CircleCI design patterns

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1538]
https://github.com/spotify/backstage/tree/master/plugins/github-actions was reincarnated from a very early version of Backstage. It should be refactored to use common components and styled similar to the Circle CI plugin

# Target: list all builds for the repo
  - [ ] create mocked response according to https://developer.github.com/v3/actions/workflow-runs/#list-workflow-runs-for-a-repository
  - [ ] copy over + adjust needed components from CircleCI plugin, use the mocked response to create a static table view of all builds

**Comment by shmidt-i** [comment]
![image](https://user-images.githubusercontent.com/5012901/86595659-57abcd80-bf99-11ea-9393-f59f516fa268.png)
![image](https://user-images.githubusercontent.com/5012901/86595674-5aa6be00-bf99-11ea-9da5-684d9e76d7b4.png)
