### ISSUE TITLE
Investigation into Github App authentication

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1539]
## Feature Suggestion
- The regular flow of oauth is going away in November with Github, and moving to the new Github Apps.
- We need to investigate what that means for Backstage, how does it work for us.
- How does this work for private repositories?

## Possible Implementation
_more to follow_

**Comment by benjdlambert** [comment]
# GitHub Authentication

## Github Apps

GitHub Apps are the officially recommended way to integrate with GitHub because they offer much more granular permissions to access data.

- GitHub Apps are first-class actors within GitHub. A GitHub App acts on its own behalf, taking actions via the API directly using its own identity, which means you don't need to maintain a bot or service account as a separate user.

- GitHub Apps can be installed directly on organizations and user accounts and granted access to specific repositories. They come with built-in webhooks and narrow, specific permissions.

- Don't expect the GitHub App to know and do everything a user can.
- Don't use a GitHub App if you just need a "Login with GitHub" service. But a GitHub App can use a [user identification flow](https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/) to log users in *and* do other things.
- Don't build a GitHub App if you *only* want to act as a GitHub user and do everything that user can do.

## OAuth Apps

An OAuth App uses GitHub as an identity provider to authenticate as the user who grants access to the app. This means when a user grants an OAuth App access, they grant permissions to all repositories they have access to in their account, and also to any organizations they belong to that haven't blocked third-party access.

- An OAuth App should always act as the authenticated GitHub user across all of GitHub (for example, when providing user notifications).
- An OAuth App can be used as an identity provider by enabling a "Login with GitHub" for the authenticated user.

- Don't build an OAuth App if you want your application to act on a single repository. With the `repo` OAuth scope, OAuth apps can act on *all* of the authenticated user's repositories.
- Don't build an OAuth App to act as an application for your team or company. OAuth Apps authenticate as a single user, so if one person creates an OAuth App for a company to use, and then they leave the company, no one else will have access to it.

![Untitled](https://user-images.githubusercontent.com/3645856/86639242-e855ce00-bfd8-11ea-813f-dfbb068c9578.png)

**Comment by Rugvip** [comment]
Looked a bit more at the APIs and noticed that it's only the OAuth Authorizations API that disappears in November, https://developer.github.com/v3/oauth_authorizations/. OAuth web flow will stay around for "login with GitHub" type scenarios.
