### ISSUE TITLE
Update messaging on welcome banner

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#1554]
### Currently

<img width="1445" alt="Screenshot 2020-07-07 at 3 40 21 PM" src="https://user-images.githubusercontent.com/61153904/86790062-467dc200-c068-11ea-833a-aaef8cf7316b.png">

### Ideally
We'd love if you could change the messaging to:

"🎉 Welcome to Backstage! Take a look around and check out our [getting started](https://github.com/spotify/backstage#getting-started) page."

**Comment by morrme** [comment]
I'd like to help with this.

**Comment by Rugvip** [comment]
@morrme, thanks!
