### ISSUE TITLE
Add Spotify logo next to 'All'

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#1555]
### Currently

<img width="353" alt="Screenshot 2020-07-07 at 3 45 48 PM" src="https://user-images.githubusercontent.com/61153904/86790692-fb17e380-c068-11ea-8144-32e67f4b0365.png">

### Ideally
<img width="367" alt="Screenshot 2020-07-07 at 3 47 02 PM" src="https://user-images.githubusercontent.com/61153904/86790819-1f73c000-c069-11ea-9cb0-2c5e8cc7f82c.png">

Note - logo should be black in light mode and white in dark mode. It should never be green.
You can access the logo here: https://developer.spotify.com/branding-guidelines/

**Comment by stefanalund** [comment]
Actually, this logo should be configurable to match the company that deploys Backstage. The label “Spotify” can already be replaced this way.

**Comment by stefanalund** [comment]
This was fixed in #1562.
