### ISSUE TITLE
Better presentation of authentication errors

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1566]
## Expected Behavior

Authentication errors should be presented in a way that is clear to both the user and a developer setting up a new deployment.

## Current Behavior

The error is ugly and doesn't provide enough information

![image](https://user-images.githubusercontent.com/4984472/86930921-d3438100-c137-11ea-8f63-72df706ba4bb.png)

## Possible Solution

- Make sure the backend provides enough error information, and translate things like a "401" into something more human readable and with a likely cause.

- Fix the presentation in the frontend.

## Steps to Reproduce

Try setting up GitHub auth but provide an incorrect secret, that'll give the error in the screenshot when trying to log in.

**Comment by ari-hacks** [comment]
I'd like to try to tackle this one 👋🏾

**Comment by Rugvip** [comment]
@ari-hacks Awesome, thanks! 😁

**Comment by stefanalund** [comment]
@ari-hacks any update? Thanks

**Comment by ari-hacks** [comment]
Hey @stefanalund , I'm not sure how to reproduce this one. I get a missing configuration message. Are there some docs around reproducing this in dev?

**Comment by soapraj** [comment]
Hey @ari-hacks 

You can follow the docs [here](https://github.com/spotify/backstage/tree/master/plugins/auth-backend) to set environment vars based on what provider you use. We will update our documentation to make it easier to find this information.

Steps (Assuming you use Google as provider)

- Set environment vars mentioned [here](https://github.com/spotify/backstage/tree/master/plugins/auth-backend#google)
- App config yaml has google provider [config](https://github.com/spotify/backstage/blob/master/app-config.yaml#L49) that reads from the env vars above.
- Start the app 

Now you should see the missing configuration errors go away and be able to log in via Google.

To Repro the issue

- Set an invalid AUTH_GOOGLE_CLIENT_SECRET to see the error shown above.

**Comment by ari-hacks** [comment]
@soapraj  - great, thanks for the info!

**Comment by Marvin9** [comment]
I want to work on this issue.

**Comment by Marvin9** [comment]
I succeeded to reach at reproducing step. However I got different popup mentioned in description but the content are same.

![Screenshot from 2020-09-30 10-50-06](https://user-images.githubusercontent.com/17699717/94646060-0a769800-030b-11eb-925f-a65c71880960.png)

**Comment by mahmoodhosseini** [comment]
Hi! I want to work on this, but I have two questions:
  1. What would be a better presentation in the frontend? A different type of popup, or cleaning up the error message?
  2. What is considered "enough information?" Let's say for a 401 error, the returned message includes `Bad credentials`; would "**Authentication failed - Bad credentials**" be enough?

**Comment by Rugvip** [comment]
@mahmoodhosseini Thanks!

> 1. What would be a better presentation in the frontend? A different type of popup, or cleaning up the error message?

Cleaning up the error message

> 2. What is considered "enough information?" Let's say for a 401 error, the returned message includes `Bad credentials`; would "**Authentication failed - Bad credentials**" be enough?

The more information we can convey to the correct person, the better. For example if we receive an error that means the `client_secret` is wrong, that should be conveyed in a way that makes it clear that it's a configuration issue in Backstage and the user themselves can't do much else than reporting the issue.

We also want to make the messages as granular as possible, so that it's possible to pinpoint errors more easily. If many different errors lead to the same message, it makes it much more difficult to troubleshoot the issue.

**Comment by mahmoodhosseini** [comment]
Thanks, @Rugvip. I'm working on it.
