### ISSUE TITLE
Allow adding components in Github not in the master branch

### ISSUE THREAD

**Issue by JordiPolo** [spotify/backstage#1573]
It just happens that we have a pretty unique git workflow. 

Could we lift the branch restriction when trying to add a new component?

**Comment by shmidt-i** [comment]
I don't see why not, @Rugvip any objections? Basically it's only in `plugins/register-component/src/util/validate.ts` afaik.

**Comment by Rugvip** [comment]
Yeah agreed, if it's only being blocked by the frontend right now, let's allow it, since we essentially already are.

**Comment by benjdlambert** [comment]
@JordiPolo, Do you wanna pick up the frontend work for this? :star:

**Comment by JordiPolo** [comment]
Sadly I do not have any extra cycles any time soon :(
