### ISSUE TITLE
Item Card Color Change for Accessibility 

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#1577]
Hi! Would love if someone could help us adjust the colors for our item card headers. Currently our item card headers don't pass color contrast standards.

If the gradient could be #187656 to #4BB8A5, that would be amazing! Thank you!

<img width="740" alt="Screenshot 2020-07-09 at 5 05 59 PM" src="https://user-images.githubusercontent.com/61153904/87056847-78c52600-c206-11ea-9c8c-6d400d998b01.png">

**Comment by varenaggarwal** [comment]
@katz95 I would love to help out. I'll look into it!

**Comment by Rugvip** [comment]
@varenaggarwal awesome, thanks! 🎉

**Comment by katz95** [comment]
@varenaggarwal hi! just checking in on this one - were you able to submit a PR?
