### ISSUE TITLE
Techdocs: CLI not working on Windows

### ISSUE THREAD

**Issue by hooloovooo** [spotify/backstage#1599]
Rugvip says "https://github.com/spotify/backstage/blob/master/packages/techdocs-cli/bin/build doesn't work on Windows. I think it might just need a .sh extension and possibly a shebang".

Do that and see if it works.

**Comment by ZaradarDFDS** [comment]
I can confirm its the missing .sh extension. :)

**Comment by ZaradarDFDS** [comment]
This is a identical to issue https://github.com/spotify/backstage/issues/1557, which make it seem like we lack some clear guidelines on cross-platform development. E.g @ https://github.com/dfds/cag/blob/master/docs/guidelines/engineering/ENGINEERING.md#cross-platform-coding

**Comment by emmaindal** [comment]
@hooloovooo can this issue be closed? seems to have been solved in https://github.com/spotify/backstage/commit/bb63c4ceba4bce6daf100d0c41fcbf1d524c0fce#diff-021f7c6b357a4171aaca0a9edc8db241 ?
