### ISSUE TITLE
TechDocs: Reading Documentation

### ISSUE THREAD

**Issue by bih** [spotify/backstage#1605]
Create a guide that walks through what reading documentation in TechDocs looks like. Screenshots, some basic explanation of the tech, etc. The consumers of this should be mostly non-technical (i.e. engineering managers, leads, etc) who are considering deploying TechDocs in their own organization.

**Comment by ellieseastream** [comment]
We decided to drop this in this version of TechDocs. Might reinstate it in a later version.
