### ISSUE TITLE
Pick a default table component

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#161]
Possible choice: https://github.com/mbrn/material-table

**Comment by Rugvip** [comment]
Some discussion around this has been going on in #315, but let's bring it here

**Comment by Rugvip** [comment]
Outlining some features that we know are useful, especially infrastructure-related tooling:

- [ ] Sortable columns, with custom sorting functions
- [ ] Column filter/search - input box in the column header to filter which rows are shown
- [ ] Global search - i.e. filter all columns
- [ ] Windowing / infinite scroll
- [ ] Material UI theming
- [ ] Expandable rows - click an item to expand the row and show custom components below
- [ ] Pagination
- [ ] Column selection - select which columns to show and persist selection in storage
- [ ] Resizable columns

@spotify/backstage-core, anything else we want to add here?

Thinking we can copy the above list and check the boxes for any suggested options

**Comment by stefanalund** [comment]
@zatine perhaps you want to chime in?

**Comment by freben** [comment]
In light of how much the internal data grid has had issues around virtual scroll and the implications with height etc - I'd like to suggest that a virtual scrollable table MAY benefit from being a separate class. Highly depends on the chosen implementation, I guess. But being able to easily throw in an auto-sizing no-overflow/scroll table is important and shouldn't be too muddled by the advanced variants and options.

**Comment by freben** [comment]
Essentially the clash between "expands to fit the contents, extending the container block" vs "requires to set the size of the container block beforehand"

**Comment by stefanalund** [comment]
@hooloovooo mind looking into this?

**Comment by stefanalund** [comment]
The example plugin that you get after scaffolding should use whatever grid/table component we choose here.

**Comment by hooloovooo** [comment]
Currently looking into https://react-table.js.org/. Not a simple solution, but extremely flexible. Could be very nice if it had a wrapper for the most common usecases. Does anyone have experience from using it?

**Comment by Rugvip** [comment]
@hooloovooo looks interesting. We'd have to wrap it quite a bit though I think, so leaves a lot of API design up to us. Still interesting to see what it would look like with mui.

**Comment by hooloovooo** [comment]
Maybe we should close this issue now?

**Comment by Rugvip** [comment]
Yes, #600, material-table selected
