### ISSUE TITLE
@backstage/plugin-techdocs does not contain a dist folder

### ISSUE THREAD

**Issue by hooloovooo** [spotify/backstage#1619]
Techdocs plugin in npm does not work because it doesn't contain the dist folder.

**Comment by Rugvip** [comment]
Because it's removed when the cli is built :grin: https://github.com/spotify/backstage/blob/f6dd091d7f696dad6195f873b2c3e33ecd23aa70/packages/techdocs-cli/bin/build#L31

**Comment by hooloovooo** [comment]
> Because it's removed when the cli is built grin
> 
> https://github.com/spotify/backstage/blob/f6dd091d7f696dad6195f873b2c3e33ecd23aa70/packages/techdocs-cli/bin/build#L31

Ohhh that explains it. Thanks!
