### ISSUE TITLE
sign In issue

### ISSUE THREAD

**Issue by anshika-cs** [spotify/backstage#1621]
after running app  sign page opens but I am not able to sign in .

**Comment by benjdlambert** [comment]
Hey @anshika-cs!

Going to need a little bit more information here, what do you see?

Any form of screenshots or logs would be helpful to find out what's going on.

**Comment by benjdlambert** [comment]
I'm guessing it's going to be part of #1618, if it is the same can you close this ticket in favour of the other one

**Comment by soapraj** [comment]
@anshika-cs - do you still face this issue? can you provide us more info so we can help?
