### ISSUE TITLE
In backstage example app templates are not visible and getting problem in signing option also.

### ISSUE THREAD

**Issue by Anshi19** [spotify/backstage#1622]
![bug1](https://user-images.githubusercontent.com/57665515/87437756-3d4ba280-c5de-11ea-8570-92074675fc0c.JPG)
![bug2](https://user-images.githubusercontent.com/57665515/87437763-3e7ccf80-c5de-11ea-866b-5bc920fd1c85.JPG)

**Comment by benjdlambert** [comment]
For the example templates to load, you'll need to run

```
yarn lerna mock-data
```

**Comment by anshika-cs** [comment]
I already run this.

yarn lerna run mock-data

**Comment by anshika-cs** [comment]
yes i have the same setup as you described above.

**Comment by benjdlambert** [comment]
Are you passing in your GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET as env variables?

Also for the templates screen, could you please get me any console logs from the webpage?

**Comment by benjdlambert** [comment]
Also the console log from `yarn lerna run mock-data` would be useful if it only completes one stage.

**Comment by soapraj** [comment]
Hi @anshika-cs - do you still face this issue? can you provide us more info so we can help?

**Comment by stefanalund** [comment]
Closing for now. @anshika-cs please reopen the issue if you still have problems with this.
