### ISSUE TITLE
Add a service template for the Scaffolder

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1627]
## Feature Suggestion
Currently the Scaffolder provides two sample templates:
- React SSR Template
- Spring Boot Template

The spring boot template doesn't work as there is no files. 
Let's get setup with some useful templates.

## Possible Implementation
- Implement a Create React App template for Websites
- Implement a Java/Node/Go template that you can use in the scaffolder.

**Comment by benjdlambert** [comment]
@shmidt-i I know you mentioned porting over the springboot stuff from internal but I don't know if it's going to be useful if we have a lot of proprietary code in there that isn't going to work outside Spotify. What did you conclude?

**Comment by stefanalund** [comment]
@benjdlambert @shmidt-i we are going to use "Spring Boot" in the copy of the revised backstage.io so please use that. I think an open source template makes more sense than lifting out our internal one.

**Comment by benjdlambert** [comment]
@stefanalund looking around for springboot cookiecutter templates on the web is pretty scarce. The ones I found are pretty outdated, and springboot push you towards using this instead to get setup: https://start.spring.io. Wouldn't be difficult to turn that into a template and add a custom templater instead of cookiecutter to go download the build zip and extract it into a folder.

**Comment by stefanalund** [comment]
@benjdlambert I see. In that case let's lift-n-shift the internal one. It's a demo in any case.

**Comment by benjdlambert** [comment]
Fixed by #1666
