### ISSUE TITLE
Validate Input Variables with the JSON Schema in the Template Entity

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1628]
## Feature Suggestion
- Currently we only use the JSON Form Schema to create the input form
- We should validate the input variables that are posted to `/v1/jobs` with the same schema
- This ensures that the input params are valid from both the frontend and other callers of the scaffolder backend

## Possible Implementation
- Use the Template Entity that is passed to the scaffolder-backend
- Validate the `values` object with the `spec.schema`

**Comment by iain-b** [comment]
Can I take this one?

**Comment by stefanalund** [comment]
@iain-b thanks, Assigned you!

**Comment by benjdlambert** [comment]
@iain-b if you need any help give me a shout.

I think basically you need to add the validation in the `.post('/v1/jobs')` route in `createRouter` of the scaffolder.

You should have everything there in terms of the schema and the input variables to make a decision on if it's valid or not.

**Comment by iain-b** [comment]
@benjdlambert Thanks, yeah the schema is there is just a matter of applying the schema to the values. The main decision is the choice of validation library which I've described in the PR (json-schema implementation seems to be buggy).
