### ISSUE TITLE
Tidy up the Scaffolder Frontend to look like designs

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1629]
## Feature Suggestion
- We have some updated designs for the Scaffolder flow.

https://www.figma.com/file/0eN6w5empYRCXAWIy7sqgr/BOSS-DLS?node-id=894%3A3101
https://www.figma.com/file/0eN6w5empYRCXAWIy7sqgr/BOSS-DLS?node-id=894%3A2276

![Screenshot 2020-07-15 at 09 26 01](https://user-images.githubusercontent.com/190856/87516187-48a1db00-c67d-11ea-9de8-fbc5cc1d03cc.png)

## Possible Implementation
- The header colour needs updating
- And the Template cards need the wave graphics

## Notes
Also @katz95, would it be possible to get some designs for the part that we kind of built on our own which is the popup flow for when you click create and you're waiting for the flow to complete.
It's the one with the console log for each step? I guess we could maybe use the granular view and the steps that run horizontally could be each phase of the scaffolder flow.

**Comment by shmidt-i** [comment]
Closing this for now, done in #1669 .
