### ISSUE TITLE
Define the scope of GraphQL MVP

### ISSUE THREAD

**Issue by soapraj** [spotify/backstage#1690]

**Comment by benjdlambert** [comment]
## Feature Suggestion
- Create a simple GraphQL service which is registered with the example backend
- Implement the Catalog in GraphQL
- Understand how we can register additional things to the schema from plugins

## Possible Implementation
- Simple GraphQL service which is written in `apollo-server`
- Experiment with `apollo-client@3`
- Add in the ability to search and filter catalog entities
- How to we let plugins register something on existing entities in `GraphQL`?
  - Probably need an RFC for this, but maybe something like this works.
```ts
import {register} from '@backstage/graphql';
import gql from 'graphql-tag';

const extension = gql`
  type Build {
    id: String!;
  }
  type GithubActions {
    builds: [Build!]!;
  }
  extend type Entity {
    githubActions: GithubActions;
  }
`;

const resolvers = {
  GithubActions: {
    builds: (entity) => githubActions.fetch(entity.id),
  }
 Build: {
   id: (build) => build.id,
 },
};

register(
  extension,
  resolvers
)
```


 
  


## Context

**Comment by shmidt-i** [comment]
Yay `Experiment with apollo-client@3` 🤩

Very nicely put, I'd only add the type definitions generation as a separate step in MVP ;)

**Comment by soapraj** [comment]
The `plugin system` idea for schema extensions sounds interesting to explore.

One more addition to the MVP would be establish Querying patters from the frontend. In the internal version, we make the GraphQL queries upfront as part of the Page component. Since we are working towards plugin composability we should think about how a single component vs entire page could get data from Graphql.
