### ISSUE TITLE
Design a nicer 404 screen

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#170]
![Screenshot 2020-03-05 at 12 55 28](https://user-images.githubusercontent.com/190856/75979373-a90b5980-5ee0-11ea-9fee-d4d43d509708.png)

**Comment by Escalion** [comment]
I whipped up a 404 page at my fork:
https://github.com/escalion/backstage

![Screenshot from 2020-03-18 13-18-20](https://user-images.githubusercontent.com/756601/76965116-af0b2c80-691b-11ea-8870-69c91869ec63.png)

Any thoughts?
I haven't added tests yet or I would submit a PR.

**Comment by stefanalund** [comment]
@katz95 @jdwelch can you have a look?

**Comment by katz95** [comment]
@Escalion thank you!! love the rad copy, and will integrate it into a design that we're currently working on! appreciate your help 🙏

**Comment by freben** [comment]
@katz95 would you like us to get a pull request from @Escalion to start us off, and then tweak that when we get the updated designs? Would that be OK with you @Escalion (potentially having your beautiful work changed after the fact)? :)

**Comment by Escalion** [comment]
That's all good with me :) Let me know if you want to do the PR, I'll get the tests written too.

**Comment by stefanalund** [comment]
@Escalion yep, please send a PR! 💯

**Comment by katz95** [comment]
some explorations for the 404 screen using @Escalion's rad copy 😊let me know if yall have any preferences/feedback!
![404 Error 1](https://user-images.githubusercontent.com/61153904/77068229-84d27100-69e6-11ea-822e-7346fd758c30.png)
![404 Error 2](https://user-images.githubusercontent.com/61153904/77068233-8734cb00-69e6-11ea-9af4-546bfea2b59d.png)

**Comment by katz95** [comment]
mics bounce right? 🎤😂

**Comment by freben** [comment]
I still would like Page not Found, and possibly also 404 (this is a techie friendly site). It's not clear what it is trying to tell me, without that at the very top.

**Comment by katz95** [comment]
Good point! will add that in

**Comment by katz95** [comment]
![404 Error 1](https://user-images.githubusercontent.com/61153904/77069216-48077980-69e8-11ea-94c9-76f4fc4387b3.png)
![404 Error 2](https://user-images.githubusercontent.com/61153904/77069220-4a69d380-69e8-11ea-8022-82f28efafa7a.png)

**Comment by katz95** [comment]
[404 Error SVGs.zip](https://github.com/spotify/backstage/files/4354932/404.Error.SVGs.zip)

**Comment by stefanalund** [comment]
Thanks @katz95 I think this looks nice. I personally like the one with the woman.

@Escalion wanna take a stab at implementing this design? 💚

**Comment by Escalion** [comment]
@stefanalund @katz95 Can do!
Will update my fork and then submit a PR.

**Comment by Escalion** [comment]
@stefanalund What URLs should I use for the links?

**Comment by stefanalund** [comment]
Not sure anymore that all of those links will make sense after someone deploys Backstage in their environment. My suggestion is to have:

> "[Go back](/)...or if you think this is a bug, please file an [issue](https://github.com/spotify/backstage/issues)."

**Comment by Escalion** [comment]
Sorry for the delays - this whole coronavirus thing has the worlds mad right now. Almost finished with this. Making it responsive too, because I'm nice like that. :)

**Comment by stefanalund** [comment]
😍

**Comment by Escalion** [comment]
![Untitled](https://user-images.githubusercontent.com/756601/77456402-17ae4980-6df3-11ea-8d3b-2dc3fbf05aae.png)

**Comment by Escalion** [comment]
Still fiddling with the spacing and sizing :)

**Comment by katz95** [comment]
@Escalion thank you so so much! you rock! 👏🏼whenever you get a chance, go ahead and submit a PR!

**Comment by stefanalund** [comment]
Any update on this issue?

**Comment by Escalion** [comment]
Apologies its been a crazy couple of weeks - still trying to catch up on jobs. I will get to it as soon as I can.

**Comment by stefanalund** [comment]
Thanks for the update @Escalion -- no worries at all, we are just happy that you're willing to put time on it :)

**Comment by loftwah** [comment]
![Backstage  (1)](https://user-images.githubusercontent.com/19922556/79837681-6fd16f00-83e4-11ea-93b6-0ee92e7da939.png)

I had a bit of a play around with some design stuff. I think it would be cool to use a play on the whole 'backstage' access thing for the 404. Maybe like a bouncer blocking someone from accessing an area.

**Comment by loftwah** [comment]
![Page not found](https://user-images.githubusercontent.com/19922556/79838819-2bdf6980-83e6-11ea-9aa7-3e930d2aa8fa.png)

**Comment by katz95** [comment]
@loftwah oooh thank you for the rad explorations! we've currently set the 404 design in place but we're definitely looking forward to collaborating with you moving forward!

@Escalion hi! hope you're doing well! it's def a busy/hectic time these days - was wondering if you wanted to just send in a PR with the current state and then our team can take it on from there! we appreciate all your help so far!

**Comment by loftwah** [comment]
> 
> 
> @loftwah oooh thank you for the rad explorations! we've currently set the 404 design in place but we're definitely looking forward to collaborating with you moving forward!
> 
> @Escalion hi! hope you're doing well! it's def a busy/hectic time these days - was wondering if you wanted to just send in a PR with the current state and then our team can take it on from there! we appreciate all your help so far!

Thanks! I'll keep an eye out and contribute wherever I think I can, not phased if any of it actually makes it to master.

**Comment by Escalion** [comment]
@katz95 No problem - was intending to take a crack at it today but everything happens. I'll submit a PR now and if I get chance to finish it over the weekend, or before your guys do, I'll make sure to push to the branch so it is reflected on the PR :)

@loftwah your design certainly rocked too! I'll keep an eye open for more of your work!
