### ISSUE TITLE
Dense property not applying to Structured Metadata Table

### ISSUE THREAD

**Issue by mikerhyssmith** [spotify/backstage#1735]
Dense property does not change how StructuredMetadataTable is rendered 

## Expected Behavior
Should use dense table when dense prop is true

## Current Behavior
Seemingly there is no change when dense is set to true on StructuredMetdataTable

## Possible Solution

I may have missread this but the change for this issue https://github.com/spotify/backstage/issues/1283 Was to apply the dense property to the Table, but it looks like in `StructuredMetadataTable.tsx` this prop isn't passed into the table. Maybe it's as simple as that to fix this ?

Would be happy to contribute if so ! 😄 

## Steps to Reproduce

Create Structured Metadata table and set Dense to true

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Mac OSX
- Browser Information: Chrome

**Comment by stefanalund** [comment]
@mikerhyssmith these are based on different table implementations currently. Passing dense will not do anything. In fact, the structured table is always showing content in a dense way. 

I’m thinking we will probably close this issue as it is expected behavior. What do you think?

**Comment by mikerhyssmith** [comment]
Hi @stefanalund  thankyou for the reply !

AHH that's interesting I'm not sure if it's on my side but I recently updated from alpha.5 to the latest and my structured metadata table is no longer dense !

I will try and get a reproduction for you 🙂

**Comment by stefanalund** [comment]
You are right! http://storybook.backstage.io/?path=/story/structured-metadata-table--default

Feel free to suggest a PR that makes it dense again, and possibly adding a prop for it (which should be true by default). Thanks!
