### ISSUE TITLE
Edit button style for template cards

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#1763]
Currently, the buttons in the cards for our software templates don't match the buttons that we have elsewhere. It would amazing if someone could fix the styling to match the tertiary button style that you see in TechDocs and Explore.

### Currently

<img width="661" alt="Screenshot 2020-07-28 at 2 33 29 PM" src="https://user-images.githubusercontent.com/61153904/88665784-78220000-d0df-11ea-8f60-299980ca0495.png">

### Ideally
<img width="631" alt="Screenshot 2020-07-28 at 2 33 09 PM" src="https://user-images.githubusercontent.com/61153904/88665787-78ba9680-d0df-11ea-963d-d5ec49f57806.png">

<img width="785" alt="Screenshot 2020-07-28 at 2 34 04 PM" src="https://user-images.githubusercontent.com/61153904/88665775-748e7900-d0df-11ea-9fd2-e4535e2508e2.png">

**Comment by rcoder23** [comment]
I can solve it

**Comment by Rugvip** [comment]
@rcoder23 Awesome 😎

**Comment by rcoder23** [comment]
Sorry ,sir I am removing my assignment .I am beginner now Thank you

**Comment by Rugvip** [comment]
@rcoder23 no problem, and good luck! :grin:

**Comment by ellieseastream** [comment]
This issue seems to have already been fixed in this pull request: #1677 
😊

**Comment by Rugvip** [comment]
@ellieseastream oh yeh, thanks! :grin:
