### ISSUE TITLE
TechDocs: Documentation Header

### ISSUE THREAD

**Issue by emmaindal** [spotify/backstage#1764]
The header for documentation currently use the standard "home" color. 
![Screen Shot 2020-07-28 at 4 30 10 PM](https://user-images.githubusercontent.com/25153114/88679384-ad364e80-d0ef-11ea-9d44-4ccb9bd9b3e9.png)

![Screen Shot 2020-07-28 at 4 33 21 PM](https://user-images.githubusercontent.com/25153114/88679777-14ec9980-d0f0-11ea-91aa-47ce9d6adc21.png)

We would like to change this to a specific color to use for documentation. 
![Screen Shot 2020-07-28 at 4 32 33 PM](https://user-images.githubusercontent.com/25153114/88679679-f5ee0780-d0ef-11ea-97b7-6ddf937bb2a8.png)

* Add new gradient to the [page theme provider](https://github.com/spotify/backstage/blob/e2ff11f77716d94e8cbf5b421a7b9ba09b07a5a0/packages/core/src/layout/Page/PageThemeProvider.ts) from [Figma sketch](https://www.figma.com/file/JE7l5zas8NEHv9VgPzOSeS/Backstage-Design-System-Community?node-id=2%3A396).
* Use new gradient for [documentation](https://github.com/spotify/backstage/blob/e2ff11f77716d94e8cbf5b421a7b9ba09b07a5a0/packages/core/src/layout/Page/PageThemeProvider.ts#L74).
* Use the page component with the new page theme type in [TechDocsPageWrapper](https://github.com/spotify/backstage/blob/master/plugins/techdocs/src/reader/components/TechDocsPageWrapper.tsx#L33). 
* Add new documentation header example to [Storybook](http://storybook.backstage.io/?path=/story/header--home). in [Header.stories.tsx](https://github.com/spotify/backstage/blob/master/packages/core/src/layout/Header/Header.stories.tsx)

**Comment by twishasaraiya** [comment]
Hi @emmaindal, I would like to take this up.

**Comment by emmaindal** [comment]
Great @twishasaraiya 😄 I'll assign it to you, just let us know if you have any questions! 🎉

**Comment by twishasaraiya** [comment]
Hi @emmaindal, can you confirm if I have picked correct shades
```
{
    colors: ['#C8077A', '#C8077A'],
    waveColor: '#262425',
    opacity: ['0', '0.8'],
  }
```

**Comment by emmaindal** [comment]
> Hi @emmaindal, can you please confirm if I have picked correct shades
> 
> ```
> {
>     colors: ['#C8077A', '#C8077A'],
>     waveColor: '#262425',
>     opacity: ['0', '0.8'],
>   }
> ```
@twishasaraiya I adjusted them a little bit, will update the sketch. Lets use the following 😄 

{
    colors: ['#C8077A', '#FF0F9E'],
    waveColor: '#ea93c3',
    opacity: ['0.8', '0.0'],
},

**Comment by twishasaraiya** [comment]
Thanks for that @emmaindal.  I have made the changes.
