### ISSUE TITLE
Upgrading Helmet to the next major version

### ISSUE THREAD

**Issue by EvanHahn** [spotify/backstage#1766]
I'm the maintainer of Helmet. I plan to release the next major version this Sunday, 2020-08-22.

Just wanted to let you know! If you'd like to try out the release candidate now, you can install it with `npm install helmet@next`.

Hope I can be helpful!

**Comment by freben** [comment]
Welp, seems like dependabot pinged us too :) https://github.com/spotify/backstage/pull/1830
