### ISSUE TITLE
Use OAuth state to forward the environment to the handler

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1775]
## Feature Suggestion

The current [EnvironmentHandler](https://github.com/spotify/backstage/blob/75abb422179b036d2be248ff39a7235a5e0b1efd/plugins/auth-backend/src/lib/EnvironmentHandler.ts#L58) implementation uses the `env` parameter in the callback URL. This can cause a bit of confusion as it needs to be part of the configured callback URL of the OAuth clients. We should be able to simplify the configuration by forwarding the environment via state instead.

## Possible Implementation

Use a querystring encoded state, something like `nonce=835v7t83&env=development`. Since the state param is specific to OAuth we also need to figure out how to do the refactor while still supporting SAML and other non-oauth flows. I think it would be reasonable to simply remove support for separate environment configs from SAML, at least until the implementation of that is more mature and we know how to do it and if it's needed.

## Context

https://discordapp.com/channels/687207715902193673/687235481154617364/738061190214713444

**Comment by GoWind** [comment]
@Rugvip I would like to help with this and take a shot at this. Can you assign it to me ?

**Comment by Rugvip** [comment]
@GoWind Awesome, thanks! 😁

**Comment by stefanalund** [comment]
@GoWind @Rugvip is this done?

**Comment by Rugvip** [comment]
Yep! Fixed by #1812
