### ISSUE TITLE
Backstage LDAP Integration

### ISSUE THREAD

**Issue by ainouche** [spotify/backstage#1807]
Hello Team,

Here a new issue, as asked by @stalund, in discord #documentation chanel.

We using backstage for the first time and we are wondering if there is any _concrete example_ (Github repository) to configure LDAP authentication.

FYI, we are using Active Directory authentication for our internal services in our company (Amadeus) .

Thanks in advance,

**Comment by Rugvip** [comment]
Hi!

So there's currently no LDAP integration available yet, and therefore no examples. It's definitely something that we want to add though, and the work to integrate with LDAP depends on a couple of different things. The main one would be to figure out how to represent organizational data inside Backstage, tracked in https://github.com/spotify/backstage/issues/1401. Once that's in place we'd need to implement the actual layer between Backstage and LDAP, whether it's a standalone service, catalog processor, or something else.

Then there's authentication, and I'm not too familar with the options there. When you say Active Directory authentication, does that mean SSO with Kerberos, or something different? Would SAML 2 suffice? :grin:

In the meantime, least for now, we'll repurpose this issue to track LDAP integration instead.

**Comment by ainouche** [comment]
Hi @Rugvip,
First, thanks for your answer.
So, in order to deploy backstage inside our infrastructure, we need it to be integrated with our Enterprise Active Directory (LDAP), by assuming that backstage will map users and groups with backstage RBAC/Permissions model.

As a first integration stage, we need to be able to authenticate through our Active Directory to validate user's passed credentials (login/password).

**Comment by freben** [comment]
Are you intending for the user to enter username and password directly into a Backstage page, rather than deploying Backstage behind an SSO such as Okta or simikar, that handles the actual authentication? Do you employ such a solution for other systems that you use?

**Comment by ainouche** [comment]
Yes, for the time being, we plan to make users enter username and password into a backstage page, but there is a global initiative about Keycloak (https://www.keycloak.org/), which is under study, that will provide in the future an OAuth2 service for our infrastructure. But as I said, this is under study and the assessment of backstage is ongoing.

**Comment by freben** [comment]
Hi! Just to loop back real quick,

The current login methods are sort of focused around refreshable tokens. You can definitely make a login method as you propose, but there isn't a lot in place to base it off of. You'll be logging in on each full page refresh, most likely. Keep us in the loop and let us know if and how we can help out.

Another point is that the logged-in identity isn't used for very much yet. If you are in a state of mostly exploring Backstage, you may be fairly well served by just using the guest login for now. Again, a lot is happening in this space as well, so let us know what you want to achieve / evaluate and we may be able to guide you or discuss future plans.

**Comment by freben** [comment]
Ingestion of LDAP groups and users into the catalog was added with #2732.

**Comment by stefanalund** [comment]
@freben can we close this?

**Comment by freben** [comment]
The ask was about using ldap for logging in. Maybe @Rugvip - any final feedback to give here or shall we close for now?

**Comment by freben** [comment]
We'll make this kind of functionality possible to add as a custom provider as part of #1984

**Comment by ainouche** [comment]
Hi, currently and witing LDAP feature, we implemented the following workaround:
We deployed locally an instance of Keycloak that is able to connect to an LDAP and on another hand offer an OAuth2 interface, that has been plugged into backstage. Everything works fine, except for the logout event, that is not propagated to the Keycloak Identity manager. But this solution is satisfying for the time being.
Thanks again guys @stefanalund, @freben and @Rugvip, for your support.

**Comment by stefanalund** [comment]
@ainouche happy to hear that! Feel free to contribute back any changes/improvements you see possible.

**Comment by ainouche** [comment]
Sure @stefanalund.

**Comment by neilbeukes** [comment]
@ainouche did you guys have to change any scope mappings ? We are using Keycloak 11.2 (latest) to solve this exact issue and we just aren't getting the right fields. `params` and `RawProfile` is undefined. This is using the OAuth2 adapter.

**Comment by ainouche** [comment]
Hi @neilbeukes, thanks for your feedback.
Yes, we did the same with Keycloak and OAuth2 on our side ;-)
The remaining thing to fix is the propagation of Backstage's 'logout' action to Keycloak service.
We are interested in a fix if you have/did one :-)
