### ISSUE TITLE
Add mock data to create-app command

### ISSUE THREAD

**Issue by pianilsson** [spotify/backstage#1824]
## Feature Suggestion

The create-app command renders an empty shell and it would be great if I as a user can click around and get to know the features in Backstage with some mock data. For this purpose you offer the: 
yarn lerna run mock-data

However, to make it easier and more self-explanatory for the user creating a Backstage app, I'd like you to consider adding this same mock data to the create-app if a service catalog isn't yet populated.

**Comment by Rugvip** [comment]
Created https://github.com/spotify/backstage/issues/1833 as a suggestion for covering this and a couple of other use-cases.

**Comment by stefanalund** [comment]
This PR takes a different route but addresses the same problem https://github.com/spotify/backstage/pull/1883.
