### ISSUE TITLE
Include more plugins in the create-app template

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1843]
## Feature Suggestion

Right now the app you get when using `@backstage/create-app` is just a barebones example app with some info on how to get started. At this point I think it makes more sense to include some of the core plugins, like `@backstage/catalog`, `@backstage/scaffolder`, `@backstage/techdocs`, etc.

## Possible Implementation

Plugins are installed as dependencies and wired up in the templated app the same way as is done in the example app in this repo.

We likely want to provide some mock data as well, probably via the method described in https://github.com/spotify/backstage/issues/1833, pending implementation of that.

Include some of the following plugins that the example app has, but probably not all of them:

- [x] @backstage/plugin-catalog
- [x] @backstage/plugin-circleci
- [x] @backstage/plugin-explore
- [x] @backstage/plugin-github-actions
- [ ] @backstage/plugin-gitops-profiles
- [ ] @backstage/plugin-graphiql
- [x] @backstage/plugin-lighthouse
- [x] @backstage/plugin-register-component
- [ ] @backstage/plugin-rollbar
- [x] @backstage/plugin-scaffolder
- [x] @backstage/plugin-sentry
- [x] @backstage/plugin-tech-radar
- [x] @backstage/plugin-techdocs
- [x] @backstage/plugin-welcome

## Context

When the `create-app` template was created Backstage was still in Phase 1, without any service catalog or things surrounding it. We're now in Phase 2 and want to make it easy to get those parts up and running too.

**Comment by ayshiff** [comment]
Can I grab this one @Rugvip ?

**Comment by Rugvip** [comment]
@ayshiff sure! Thanks again! :grin:

I think we can start with the catalog and scaffolder plugins and then go from there?

**Comment by stefanalund** [comment]
Thanks, this is much needed and appreciated.

**Comment by ayshiff** [comment]
> @ayshiff sure! Thanks again! 😁
> 
> I think we can start with the catalog and scaffolder plugins and then go from there?

Yes, sure ! 👍

**Comment by stefanalund** [comment]
@Rugvip @ayshiff I've checked the boxes for which plugins I think should be available. Thanks for taking this on 🎯

**Comment by angeliski** [comment]
Hey @stefanalund 

What do you think about making the create-app ask about which plugins I would like to use?
Something like the [vue-cli](https://cli.vuejs.org/guide/creating-a-project.html#vue-create) does.
![vue-create](https://user-images.githubusercontent.com/1574240/89955384-49d91000-dc09-11ea-9f16-1806bdbd0838.png)

Would be nice remove sentry and add rollbar in runtime 

Do you need any help here @ayshiff?

**Comment by Rugvip** [comment]
Let's do this in a couple of iterations, starting with only the catalog and scaffolder plugins, and required dependencies of those. Getting this in well help people using `create-app` a lot, so better to get initial minimal implementation merged and then improve on that.

@angeliski Regarding plugin selection, we're definitely heading towards that, but it's really tricky to implement on top of some of the existing patterns, so will likely have to wait a bit.

**Comment by angeliski** [comment]
Make sense to me @Rugvip is leaner and fast for feedback
