### ISSUE TITLE
[Plugin] Implement my own backend plugin

### ISSUE THREAD

**Issue by ynambiar** [spotify/backstage#1868]
Hi, I would like to hook up my own backend database to Backstage's frontend UI. From what I can see now, the catalog model is tightly coupled with the existing database model, and I'm not sure how creating a plugin for my backend database would work in the existing framework. Is there documentation that explains how to do this?

Thanks!

**Comment by freben** [comment]
Hi! What data is it that you want to present?

**Comment by ynambiar** [comment]
I'd like to be able to list and display API specs which the existing backend implementation does really well. I'd just like the ability to use my own backend (e.g. CosmosDB) if that's possible.

**Comment by freben** [comment]
OK! I'll unfortunately have to get back to you about this next week, I've left for the day. But let's talk more!

**Comment by ynambiar** [comment]
Sounds good, thanks!

**Comment by ynambiar** [comment]
Hey @freben, any information on how I can do this?

**Comment by freben** [comment]
Sorry, I have been swamped recently.

You say that the current backend implementation displays API specs, would you mind elaborating on what that means? I am a bit unclear on what you have and where you want to go with it.

However, you also say that you want to back it with CosmosDB. The backend plugins that come out of the box are written using [Knex](http://knexjs.org/). It does not list CosmosDB as a supported database, but I am not familiar with the capabilities of CosmosDB to say whether that poses a problem or not.

However if you make some NEW plugin to the backend, there's nothing stopping you from making that plugin talk to any technology that has a functioning js driver.

**Comment by ynambiar** [comment]
Thanks!

I mentioned CosmosDB as an example of a backend datastore, but I think my real question is around having Backstage call into our backend API instead of calling into the catalog-backend plugin and following the processor/yaml model that's currently defined. And like you mentioned, I think I could definitely create a new plugin to do this - was just curious if there's documentation or list of integration requirements I could use for reference?

**Comment by freben** [comment]
Ah - yes you may replace the entire catalog backend implementation even though it's not a recommended path at this point - you can make the frontend plugin make requests to [a different endpoint]https://github.com/spotify/backstage/blob/master/packages/app/src/apis.ts#L157), including one that you happen to [be proxying](https://github.com/spotify/backstage/blob/master/app-config.yaml#L13) to your very own API.

However, your API of course has to conform to the built in catalog API exactly, and that can be a moving target particularly in these alpha times. What you may want to do is to build an ingestion from that third party system into our catalog, or build a backend plugin that exposes the catalog API but does requests to your service and does payload translation on the fly. It kind of depends on what the use case is, how fast your service is at responding to interactive queries, and how much they differ semantically.

**Comment by freben** [comment]
Can you describe your existing catalog a bit? Is it written entirely in-house or is it a product of some sort?

**Comment by stefanalund** [comment]
I may be wrong but they way I understand the question, you don’t really want to replace the catalog but just call out to a backend that exposes and API for your plugin?

If that’s correct then there is not reason to go through the catalog at all.

**Comment by ynambiar** [comment]
Thanks for the responses! 

@freben, since the defined catalog model is a moving target like you said, we'd like to be able to either completely sidestep it or replace it with our own model. I think @stefanalund correctly stated that we just want to be able to make calls to a backend that exposes an API for our plugin...but I don't see how to do that without using the catalog model (which requires a locationURL, component yaml, etc.). Is there a straightforward way to use a different model, say something written in-house that isn't location based? Which plugins/parts of the code would we need to change?

**Comment by freben** [comment]
Ok!

So, for starters, a frontend plugin will always be at liberty to do essentially anything it wants. At one extreme end of the scale, you could always make a plugin that has absolutely no relation to the catalog or anything else, but instead just issues `fetch` queries to your existing backend and renders the results. We have a lot of plugins internally that do things like that. You may or may not choose to use our backend and proxy facilities to do so, it's all essentially optional.

However the cost of that, if it's catalog related  data, is that it will tend to be a bit of an isolated island of functionality. OTHER parts of the ecosystem may rely on the existence of a catalog - and the shape of the entities is part of that API contract. For example, the scaffolder may want to access template data stored in the catalog, and it needs to understand the data format to do so.

This may or may not be perfectly fine, depending on your needs and plans for how you intend to use Backstage. You can write features any way you please, but to unlock the full power of the integrations and of the rapidly growing ecosystem of plugins, they need to have a common language between each other.

Maybe we can help you find a path for getting your entity data into our catalog form?

**Comment by ynambiar** [comment]
Got it, thank you for that explanation. At the moment, my team is still in the investigation phase and we don't yet have a concrete design for our entity model. The options you described, however, make a lot of sense and give us a place to start. I will let you know if I have more questions as we move forward. Thank you!

**Comment by stefanalund** [comment]
Ok! Closing this for now then.
