### ISSUE TITLE
[plugin-scaffolder-backend] Problems on try generate in a new project

### ISSUE THREAD

**Issue by angeliski** [spotify/backstage#1881]
When a new project is created using the `@backstage/create-app`, the scaffolder functionality isn't working.
After fix the #1874 I got some errors on try that flow:
- [P1] If I try use a user account (and not a org) the process break on get info
- [P2] When a setup a new project using a org, the process break on try init the git repo (permission denied)

## Expected Behavior
The scaffolder should run without errors

## Current Behavior
The process is interrupted by a error in console.
[P2]
![permission error](https://user-images.githubusercontent.com/1574240/89739780-ce852c00-da59-11ea-8ef4-a023ef958eba.png)

## Possible Solution
- [P1] Maybe something is wrong [here](https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts#L48). I will check to try find the problem
- [P2] The docker image is creating the project template as root user. But I don't know who create/update the permissions to current user 
## Steps to Reproduce

1. Run a `npx @backstage/create-app`
2. Configure the app frontend to use the [@backstage/plugin-scaffolder](https://www.npmjs.com/package/@backstage/plugin-scaffolder). Repo example: [angeliski/test-backend](https://github.com/angeliski/test-backend/blob/master/packages/app/src/plugins.ts)
3.Start front/backend projects
4. Add a a template to generate. Example:
```
curl \                                                                                                                 
    --location \
    --request POST 'localhost:7000/catalog/locations' \
    --header 'Content-Type: application/json' \
    --data-raw "{\"type\": \"github\", \"target\": \"https://github.com/spotify/cookiecutter-golang/blob/master/template.yaml\"}"
```
5. Try create a new project

## Context
That bug is breaking the software creation templates feature.

Console logs:
[P1]
```
info: 127.0.0.1 - - [09/Aug/2020:19:08:56 +0000] "GET /scaffolder/v1/job/617a458b-c4b8-4008-a66b-a08ce01e48a8 HTTP/1.1" 200 - "http://localhost:3000/create/springboot-template" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
 {"type":"incomingRequest","service":"backstage","timestamp":"2020-08-09T19:08:56.318Z"}
deu ruim RequestError [HttpError]: Not Found
    at /usr/workspace/test-backend/node_modules/@octokit/request/dist-node/index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GithubPublisher.createRemote (webpack-internal:///../../node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:105:20)
    at async GithubPublisher.publish (webpack-internal:///../../node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:98:23)
    at async Object.handler (webpack-internal:///../../node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:447:33)
    at async JobProcessor.run (webpack-internal:///../../node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:353:35) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 09 Aug 2020 19:08:56 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'BE0A:6A6D:10607E8:177B431:5F3049C8',
    'x-oauth-scopes': 'admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, delete_repo, gist, notifications, read:packages, repo, user, workflow, write:discussion, write:packages',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4997',
    'x-ratelimit-reset': '1597002880',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/orgs/angeliski/repos',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.0.3 octokit-core.js/3.1.2 Node.js/12.18.3 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"name":"backstage-java-test"}',
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/repos#create-an-organization-repository'
}
info: 127.0.0.1 - - [09/Aug/2020:19:08:57 +0000] "GET /scaffolder/v1/job/617a458b-c4b8-4008-a66b-a08ce01e48a8 HTTP/1.1" 200 - "http://localhost:3000/create/springboot-template" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
```

## Your Environment

Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.18.3 - ~/.asdf/installs/nodejs/12.18.3/bin/node
    Yarn: 1.22.4 - ~/.asdf/shims/yarn
    npm: 6.14.6 - ~/.asdf/installs/nodejs/12.18.3/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 79.0
  npmPackages:
    typescript:  3.9.7

**Comment by angeliski** [comment]
The problem [P1] was mapped [here](https://github.com/spotify/backstage/blob/master/plugins/scaffolder/src/api.ts#L55),so I believe could be ignored :smile:

**Comment by benjdlambert** [comment]
Hey @angeliski!

Thanks for trying out the new Software Templates! 💯 

Yep, you're 100% correct, right now, it only supports organisations in github, I think that the issue that you're having right now is because the `GITHUB_ACCESS_TOKEN` environment variable doesn't have the right access to either create repositories in the Organisation, or push commits to it.

We're looking at changing the whole authentication part of backstage with Github to use Github Apps instead, and then the last part of the flow when creating things in the scaffolder will be replaced with a drop down of the places that you have authorised the github app rather than it being like it is right now.

That work is currently in RFC phase, but we should be creating tickets and prioritising that later on this week.
https://github.com/spotify/backstage/issues/1565

Optionally, if you're running things locally you can change the contents of
https://github.com/spotify/backstage/blob/master/plugins/scaffolder/src/api.ts#L55 to `isOrg: false` and it should create as normal in your personal account.

Hope this helps, let me know if you have any trouble getting it working! 👍

**Comment by angeliski** [comment]
Hey @benjdlambert 

The Software Templates feature is really amazing. I just created an org to test in my local environment.
But the docker issue [P2] is really tricky, I didn't find a way to fix that

Could you see if your team has any idea about that?
I can work to implement the solution if you can provide a path for this

Thank you for the great work

**Comment by benjdlambert** [comment]
@angeliski ah ok, so you mean that it creates files as root user?

What's your use case? Are you trying to modify the files after docker has done it's stuff?

I think there's a maybe simple fix, just need to know what you're trying to do to see if it's going to help.

We should perhaps get the docker container to write files using your `USERID` and `GROUPID` which would make them modifiable. I'm just gonna get some food and I can take a look at trying to fix that.

**Comment by angeliski** [comment]
@benjdlambert When the files are created as the root user, the flow (on git init) breaks.
Something like that ![](https://user-images.githubusercontent.com/1574240/89739780-ce852c00-da59-11ea-8ef4-a023ef958eba.png)

The problem is, after create the template project, the backstage couldn't push to the remote

Make sense?

**Comment by benjdlambert** [comment]
@angeliski ah now I see what the issue is, seems like docker on Linux behaves a little different to what we've been running on. Give me 20 mins and i think I can have a fix for you to try locally and we can do a release as quick as possible if it works

**Comment by benjdlambert** [comment]
@angeliski are you on discord? Might be better to sync up and work through fixing this. Reach out to me, `@blam`
