### ISSUE TITLE
[RFC] Shared database helpers & config

### ISSUE THREAD

**Issue by andrewthauer** [spotify/backstage#1882]
The database code in the `backend-example` is currently a bit verbose. I created some code in an example backstage app that could be potentially useful in backstage core.

## Feature Suggestion

- Shared database connection code that could be added to `@backstage/backend-common`
- Support for `postgres` database uri connection strings (e.g. `postgresql://postgres@localhost:5432/dbname`)
- Database migrations for creating plugin databases + helpers
- Making `knexfile` use config + common connection code.

## Possible Implementation

> See https://github.com/andrewthauer/backstage-example/pull/1 complete examples with code.

```yaml
backend:
  POSTGRES_URL: `postgresql://postgres@localhost:5432/backstage`
```

```ts
// packages/backend/src/index.ts
function makeCreateEnv(config: ConfigReader) {
  return (plugin: string): PluginEnvironment => {
    const logger = getRootLogger().child({ type: 'plugin', plugin });
    // single line to create knex client
    const database = createDatabase(config, `backstage_plugin_${plugin}`);
    return { logger, database, config };
  };
}

// packages/backend/src/index.ts
async function main() {
  const configs = await loadBackendConfig();
  const config = ConfigReader.fromConfigs(configs);

  // run migrations to create databses (e.g. backstage_plugin_auth & backstage_plugin_catalog)
  const migrationsDir = path.resolve(__dirname, '../migrations');
  await runDatabaseMigrations(createDatabase(config), migrationsDir);

  // ...
}
```

```ts
// packages/backend/knexfile.ts
import path from 'path';
import { loadBackendConfig, getDatabaseConfig } from '@backstage/backend-common';
import { ConfigReader } from '@backstage/config';

module.exports = async () => {
  const configs = await loadBackendConfig();
  const config = ConfigReader.fromConfigs(configs);
  const dbConfig = getDatabaseConfig(config);

  return {
    ...dbConfig,
    migrations: {
      directory: path.resolve(__dirname, './migrations'),
    },
  };
};
```

## Context

Looking to get some feedback on what portions might be useful to port to backstage core. I can create PR's to get the ball rolling for anything that seems relevant.

**Comment by dtuite** [comment]
The only thing I would add, (and this is probably off topic - 😄 ), is that I would love to see SSL verification support. 

I've hacked my own like this

```ts
port: config.getOptionalNumber('backend.postgresPort'),
host: config.getString('backend.postgresHost'),
user: config.getString('backend.postgresUser'),
password: config.getString('backend.postgresPassword'),
database: `backstage_plugin_${plugin}`,
ssl: {
  ca: fs.readFileSync(config.getString('backend.postgresPathToCa')),
  rejectUnauthorized: true,
},
```

IMO, the config names should be camelCased too.

**Comment by andrewthauer** [comment]
It might also be worth considering nesting the database config under an actual `database` key:

```yaml
backend:
  database:
    client: 'pg'
    connection:
      host: ...
      ssl: ...
      # ...
```

As an added bonus, this should make it easier to re-use settings with yaml anchors if desired.

**Comment by freben** [comment]
I like the idea of a dedicated `database` root key, that a dedicated common function can consume and parse to emit a Knex config.

The one complication that I can see is if we don't cleanly permit varying types on config values. That is, for a one-to-one mapping to Knex, the config key `database.connection` would need to be able to be both a string and a complex object.

```yaml
database:
  client: pg
  connection: postgresql://postgres@localhost:5432/dbname
```

vs

```yaml
database:
  client: 'pg'
  connection:
    host: localhost
    ...etc
```

**Comment by andrewthauer** [comment]
@freben - One downside from taking the `connection` config directly is you can't modify things like the actual database. In my [example code](https://github.com/andrewthauer/backstage-example/pull/1/files#diff-281536d0797fddcdb23b7023eb95925dR12), I am parsing the uri and able to swap out the database name for each plugin. I also didn't realize `knex` supported passing the `uri` as a string to `connection`. It didn't seem documented anywhere :(

**Comment by freben** [comment]
Right, maybe it can be broken apart into separate helper functions, so you can get out a uri (built from parts if the config actually was an object) or an object (parsed out of a uri if that's what the config was) etc. Or, have a single call but it can accept an overrides object parameter.

I guess then you are at a level where you know your own config and what you want to do with it, rather than doing a generic thing.

**Comment by andrewthauer** [comment]
@freben - I have the draft PR #1915 up, which could currently be used in some of the following ways:

```ts
const dbConfig = config.get('backend.database');
const database = createDatabase(config, `backstage_plugin_${plugin}`);

// or

const database = knex({
  pg: 'pg'
  connection: buildPgConnectionConfig(dbConfig, `backstage_plugin_${plugin}`),
}};
```

However, I'm wondering if this is more what your after?

```ts
const database = createDatabase(
  getDatabaseConfig(dbConfig, { database: `backstage_plugin_${plugin}` }),
)
```

The caveat is the override object is highly dependent on the client type, so passing through directly and overriding could cause issues. I suppose `knex` will hopefully throw an error right away so it's clear to the problem. Another option would be ignore / strip keys that are not allowed for particular client types.

**Comment by freben** [comment]
My thinking goes something like this:

* Overrides are an optional feature, and one that may be used by a smaller number of people (don't have anything to back this statement up, it's frankly mostly gut feel :))
* The default should be sane and simple - basically, a raw passthrough of what's in the config directly to knex should be the "common path"

In the case that overrides ARE present, the points below apply:

* The code making the override is probably in `packages/backend`, where it's completely controlled by the org in question
* The choice of database, for that org, is basically known beforehand and static. They will be fine with the fact that if they use overrides, then it's a basic deep-merge of objects, and that if they try to use a connection string in conjunction with overrides, an error will be thrown

Does that make sense? It would reduce the problem scope immensely and not require any parsing or per-database logic or so.

**Comment by freben** [comment]
@timja may want to pitch in too ^

**Comment by andrewthauer** [comment]
@freben - Yes, I'm in complete agreement. #1915 mostly follows this line of thinking now. I've tried to keep these as small building blocks, but I think there is still some room for improvement.

The common cases I see for overriding seem to be:

- swapping the database name for separate plugin databases
- SSL - injecting the contents of a certificate that needs to be read in from a file (since a pass through won't suffice). I'm not sure if `node-postges` supports path based strings but those should work fine with a pass through.

Using straight pass through and deep merging will work for both of these except when using a `postgres` connection string. I looked into this a bit further and seems `knex` uses [node-postgres](https://node-postgres.com/features/connecting) which in turn uses [pg-connection-string](https://github.com/iceddev/pg-connection-string) for this. It looks like `pg-connection-string` has support for handling `ssl` keys. https://github.com/iceddev/pg-connection-string/blob/master/index.js#L65. If we are willing to pull in a dependency on this (or maybe treat it as an optional peer), this could be used instead. I don't see that it supports some of the timeout related options which would probably require overrides on top of it as well.

I'd like to answer the following questions:

- Do we want to provide a single common `createDatabase` method that handles all known cases or do we want the `packages/backend` to use the underlying database specific functions?
- Do we want to use `pg-connection-string` to handle connection string handling when having to do overrides?

**Comment by Rugvip** [comment]
@andrewthauer Regarding reading certificate files, I think we should be able to rely on file secrets for that: https://github.com/spotify/backstage/blob/master/docs/conf/writing.md#file-secrets. That leaves it open for other ways of bringing in certificates too

**Comment by andrewthauer** [comment]
> @andrewthauer Regarding reading certificate files, I think we should be able to rely on file secrets for that: https://github.com/spotify/backstage/blob/master/docs/conf/writing.md#file-secrets. That leaves it open for other ways of bringing in certificates too

Agreed. This would work nicely out of the box for non connection string based database configs.

**Comment by freben** [comment]
And I don't at all mind bringing in the connection string parser lib dependency if that's usable. And that would mean that the only time that it was ever invoked, was if (1) it's a pg connection string, and (2) overrides were specified, correct?

**Comment by freben** [comment]
I think it can still be all exposed as a single function, to answer your first point.

**Comment by andrewthauer** [comment]
I believe everything discussed here in regards to the database connection, ssl, etc. is covered in #1915 now.

**Comment by andrewthauer** [comment]
The only other use cases here not covered by #1915 are related to migrations. It might make sense to cover that in a separate issue since the majority of this thread is relation he the configuration and db connection.

Specifically, I'm thinking about:

- Updating the knexfile's to use the new connection helpers
- Ability to create new plugin databases easily on a newly provisioned db (possibly using pgtools)
- Common migration API for plugins with the ability to register and run them as a pre-deploy step

**Comment by nikek** [comment]
I'll close this ticket, but feel free to open issues for the additional improvements.
