### ISSUE TITLE
No progress indicator during plugin creation

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#190]
I do not seem to get the same visuals as others when creating a plugin. There is no progress indicator and some emojis seems to be missing: 

<img width="1180" alt="Screenshot 2020-03-07 at 14 21 05" src="https://user-images.githubusercontent.com/190856/76144331-5fa54080-607f-11ea-9317-4e7cd36fdde6.png">

**Comment by Rugvip** [comment]
Fixed by #437
