### ISSUE TITLE
Migration fails on 'add_bootstrap_location' for postgres

### ISSUE THREAD

**Issue by andrewthauer** [spotify/backstage#1937]
I started seeing the following error when trying to run the backend on the latest code:
```
migration file "20200809202832_add_bootstrap_location.js" failed
migration failed with error: insert into "locations" ("id", "target", "type") values ($1, $2, $3) - invalid input syntax for type uuid: "bootstrap"
```

It seems related to #1890, however, I thought postgres migrations were run in CI now, so not sure how this crept through.

**Comment by Rugvip** [comment]
Yep, the bug is fixed by #1935, but I'll do a proper fix of the actual issue of tests not being run for that code :grin:
