### ISSUE TITLE
[Auth] Add Microsoft Authentication

### ISSUE THREAD

**Issue by javaniecampbell** [spotify/backstage#1967]
## Summary

In order to use the azure pipeline api it requires a personal access token which is unique to that user with includes the permissions and access needed for a given project.

The basic steps required to use the OAuth 2.0 authorization code grant flow to get an access token from the Microsoft identity platform endpoint are:

### Steps: 

1. Register your app with Azure AD.
2. Get authorization.
3. Get an access token.
4. Call Microsoft Graph with the access token.
5. Use a refresh token to get a new access token.

## Project website (if applicable)

- [Azure DevOps Node API](https://www.npmjs.com/package/azure-devops-node-api)

- [Personal Access Tokens to Authenticate](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)

- [Authorize Apps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops)

- [Get access on behalf of a user](https://docs.microsoft.com/en-us/graph/auth-v2-user)

## Context

All of which is to be give the access to the user with build info, release, build status, release status, git repository,  commits etc.

```javascript
import * as azdev from "azure-devops-node-api";
 
// your collection url
let orgUrl = "https://dev.azure.com/yourorgname";
 
let token: string = process.env.AZURE_PERSONAL_ACCESS_TOKEN; // e.g "cbdeb34vzyuk5l4gxc4qfczn3lko3avfkfqyb47etahq6axpcqha"; 
 
let authHandler = azdev.getPersonalAccessTokenHandler(token); 
let connection = new azdev.WebApi(orgUrl, authHandler); 
```

**Comment by javaniecampbell** [comment]
#1966  May be a blocker any suggestions, I was pointed to these to try and configure in master #1950

#1958 #1915

**Comment by stefanalund** [comment]
Looks like there is already an issue for this https://github.com/spotify/backstage/issues/348 -- and now also a PR to fix it: https://github.com/spotify/backstage/pull/1990 🎉
