### ISSUE TITLE
Review architectural diagrams in the documentation and update as requried

### ISSUE THREAD

**Issue by leemills83** [spotify/backstage#1980]
Review all architectural diagrams and update as required. 

As part of this we decided to work with PlantML.

**Comment by prakhargurunani** [comment]
@leemills83 I am interested in contributing to this. Can you describe more about this issue..

**Comment by OrkoHunter** [comment]
Related https://github.com/spotify/backstage/issues/1645

**Comment by marcuseide** [comment]
Closing this in favor #1645
