### ISSUE TITLE
Docs from backstage.io/docs having markdown as description

### ISSUE THREAD

**Issue by shmidt-i** [spotify/backstage#1994]
E.g. https://backstage.io/docs/features/techdocs/techdocs-overview

> TechDocs Documentation · Backstage
> \#\# What is it?

The problem being that .md files in /docs folder of the repo doesn't have `description` document header field (https://docusaurus.io/docs/en/doc-markdown#documents).

So the solution is to go through all files and add `description` for each one of them ;)

**Comment by iamrajiv** [comment]
@shmidt-i Can I work on this issue?

**Comment by stefanalund** [comment]
@iamrajiv please do, thanks!

**Comment by iamrajiv** [comment]
@shmidt-i What should I give in `description:` should I give same as of `title:` in very `.md` file

**Comment by iamrajiv** [comment]
@stefanalund What should I give in `description:` should I give same as of `title:` in very `.md` file.

**Comment by shmidt-i** [comment]
Can be first paragraph of the text, just cleared from image tags or any markdown.
E.g.
https://backstage.io/docs/overview/what-is-backstage
<img width="577" alt="Screenshot 2020-09-14 at 15 45 42" src="https://user-images.githubusercontent.com/5012901/93093759-5ab1f100-f6a1-11ea-9f31-ade8cd5bd3b2.png">

Imagine string `![service-catalog]...` being replaced by 
```
Backstage is an open platform for building developer portals. Powered by a centralized service catalog, Backstage restores order to your microservices and infrastructure. So your product teams can ship high-quality code quickly — without compromising autonomy.

Backstage unifies all your infrastructure tooling, services, and documentation to create a streamlined development environment from end to end...
```
