### ISSUE TITLE
Backstage.io/docs dark mode styling issues

### ISSUE THREAD

**Issue by shmidt-i** [spotify/backstage#1995]
E.g. https://backstage.io/docs/features/techdocs/techdocs-overview
![image](https://user-images.githubusercontent.com/5012901/90485859-68269a80-e138-11ea-8d5f-fb7512f7a302.png)

## How to solve
Look into adjusting styles for docusaurus - https://v2.docusaurus.io/docs/styling-layout

**Comment by Fox32** [comment]
I would also add: https://backstage.io/docs/features/software-catalog/system-model

![image](https://user-images.githubusercontent.com/648527/90489367-7925da80-e13d-11ea-93de-4c3620c94abe.png)

Hard to see, but there are arrows with text between the boxes. However making them white, makes it difficult to view the files on GitHub...

**Comment by stefanalund** [comment]
@Fox32 yep, I'm on it!

**Comment by stefanalund** [comment]
Fixed https://backstage.io/docs/features/techdocs/techdocs-overview
