### ISSUE TITLE
Backstage.io: Change mobile nav bar to hamburger menu

### ISSUE THREAD

**Issue by fengypants** [spotify/backstage#2008]
## Feature Suggestion

Change the navigation bar to a hamburger menu on the mobile version of the microsite. Here's an example of how it looks now:
![Image from iOS](https://user-images.githubusercontent.com/46946747/90529508-cefc8180-e141-11ea-9ad4-6fddb4075765.png)

## Possible Implementation

@katz95 previously provided specs and icon assets here:
https://github.com/spotify/backstage-microsite/files/4369934/Mobile.Menu.Assets.zip

Screenshot examples of how a new hamburger menu would look:
![77304142-50b3c480-6cf4-11ea-9348-a4dc7ab4de37](https://user-images.githubusercontent.com/46946747/90526904-ef770c80-e13e-11ea-84cf-788585cc53ae.png)
![77304055-337ef600-6cf4-11ea-9491-748c9e3f7036](https://user-images.githubusercontent.com/46946747/90526907-f00fa300-e13e-11ea-8130-acecd5d495a7.png)

(Note: the screenshot examples above use the old site/old menu items. So this is just reference for the design/placement of the hamburger icon, the close (X) icon, the list of menu items, and the field of dots for the menu background.)

## Context

This is picking up [an issue from the old repo](https://github.com/spotify/backstage-microsite/issues/113#issue-586075394), which was opened by @katz95 and worked on by @mateusmarquezini to make the mobile nav more responsive than it was before. 

We've since updated the microsite and added even more items to the navbar, so it would be great to get a hamburger menu in here. Now that we've been updated to Docusaurus 2.0, hopefully this is more doable!

**Comment by stefanalund** [comment]
Ideally it should also be possible to navigate the documentation structure on mobile as well. But let's consider that a bonus for now 😏

**Comment by OrkoHunter** [comment]
The Documentation navigation menu seems to be hidden by the website nav bar. Adding a margin to `.docMainWrapper.wrapper` class should make the docs nav bar appear again. See here

![Screenshot 2020-09-11 at 11 48 03](https://user-images.githubusercontent.com/8065913/92906311-a9068c00-f424-11ea-9ccf-8ec218001f8c.png)

**Comment by OrkoHunter** [comment]
@stefanalund Here you go! 😄 
https://github.com/spotify/backstage/pull/2431

**Comment by stefanalund** [comment]
Thanks for fixing this @OrkoHunter! I know it is not identical to the UX solution suggested in this ticket, but at least it works now.
