### ISSUE TITLE
Plugin marketplace

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#2009]
## Feature Suggestion

As the ecosystem of [Backstage plugins](https://github.com/spotify/backstage/tree/master/plugins) continues to grow it is becoming increasingly hard to keep track of what plugins are available. To solve this we imagine a "Plugin marketplace" that can:

* Help discover what plugins are available
* Make it clear who (user or company) that contributed it
* Show title, description, category (CI, Machine Learning, Services, Monitoring, ...)
* Link out to docs (preferably including installation instructions)
* _Future: allow users to sort based on various metadata_

## Possible Implementation

* Create a new page on [backstage.io](https://github.com/spotify/backstage/tree/master/microsite) based on [Docusaurus](https://docusaurus.io).
* Make it possible to submit a plugin to be included by adding static information, including a README.
* Add "PLUGINS" link to the main navigation in backstage.io.

## Context

Grafana has a very nice implementation of this that could serve as inspiration:

![Screenshot 2020-08-18 at 16 47 18](https://user-images.githubusercontent.com/190856/90528280-bbb5da00-e172-11ea-9916-91ecf39f01c5.png)

https://grafana.com/grafana/plugins

**Comment by iain-b** [comment]
@stefanalund I'd like to pick this up if that's ok? Thanks

**Comment by javaniecampbell** [comment]
Hey @stefanalund I believe #1683 and this feature might be related can you guy looking into both as a pair?

**Comment by stefanalund** [comment]
> Hey @stefanalund I believe #1683 and this feature might be related can you guy looking into both as a pair?

Not sure I agree :) I think these two issues should be tackled independently.

**Comment by Fox32** [comment]
As an alternative to the microsite: Deploy a backstage instance and use it as a catalog 😄 But I think a website would be better 😉

**Comment by iain-b** [comment]
@stefanalund I’ve had a look into this and I've got some questions. 
Given the micro site is static it looks like we'd have to keep the plugin data in files in the microsite repo and use those to generate the plugins page (I'm open to better ideas). That being the case to add a plugin the best I can propose is the user enters the required information and we redirect them to GitHub to create an issue from template. Does that sound acceptable?
Also, regarding design this goes a bit beyond the tools in the docusaurus framework. I'm happy to do my best for now to build something along the lines of the Grafana sample but is there anyone I can/should talk to regarding styles?

**Comment by stefanalund** [comment]
@iain-b thanks for checking in. 

I think we can live with people adding plugins themselves by submitting a PR with static information/config for their plugin. If they are sophisticated enough to build a plugin I’m sure that should be fine for now. 

When it comes to design, my suggestion is to do a first barebones iteration inspired by Grafana, and then we can ask @katz95 to have a look later on.
