### ISSUE TITLE
TechDocs: As a consumer of docs in Backstage, I want to see breadcrumbs of the current documentation page I am looking at

### ISSUE THREAD

**Issue by garyniemen** [spotify/backstage#2029]
`TechDocs > MkDocs`

<img width="500" alt="Screen Shot 2020-09-21 at 2 30 18 PM" src="https://user-images.githubusercontent.com/25153114/93766645-fe0d8380-fc16-11ea-97bf-4e96da601385.png">

These breadcrumps are hyperlinks to the page.

# Possible Implementation

Can use this UI component https://material-ui.com/components/breadcrumbs/

On individual TechDocs page, we have access to path. We can use the path to show the breadcrumbs.

**Comment by emmaindal** [comment]
@katz95 do we have any design ready for this that we can attach to this issue?

**Comment by mahmoodhosseini** [comment]
Hi, I'd like to work on this.

**Comment by soapraj** [comment]
@mahmoodhosseini - Awesome! Assigning this to you.
