### ISSUE TITLE
Improve Information card on Overview pages

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#2039]
## Feature Suggestion

The information card on the overview page should show the most relevant metadata about the entity. Today it is just a simple, unweighted, list of attributes:

![Screenshot 2020-08-20 at 10 34 12](https://user-images.githubusercontent.com/190856/90746285-c25a6380-e2d0-11ea-8674-c4a2280898de.png)

Prior art (from Spotify's internal dataset information card):

![Screenshot 2020-08-20 at 10 51 12](https://user-images.githubusercontent.com/190856/90749004-2f6ef880-e2d3-11ea-83dc-12f6b08e83cd.png)

**Comment by Fox32** [comment]
Having a more styled and specialized component would allow to display the tags properly 👍

**Comment by stefanalund** [comment]
@Fox32 for sure! That will definitely be part of an updated design.

**Comment by katz95** [comment]
###Updated About Card

Please check out the specs in our Figma file, which you can access by duplicating from [here](https://www.figma.com/community/file/850673348101741100).

![About Card](https://user-images.githubusercontent.com/61153904/91305446-5afa5300-e7ab-11ea-95f7-a6875c85e4a5.png)

You can click into the card to access the different specs.

<img width="1485" alt="Screenshot 2020-08-26 at 2 50 21 PM" src="https://user-images.githubusercontent.com/61153904/91305623-94cb5980-e7ab-11ea-8bf9-9d4c397d8fc2.png">
