### ISSUE TITLE
PlantUML diagrams do not appear on backstage.io docs

### ISSUE THREAD

**Issue by freben** [spotify/backstage#2043]
UML diagrams that appear [on GitHub](https://github.com/spotify/backstage/blob/master/docs/auth/oauth.md) do not appear [in the backstage.io docs](https://backstage.io/docs/auth/oauth#sequence-diagram).

**Comment by Patil2099** [comment]
Hi @freben, I would like to help in fixing this issue. Can I get some instructions for it?
