### ISSUE TITLE
Service Catalog - Invalid entity updates feedback loop

### ISSUE THREAD

**Issue by althafh** [spotify/backstage#2053]
Assuming a location has been successfully registered into the service catalog pointing to a valid component entity definition in a YAML file.
Subsequently an invalid modification is made to that entity file that does not conform to the spec and will thus fail validation during the subsequent re-ingestion process during the location refresh loop?

What is the expected feedback loop to inform that the edit made is invalid. since the location refresh loop is happening separately in the catalog backend?

I would separate this into two separate parts
a) Providing feedback to the user during the modification process - i.e. when a user is attempting to modify a file, prior to a commit they need to be able to check whether the entity definition is valid?
b) Providing feedback, post commit. - i.e. when a user has committed an entry that is invalid and has thus failed the re-ingestion process during the location refresh loop.

**Comment by freben** [comment]
In the internal legacy catalog, which has similar semantics, this happens in a few different ways in different steps of the process:

- There is a validator service that anybody can post YAML data to, and receive feedback on its syntax and semantics without modifying anything.
- There is a Maven plugin that uses that service, to give early feedback during the development phase (essentially linting of those files)
- Each entity in the catalog comes with a readonly `state` field essentially, that contains the state and description of the last refresh run. This is used by the Backstage frontend to put a big warning in your face on the entity page that things are wrong (and in what ways they are wrong) and that you should fix them, also linking to the actual file in question so you can easily go to it.

We are looking into designing that state field in the open source catalog right now. It would probably contain more nice stuff than just the refresh information!

That kind of visual feedback in the frontend is a common pattern and something that will definitely be introduced in the open source frontend too.

Maybe it would be a nice feature to be able to do a "dry run" post of entity data to the catalog, that does all of the validation and processing except the final write, to get feedback on its syntax and semantics.

Longer term, it would be cool to publish a living schema for the catalog, making it easy to do for example a VSCode plugin to get completion and validation while writing the file as well.

**Comment by freben** [comment]
And going even farther - It would make sense for the catalog to be able to emit an event stream (e.g. via pubsub) about its inner ongoings that others can latch onto and react to, for example by connecting it to an alerting system.

**Comment by althafh** [comment]
That makes a lot of sense and is exactly what I was looking for so that we can build a linter as that makes the most sense. 

Looking forward to seeing the design of the state field and the validator service and I'm happy to help contribute/work on the implementation if required.

**Comment by freben** [comment]
Hi again, just checking in:

Would it be OK to close this ticket? We will definitely eventually settle the refresh loop feedback.
