### ISSUE TITLE
Add Backstage logo to the Open Graph Image metadata of backstage.io

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#2054]
## Feature Suggestion

When we share https://backstage.io over social media like Twitter, it is good that the card they generate for the link has useful information.

<img width="1080" alt="Screenshot 2020-08-20 at 21 50 05" src="https://user-images.githubusercontent.com/8065913/90818662-26137980-e32f-11ea-9222-9f41dce63d94.png">

Currently Twitter does not get any image to use for backstage.io

## Possible Implementation

~Add an [`og:image`](https://ogp.me/) metadata to the website and use the backstage logo. I think we already have `og:title` and `og:description`, but I might be wrong.~

Use `png` instead of `svg` [here](https://github.com/spotify/backstage/blob/95596b812983f892411c32fa67a5ca7de4b22cd3/microsite/siteConfig.js#L99-101).

## Context

Use https://cards-dev.twitter.com/validator to validate results.

**Comment by OrkoHunter** [comment]
There is already a configuration for it in `microsite/siteConfig.js`

https://github.com/spotify/backstage/blob/95596b812983f892411c32fa67a5ca7de4b22cd3/microsite/siteConfig.js#L99-101

I wonder, why it isn't working 🤔.  [It never has](https://twitter.com/search?q=backstage.io&src=typed_query).

**Comment by OrkoHunter** [comment]
Open Graph protocol does not support SVG 😮 😮 😮 

https://indieweb.org/The-Open-Graph-protocol#Does_not_support_SVG_images
https://stackoverflow.com/questions/21636503/use-svg-as-ogimage

We'll then have to set a png image to `og:image` and `twitterImage`. 💯

**Comment by stefanalund** [comment]
@katz95 any suggestion to what png image to use?

**Comment by iamrajiv** [comment]
@OrkoHunter @stefanalund Can I work on this issue? I think this may work https://github.com/vercel/og-image

**Comment by OrkoHunter** [comment]
Hey @iamrajiv ! Thank you for the interest. :)

IMO the use case for the `og-image` services is when we want "dynamic" open graph images generated for each page.

For Backstage, we can go with a static png image (the logo) for _all_ of our pages.

**Comment by OrkoHunter** [comment]
We have `logo.svg` here - https://github.com/spotify/backstage/tree/master/microsite/static/img

Let's wait for @katz95 to create a suitable `logo.png` for this purpose and we can use that.

**Comment by iamrajiv** [comment]
@OrkoHunter means all the `.svg` images will be converted to `.png` then we will update the `microsite/siteConfig.js`.

**Comment by OrkoHunter** [comment]
#2395 was merged and so this issue is unblocked!

IMO [this image](https://github.com/spotify/backstage/blob/master/microsite/static/logo_assets/png/Backstage%20Identity_Assets_Artwork_RGB_04%20Icon_Teal.png) can be used as the logo. @iamrajiv you can go for it now!

**Comment by iamrajiv** [comment]
@OrkoHunter There are spaces in filename of images in `logo_assets` folder. I would prefer spaces should be removed since in URL of images we have to replace all the spaces with its hex value i.e. `%20`.

**Comment by OrkoHunter** [comment]
It shouldn't be any problem I guess? We can try using `https://raw.githubusercontent.com/spotify/backstage/master/microsite/static/logo_assets/png/Backstage%20Identity_Assets_Artwork_RGB_04%20Icon_Teal.png` to link to the image.

**Comment by iamrajiv** [comment]
@OrkoHunter Yeah I have done the same in #2401.
