### ISSUE TITLE
[TechDocs] Add PlantUML support to the techdocs container

### ISSUE THREAD

**Issue by emmaindal** [spotify/backstage#2068]
Suggested extension: https://github.com/mikitex70/plantuml-markdown

But feel free to suggest other extensions that are compatible with MkDocs

**Comment by andrewthauer** [comment]
Thanks @emmaindal. The `mdx_truly_sane_lists` plugin is probably the most important for us since it fixes nested bullet spacing issues since `python-markdown` does not follow `commonmark` exactly.

It might be useful to allow the docker image to be customized? I can foresee someone just using the techdocs image as a base and then installing some additional mkdocs plugins and away they go (assuming they include them in their `mkdocs.yml` file.

**Comment by emmaindal** [comment]
@andrewthauer that sounds like an extension we should definitely add. The differences between python flavoured markdown list syntax and github flavoured markdown has been something we have struggled with before. Does the `mdx_truly_sane_lists` cover the "empty line before list starting" problem as well? 

I love the idea of having the docker image to be customized and I think we will see more need for this in the future as TechDocs will be used with different needs. If you want to give it a go, feel free to open a PR 😄

**Comment by andrewthauer** [comment]
> @andrewthauer that sounds like an extension we should definitely add. The differences between python flavoured markdown list syntax and github flavoured markdown has been something we have struggled with before. Does the `mdx_truly_sane_lists` cover the "empty line before list starting" problem as well?

@emmaindal - I believe it does handle empty lines like you are referring to https://github.com/radude/mdx_truly_sane_lists#features. We also had a lot of annoying problems before finding this plugin. For instance running prettier formatting on the markdown causes many issues. Everything seemed to clear up and be more predictable after starting to use it.

> I love the idea of having the docker image to be customized and I think we will see more need for this in the future as TechDocs will be used with different needs. If you want to give it a go, feel free to open a PR 😄

I'll create an issue for the custom docker now. I've been able to successfully integrate our current s3 based storage into backstage as is. I'd love to migrate our custom build / publish over to techdocs at some point, but we have a few custom use cases that are not supported. One is integrating API docs (built at CI time), which should be portable to the new `api-docs` plugin. The other is generating and created dynamic markdown pages for various diagrams with `graphviz` and `plantuml`. I will loop back at some point to re-evaluate and possibly propose some additional features/changes.

**Comment by emmaindal** [comment]
@andrewthauer please do! Thank you!
