### ISSUE TITLE
Creating repo from template redirect broken: 'Error: Missing ":selectedTabId" param'

### ISSUE THREAD

**Issue by timja** [spotify/backstage#2106]
## Expected Behavior

Redirected to the catalog page

## Current Behavior

White screen instead of redirect, and browser console error:
![image](https://user-images.githubusercontent.com/21194782/91164380-d7ffcc80-e6c6-11ea-8d29-1ea226414b92.png)

```
TemplatePage.tsx?6d01:122 Uncaught (in promise) Error: Missing ":selectedTabId" param
    at l (index.js?d314:1)
    at eval (index.js?d314:22)
    at String.replace (<anonymous>)
    at generatePath (index.js?d314:22)
    at JobStatusModal (JobStatusModal.tsx?6fd6:75)
    at renderWithHooks (react-dom.development.js?a0ac:14826)
    at updateFunctionComponent (react-dom.development.js?a0ac:17059)
    at beginWork (react-dom.development.js?a0ac:18644)
    at HTMLUnknownElement.callCallback (react-dom.development.js?a0ac:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?a0ac:238)
```

![image](https://user-images.githubusercontent.com/21194782/91164334-ca4a4700-e6c6-11ea-8bcf-ffbe09aa5db3.png)

## Possible Solution

fix the bug

## Steps to Reproduce

1. Create a repo from a template
2. ...

## Context

cc @emmaindal I think you were working in this area

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by emmaindal** [comment]
Yay thanks @timja for reporting, we added a note to our project board when we found this as well so I'll switch that out with this issue, much better. A follow-up question, this happens for all templates and not only for the docs template, is that correct?

**Comment by timja** [comment]
> Yay thanks @timja for reporting, we added a note to our project board when we found this as well so I'll switch that out with this issue, much better. A follow-up question, this happens for all templates and not only for the docs template, is that correct?

I expect so, I'm using the springboot template in this case

**Comment by emmaindal** [comment]
> > Yay thanks @timja for reporting, we added a note to our project board when we found this as well so I'll switch that out with this issue, much better. A follow-up question, this happens for all templates and not only for the docs template, is that correct?
> 
> I expect so, I'm using the springboot template in this case

cool, thanks for fast response. So its around the new tab implementation I think.
