### ISSUE TITLE
Missing apis.ts in applications created with @backstage/create-app

### ISSUE THREAD

**Issue by chrisisbeef** [spotify/backstage#2119]
## Expected Behavior

After creating an application, I wanted to add the service catalog to it. Following the instructions located at https://backstage.io/docs/features/software-catalog/installation you are instructed to add a block of code to the `apis.ts` file located in `packages/app/src` 

## Current Behavior

The file is missing from the generated project 

## Steps to Reproduce

1. `npx @backstage/create-app`
2. `packages/src/app/apis.ts` file is not in the project
## Your Environment

- NodeJS Version (v12): v12.18.2
- Operating System and Version (e.g. Ubuntu 14.04): MacOSX Catalina
- Browser Information:

**Comment by soapraj** [comment]
@chrisisbeef Hi! I tried the create-app on the latest version and I do see the `packages/src/app/apis.ts` file created. Do you still see this issue?

**Comment by freben** [comment]
Hey, this seems to be OK in master, so closing for now. Let us know if it still persists for you.
