### ISSUE TITLE
Add test coverage tooling

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#212]
It is useful for packages to be able to see their own test coverage, and to enforce limits on it.

**Comment by OrkoHunter** [comment]
@Rugvip Is this test coverage tooling supposed to be a part of `backstage-cli`? This would mean the packages could run `backstage-cli test --coverage` and get the results.

I am exactly sure how can these coverage change limits be enforced on package level. In my understanding, CI/CD pipelines can be failed for PRs if the coverage change is less than the limit.

**Comment by Rugvip** [comment]
@OrkoHunter yeah I think it makes sense to build this into the cli, since we're using jest and there's a bunch of tooling there. There's already a `--coverage` flag for the `test` command, so this issue is more about determining a pattern to configure the limits and how to surface it to the user in a nice way, likely through some GitHub checks/workflows. And ofc make CI fail if the limit/deltas are not met.

When it comes to config I think the initial approach would be to see if we can just put it in the `"jest"` field in the `package.json` of each package, which will be merged into the jest config [here](https://github.com/spotify/backstage/blob/6f1c443ee02e2bb47756a21ad76ad9107af54544/packages/cli/config/jest.js#L45)

**Comment by stefanalund** [comment]
We now have Codecov.
