### ISSUE TITLE
Example Plugin for Storybook

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#2122]
## 🗒 General

Hi! Would love some help getting the UI for this 'example plugin' built and incorporated into our storybook! This is just a static page example of how a plugin could be structured.

![Plugin 1](https://user-images.githubusercontent.com/61153904/91275039-e2ca6800-e77f-11ea-9433-6b988e121f43.png)

## 💻 Usage

We based this plugin example off of one of the Circle CI plugin we're building. It utilizes a full page table. The filter component for the table is currently under design right now, and we hope to ship it soon.

## 📐 Specs

You can access the Figma file [here](https://www.figma.com/community/file/850673348101741100). Feel free to duplicate it and open the 'Create a Plugin' page on the left side panel. If you click into the different elements, you can see the component specs. We've also leveraged some existing components in this design - namely, the [header](https://backstage.io/storybook/?path=/story/header--home), the [sidebar](https://backstage.io/storybook/?path=/story/sidebar--sample-sidebar), and the [table](https://backstage.io/storybook/?path=/story/table--default-table). 
<img width="1542" alt="Screenshot 2020-08-26 at 9 42 36 AM" src="https://user-images.githubusercontent.com/61153904/91275482-8582e680-e780-11ea-946f-29396d0444b7.png">

DM @katz on Discord if you have any questions! Thank you!

**Comment by stefanalund** [comment]
Related issue: https://github.com/spotify/backstage/issues/2122

**Comment by tudi2d** [comment]
Hey. I would like to add this to storybook 🙂
