### ISSUE TITLE
Another Example Plugin for Storybook

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#2123]
## 🗒 General

Hi! Would love some help getting the UI for this 'example plugin' built and incorporated into our storybook! This is just a static page example of how a plugin could be structured.
![Plugin 2](https://user-images.githubusercontent.com/61153904/91275984-2a052880-e781-11ea-9e80-f263d94d79d1.png)

## 💻 Usage

This is a generic example that demonstrates how one might structure a plugin within Backstage.

## 📐 Specs

You can access the Figma file [here](https://www.figma.com/community/file/850673348101741100). Feel free to duplicate it and open the 'Create a Plugin' page on the left side panel. If you click into the different elements, you can see the component specs. We've also leveraged some existing components in this design - namely, the [header](https://backstage.io/storybook/?path=/story/header--home), the [sidebar](https://backstage.io/storybook/?path=/story/sidebar--sample-sidebar), [tabs](https://backstage.io/storybook/?path=/story/tabs--default), and the [progress card](https://backstage.io/storybook/?path=/story/progress-card--default).
<img width="1546" alt="Screenshot 2020-08-26 at 9 47 02 AM" src="https://user-images.githubusercontent.com/61153904/91275975-24a7de00-e781-11ea-9d83-472baecdab80.png">

DM @katz on Discord if you have any questions! Thank you!

**Comment by tudi2d** [comment]
Hey. I would like to add this to storybook as a follow up to #2122 :)

**Comment by stefanalund** [comment]
Thank you @tudi2d -- I've assigned you 🙏
