### ISSUE TITLE
Yarn install fails with acceptable node version

### ISSUE THREAD

**Issue by johnson-jesse** [spotify/backstage#2146]
Following the [Getting Started > Running Backstage Locally](https://github.com/spotify/backstage/blob/master/docs/getting-started/index.md) instructions fail with error when node version greater than minimum required.

## Expected Behavior
When running `yarn install`, I should see the install process continue past the validation step when my node version meets the minimum required.

## Current Behavior
`yarn install` fails validation and task exits without completing successfully.

```zsh
✔︎ backstage % yarn install                                                                             (master)backstage
yarn install v1.22.1
[1/5] 🔍  Validating package.json...
error root@1.0.0: The engine "node" is incompatible with this module. Expected version "12". Got "14.7.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
✘[1] backstage % 
```

## Possible Solution
1) Adjust the package.json's engine node version specified to accept anything greater than the minimum required.
or
2) Adjust the [Getting Started > Running Backstage Locally](https://github.com/spotify/backstage/blob/master/docs/getting-started/index.md) documentation's verbiage.

> _First make sure that you have ~~at least~~ node version 12 installed locally_
> _First make sure that you have node version **12** installed locally_

## Steps to Reproduce

1. run `yarn install` with node version greater than 12.

## Context

Stops me from exploring Backstage

## Your Environment

- Yarn (1.22.1)
- NodeJS Version ( v14.7.0 ):
- Operating System and Version ( macOS 10.15.6 (19G2021) ):
- Shell (zsh)
- Browser Information: n/a

**Comment by freben** [comment]
Thanks for reporting. There were actually node 14 issues at some point at least, I think. Definitely with node 13, that much I'm sure of. Version 14 is due to become LTS soon, and we will definitely switch up at least then.

We should adjust the wording as you suggested (maybe you would even like to make a PR? :)) for starters, and later try to evaluate everything on node 14.
