### ISSUE TITLE
[RFC] Rename Service Catalog

### ISSUE THREAD

**Issue by althafh** [spotify/backstage#2148]
### Background
Currently the Catalog is known everywhere in the documentation as the [Service Catalog](https://backstage.io/docs/features/software-catalog/software-catalog-overview), and in some places it being referred to as a [Software Catalog ](https://github.com/spotify/backstage/tree/master/docs/features/software-catalog)

However with more entity types like the ones described in #1401 the name starts becoming a misnomer and potentially confusing. In addition the word Service is often overloaded in many companies and can create additional confusion. 

With the possibility of custom entity types being defined in private customization, this confusion can be further exacerbated.

### Proposal
To alleviate this confusion, I propose renaming the Service Catalog to **Entity Catalog** to reflect the generic nature of the Catalog without any shoe-horning of it into a specific role with preconceived notions.

This would involve some additional work in renaming existing use-cases which might not be considered a good use of time at this stage in the project, and thus opening this issue for discussion and feedback.

**Comment by dtuite** [comment]
What about just calling it Catalog?

**Comment by stefanalund** [comment]
This is a question that we have debated quite a lot internally 😄 Our reasoning has been going something like this:

Long-term we will use **Backstage Software Catalog** (or maybe simply Backstage Catalog as @dtuite suggests), but short-term we will continue to use Service Catalog. The main reason for this is that "service catalog" is what the industry is already using and what many companies use to describe systems they've built that are similar to Backstage. 

I.e. we are optimising for making it easy to understand what Backstage is/does. An Entity Catalog would be technically more accurate, but ultimately harder to explain.

Example of how we have tried to thread this needle:

> The Backstage Service Catalog — actually, a software catalog, since it includes more than just services — is a centralized system that keeps track of ownership and metadata for all the software in your ecosystem (services, websites, libraries, data pipelines, etc).

cc @fengypants

**Comment by fengypants** [comment]
Yes, at this early stage in the category, we think it's still better to take the approach of saying "service catalog and more" — start with the term people are familiar with and the most common use case — than to say "X catalog" and have them be a little unsure what the term means when they first read it ("What is an X catalog?").

**Comment by althafh** [comment]
Fair enough, thank you for the comments.
