### ISSUE TITLE
Module Federation for plugins

### ISSUE THREAD

**Issue by drsounds** [spotify/backstage#2174]
I think Backstage would benefit from using Webpack 5 Module federation, it is a new way to make apps extensible at runtime by taking advantage of components from other compiled apps at runtime

## Feature Suggestion

Backstage should be developed so module and plugin architecture will be based on Webpack 5 Module Federation, so Backstage users can add new plugins without having to recompile the whole code.

## Possible Implementation

Read more here
https://medium.com/swlh/webpack-5-module-federation-a-game-changer-to-javascript-architecture-bcdd30e02669

## Context

https://medium.com/swlh/webpack-5-module-federation-a-game-changer-to-javascript-architecture-bcdd30e02669

**Comment by stefanalund** [comment]
> Backstage users can add new plugins without having to recompile the whole code.

I don’t understand what this means in practice. Can you elaborate on the possible benefits for plugin developers and/or users of Backstage?

**Comment by drsounds** [comment]
I mean an approach like Single SPA

https://single-spa.js.org/

Den sön 30 aug. 2020 15:01Stefan Ålund <notifications@github.com> skrev:

**Comment by stefanalund** [comment]
Thanks for the suggestions. We have discussed it in the team and decided that we are not going down this route. Closing the issue.

**Comment by drsounds** [comment]
> If you come across this issue and you're curious about the latest developments in this area, you can checkout #18372 RFC

Nice to ser you are considering something that is similar to my suggestion 3y in your RFC, like have made an embryo for this idea three years ago!

**Comment by taras** [comment]
Some companies are already using Webpack Federation by patching Webpack config, but that RFC introduces the foundation for declaratively configuring Backstage with components from different modules. Red Hat folks are using Webpack Federation in their OpenShift Console, so they're driving the work to introduce it to Backstage.
