### ISSUE TITLE
Create an EmptyState component for InfoCard and Tab

### ISSUE THREAD

**Issue by marcuseide** [spotify/backstage#2179]
Present an empty state component if a tab or an overview does not match any annotations for an entity.

Help app-developers/integrators to develop guidelines, instructions on how to get started with whatever is missing. A user is presented with some information referring to why the specific plugin/view is not displayed.

**Comment by stefanalund** [comment]
Adding some prior art from Spotify's internal version. Something that we may want to reuse is the pattern of placing empty-state information directly on the page background vs all other information being wrapped in an `<InfoCard>`. This creates a clear distinction for empty-states:

![Screenshot 2020-09-02 at 09 10 12](https://user-images.githubusercontent.com/190856/91950435-ac9d6300-ed00-11ea-8e2c-e87eb9395850.png)

**Comment by katz95** [comment]
Attaching designs for empty states in various use cases. 

You can access specs here: https://www.figma.com/community/file/850673348101741100

![Guide](https://user-images.githubusercontent.com/61153904/92486096-02d04180-f1ec-11ea-9dfd-fb93fcc13383.png)
![Empty Page](https://user-images.githubusercontent.com/61153904/92486108-05cb3200-f1ec-11ea-9992-6d39abc3fb37.png)
![Empty Table](https://user-images.githubusercontent.com/61153904/92486111-0663c880-f1ec-11ea-990c-07a6b474bdce.png)
![Empty Card](https://user-images.githubusercontent.com/61153904/92486116-06fc5f00-f1ec-11ea-8f25-2f8f183d29f2.png)
![Create a Component](https://user-images.githubusercontent.com/61153904/92486131-08c62280-f1ec-11ea-876b-d4c228c65bc6.png)
![No Builds to Show](https://user-images.githubusercontent.com/61153904/92486134-095eb900-f1ec-11ea-92c6-9d03c2eca451.png)

**Comment by stefanalund** [comment]
Thanks @katz95 --looks awesome. I'm removed you from being Assigned and thus open up the issue for someone that wants to help out 👍 (cc @ayshiff since you usually like these kinds of challenges 🙃 )

**Comment by ayshiff** [comment]
> Thanks @katz95 --looks awesome. I'm removed you from being Assigned and thus open up the issue for someone that wants to help out 👍 (cc @ayshiff since you usually like these kinds of challenges 🙃 )

@stefanalund Yes of course ! If no one takes it before I finish #2218, I will take it 👍

**Comment by marcuseide** [comment]
Thought I'd share a recent discussion amongst the team related to this issue. We think these `EmptyState` components would primarily be used inside plugins to relay information back to the user that something is lacking or missing or needs to happen. As to how the design portraits it.
For an `App` on the other hand, it should rely on the routing, and present a `404` (Mic Drop) page if the route was not found.

We'd also appreciate adding a stories for the `EmptyState` components.

**Comment by marcuseide** [comment]
@ayshiff Hey, me and @samiramkr are going to pick this up, hopefully you haven't started yet (if so, give us a shout and we can coordinate).

**Comment by ayshiff** [comment]
> @ayshiff Hey, me and @samiramkr are going to pick this up, hopefully you haven't started yet (if so, give us a shout and we can coordinate).

@marcuseide Yes, no problem ! I haven't started working on it

**Comment by Fox32** [comment]
Beside empty state, e.g. because of missing configuration, is there a UI suggestion how to display errors in widgets? E.g. transitive errors, or errors in the widget code itself?

**Comment by katz95** [comment]
@Fox32 we're working on designing error states currently! :) will be creating an issue for that soon!
