### ISSUE TITLE
Refactor plugins to use the new routing API

### ISSUE THREAD

**Issue by shmidt-i** [spotify/backstage#2200]
- [x] @backstage/plugin-circleci @shmidt-i 
- [x] @backstage/plugin-explore @shmidt-i 
- [x] @backstage/plugin-lighthouse @marcuseide 
- [x] @backstage/plugin-sentry @muffix 
- [x] @backstage/plugin-tech-radar @Rugvip 
- [x] @backstage/plugin-graphiql @Rugvip 
- [x] @backstage/plugin-techdocs @emmaindal 
- [ ] ... other plugins

**Comment by dhenneke** [comment]
I can help with the @backstage/plugin-api-docs. Let me know if I should prepare a PR.

The only thing that is unclear is how to best distinguish the two routers (root and catalog) since the plugin both can be integrated in the root app and in the service catalog, similar to the techdocs plugin.

**Comment by shmidt-i** [comment]
@dhenneke that would be super helpful! So from the perspective of plugin in your case it seems like you need to export 2 routers - one for standalone functionality, another one to be a part of catalog's entity page.

**Comment by dhenneke** [comment]
So the `plugin.ts` will setup the router for the plugin and the `Router.tsx` will setup the router for the catalog integration? I hope that will not lead to confusions in the future. But I will start with that.

**Comment by shmidt-i** [comment]
@dhenneke it's a bit confusing atm, you are correct here, we are in the middle of propagating the changes everywhere. But the idea is that we go away from registering routes inside `plugin.ts` and do it directly inside `App.tsx`, so from that perspective mounting the Router under catalog or on top level of the App makes a very little difference ;)

**Comment by dhenneke** [comment]
Okay. Unless you want different routes for different use cases :-). But that's open for future improvements.

**Comment by shmidt-i** [comment]
Agree, that's what I meant by exporting 2 different routers, one per use case 😀

**Comment by andrewthauer** [comment]
I've updated the rollbar plugin in #2301

**Comment by Rugvip** [comment]
Gonna look at migrating the tech-radar.

**Comment by marcuseide** [comment]
I'm taking a look at `lighthouse`

**Comment by timja** [comment]
Taking a look at Jenkins

**Comment by timja** [comment]
Jenkins WIP: https://github.com/spotify/backstage/pull/2352

**Comment by mcalus3** [comment]
Can these plugins be ran independently now (`yarn start` from the plugin folder)? When I try it, I see the '404' page and I can't navigate to the plugin. Will local development of plugins that way still be possible? I'm also asking, because I don't understand how `entity` object could be read if it's not passed as a prop from the catalog router. Or maybe the only way for the local development is to mock it?

**Comment by Rugvip** [comment]
@mcalus3 Yep, looks broken right now. We do still want to support isolated plugin development, gonna look for a fix!

Regarding entities the way forward for local development will most likely be to have to mock the entities. It's possible we could provide some base entities to extend as a part of `dev-utils` though, but nothing decided there yet.
