### ISSUE TITLE
Primary color in theme is not in sync with Figma

### ISSUE THREAD

**Issue by ilyamkin** [spotify/backstage#2217]
The primary color in the theme is not in sync with Figma. 

## Expected Behavior

The color used for buttons, inputs, and other basic elements in Figma is #2E77D0 (UI / Blue).

## Current Behavior

The primary color defined in theme:
```
primary: {
  main: blue[500], // #2196f3
},
```

## Possible Solution

```
primary: {
  main: '#2E77D0',
},
```

**Comment by stefanalund** [comment]
@katz95 could you help here?
