### ISSUE TITLE
Filter Component

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#2218]
## 🗒 General

Would love some help building out this filter component for Storybook! Includes several different input options, including single select dropdown, multiselect dropdown, and nested subcategories. This filter is meant to be used with a full page [Table ](https://backstage.io/storybook/?path=/story/table--default-table)component.

![Filters hidden](https://user-images.githubusercontent.com/61153904/91875923-6bfc0600-ec7c-11ea-992c-76898af22f92.png)
![Filters revealed](https://user-images.githubusercontent.com/61153904/91875889-60a8da80-ec7c-11ea-8b47-4816d9c91f79.png)

## 💻 Usage
Usage details can be found in the screenshots below.

![Filters revealed _ Expanded Dropdown _ Many Checkbox Chips](https://user-images.githubusercontent.com/61153904/91875915-68687f00-ec7c-11ea-90d9-9189aae8a942.png)
![Filters revealed _ Expanded Dropdown _ Checkbox Chips](https://user-images.githubusercontent.com/61153904/91875916-6999ac00-ec7c-11ea-9c74-dcf2996603dd.png)
![Filters revealed _ Expanded Dropdown _ Checkbox](https://user-images.githubusercontent.com/61153904/91875917-6a324280-ec7c-11ea-917b-877a73bc5c23.png)
![Filters revealed _ Expanded Dropdown](https://user-images.githubusercontent.com/61153904/91875918-6acad900-ec7c-11ea-8ffc-9e4171b9d4a8.png)
![Filters revealed](https://user-images.githubusercontent.com/61153904/91875921-6b636f80-ec7c-11ea-9c85-2139926a1983.png)

## 📐 Specs
You can access specs by duplicating our [Figma UI kit](https://www.figma.com/community/file/850673348101741100). Click on the 'Filters' page on the left hand side. 
<img width="1242" alt="Screenshot 2020-09-01 at 5 59 17 PM" src="https://user-images.githubusercontent.com/61153904/91876352-e3319a00-ec7c-11ea-8824-b29ed5d46637.png">

**Comment by ayshiff** [comment]
Can I grab this one ? 👍

**Comment by freben** [comment]
Sure! Assigned you.
