### ISSUE TITLE
Chips

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#2219]
## 🗒 General
Would love if someone could help us add chips to our Storybook. We've got two versions that differ by size. Functionality follows [Material-UI's chips](https://material-ui.com/components/chips/).

<img width="707" alt="Screenshot 2020-09-01 at 6 02 55 PM" src="https://user-images.githubusercontent.com/61153904/91876762-6357ff80-ec7d-11ea-8e27-a3de3ed385a3.png">

## 💻 Usage
These are meant to be used as tags or as indicators of what's been selected in a dropdown!

## 📐 Specs
You can access specs in our [Figma UI Kit](https://www.figma.com/community/file/850673348101741100). Click on the 'Chips' page on the left hand side.
<img width="1080" alt="Screenshot 2020-09-01 at 6 03 52 PM" src="https://user-images.githubusercontent.com/61153904/91876873-8682af00-ec7d-11ea-9ebb-7ded5868c229.png">

**Comment by ayshiff** [comment]
Can I work on it ? 👍

**Comment by stefanalund** [comment]
Thanks @ayshiff
