### ISSUE TITLE
Rename ProgressBar components to *Gauge

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#2227]
https://github.com/spotify/backstage/blob/1812fd05e6cc27cb1c845020b422d6e82b330183/packages/core/src/components/ProgressBars/CircleProgress.tsx#L80 to `Gauge`

https://github.com/spotify/backstage/blob/1812fd05e6cc27cb1c845020b422d6e82b330183/packages/core/src/components/ProgressBars/HorizontalProgress.tsx#L31 to `LinearGauge`

https://github.com/spotify/backstage/blob/1812fd05e6cc27cb1c845020b422d6e82b330183/packages/core/src/components/ProgressBars/ProgressCard.tsx#L39 to `GaugeCard`

Always get them confused with the `Progress` component and don't remember what they're for until I actually look at them in storybook :p

**Comment by freben** [comment]
Sure!

**Comment by stefanalund** [comment]
I'm +1 for renaming this component but -1 on *Gauge. It's not a word that is familiar to me.

Suggestion: *Loading or *LoadingIndicator

**Comment by freben** [comment]
But it's not loading things in general right? It's more like "you are 20% done with this task" or "you are 70% cost efficient" - things that you gauge. The word itself I think is well fitting (and commonly used in this kind of scenario).

**Comment by Rugvip** [comment]
But it's never used as a loading indicator 😅 ?

Fwiw MUI want to add a Gauge component too: https://material-ui.com/discover-more/roadmap/#new-components

**Comment by stefanalund** [comment]
Ooooo I misread this. I (for some unclear reason) thought you wanted to rename the `Progress` component.

I'm 👍 on this 😃

**Comment by Rugvip** [comment]
@stefanalund That confusion is exactly why I want to rename 😁

**Comment by stefanalund** [comment]
![](https://images.rapgenius.com/90b4eccea26efa04418bf71a75604e4e.450x254x18.gif)
