### ISSUE TITLE
Change ExpansionPanel to Accordion 

### ISSUE THREAD

**Issue by NetPenguins** [spotify/backstage#2238]
Material-UI has changed their naming of `ExpansionPanel` to `Accordion`. This change was made to keep in consistent with what Devs are most used to seeing. The translation is 1:1 just a simple name change. 

https://material-ui.com/api/expansion-panel/

**Comment by stefanalund** [comment]
@NetPenguins do you want to submit a PR for these changes?

**Comment by NetPenguins** [comment]
Yea I'll have these open for #2172 alright to include in there?

**Comment by stefanalund** [comment]
Sounds good! Thanks

**Comment by freben** [comment]
@NetPenguins We got this change in as part of us doing a run through our documentation and fixing up the experience. I hope that's OK with you, and you can just rebase on master to get all the Accordion goodness.
