### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#224]
Example: https://github.com/spotify/scio/blob/master/CONTRIBUTING.md

**Comment by OrkoHunter** [comment]
(Some of the) Things which could be helpful for someone new in the community, in my opinion -

1. How to understand the project well. (Blog posts, videos, are good to begin with)
2. How to set up development environment (It's already documented well)
3. Issues to begin with (`good first issue` labeling is done well on the issues) 👏 
4. Coding standards and recommendations
5. Joining the community and channels (Discord, etc.)
6. Code of Conduct
7. Future plan (Useful when contributors are looking for more issues, and don't know what to prioritize)
