### ISSUE TITLE
Add a lint rule to avoid using __dirname

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#2244]
## Feature Suggestion

It is recommended to use the `resolvePackagePath` in `@backstage/backend-common` package instead of doing a custom path resolution using `__dirname`. See https://github.com/spotify/backstage/pull/2237 for example.

## Possible Implementation

Add an ESLint rule which disallows using `__dirname`. (Maybe give a warning with the message about `resolvePackagePath`?)

**Comment by AnshuTrivedi** [comment]
I want to work on this issue.
Please assign to me.

**Comment by Rugvip** [comment]
@AnshuTrivedi Thanks! 🎉

**Comment by Marvin9** [comment]
@AnshuTrivedi Please let me know if you are not working on this issue.

**Comment by AnshuTrivedi** [comment]
@Marvin9 i'm working on it , if you wish you we can collaborate.

**Comment by themousepotato** [comment]
Hey @AnshuTrivedi  and @Marvin9, I have created #2684. Apologies if you already had something. Please take a look and feel free to suggest anything
