### ISSUE TITLE
Fix banner component

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#2245]
## 🗒 General

Hi! Would love if someone could help us update our DismissableBanners component. Currently, the banner appears at the top, and the colors don't pass accessibility standards. We'd love for the banner to show at the bottom (20px above the bottom). 
![Banners](https://user-images.githubusercontent.com/61153904/91991348-15053800-ed33-11ea-96ab-bd95874b674c.png)

![Example 1](https://user-images.githubusercontent.com/61153904/91991340-133b7480-ed33-11ea-8960-847de37beac9.png)

![Example 2](https://user-images.githubusercontent.com/61153904/91991346-146ca180-ed33-11ea-8b28-cf9d04191eba.png)

## 📐 Specs
You can access specs by duplicating our [Figma UI Kit](https://www.figma.com/community/file/850673348101741100). Click on the "Dismissable Banner" page on the left. 
<img width="1278" alt="Screenshot 2020-09-02 at 3 46 46 PM" src="https://user-images.githubusercontent.com/61153904/91991723-8a710880-ed33-11ea-98d8-93355b72fb02.png">

**Comment by Rugvip** [comment]
@katz95 You're thinking a `fixed` position to always show at the bottom of the page?

Right now it's up to the dev to position the banner, it shows up wherever it's added to the UI. Would it make sense to keep that option but allow for a `fixed` property or something like that?

**Comment by katz95** [comment]
Yes, that makes sense! @Rugvip

**Comment by marcuseide** [comment]
Me and @samiramkr will look into this.
