### ISSUE TITLE
backend: Mount all backend plugin routers under a common `/api` router

### ISSUE THREAD

**Issue by shmidt-i** [spotify/backstage#2287]
Since #1986 was merged one can simply start full backstage instance by just starting the backend, which is imo very sweet 😃 
But, some backend plugins that are missing 404 handler of their own are now showing 404 of the frontend, which is not desirable behavior in the most of the cases.
As a starting point - `plugin-proxy-backend` should really just give 404 of its own if something isn't there on `/proxy/<whatever>`

As a bigger discussion - maybe it's time to move all of the backend-related stuff to `/api` and then we can at least have unified way of dealing with 404 for `/api`?

**Comment by Rugvip** [comment]
Repurposing this as the ticket to switch to using `/api` route, as that'll be a solution to the original issue.

Regarding the `/proxy` endpoint, I think we should mount it at `/api/proxy` like all other routes, that way the service discovery is much more straightforward, and we don't need separate handling of the proxy.

**Comment by Rugvip** [comment]
Fixed by https://github.com/spotify/backstage/pull/2562
