### ISSUE TITLE
TO CATALOG button after creating new component does not work

### ISSUE THREAD

**Issue by ebarriosjr** [spotify/backstage#2309]
After the change to the new routing model the button on the pop up after creating a new component does not redirect anywhere.
## Expected Behavior
On clic it should take you to the new component catalog page

## Current Behavior
TO CATALOG link does nothing.

## Possible Solution
Update routing to point to backstage/catalog/Component/<ComponentName>

## Steps to Reproduce
Try clicking on the TO CATALOG button.

1. Start the app on master.
2. Register an existing service (http://localhost:3000/register-component)
3. Try clicking on the TO CATALOG button

## Your Environment

- NodeJS Version (v12): v12.18.2
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 20.04
- Browser Information: Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by shmidt-i** [comment]
Thanks for reporting @ebarriosjr, I'm going to take a look 😉
