### ISSUE TITLE
Scaffolder: Automatically add access to scaffolded repos

### ISSUE THREAD

**Issue by timja** [spotify/backstage#2311]
## Feature Suggestion

Currently scaffolder doesn't explicitly add access to anyone when it creates a repository.
Only org owners / the owner of the PAT token (in the case of GitHub) will have access to it.

This doesn't scale very well.

Bring your own PAT isn't a good solution either as in many cases users won't have access to create repositories directly.

From our perspective it would be ideal to be able to specify a team that should get access to the repo.

Likely it's very organisation specific so it would be good if there's a way to provide your own specific implementation.

At the very minimum to make this work I think if the user who created the repo was given access then they could setup the permissions from there (but not ideal).

## Context

Someone who has minimal access is able to create a repo for their team to work on and will have the appropriate access

**Comment by Rugvip** [comment]
This is what the ownership selection looks like in our internal version of Backstage currently:

![create](https://user-images.githubusercontent.com/4984472/92393225-d7802080-f11f-11ea-8d99-9575eb88dfd0.png)

Agreed that this is very much needed, and likely ties into GitHub App integration as well

**Comment by mfrinnstrom** [comment]
Hello,

I will just add some things that we have discussed when talking about implementing Backstage. Hopefully some of it will be relevant at least.

Our plan is to have each person connected to one team in the identity model. Then when creating a new component the owner will be that team. If a person should be able to belong to multiple teams I assume we will have something similar to what you showed in the screenshot above.

We are using Azure DevOps where there exists organizations (used for departments in our case) that has projects (connected to systems/solutions in our case) and in those projects there are repos. Each team can have access to multiple projects and multiple teams can have access to the same project.

So for repos our plan has been that you get to select one of the projects that you have access to and the component id will be used for the repo name. The repo is then created in the selected project and by that all teams that have access to that project will have access to the repo. We don't anticipate more fine-grained access control than that.

I'm not sure how generic you can make this but we would like to be able to supply our own logic for getting a list of owners (like shown in the picture) and also for projects but that is probably Azure DevOps specific. The component id will most probably always be used as the repo name.

Not sure if that made sense but I'm happy to elaborate if needed.

**Comment by BROGVOIDOVO** [comment]
When do we get paid

**Comment by timja** [comment]
MVP PR: https://github.com/spotify/backstage/pull/2442
