### ISSUE TITLE
Add release notes for each version

### ISSUE THREAD

**Issue by timja** [spotify/backstage#2362]
## Possible Implementation

https://github.com/release-drafter/release-drafter is a great hands off way to do this, just add a github action, some config and label PRs as they are merged (or after), and then publish the release notes after tagging

Examples: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/plugin-management-parent-pom-2.0.0 https://github.com/jenkinsci/jenkins/releases/tag/jenkins-2.254 https://github.com/jenkinsci/github-branch-source-plugin/releases/tag/github-branch-source-2.9.0

## Context

Know roughly what's changed, without having to review all PRs, prioritised by what I'm most interested in, rough order: breaking changes => bug fixes => new features => docs updates => project maintenance / deps

**Comment by Rugvip** [comment]
Duplicate of #1839 😅 , alright with closing this?

**Comment by timja** [comment]
ah yup
