### ISSUE TITLE
Design: Low visibility/contrast in sidebar on backstage.io/docs

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#2367]
## Expected Behavior

The sidebar on the Backstage docs page should have a clear visibility of the sections and subsections (contrast and font size).

## Current Behavior

It is currently hard to read the sidebar on the docs page. See screenshot.

![low_visibility](https://user-images.githubusercontent.com/8065913/92597793-2b1d7600-f2a8-11ea-98ef-8421a9035f73.png)

## Possible Solution

We can take inspiration from TechDocs page's sidebar.

![Screenshot 2020-09-09 at 14 25 45](https://user-images.githubusercontent.com/8065913/92597969-661fa980-f2a8-11ea-9cb0-3d126e212203.png)

## Steps to Reproduce

Visit https://backstage.io/docs/features/techdocs/techdocs-overview (maybe disable the darkreader extension :P).

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by iamrajiv** [comment]
@OrkoHunter Can you give colour combination which suits best? The current t sidebar has three colour combination the main sidebar section has `#9e9e9e`, subsection have `#393939` and subsubsection have `#616161`. I think subsection and subsubsection should be updated to the same colour as that of section i.e. `#9e9e9e`. After updating, the sidebar will look like this
<img width="289" alt="Screenshot 2020-09-11 at 2 44 50 AM" src="https://user-images.githubusercontent.com/42106787/92807737-c6ae0400-f3d8-11ea-875c-8d4d51142cb5.png">

**Comment by OrkoHunter** [comment]
@iamrajiv Thanks for looking into it! Your suggestion looks like an improvement to me. I will defer to what @katz95 and @stefanalund have to say on this one. :)

IMO more can be done to differentiate "subsections" from "subsubsections". Perhaps increasing indentation padding or change in font size or both.

**Comment by iamrajiv** [comment]
@OrkoHunter Yeah, changing fonts and padding sounds good. Also, we can get some colour combination from https://www.spotify.com/ so that everything looks consistent. This section of https://www.spotify.com/ have a good colour combination
<img width="812" alt="Screenshot 2020-09-11 at 3 10 18 AM" src="https://user-images.githubusercontent.com/42106787/92811720-5608e680-f3dc-11ea-90b7-f164100651c6.png">

**Comment by stefanalund** [comment]
@iamrajiv not sure I think we should change the font. I would suggest using `#e4e4e4` for the main sections and then, as you say, `#9e9e9e` for the subsections and sub subsections.
