### ISSUE TITLE
[scaffolder, scaffolder-backend] GitLab support

### ISSUE THREAD

**Issue by muffix** [spotify/backstage#2372]
## Feature Suggestion

The Scaffolder plugin currently supports only GitHub as the output platform. I'd like to see support for GitLab. 

## Possible Implementation

We'd need to add a preparer and a publisher for GitLab (see [the documentation](https://backstage.io/docs/features/software-templates/extending/extending-index)). 

## Context

I'm happy to put in a PR for a GitLab preparer and publisher, but would like to discuss the scope.

### Configuration
I'd like to add support for self-hosted GitLab versions, so would need to specify the base URL for the API. It seems worth introducing a config section for the scaffolder. Does something like this make sense? 

```yaml
scaffolder:
  gitlab:
    api:
      baseUrl: 'https://gitlab.my-company.com/'
      token: FEEDC0DE
```

Until now, GitHub is taking its API key from the environment variable `GITHUB_ACCESS_TOKEN` - which might be used by other plugins as well. Does it make sense to move the config into the new scaffolder object, too?

### Access control
As far as I can see, the current implementation for GitHub assumes that the token used to authenticate against GitHub has privileges to create repositories (and push to them) in whatever organisation/user namespace that is defined by the user. Is this a concern at the moment? Would we expect the same for GitLab or should users only be able to create new repos in the organisations/namespaces that they have access to? How would we authenticate them with GitHub/GitLab?

### Frontend
We're likely to need to allow users to choose where to create new repos if both GitHub and GitLab are configured. We could add a dropdown to step 2 of the wizard in that case.

**Comment by stefanalund** [comment]
@muffix thanks -- adding this to the "Production" milestone.

**Comment by muffix** [comment]
So for the first step, I'd then follow the

**Comment by muffix** [comment]
Thanks @stefanalund 🙌 
So for the first step, I'd then follow what the GitHub implementation does and assume that the token supplied has permissions to create repo anywhere specified by the user. We'd need to look at access control in a later PR.

**Comment by stefanalund** [comment]
@benjdlambert please comment on the suggestion above. 

@muffix should I assign you to this issue? Otherwise I'll add a [help-wanted] label to it.

**Comment by muffix** [comment]
Yeah, happy to take it. 👍

**Comment by muffix** [comment]
For the token, I'll keep a close eye on #1565.
