### ISSUE TITLE
80,000 records created in location_update_log table in few days

### ISSUE THREAD

**Issue by taras** [spotify/backstage#2376]
![](https://i.imgflip.com/4ectc3.jpg)

I deployed alpha20 and later upgraded to alpha21 to Heroku. I created a separate PostgreSQL database for each plugin. 
1 day later I got a notification from Heroku saying that I'm exceeding Hobby limits of 10,000 records. 

![image](https://user-images.githubusercontent.com/74687/92613210-b424b500-f288-11ea-8448-aefcd69f2b37.png)

## Expected Behavior

To be able to run Backstage on Heroku for 1 day without exceeding their database write limits.

## Current Behavior

I ran `SELECT count(*) FROM location_update_log;` query on the database and got 87360 records. I'm not sure if this is intentional. 

## Steps to Reproduce

1. Create a separate Heroku PostgreSQL for each plugin
2. Deploy to Heroku and configure each plugin to use a different connection string
2. Wait 1 day
3. You should get a notification from Heroku

## Context

I'm in the process of setting up a demo instance of Backstage. This happened while doing this setup.

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 14
- Browser Information: N/A

**Comment by freben** [comment]
It kind of is, in the current state of the code, but maybe we should have a default limit on that table... The refreshes happen in a fairly frequent loop now. I'll have to look into it tomorrow because the day has ended over here. Maybe you would like to contribute a cleanup task that cuts off the log table per-entity to like the last ten entries or something?

**Comment by Rugvip** [comment]
Could we skip adding entries for successful updates that don't change anything? :> Assuming that's the case atm given the size

**Comment by taras** [comment]
@Rugvip yes, it's writing more information than is useful.

**Comment by Rugvip** [comment]
Tbh I'd be all for just keeping just the current state of locations at this point.

**Comment by taras** [comment]
BTW, we're at 800,000 records now :)

**Comment by freben** [comment]
@Rugvip mmmmaybe we could squeeze in a fix for this as well before releasing :D

**Comment by taras** [comment]
@freben as a result of #2519, number of records went from 1m+ to 182 :)

**Comment by freben** [comment]
Woo! :)
