### ISSUE TITLE
Scaffolder plugin should read GitHub PAT from config

### ISSUE THREAD

**Issue by taras** [spotify/backstage#2384]
## Motivation

I deployed an instance using auth21, figured out how to get cookiecutter installed but I got "Requires authentication" error which is rather cryptic. Then I peeked into the generated Scaffold plugin and found that it was using an environment variable [here](https://github.com/spotify/backstage/blob/2a4407ccc1158afffc934ebe8d6cc1f030eb9097/packages/create-app/templates/default-app/packages/backend/src/plugins/scaffolder.ts#L29) and [here](https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts#L77)

It would have been more helpful to see an error that config was missing rather than silently relying on an environment variable. 

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/74687/92638118-cf52ed00-f2a7-11ea-992f-91885e4ddb23.png">

## Approach

I changed in my code to `const githubClient = new Octokit({ auth: config.getString('scaffolder.githubApi.privateToken') });`

I can create a PR to fix it if someone can suggest where this value should come from.

**Comment by Rugvip** [comment]
Fwiw the proper docs for setting up the scaffolder are at https://backstage.io/docs/features/software-templates/installation
They do mention the env var, but it should definitely be switched out to be read from config.

We will be consolidating the different repo reading strategies in the future, but for now it's probably best to stick to `scaffolder.github.token`.

**Comment by taras** [comment]
@Rugvip do you want me to create a PR that changes docs and code to use `scaffolder.github.token`?

**Comment by taras** [comment]
Completed by #2429
