### ISSUE TITLE
Scaffolder's GitHub client requires an admin user

### ISSUE THREAD

**Issue by taras** [spotify/backstage#2386]
I'm trying to setup Backstage for one of the organizations that I work with. It's a big company and very few users have admin permissions. I wanted to do some internal demos of the scaffolder plugin. Followed instructions on the [official installation page](https://backstage.io/docs/features/software-templates/installation#runtime-dependencies) to create a PAT with `repo` permissions. I configured the plugin to use the new PAT.

## Expected Behavior

I was expecting `repo` permissions to be enough as per documentation.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/74687/92646818-fc59cc80-f2b4-11ea-9a43-4072c8f700d0.png">

I was hoping to be able to use a GitHub user that the organization uses for creating repoes. 

## Current Behavior

When I tried to scaffold the project, I got "You need admin access to the organization before adding a repository to it."

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/74687/92646634-b7ce3100-f2b4-11ea-9093-2a9c4fea7cc3.png">

## Possible Solution

I'm not sure if it's my particular org. Giving the bot admin permissions is not feasable.

## Steps to Reproduce

As per documentation on the site,

1. create a PAT with repo permissions
2. use it to start backstage
3. attempt to create a project

## Your Environment

- Version: alpha21
- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu
- Browser Information: NA

**Comment by Rugvip** [comment]
#1565 is really the way forward here. For now a workaround is to create a separate demo org.

A bit confused about why `repo` scope isn't enough though, I'd imagine that's a org-wide setting that limits the creation of repos? Or maybe repo is enough, but your user needs admin access.

**Comment by timja** [comment]
I expect it’s the user can create repositories option which will be disabled on your org

**Comment by taras** [comment]
> A bit confused about why repo scope isn't enough though

me too

> I expect it’s the user can create repositories option which will be disabled on your org

the weird thing is that i can create repos via UI.

> #1565 is really the way forward here. For now a workaround is to create a separate demo org.

do you have any timeline for #1565?

**Comment by taras** [comment]
This looks related https://github.com/octokit/octokit.net/issues/1812

**Comment by taras** [comment]
@Rugvip I think the problem is that the org allows creating Internal or Private projects - but current implementation to creating a public project. (I think)

**Comment by Rugvip** [comment]
Oh that sounds reasonable, either way it's likely that private/public repo is something you want to both be able to select and configure org-wide rules for. Again something GitHub apps can likely help out with 😅

**Comment by timja** [comment]
Agree that's most likely, I've set our org up with a non owner user and it works fine.

**Comment by taras** [comment]
I will create a PR that will fix this and read visibility from config.

> Again something GitHub apps can likely help out with 😅

🕺
