### ISSUE TITLE
[bug] Handle TechDocs missing more gracefully

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#2389]
## Expected Behavior

If TechDocs is missing for a component I expect to get a more helpful error/warning message.

Also, this URL looks really weird to me: `http://localhost:3000/docs/Component::searcher`. Should there really be `::` in the path?

## Current Behavior

Clicking a TechDocs link when About card "crashes" rendering...

![Screenshot 2020-09-10 at 08 26 19](https://user-images.githubusercontent.com/190856/92689490-61f29b00-f33f-11ea-832e-cc99239bae9b.png)

...leads to this problem:

![Screenshot 2020-09-10 at 08 26 35](https://user-images.githubusercontent.com/190856/92689492-628b3180-f33f-11ea-87a8-5268556bf377.png)

If I click the DOCS tab I get a different experience:

![Screenshot 2020-09-10 at 08 26 11](https://user-images.githubusercontent.com/190856/92689482-60c16e00-f33f-11ea-9813-b29548a62789.png)

**Comment by stefanalund** [comment]
@emmaindal @OrkoHunter

**Comment by OrkoHunter** [comment]
> Also, this URL looks really weird to me: http://localhost:3000/docs/Component::searcher. Should there really be :: in the path?

I am curious about this as well.
@emmaindal @hooloovooo Can we easily change this URL to `/docs/Component/<component>`? Or is it somehow related to [this RFC - Uniform Entity Refs](https://github.com/spotify/backstage/issues/1947)? 🙇

**Comment by freben** [comment]
That RFC will be related, yes. We'll settle on something first, and then change all places as necessary after to make it consistent.

**Comment by freben** [comment]
And input is of course welcome!

**Comment by OrkoHunter** [comment]
Thanks for the clarification, @freben !
