### ISSUE TITLE
Move "Getting Started" section from repo readme to backstage.io/docs/getting-started

### ISSUE THREAD

**Issue by taras** [spotify/backstage#2402]
A new user reached out to me yesterday via Discord asking for help getting started with Backstage. I suggested that they read the docs. They said they did. I asked them what they were reading and they gave me a link to [Getting Started](https://backstage.io/docs/getting-started/index). I can see why they were confused. 

## Expected Behavior

New users should start with the shortest path to understanding how to get started. 

## Current Behavior

They're taken to starting the project locally which might resemble the development workflow but not how Backstage is meant to be used.

## Possible Solution

Getting Started should take users to Create an App page with some context or a landing page where they can choose their path: development or starting project.

## Steps to Reproduce

1. Go to [Getting Started](https://backstage.io/docs/getting-started)
2. Try to follow those instructions to create a new project
3. much confuse

## Context

*How has this issue affected you?*

I don't like seeing people be confused.

*What are you trying to accomplish?*

Make it easier for new people to try Backstage.

**Comment by johnson-jesse** [comment]
I agree. I went down this same path only to discover the easier `npx @backstage/create-app` Though I have yet to get GitHub auth to work with this second approach.

**Comment by Rugvip** [comment]
The proper getting started entrypoint is here: https://github.com/spotify/backstage#getting-started
With the move to backstage.io/docs from GitHub, that wasn't carried along.

Repurposing this as an issue to move that section of the docs to the docs site :grin:

**Comment by OrkoHunter** [comment]
@johnson-jesse If you follow the steps [here](https://github.com/spotify/backstage/tree/master/plugins/auth-backend#github), you should be able to set up GitHub auth smoothly. 🥳 
Created #2415 based to make this experience better.
