### ISSUE TITLE
Unreadable error message when trying to create a component from invalid backstage.yaml config file

### ISSUE THREAD

**Issue by mcalus3** [spotify/backstage#2405]
If in the default catalog file (backstage.yaml) exist any annotation that has value other than string, error occures during component creation. It's due to the architecture decision described here https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md.

![repro](https://user-images.githubusercontent.com/24685983/92741046-8b7ee700-f37e-11ea-8e03-ca33b9926766.gif)

## Expected Behavior

Instead of `Error: x: "y" is not valid at HigherOrderOperations.addLocation` there should be more descriptive error, for example "Error: values other than string are not valid for an annotation. To learn more about catalog file format visit https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md"

## Current Behavior

The error message being displayed looks like that:

> InputError: Failed to read location github https://github.com/mcalus3/sample-service/blob/invalid-config-reproduction/backstage.yaml, Error: Processor EntityPolicyProcessor threw an error while processing entity at github https://github.com/mcalus3/sample-service/blob/invalid-config-reproduction/backstage.yaml, Error: annotations.cloud.google.com/function-ids "projects/backstage-test-project/locations/us-central1/functions/helloMarek,projects/backstage-test-project/locations/us-central1/functions/helloWorld,projects/backstage-test-project2/locations/us-central1/functions/helloMarek,projects/backstage-test-project2/locations/us-central1/functions/helloWorld" is not valid at HigherOrderOperations.addLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:89:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async eval (webpack-internal:///../../plugins/catalog-backend/src/service/router.ts:98:22)

## Steps to Reproduce

1. In Component Catalog click "create component" button
2. Click "register existing component" button
3. Paste component file url https://github.com/mcalus3/sample-service/blob/invalid-config-reproduction/backstage.yaml and click "submit" button

## Context

It does not block me because I can still insert a list of elements as a comma delimited strings, although making the possibility to make annotation a list would surely improve the readability. For future users it certainly would be more helpful to see the errors about invalid catalog file format.

## Your Environment

- [not relevant]

**Comment by mcalus3** [comment]
If you decide that it's worth it, I can try to fix it and submit a PR :)

**Comment by stefanalund** [comment]
@mcalus3 we would love to get a contribution fixing this.

**Comment by erictnilsson** [comment]
Are you still working on this? @mcalus3

**Comment by marcuseide** [comment]
@erictnilsson Interested in picking this up as we haven't heard back from @mcalus3 ?

**Comment by mcalus3** [comment]
@marcuseide I'm not working on it, sorry for the confusion.

**Comment by erictnilsson** [comment]
@marcuseide Yes I'd like to take a look at it!

**Comment by erictnilsson** [comment]
Hey!
How much of the error message/stack trace do we want to exclude in favour of readability? 
So far, I've added a more descriptive error at the root, but I'm not sure if  it the error message as a whole is readable enough.
<img width="642" alt="Screenshot 2020-10-19 at 11 36 32" src="https://user-images.githubusercontent.com/16206098/96429134-e1a63c00-1200-11eb-93b4-218fa0c0aa46.png">

What do you think?

**Comment by freben** [comment]
The location is written twice, maybe one of those can be left out.

I guess cutting out the stack trace would help too.

Sometimes it helps to move the pertinent parts of the message nearer the start, along the lines of `Annotation X is not valid; expected a string but found Y` (where Y is a very long piece of text).

**Comment by freben** [comment]
At some point we should look into if we can break apart errors into a more useful structure somehow... This would be so much more readable as a list for example

```
Invalid annotation: Expected string, but found array

At annotation annotations.cloud.google.com/function-ids

At entity component:default/sample-service

At location github https://github.com/mcalus3/sample-service/blob/invalid-config-reproduction/backstage.yaml
```

**Comment by erictnilsson** [comment]
I've landed on this: 
<img width="662" alt="Screenshot 2020-10-20 at 14 37 52" src="https://user-images.githubusercontent.com/16206098/96588116-839e5500-12e3-11eb-981b-df015a45f8f1.png">

Just gonna test it out to make sure nothing breaks then I'll have a pull request ready if you don't have any objections and/or suggestions :)

**Comment by freben** [comment]
Looks good. LOOOONG but informative and to the point
