### ISSUE TITLE
Can't pull spotify/backstage:latest

### ISSUE THREAD

**Issue by lelvisl** [spotify/backstage#2411]
Can't pull spotify/backstage:latest

## Expected Behavior

Container pulling

## Current Behavior

Error response from daemon: pull access denied for spotify/backstage, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
## Possible Solution

Allow to pull image

## Steps to Reproduce

1. docker pull spotify/backstage:latest

## Context

cant use https://github.com/spotify/backstage/tree/master/install/kubernetes

## Your Environment

```
docker version                                                                                            
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by OrkoHunter** [comment]
I don't think there is any `spotify/backstage` docker image to pull. Did you get this instruction from our documentation?

**Comment by lelvisl** [comment]
I look at https://github.com/spotify/backstage/blob/226c5488045d5bd6feed704bbf732af52fa0ea2b/install/kubernetes/app.yaml#L22

**Comment by OrkoHunter** [comment]
@Rugvip will know more about it. Looks like a Work in Progress. Probably, it's not published yet. 😅

**Comment by freben** [comment]
Hi! These are not publicly available images. Backstage does not have a one-size-fits-all build artifact. You are expected to make your own backstage project, customize config and write actual glue code to wire things up and fit your particular needs, then build your own images that you push to your own registry and finallu deploy using your own deployment routines.

We have gotten this question a few times and there is clearly a need to clarify the ways of working upfront in the docs - we'll take this to heart.

Closing for now singe things work as expected, but we are very happy to answer questions here or on Discord to help get you started.

**Comment by freben** [comment]
So to clarify, the instructions would have been correct if you had your systems pointing to `dockerregistry.yourcompanyname.com` and those images had been built and pushed there using your CI/CD pipelines, based off a code base in your own version control system.
