### ISSUE TITLE
Show a message if TechDocs page takes long time to load (first time visit)

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#2416]
## Feature Suggestion

We now have TechDocs setup in out of the box Backstage! When we visit one of the component's docs for the first time, it could take up to 10 or more seconds to load the docs. This happens for the first time page visit only. Also the out-of-box setup is not optimised for speed yet.

10 seconds is a long time to wait and users might start wondering if the page is broken. So, it would nice to display a message saying that loading could take a while. And possibly also explain why it's taking this much time.

## Possible Implementation

The progress bar comes from [here](https://github.com/spotify/backstage/blob/30fcae37cd45a8fc5dfb72b10e59560785e85536/plugins/techdocs/src/reader/components/Reader.tsx#L136).
If it's more than a few seconds (let's say 4) and the state is still `loading`, a message should appear below the progress bar with some text. It can say -
```
First time load is slow, but the page is still loading. Please wait...
```

**Comment by harshilparmar** [comment]
Can I take this issue ?

**Comment by emmaindal** [comment]
@harshilparmar Yess please do! I'll assign it to you. Thanks! 💯

**Comment by harshilparmar** [comment]
@emmaindal  Thanks..Can you help me to setup.
I have done my installation as per [https://github.com/spotify/backstage/blob/master/CONTRIBUTING.md](url),but still it gives me blank page on this http://localhost:3000/docs using guest login.

Steps I had followed 
1) yarn install 
2) yarn start
3) cd packages/backend
4) yarn lerna run mock-data

Please correct me If I have done something wrong.

**Comment by emmaindal** [comment]
Did you run`yarn lerna run mock-data` in the root of the project?

1. yarn install
2. cd packages/backend
3. yarn start
5. open new terminal tab
4. cd root of project 
5. yarn lerna run mock-data
6. yarn start

**Comment by emmaindal** [comment]
Hmm just realized you could run it from /packages/backend as well so the step you took should be correct. Do you get any errors or so in your terminal window or can you see that mock-data has been generated? @harshilparmar

**Comment by harshilparmar** [comment]
![Capture](https://user-images.githubusercontent.com/45915468/92893012-ebd15f80-f436-11ea-84bd-31cb38032d71.PNG)
Can't sign-in via other method also.

**Comment by emmaindal** [comment]
@harshilparmar you shouldn't have to sign in more than a guest to access docs. Can you look in your terminal (where you started the backend), can you see any logs there from when you were running the "yarn lerna run mock-data" command?

**Comment by harshilparmar** [comment]
> 
> 
> @harshilparmar you shouldn't have to sign in more than a guest to access docs. Can you look in your terminal (where you started the backend), can you see any logs there from when you were running the "yarn lerna run mock-data" command?

![error](https://user-images.githubusercontent.com/45915468/92906790-60f66200-f442-11ea-9519-c5f8db377c61.PNG)

**Comment by OrkoHunter** [comment]
@harshilparmar When you run `yarn lerna run mock-data` (from the root of the package - `C:\hp\backstage`) it sends lots of requests to the backend that you have running. That would mean that the mock data was added. So, you should see the logs of those requests on the terminal where you have the backend running (instead of where you run the mock data command).

**Comment by harshilparmar** [comment]
@OrkoHunter 
![error](https://user-images.githubusercontent.com/45915468/92909101-710f4100-f444-11ea-83d2-7905ca4568e9.PNG)

**Comment by freben** [comment]
Related? https://github.com/spotify/backstage/issues/1557

**Comment by OrkoHunter** [comment]
Hey @harshilparmar, sorry that you have been blocked. You can now fetch the latest branch and start again. With https://github.com/spotify/backstage/pull/2439 merged, you will not need to run mock-data command. :)

Start by doing `yarn start` in the root of the repository and `packages/backend` separately, and you will see a docs component which you can use to work on this issue. Let us know if you need any help.

**Comment by harshilparmar** [comment]
@OrkoHunter Thank you so much🙇

**Comment by harshilparmar** [comment]
@OrkoHunter now facing different error
![error](https://user-images.githubusercontent.com/45915468/93009910-ef362980-f5a3-11ea-9fb6-5335e4f567e6.PNG)

**Comment by OrkoHunter** [comment]
@harshilparmar Can you please create a [bug ticket](https://github.com/spotify/backstage/issues/new?labels=bug&template=bug_template.md)?
Mention that this is an issue with using TechDocs on Windows OS. Please write the steps to reproduce. Please attach the logs of the backend when this error occurs. We will take a look. 🙇

**Comment by themousepotato** [comment]
@OrkoHunter I've made a custom progress bar component for techdocs in PR #2598. Let me know if that works :sweat_smile:
