### ISSUE TITLE
[templates] Add waves patterns to cards

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#2422]
The header in the Software Template cards currently lack the visual patterns:

![Screenshot 2020-09-11 at 10 51 34](https://user-images.githubusercontent.com/190856/92896578-c8012000-f41c-11ea-9b65-53b6ff7eef0f.png)

* Cards should be updated to include the "waves".
* Reuse pattern based on type (service, websites, ...) of the template. 

Cards should look similar to our Headers:

![Screenshot 2020-09-11 at 10 47 10](https://user-images.githubusercontent.com/190856/92895855-28dc2880-f41c-11ea-9b79-2e1f324e3964.png)

https://backstage.io/storybook/?path=/story/header--website

**Comment by JoelLau** [comment]
Hi @stefanalund, if no one already has, I would like to take this up!

**Comment by stefanalund** [comment]
Great! Assigned you.
