### ISSUE TITLE
Improve UX of creating new component using Software Template

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#2458]
## Feature Suggestion

When a new component is created using the templates available in `/create`, the UI should convey properly that the component has been created.

## Possible Implementation

Use words like "Done" or "Successfully created" or a Green check. And remove "Creating component..." when it's done.

## Context

**Current behaviour**

![create-new-component](https://user-images.githubusercontent.com/8065913/93077201-c6d42b00-f688-11ea-9093-101d450c3755.gif)

**Take inspiration from Spotify's internal backstage**

In progress

![Screenshot 2020-09-14 at 12 47 06](https://user-images.githubusercontent.com/8065913/93077310-e8cdad80-f688-11ea-8c15-af01c3921349.png)

Component created

![Screenshot 2020-09-14 at 12 47 35](https://user-images.githubusercontent.com/8065913/93077307-e79c8080-f688-11ea-96cc-0f746ee910e4.png)

**Comment by hrishikeshnikam2000** [comment]
@OrkoHunter  I would like to work on this issue.
How do you want me to implement it?

**Comment by OrkoHunter** [comment]
Hey @hrishikeshnikam2000. Sure, go ahead!

I don't have a design mockup. But to begin with, I will use the component's state and update the header text. Also, see the inspiration from the images above. :)

**Comment by soapraj** [comment]
@katz95 would be great to get some design inputs here

**Comment by hrishikeshnikam2000** [comment]
thank you @OrkoHunter . will start working on it .

**Comment by themousepotato** [comment]
@OrkoHunter Created a minimal fix in #2624.
