### ISSUE TITLE
[RFC] A Place for Contributions

### ISSUE THREAD

**Issue by freben** [spotify/backstage#2459]
**Status:** Open for comments

## Need

There is lots of great work being done in the community in terms of getting builds and deployments and similar working in their specific environments. There are fairly frequent questions on Discord and in issues pertaining to for example getting ingress setup working in kubernetes, or getting builds to work inside Docker instead of on the host, or setting up GitHub actions to run your builds, etc etc.

It would be great if these contributions were persisted somewhere and were easy to find by newcomers to the platform. The core Backstage team may not have the bandwidth or know-how to support every platform and situation out there as a golden path, so there seems to exist a need for a place for non-core community contributions to live.

## Proposal

Create a new repository on GitHub next to the primary one, for example `spotify/backstage-contrib`. It would have its own setup in terms of end-to-end tests, builds etc. Some of the contributions may only be almost gist-like, putting a few files in a directory and stating in a README file that this is on an "at your own risk" or "for inspiration" level of ambition. Some may be on the level of libraries or actual full examples.

## Alternatives

We could add a `/contrib` directory in the root of the main repo. There is already an `/install` directory whose future is slightly unclear. My main concern with this is build times and polluting the main workflows.

## Risks

Having a separate repo comes with its own cost. It will have to have a functioning build setup of its own, teams and rights management may be different, licensing has to be solved, and the ownership issue will have to be managed separately if Backstage gets fully adopted by CNCF.

**Comment by Fox32** [comment]
Before reading the full post I thought: Isn't this GitHub Discussions stuff available? it's something like StackOverflow and could be an option too. That could be useful for a QA style and might be easier to discover then Discord. 
But it wouldn't be useful if one want to share bigger things like you suggested.

**Comment by freben** [comment]
I was thinking that the official documentation on backstage.io would link into the contrib repo, per tech/topic essentially. So as a docs reader I'd find a nice list of helm, istio etc that would link out to the respective dir in contrib. The readme in that dir would hopefully be well structured and informative as well.

**Comment by Rugvip** [comment]
Me feeling regarding in/out of repo is that it's better to keep it in `/contrib` inside this repo, at least to begin with. We'd exclude it from workflows and linting, and I wouldn't be expecting (or accepting) any large binary blobs, mostly just markdown and yaml :grin:

Ofc the benefit of keeping inside this repo is that you at least increase the change that they'll be updated when changes are made. You'll find them when searching for APIs you're changing etc.

**Comment by freben** [comment]
The more I think about it, the more I lean toward internal `/contrib` too.

**Comment by freben** [comment]
We have made a decision that the more lightweight option of putting things in a `/contrib` directory in the main repository is better in the near term. If things grow too large or need breaking out for other reasons, we can revisit this decision in the future.
