### ISSUE TITLE
Unable to find @backstage/plugin-newrelic

### ISSUE THREAD

**Issue by alileza** [spotify/backstage#2464]
## Expected Behavior

Unable to find @backstage/plugin-newrelic while doing yarn install, it seems doesn't exist here https://www.npmjs.com/package/@backstage/plugin-newrelic

## Current Behavior

```
error Couldn't find package "@backstage/plugin-newrelic@^0.1.1-alpha.21" required by "example-app@0.1.1-alpha.21" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Rugvip** [comment]
@alileza indeed, it's still private, and I believe it's supposed to be marked as public.

#2316 is about to make plugins public by default
