### ISSUE TITLE
TechDocs: required description field for docs-template

### ISSUE THREAD

**Issue by emmaindal** [spotify/backstage#2477]
## Expected Behavior

The fields that are required should be validated before it's possible to create a component.

## Current Behavior

You are able to go through the steps to create a new component but in the generating step it hangs and throws this error.

DEBUG cookiecutter.generate: Check component-info.yaml to see if it's a binary
Unable to create file 'component-info.yaml'
Error message: 'collections.OrderedDict object' has no attribute 'description'
Context: {
    "cookiecutter": {
        "_template": "/template", 
        "component_id": "Nylas", 
        "isOrg": "True", 
        "owner": "tjperry07", 
        "storePath": "tjperry07/backstage-doc-template"
    }
}

**Comment by dtuite** [comment]
@emmaindal I believe I have fixed this in https://github.com/spotify/backstage/pull/2470/commits/ae081ebd354fc904222b9c420956deabc6d85e29

It's awaiting review.

**Comment by emmaindal** [comment]
@dtuite fantastic, thank you! 💯
