### ISSUE TITLE
Register existing component fails when adding an internal repository via GitHub API

### ISSUE THREAD

**Issue by taras** [spotify/backstage#2506]
![Screen Shot 2020-09-17 at 2 06 29 PM](https://user-images.githubusercontent.com/74687/93510570-6561c580-f8ef-11ea-802d-34cdb3fdaa2f.png)

## Expected Behavior

I would like to be able to add a project that's internal to an enterprise organization to Backstage via "Register existing component" 

## Current Behavior

I get the following error attempting to register the component.

```
InputError: Failed to read location github https://github.com/<enterprise_org>/pulse-documentation/blob/master/component-info.yaml, NotFoundError: https://github.com/resideo/pulse-documentation/blob/master/component-info.yaml could not be read as https://raw.githubusercontent.com/<enterprise_org>/pulse-documentation/master/component-info.yaml, 404 Not Found at HigherOrderOperations.addLocation (/Users/tarasmankovski/Projects/pulse/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:543:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async /Users/tarasmankovski/Projects/pulse/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1472:22
```

## Possible Solution

I did some digging. It looks like the problem is caused by the wrong processor being used to handle submission to 
`/register-component`. 

The request includes the following payload: `{"type":"github","target":"https://github.com/resideo/pulse-documentation/blob/master/component-info.yaml"}` which specifies type as "github" instead of "github/api".

We should determine the type on the backend rather than the frontend.

## Steps to Reproduce

1. Try to add a component from an internal repository of a GitHub enterprise organization

## Context

*How has this issue affected you?*

I believe this problem affects both "register component" and scaffolder. When scaffolder is used to add to an enterprise organization the component is not added to list of components.

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu
- Browser Information: Chrome

**Comment by Rugvip** [comment]
Thanks! And alright alright, yet another reason for https://github.com/spotify/backstage/pull/2501 to exist, it should be fixed by that :grin:
