### ISSUE TITLE
Techdoc plugin not loading the docs

### ISSUE THREAD

**Issue by saranyavignesh2123** [spotify/backstage#2518]
## Current Behavior

![image](https://user-images.githubusercontent.com/70377631/93590996-20ac5c00-f9cd-11ea-8a41-29d3ebe8f85f.png)

## Steps to reproduce

sync local branch with remote repo
git fetch upstream
git merge upstream/master
yarn start in root folder
cd .\packages\backend\
yarn start

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by hooloovooo** [comment]
Could you please provide the server logs for this as well? That should contain some useful information. Also make sure you have set the new required requestUrl config url in your app-config.yaml.

**Comment by saranyavignesh2123** [comment]
HI,

Below is the information got from backend run 

![image](https://user-images.githubusercontent.com/70377631/93592722-51da5b80-f9d0-11ea-88b4-abaaf1bd6584.png)

My request URL in app-config.yml is requestUrl: http://localhost:7000/techdocs/docs

**Comment by saranyavignesh2123** [comment]
Getting this error intermitently. Why this behaviour.
![image](https://user-images.githubusercontent.com/70377631/93592987-d927cf00-f9d0-11ea-866d-2bbd987bf498.png)

**Comment by hooloovooo** [comment]
Not sure what that error is, but it looks like it's trying to request techdocs from localhost:3000/docs/<componentId>. This looks a bit strange. How does your techdocs section look in your app-config?

**Comment by saranyavignesh2123** [comment]
Error in browser console and my request Url is: 
  storageUrl: http://localhost:7000/techdocs/static/docs
  requestUrl: http://localhost:7000/techdocs/docs

![image](https://user-images.githubusercontent.com/70377631/93596441-f364ab80-f9d6-11ea-97f5-89822b1f9ad5.png)

**Comment by hooloovooo** [comment]
Not sure what's going on. I think i will have to try and recreate this on windows this weekend and get back to you. :)

**Comment by FabianHippmann** [comment]
So - I had the same problem - 

Problem was -> that in `techdocs-backend/src/helpers.ts` the github repo from the schema/annotation tries to get loaded & theres a Github user hardcoded trough `GITHUB_PRIVATE_TOKEN_USER`

If you did not pass the `GITHUB_PRIVATE_TOKEN_USER` as an env - variable - the plugin creates the directory - tries to do a git clone & fails. 

```js
  fs.mkdirSync(repositoryTmpPath, { recursive: true });
```

If you refresh the page techdocs goes here -> 

```js
 if (fs.existsSync(repositoryTmpPath)) {
```

And as the git clone before was unsuccessful - the docs never get built. 

The git clone should be wrapped in a try catch - so that the directory will be removed again & `GITHUB_PRIVATE_TOKEN_USER` should get documented.   

I'll try to submit as soon as i get the whole docs generation working

**Comment by OrkoHunter** [comment]
Oh thank you @FabianHippmann! We'll make sure to update our docs or throw a better error.

**Comment by saranyavignesh2123** [comment]
After hardcoded the user name i am still getting same error. Either 404 not found or server is too busy.(Error: EBUSY: resource busy or locked, )

**Comment by OrkoHunter** [comment]
Just wanted to add a FYI here that `GITHUB_PRIVATE_TOKEN_USER` environment variable is not required for a public repository to work in TechDocs.

**Comment by OrkoHunter** [comment]
@saranyavignesh2123 I wonder if you are still facing the problem with TechDocs on Windows. I'll close this issue right now because it is unclear what the exact problem is. But feel free to jump over on our Discord (#docs-like-code channel) or create another issue.
