### ISSUE TITLE
scaffolder: Tests are failing for ssr template

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#2533]
## Expected Behavior
- Tests and CI should pass for the scaffolded template

## Current Behavior
- Test fail due to `--if-present` not being a valid option when using `next build`

## Possible Solution
- Update to latest `SSR` in the docker template?

## Steps to Reproduce
- Scaffold a `SSR` project into `Github`
- Watch the failing build on `Github Actions`

**Comment by Marvin9** [comment]
Can I reproduce it on starting up environment with ```yarn dev```?

**Comment by benjdlambert** [comment]
These docs should help you get started adding the scaffolder functonality: https://backstage.io/docs/features/software-templates/installation

But you'll need to start the backend and the frontend to get this runnning.
