### ISSUE TITLE
[RFC] Easy deployment on any Kubernetes cluster

### ISSUE THREAD

**Issue by martina-if** [spotify/backstage#2540]
**Status:** Open for comments

## Need

Today there are instructions on how to deploy Backstage locally but deploying it to a Kubernetes cluster requires building Docker images and Kubernetes manifests.

## Scope

Managing cloud specific resources (like managed databases) is out of scope for this proposal.

## Proposal

It would be nice to have a way to deploy it to any Kubernetes cluster regardless of its platform. One way to do that is to use [Helm](https://helm.sh/) which is widely used and graduated in CNCF.

To deploy it one would need to install helm locally and run:

```
helm repo add spotify https://charts.spotify.com
helm install backstage-demo spotify/backstage
```

or for a more customized installation:

```
helm install -f backstage-prod.yaml backstage-prod spotify/backstage
```

Ideally the charts:

- work on all Kubernetes clusters
- can work with zero extra configuration (i.e. they have reasonable defaults, auto-generated credentials and certificates) but also are flexible enough for production deployments
- can also include and install the sub-charts for the dependencies like [PostgreSQL](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
- should also admit configuration for Backstage to connect to an existing Postgres DB
- would live in ~a [Chart repository](https://helm.sh/docs/topics/chart_repository/) hosted by Spotify and published in [Helm Hub](https://hub.helm.sh/)~ (edit) the Backstage repo under `contrib/helm` (see [comment below](https://github.com/spotify/backstage/issues/2540#issuecomment-696665463))

Additionally:

- on each Backstage release new Docker images are built and published
- there is good documentation on how to configure things
- there are tests for the charts

## Alternatives

Terraform, or Ansible could be alternatives to Helm charts, but these require extra infrastructure.

Kustomize or Ksonnet with plane Kubernetes manifests are other alternatives that let the user customize plain Kubernetes manifests, but we believe Helm is more mature and widely used than these.

**Comment by dtuite** [comment]
Looks like there is related conversation in https://github.com/spotify/backstage/issues/2540.

**Comment by dtuite** [comment]
We (Roadie) and more specifically, Martina, are prepared to contribute this work. We already have a prototype working which creates the PG instance in kubernetes and configures Backstage to talk to it over automatically generated certs.

There are some things we will need from Spotify in order to achieve the interface presented above.

1. A place to store Docker images. e.g. A Spotify controlled Docker Hub repo and secrets to push images.
2. a GitHub repo in the Spotify GitHub org to act as a Helm chart index. [As described here.](https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417)
3. A DNS record (CNAME) pointing https://charts.spotify.com at that GitHub repo.

Can't wait to hear some opinions.

**Comment by stefanalund** [comment]
Another related issue: https://github.com/spotify/backstage/issues/373

**Comment by Rugvip** [comment]
@dtuite @martina-if what's your thinking around what would be part of the docker images you want to store?

Regarding helm charts, we could also rely on `raw` GitHub URLs for now right? Same question here though, what would the helm charts actually include?

**Comment by dtuite** [comment]
@Rugvip 

> Regarding helm charts, we could also rely on raw GitHub URLs for now right? 

You mean like this?

```
helm repo add roadie https://raw.githubusercontent.com/RoadieHQ/helm-charts/master/index.yaml
```

I expect that would work. I haven't tested it yet.

**Comment by Rugvip** [comment]
@dtuite yeah that, to get started anyway

**Comment by stefanalund** [comment]
> There are some things we will need from Spotify in order to achieve the interface presented above.

@dtuite please consider that Backstage is being donated to the CNCF and that we would want to move away from Spotify dependencies.

**Comment by martina-if** [comment]
> what's your thinking around what would be part of the docker images you want to store?

Probably an image for each piece: backend, frontend and lighthouse plugin to start with.

> what would the helm charts actually include?

- deployment, service, configmaps, etc. for Backstage backend
- deployment, service, configMap, etc for Backstage frontend
- deployment, service, etc. for lighthouse backend plugin
- ingress and optional auto generated certificate
- optional postgresql dependency. The alternative would be to configure the connection to an existing db.
- secrets to store auto-generated credentials and certificates for postgresql. (This would be optional and values can be provided by the user).

**Comment by martina-if** [comment]
> Regarding helm charts, we could also rely on raw GitHub URLs for now right?

Hosting the charts with [Github pages](https://helm.sh/docs/topics/chart_repository/#github-pages-example) should be quite simple. Do you think this could be a good option here?

**Comment by Rugvip** [comment]
@martina-if What is the purpose of the backend and frontend images? is to provide an up-to-date demo deployment of the example app in this repo? If the goal is for actual deployment and use by organizations, is the plan to wrap them up in additional layers to make it possible to select which plugins to include?

**Comment by martina-if** [comment]
@Rugvip I think, initially at least, yeah, they would provide a demo deployment of the example app. I guess then each company can use these charts as a starting point for their own charts for their own backstage app.

I haven't looked into customizing which plugins to include. What do you think we should do here? Perhaps limit the scope to a demo deployment?

**Comment by martina-if** [comment]
Regarding hosting the charts. Given what stefan mentioned about Backstage being donated to CNCF, it's probably better that the charts live inside the backstage repo under `charts/backstage`, for example. As an example, [flux](https://github.com/fluxcd/flux/tree/master/chart) and [ArgoCD](https://github.com/argoproj/argo-helm/tree/master/charts) do it the same way.

**Comment by freben** [comment]
possibly `contrib/helm`?

**Comment by martina-if** [comment]
@stefanalund @Rugvip A couple more details regarding the potential dependencies of a demo installation:

- ingress would be done through [ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx). This means that for the demo setup to work we would require this controller to exist in the cluster. 

- DNS: I think there should be a way to deploy the demo backstage that doesn't require the user to create DNS entries. That will be relatively easy after [this is merged](https://github.com/spotify/backstage/pull/2562). There should also be an option to use it with a domain. We could add instructions on how to use [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) to make it easier.

- regarding the different certificates and CAs I think the demo deployment could work with auto-generated self-signed certificates. And a more advanced setup with [cert-manager](https://github.com/jetstack/cert-manager) could also be set up as an opt-in, since it requires that the controller is already installed in the cluster.

What are your thoughts? I have a prototype that I could clean up and submit as a PR if you think it would be valuable.

**Comment by Rugvip** [comment]
@martina-if Those things aren't very Backstage specific, so it may be worth finding an external guide to base the entire thing on and mainly reference that. It's really just a single (or two) containers with external access right?

Nginx ingress + ExternalDNS + and cert-manager all seem like sane choices, although an option could be to use Traefik for ingress as it has native support for Let's Encrypt, making the setup slightly simpler. In the end the choices of the surrounding infra should ofc not be done based on any requirements from Backstage itself, but from the wider organization that it's deployed in.

Once we start considering splitting the backend up into individual pieces it becomes a bit more interesting though, but that requires some more work before we have a recommended way to do that imo.

**Comment by dtuite** [comment]
That sounds like approval to me! 😄

**Comment by Rugvip** [comment]
Well yes xP

**Comment by dtuite** [comment]
@martina-if this can probably be closed now right?

**Comment by Hokwang** [comment]
@martina-if 
I think you can go next step.
User needs doker images and helm chart continuously updated.
