### ISSUE TITLE
Showcase Backstage react components with Storybook 

### ISSUE THREAD

**Issue by nikek** [spotify/backstage#255]
This would act as reference documentation for reusable react components built for Backstage.

Tasks:
- [x] Integrate Storybook in the project (done: #350)
- [x] Setup publishing to storybook.backstage.io during CI (https://github.com/spotify/backstage/issues/365)
- [ ] Add documentation about Storybook and how to contribute

Once these are done we can start tracking the individual components that should be added.

**Comment by mateusmarquezini** [comment]
Hi @nikek ! Maybe I can help with this! Any pointers to get started?

**Comment by stefanalund** [comment]
The foundation was done in #350. Adding the remaining tasks that we have before closing this issues.

**Comment by mikqi** [comment]
You're welcome @stefanalund. In this issue point no 2 is just like this  https://github.com/spotify/backstage/pull/350#issuecomment-602188657 right?
I'll try add it to CI in this repo.

**Comment by stefanalund** [comment]
@mikqi yes! created a separate issue: https://github.com/spotify/backstage/issues/365 and will assign you if you're up for it.
