### ISSUE TITLE
cli: backend build-image doesn't add the app to the image

### ISSUE THREAD

**Issue by mfrinnstrom** [spotify/backstage#2573]
## Expected Behavior

I was expecting the app to be packages into the container image that is built for the backend when running `yarn build-image`. I'm trying to build an image that serves the frontend from the backend. That parts works when running it locally.

## Current Behavior

I get the following error message: 
```
Backend failed to start up, Error: Cannot find module 'app/package.json'
```

## Possible Solution

Not really sure how everything is done but one possible solution might be to add the option to specify extra packages to the build-image command.

## Steps to Reproduce

1. Create a new app through `npx @backstage/create-app`
2. Configure the backend to serve the app through the `plugin-app-backend`
3. Run `yarn workspace backend build-image` to build container image
4. Try and run the created container image

**Comment by Rugvip** [comment]
@mfrinnstrom Did you add the app as a `dependency` is `packages/backend/package.json` as well?

**Comment by mfrinnstrom** [comment]
@Rugvip I really thought I had tried that, it seemed like the logical thing to check. I must have messed up or something else was off. It works now though. Thank you for your help.
