### ISSUE TITLE
[RFC] Plans for the support buttons

### ISSUE THREAD

**Issue by dtuite** [spotify/backstage#2574]
We're building a few Backstage plugins and following the patterns we find in the Circle CI plugin and other existing plugins that the community has developed.

Each plugin seems to come with a Support Button in the top right corner.

![screenshot of the support button from the lighthouse plugin](https://user-images.githubusercontent.com/562403/94011896-f88f7500-fd9f-11ea-9778-a779dad5fd7f.png)

Currently, the support buttons don't seem to do much. The [lighthouse plugin](https://backstage-demo.roadie.io/lighthouse) seems to be a link to a Slack channel but it doesn't actually link, and the channel doesn't exist. 😄 

I'm wondering what the long term plan is for these support buttons, so we can try to go that direction with our own plugins.

Some questions to stimulate the conversation...

 1. Should the support buttons go to a channel that the plugin maintainer runs, or the "IT department" of the company running Backstage?
 2. What kind of support is expected to be provided?
 3. Does GitHub issues and the official Backstage Discord provide much of the functionality that could be provided by the support button?
 4. Should there be one Backstage-wide support button in the sidebar, or is it important for each plugin to provide individual support?

**Comment by benjdlambert** [comment]
Hey @katz95 have you had any thoughts about what this looks like in Backstage? Would lifting over the behaviour from the internal ones work?

**Comment by katz95** [comment]
Good questions, @dtuite! And yes, @benjdlambert, I think we could just lift the behavior from our internal version, providing users with a couple of options that are customizable by the plugin owners.

<img width="388" alt="Screenshot 2020-09-28 at 12 18 27 PM" src="https://user-images.githubusercontent.com/61153904/94420756-e721e080-0184-11eb-924e-c2944c971864.png">

**Comment by dtuite** [comment]
The screenshot is great @katz95. Thanks.

For our plugins, I think we should do this:

 1. Create an email address where we can offer support to people, perhaps `feedback@roadie.io`.
 2. Link to any docs which are available, likely on GitHub or the roadie.io website.
 3. Link to the Backstage discord support channel since we don't have our own one.

StackOverflow is internal to Spotify I presume?

**Comment by Rugvip** [comment]
> 1. Should the support buttons go to a channel that the plugin maintainer runs, or the "IT department" of the company running Backstage?

Most likely "IT department", or more like "owner of the plugin inside the org". I don't think we should expect plugin authors to provide first-line support for their plugins. The support requests won't come from Backstage developers or maintainers much, and more likely from any employee at a company.

Would be lovely to bake feedback into it though, and that could have a more direct connection to the author :grin:

> 2. What kind of support is expected to be provided?

What we typically get are things like "this page doesn't load", "this button is throwing me an error but it doesn't explain why", "hey this process stopped half-way, can you help me sort it out?". Usually you'll need to have access to infra in the org to be able to help out with these things, or to the Backstage codebase within the org itself.

> 3. Does GitHub issues and the official Backstage Discord provide much of the functionality that could be provided by the support button?

The way we use the support button it's more of a direct helpline to solve an issue now. Issues and Discord is a bit more long-term feedback I think.

> 4. Should there be one Backstage-wide support button in the sidebar, or is it important for each plugin to provide individual support?

For Backstage deployments backed by multiple teams it's important that each plugin has individual support configuration. Basically it maps to the teams you have exposing infra things through Backstage. It also acts as a way to get support for an entire internal infra offering btw, not just the Backstage frontend GUI.

**Comment by Rugvip** [comment]
> 1. Create an email address where we can offer support to people, perhaps `feedback@roadie.io`.

Yep, makes sense, could probably label it feedback too.

> 2. Link to any docs which are available, likely on GitHub or the roadie.io website.

This may not be very helpful for end users, unless you also have end user docs ofc.

> 3. Link to the Backstage discord support channel since we don't have our own one.

We may want to create a separate user-support channel or similar for this.

> StackOverflow is internal to Spotify I presume?

Yup

**Comment by dtuite** [comment]
Cool. Feels like that's enough ideas for the moment. Let's close this for now.
