### ISSUE TITLE
Share some roadmap info

### ISSUE THREAD

**Issue by JimHaughwout** [spotify/backstage#258]
In our **README** *Overview*, we talk about things that are "not release yet". This will generate questions and interest from others.

I know we want to work with others to create these. It might be useful to have a section or issue area that shows a *Strategic Backlog* and lightweight *Roadmap*, including requests to partner with us on these, so that people can see what is coming  

#question #roadmap #backlog

**Comment by stefanalund** [comment]
This is done now.
