### ISSUE TITLE
Use DiscoveryApi to find the catalog API route in techdocs-backend router.

### ISSUE THREAD

**Issue by hooloovooo** [spotify/backstage#2596]

**Comment by Rugvip** [comment]
Would be https://github.com/spotify/backstage/issues/1847 right? 😅

**Comment by hooloovooo** [comment]
> Would be #1847 right? sweat_smile

Ohhh it's not implemented yet. Leaving in the backlog column for now. :)

**Comment by Rugvip** [comment]
Fixed in #2600
