### ISSUE TITLE
[bug] starting the backend fails after creating a new App

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#2608]
I'm on https://backstage.io/docs/getting-started/create-an-app trying to create a new App. The frontend starts, but not the backend:

```
**yarn workspace backend start**

yarn workspace v1.21.1
yarn run v1.21.1
$ backstage-cli backend:dev
Build succeeded
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
2020-09-25T12:16:44.834Z catalog info Beginning locations refresh
Backend failed to start up, Error: Missing required config value at 'scaffolder.github.token'
```

**Comment by benjdlambert** [comment]
What would be the better solution here @stefanalund? Document that that a Github Access Token is required to start the backend, or not enable github support for the scaffolder without the token?

If it's the latter, then I think some of this work makes this easier https://github.com/spotify/backstage/issues/1503.

It comes from the initialisation of the publishers I think.

**Comment by benjdlambert** [comment]
And how we by default have the github publisher enabled by default. I can probably remove that check for now and not add it as a publisher if no token is provided.

**Comment by stefanalund** [comment]
Not sure. I feel like the backend should at least not fail to start.

**Comment by shmidt-i** [comment]
We have it already in the example-backend, but I think long term better to show something in the frontend, like `Oops, you didn't provide a valid configuration, here is docs reference` kind of a thing
