### ISSUE TITLE
Improve contrast in default plugin header

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#261]
The pattern in the main plugin header gradient is hardly visible:

![Screenshot 2020-03-15 at 20 53 38](https://user-images.githubusercontent.com/190856/76709455-2e6fe480-66ff-11ea-99af-d71b8388fdcc.png)

**Comment by braulio-balanza** [comment]
Would this work? 

![purpleBlue](https://user-images.githubusercontent.com/62359443/77010840-98bf9980-6938-11ea-8bfb-91c66490d480.png)

Changed the purpleBlue gradient in PageThemeProvider

**Comment by stefanalund** [comment]
@braulio-balanza that looks like a significant improvement! Would you mind sending a PR? 🙏

**Comment by freben** [comment]
agreed, that is way more crisp!
