### ISSUE TITLE
Kubernetes plugin productionising 

### ISSUE THREAD

**Issue by mclarke47** [spotify/backstage#2636]
Error handling:
- [x] Failed kubernetes cluster calls (500s)
- [x] Failed backend calls
- [x] Handling incorrect authentication config

Documentation:
- [x] Plugin documentation
- [ ] Add to plugin marketplace
- [ ] Documenting code and interfaces

...

**Comment by mclarke47** [comment]
We will probably add to the plugin marketplace, when the UI is in better shape

**Comment by ananthulasrikar** [comment]
I am having similar 500 errors with EKS and trying to fix since 20 days, did not find a solution yet. 
For sure as soon as deployments have 2 labels it throws. Not sure how to fix this.
`Errors: Request failed with 500 Internal Server Error, {"error":"HTTP request failed"}`
