### ISSUE TITLE
discuss: Inconsistency in GitHub/GitLab environment variable names

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#2652]
In our `app-config.yml`, we seem to have variants of GitLab/GitHub environment variables  -

1. https://github.com/spotify/backstage/blob/f9fa53153e822042b76f34fb894541cf713e9cc9/app-config.yaml#L79
2. https://github.com/spotify/backstage/blob/f9fa53153e822042b76f34fb894541cf713e9cc9/app-config.yaml#L133
3. https://github.com/spotify/backstage/blob/f9fa53153e822042b76f34fb894541cf713e9cc9/app-config.yaml#L140
4. https://github.com/spotify/backstage/blob/f9fa53153e822042b76f34fb894541cf713e9cc9/app-config.yaml#L102

* Can we pick one and make these consistent?
* How should we avoid such inconsistencies? Should there be one source of truth for all the environment variables instead of `app-config.yml`?

**Comment by OrkoHunter** [comment]
@spotify/backstage-core Do you have any comments around this? 🙇‍♂️ 

> Can we pick one and make these consistent?
> How should we avoid such inconsistencies? Should there be one source of truth for all the environment variables instead of `app-config.yml`?

**Comment by Marvin9** [comment]
I would like work on it.

**Comment by Marvin9** [comment]
@OrkoHunter I think only documentation and some tests updates will be required if we make them consistent.

**Comment by nikek** [comment]
Whatever surprises the user the least, right? I haven't looked into how these tokens are used or what the respective documentation say, but if there is already a name for these thing within the github/gitlab docs I'd prefer that. If it's something we came up with, a short `*_TOKEN` might be fine.
