### ISSUE TITLE
Make use of EmptyState throughout the Plugins

### ISSUE THREAD

**Issue by marcuseide** [spotify/backstage#2694]
The new [`<EmptyState />`](https://backstage.io/storybook/?path=/story/emptystate--missing-annotation) should be used when a plugin wants to guide a user to an action related to something missing or wants to display more information on why something is missing.

We should look through our existing plugins and update them to use `<EmptyState />`.

**Comment by freben** [comment]
Closing for now, was added in a lot of places.
