### ISSUE TITLE
Fix opacity on illustration in "Developers are People, Too" section

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#270]
The opacities for the illustration in the "devs are people too' section is fainter than it should be on the website version, and in the mobile version, there's some interesting transparency funkiness haha! The illustrations should be 100% opacity.

**Comment by katz95** [comment]
![IMG_1028](https://user-images.githubusercontent.com/61153904/76774360-1900c600-67a4-11ea-8936-9554056b7a7d.PNG)
![Screenshot 2020-03-16 at 4 35 21 PM](https://user-images.githubusercontent.com/61153904/76774390-261db500-67a4-11ea-9e6c-5f3c0b85fb81.png)

**Comment by katz95** [comment]
ideally 🥳:

<img width="787" alt="Screenshot 2020-03-16 at 4 36 26 PM" src="https://user-images.githubusercontent.com/61153904/76774516-4b122800-67a4-11ea-959f-8fc6c8905eb5.png">

**Comment by Rugvip** [comment]
Fixed! Root cause was svgo removing mask-type attributes on svg elements during production build.
