### ISSUE TITLE
Adding meta tags to the site for social media images 

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#271]
Currently there aren't images that pop up in our social media links.

<img width="604" alt="screenshot_2020-03-16_at_16 34 37" src="https://user-images.githubusercontent.com/61153904/76776057-8ca3d280-67a6-11ea-997e-39165e436c53.png">

**Comment by stefanalund** [comment]
Fixed now by @kaimallea:

![Screenshot 2020-03-17 at 08 50 21](https://user-images.githubusercontent.com/190856/76833866-66287a80-682c-11ea-92c6-a38d80462ef9.png)

**Comment by kaimallea** [comment]
Would look even better if Docusaurus framework used Twitter's large summary rather than the small one. I'm going update the image to be the B logo per @katz95 's request
