### ISSUE TITLE
Website font-family uses default serif on Firefox/Windows

### ISSUE THREAD

**Issue by stuart897** [spotify/backstage#272]
In `main.css` the font-family specified is `Helvetica Neue,"sans-serif","system-ui";`

`Helvetica Neue` is missing quotes, and `sans-serif` doesn't require quotes and should probably be the last font in the list since it's the fallback.

![image](https://user-images.githubusercontent.com/17980212/76776314-7e51b880-679e-11ea-8d20-335512d72749.png)

**Comment by freben** [comment]
@stuart897 Thanks for reporting! I checked the delivered CSS and it looks like the font declaration was quoted correctly in the wrapping element. However, some redudant declarations had leaked into subelements, hopefully fixed in https://github.com/spotify/backstage-microsite/pull/96

**Comment by freben** [comment]
Let me know if this didn't address the issue. I unfortunately don't have a windows installation nearby at the moment.

**Comment by stuart897** [comment]
Has your alteration been deployed to the live website? I've cleared browser cache & refreshed but the serif font & CSS is unchanged.

**Comment by freben** [comment]
Yeah. Hm, it seems there's some overly-aggressive CSS optimisation step happening only for prod. Let me check it out more.

**Comment by Rugvip** [comment]
Second fix is live now, looks better for me in FF + Win10

**Comment by stuart897** [comment]
Looks good
