### ISSUE TITLE
Prompt about enabling auth providers when creating new app

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#2721]
## Feature Suggestion

When a new standalone backstage app is created using `npx @backstage/create-app`, it should prompt to relevant docs about enabling Auth providers like GitHub/Google/etc.

## Possible Implementation

* Update `@backstage/create-app` so that it prompts relevant docs links about how the user can enable new authentication providers. https://backstage.io/docs/tutorials/quickstart-app-auth
* Add comments in the [`app-config.yml`](https://github.com/spotify/backstage/blob/1fcf8a75c3dd8b8d0638daa7790590ceab9a3522/packages/create-app/templates/default-app/app-config.yaml.hbs#L57-L58) of the default app about enabling auth providers.

## Context

When a user creates a new standalone app, they don't get any auth providers in their app config. But they will eventually end up adding a few - Google/GitHub.

**Comment by themousepotato** [comment]
Sounds interesting! I'm working on this.

**Comment by Rugvip** [comment]
I think the most straightforward way to solve this is to just add some comments in the created `app-config.yaml` explaining how to populate the auth providers

**Comment by OrkoHunter** [comment]
Adding comments to `app-config.yaml` and prompting relevant auth docs during create-app sounds straightforward and important things at the very least.

Having the ability to choose a few from Google/GitHub/GitLab/Okta/etc. in the create app process might be a fantastic experience IMO. 🤩

**Comment by Rugvip** [comment]
@OrkoHunter you have to go and set up OAuth apps to get client_id + client_secret etc. I feel that would interrupt the flow of the create-app process too much

**Comment by OrkoHunter** [comment]
Hmm. I think you're right. It wouldn't be that helpful to have the Auth environment variables in app-config without them actually being set.

Let me re-purpose my issue. Thanks so much!
