### ISSUE TITLE
Cannot sign in with GitHub locally

### ISSUE THREAD

**Issue by alxmrtn** [spotify/backstage#2733]
## Expected Behavior

I should be able to sign in with GitHub locally

## Current Behavior

Whenever I start the application with the GitHub Client ID and Client Secret, I am able to go through the GitHub login process but then I receive a `Login failed, popup was closed.` error message.

This error is logged in the browser console:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:3000') does not match the recipient window's origin ('http://localhost:7000').
```

There are no errors logged in backend.

## Steps to Reproduce

1. Create OAuth Application on GitHub w/ callback URL of `http://localhost:7000/api/auth/github`
2. Clone backstage git repository
3. Start the application `cd packages/backend && AUTH_GITHUB_CLIENT_ID=xxx AUTH_GITHUB_CLIENT_SECRET=xxx yarn start`
4. Navigate to `localhost:7000`
5. Click "Sign In using GitHub"
6. Follow authorization flow
7. Notice errors mentioned above once signed in

## Context

Was just trying to sign in with GitHub after a fresh install

## Your Environment

- NodeJS Version (v12): 12.18.4
- yarn Version: 1.22.1
- Operating System and Version (e.g. Ubuntu 14.04): macOS 10.15.5
- Browser Information: Opera Version: 71.0.3770.198

**Comment by marcuseide** [comment]
Hey @alxmrtn , Just double-checking here that navigate to `http://localhost:3000` and not `7000` when you run locally. Port `7000` is running the build version and would not pick up the `env` passed in to the command line I think.

**Comment by dtuite** [comment]
@alxmrtn looks like your callback URl is also incorrect. It should be `http://localhost:7000/api/auth/github/handler/frame`.

Here is more information about [setting up GitHub authentication with Backstage](https://roadie.io/blog/github-auth-backstage/).

**Comment by alxmrtn** [comment]
Howdy, thanks for the reply. I was mislead in thinking that the ui that presents itself on `:7000` when booting the backend was the ui to use, when I should be booting the ui on `:3000` in a separate process. Once I had both running and was accessing the frontend on `:3000` I was able to authenticate. Thank y'all for the input. I'm gonna close this.

**Comment by freben** [comment]
Nice! Happy you got it sorted.
