### ISSUE TITLE
Add support for Bitbucket Server as a ReaderProcessor

### ISSUE THREAD

**Issue by goober** [spotify/backstage#2735]
## Add Provider Configuration for Bitbucket Server Processor
Currently, the BitbucketReaderProcessor.ts does not support additional parameters such as target or apiBaseUrl.

## Possible Implementation
Copy the providerconfig and implementation from GithubReaderProcessor in a way that makes sense for BitbucketReaderProcessor. Make sure that api differences between bitbucket.org and a self-hosted Bitbucket server are taken into acount.

Take inspiration of changes made in #2582 

## Context
Access a self-hosted Bitbucket server instance with a custom url.

**Comment by freben** [comment]
Related: https://github.com/spotify/backstage/issues/2735

**Comment by goober** [comment]
I can take a shot at this issue if it is accepted by the project

**Comment by stefanalund** [comment]
Thanks @goober -- I've assigned you!

**Comment by goober** [comment]
I have opened an issue against the git-url-parse repository https://github.com/IonicaBizau/git-url-parse/pull/113 for adding support for bitbucket server url parsing. 

I will hold on further implementation of this feature until the above pull request has been sorted out

**Comment by amitkhurana92** [comment]
Hi Team, any update on this? I need to integrate repo from bitbucket server.

**Comment by goober** [comment]
@amitkhurana92 Thanks for the reminder. IonicaBizau/git-url-parse#113 is now ready for review, and work can be continued when it has been accepted.

**Comment by amitkhurana92** [comment]
@goober the code you have suggested is not working. I think you also need to change in the type mapping

     const typeMapping = [
        { url: /^https:\/\/gitlab\.com\/.*/, type: 'gitlab/api' },
        { url: /^https:\/\/bitbucket\.org\/.*/, type: 'bitbucket/api' },
        { url: /^https:\/\/dev\.azure\.com\/.*/, type: 'azure/api' },
        { url: /.*/, type: 'github' },
      ];

**Comment by goober** [comment]
The open pull request is to add support in the underlying library that backstage is using for fetching content from bitbucket server. No work has started yet in the backstage project

**Comment by goober** [comment]
@amitkhurana92 Please feel free to test the open pull request #3030 to verify that my implementation solves your issues

**Comment by amitkhurana92** [comment]
> @amitkhurana92 Please feel free to test the open pull request #3030 to verify that my implementation solves your issues

@goober good to see that. I will check this over the weekend.

**Comment by JdataNich** [comment]
Is there a template with an example of the Integration for the custom bitbucket urls?

**Comment by amitkhurana92** [comment]
Hi @goober, can you share an example where should I write the credentials?

**Comment by goober** [comment]
Hi @regicsolutions.
Sorry for the late reply. It looks like you are trying to access a bitbucket server that has a self-signed certificate.
We have the same situation and has solved it by telling node to trust our self-signed cert using `NODE_EXTRA_CA_CERTS` environment variable. See https://docs.axway.com/bundle/API_Builder_4x_allOS_en/page/enable_additional_ca_certificates.html for some guidance

**Comment by goober** [comment]
@amitkhurana92 if you are using Bitbucket Server the following setup should work for you:
```yaml
integrations:
   bitbucket:
      - host: bitbucket.mycompany.com
        apiBaseUrl: https://bitbucket.mycompany.com/rest/api/1.0
        token: <your personal access token> # https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html
```

**Comment by regicsolutions** [comment]
Thanks @goober ill give that a try. Have you had any luck integrating Bitbucket Server with the scaffolder backend for software templates?

**Comment by amitkhurana92** [comment]
> @JdataNich and @amitkhurana92 if you are using Bitbucket Server the following setup should work for you:
> 
> ```yaml
> integrations:
>    bitbucket:
>       - host: bitbucket.mycompany.com
>         apiBaseUrl: https://bitbucket.mycompany.com/rest/api/1.0
>         token: <your personal access token> # https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html
> ```

Hi Goober,

It is not working

This is my app-cofig.yaml
`  bitbucket:
    - host: https://bitbucket.mycompany.com/bitbucket
      apiBaseUrl: https://bitbucket.mycompany.com/bitbucket/rest/api/1.0
      token: abcd`

Below is the exception I am getting
`Error: Expected object at root, got string at Module.generalError (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/processors/results.ts:59:56) at parseEntityYaml (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/processors/util/parse.ts:52:68) at parseEntityYaml.next (<anonymous>) at UrlReaderProcessor.readLocation (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/processors/UrlReaderProcessor.ts:64:18) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async LocationReaders.handleLocation (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/LocationReaders.ts:142:13) at async LocationReaders.read (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/LocationReaders.ts:74:11) at async HigherOrderOperations.addLocation (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/HigherOrderOperations.ts:80:26) at async eval (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/service/router.ts:115:22)`

**Comment by Rugvip** [comment]
For reference the issue ^ was `https://bitbucket.mycompany.com/bitbucket` not being a proper host. Added a check for that in https://github.com/backstage/backstage/pull/3692
