### ISSUE TITLE
TechDocs: Cannot view documented-component locally as Guest

### ISSUE THREAD

**Issue by ron-debajyoti** [spotify/backstage#2736]
## Expected Behavior

I should be able to view the documented-component page as a Guest.

## Current Behavior

- Received an ERROR 404: Documentation not found. 
- Browser console shows a CORS error at the end.
- Multiple instances of SSL errors and `repository not found` errors at _backstage_ and  _techdocs_ while running the backend server.
![backstage_earlier](https://user-images.githubusercontent.com/22571664/94989681-36f11500-0594-11eb-8ae3-550fb9094a24.png)
![backstage_bug](https://user-images.githubusercontent.com/22571664/94989670-250f7200-0594-11eb-92e5-25ead9d3458d.png)

## Possible Solution
Maybe handling the CORS issue at the the backend server or techdocs-backend.

## Steps to Reproduce

1. Clone the repo and start the frontend `yarn start ` in a terminal
2. Open another instance and start the backend `cd packages/backend && yarn start`
3. Navigate to `localhost:3000/docs` on browser and click **Read Docs** under documented-component

## Context

 Trying to view Techdocs as a Guest

## Your Environment

- NodeJS Version (v12): 12.16.2
- yarn Version: 1.22.1
- Operating System and Version: Ubuntu 18.04.4
- Browser Information: 81.0 (64-bit)

**Comment by ron-debajyoti** [comment]
Update: 
I added the cors configuration to the `app-config.yaml` in the root directory. This solved the cors issue, but the frontend is unable to perform a GET request to `localhost:7000/api/techdocs/docs`, and the backend server still shows the SSL errors. 
![update](https://user-images.githubusercontent.com/22571664/95102502-18844880-0751-11eb-84c6-93219ad02401.png)

**Comment by hooloovooo** [comment]
@ron-debajyoti Do you have a local git config overriding your gits https url with a ssh url?

**Comment by ron-debajyoti** [comment]
@hooloovooo my global gitconfig file has just my email & my name. The local backstage .git/config file has the https url only.
In my case, I found out that this [function](https://github.com/spotify/backstage/blob/3cfdbd10ad8aea0d621bc490bbe202814a40a185/plugins/techdocs-backend/src/helpers.ts#L100) is resulting in storing an empty repo with no `master` in the `repositoryTmpPath`.

**Comment by ron-debajyoti** [comment]
@hooloovooo my global gitconfig file has just my email & my name. The local backstage .git/config file has the https url only.
In my case, I found out that this [function](https://github.com/spotify/backstage/blob/3cfdbd10ad8aea0d621bc490bbe202814a40a185/plugins/techdocs-backend/src/helpers.ts#L100) is resulting in storing an empty repo with no `master` in the `repositoryTmpPath`.

**Comment by hooloovooo** [comment]
@ron-debajyoti The repository is empty because the checkout fails due to an ssl error. The only times i've seen this it has been because of a url rewrite rule in the git config similar to this. https://www.jvt.me/posts/2019/03/20/git-rewrite-url-https-ssh/

Could you post the output of `git config --list --show-origin` and post that here? Make sure to not include any sensitive info.

**Comment by ron-debajyoti** [comment]
@hooloovooo 
![op](https://user-images.githubusercontent.com/22571664/95190796-75354100-07ed-11eb-9b38-d99ec3444fc7.png)

**Comment by ron-debajyoti** [comment]
@hooloovooo 
![update2](https://user-images.githubusercontent.com/22571664/95190953-ab72c080-07ed-11eb-8fe0-b94471c00788.png)

**Comment by hooloovooo** [comment]
Hmm that looks correct. Can you ping github.com from the commandline and it works?

**Comment by ron-debajyoti** [comment]
@hooloovooo  No, I cannot! That's probably why it wasn't working. Let me try to fix it and update asap.

**Comment by hooloovooo** [comment]
@ron-debajyoti Are you ok with us closing this for now, and you can open up a new issue with the new information we have if you think we have some other issue causing this?

**Comment by ron-debajyoti** [comment]
@hooloovooo yes sounds fine.
