### ISSUE TITLE
Add default catalog-info.yaml when creating new App

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#2754]
## Feature Suggestion

When you [create a new Backstage app](https://backstage.io/docs/getting-started/create-an-app) it should come with a default `catalog-info.yaml` file that can be used to register the Backstage (website) to your own Backstage deployment.

## Possible Implementation

Use this file as a template: https://github.com/spotify/backstage/blob/master/catalog-info.yaml

## Context

This is part of easing the onboarding for someone that adopts Backstage.

**Comment by mahmoodhosseini** [comment]
Hi, I'd like to take this.
