### ISSUE TITLE
Use rel="noopener noreferrer" in anchor tags for external links

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#2760]
## Feature Suggestion

When creating an anchor tag or a `Link` component from Material UI, if the link points to an external website, we should add `rel="noopener noreferrer"` to it for security reasons.

## Possible Implementation

Change https://github.com/spotify/backstage/blob/b407dbf724473d07d36c9bef46ce918c9790e5cc/plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx#L69-L69
to 
```
            <a href={locationMetadata.target} target="_blank" rel="noopener noreferrer">
```

Also change any `Link` components pointing to external websites. (Not sure exactly how to find them apart from manually doing a search for `<Link`)

## Context

https://github.com/spotify/backstage/security/code-scanning/10?query=ref%3Arefs%2Fheads%2Fmaster
https://material-ui.com/components/links/#security

<details>
<summary>Screenshot with security explanation</summary>

![Screenshot 2020-10-05 at 16 47 38](https://user-images.githubusercontent.com/8065913/95094713-7cdfe180-072a-11eb-9f47-a65ec22361b6.png)

</details>

**Comment by Marvin9** [comment]
I would like to work on it.
