### ISSUE TITLE
Control the headers that the proxy backend forwards to the target

### ISSUE THREAD

**Issue by dhenneke** [spotify/backstage#2763]
The proxy backend uses https://github.com/chimurai/http-proxy-middleware to implement the proxy functionality. However, in its current state, it forwards all request headers to the proxy-target. This includes headers that are not meant for the other API, like `Cookie`, but also others that are injected by identity-proxies (`X-Auth-Request-User`, `X-Auth-Request-*`, ...).

## Feature Suggestion

Configure the proxy middleware to not forward certain headers.

## Possible Implementation

There are different approaches for solving this:
1. Hard code a list of non-forwarded headers (Cookie).
2. Make it configurable and decide about a reasonable default.

One option could be to specify a custom [onProxyReq](https://github.com/chimurai/http-proxy-middleware/blob/c8cd3ced13314a401f1e41a01687cce5c280823f/src/types.ts#L29) handler and modify the request. This should of course not override the values that are added in the `headers` config.

If we agree on a solution, we would be happy to contribute the implementation.

**Comment by Rugvip** [comment]
Looks like headers are copied unconditionally, https://github.com/http-party/node-http-proxy/blob/9b96cd725127a024dabebec6c7ea8c807272223d/lib/http-proxy/common.js#L43`

I would imagine it makes sense to explicitly have to allow headers, except for a couple of defaults like `Host`, `Accept`, etc.

**Comment by Fox32** [comment]
> I would imagine it makes sense to explicitly have to allow headers

So are we going into the direction of an allow list with a predefined set of safe headers? If yet, than I guess we can do an implementation.

**Comment by dhenneke** [comment]
Since the `Host` header is already rewritten to the target [by default](https://github.com/spotify/backstage/blob/a10f7ab2a2ea906adde98763576c8fc0fe73ebce/plugins/proxy-backend/src/service/router.ts#L60) so this should be safe to forward.

**Comment by freben** [comment]
I would definitely prefer an allowlist as well.

**Comment by Rugvip** [comment]
I say we
![image](https://user-images.githubusercontent.com/4984472/95125288-03111d80-0755-11eb-81da-33737d7aba13.png)

I would imagine a sane set to always allow headers would be any header crucial to the proxying functionality, like `Host`, along with the headers that are allowed by default in CORS?

**Comment by dhenneke** [comment]
CORS is a great idea. I tried to find references on what headers might be safe in such scenarios, but didn't found the right google search for that. But https://fetch.spec.whatwg.org/#cors-safelisted-request-header seems like a good start.
