### ISSUE TITLE
Rename GaugeProgress to just Gauge

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#2773]
## Feature Suggestion
The `GaugeProgress` component lives in a folder called `progress` already. Let's just move it to `Gauge` instead, and remove the `Progress` part.

Both the filename and the exported variable :)

**Comment by jadonwolffs** [comment]
I'd love to be assigned this if possible

**Comment by stefanalund** [comment]
All yours @jadonwolffs ⚡️

**Comment by Rugvip** [comment]
Fixed by #2774
