### ISSUE TITLE
Sourcemaps are missing from distribution packages and local builds

### ISSUE THREAD

**Issue by taras** [spotify/backstage#2785]
I'm trying to debug #2764 but finding it difficult to navigate the codebase with the Node.js Inspector because there are no source maps. Without sourcemaps, it's very difficult to place breakpoints by looking at TypeScript source code. This problem effects both contributors to Backstage and developers consuming Backstage.

## Expected Behavior

Backstage distribution packages should include working sourcemaps. Building a development environment locally should generate sourcemaps for local debugging.

## Current Behavior

Sourcemaps are not included in distribution packages. Sourcemaps are not generated when running the project locally from source.

## Possible Solution

For distribution packages, we need to configure `esbuild` to include sourcemaps. We might also need to include the TypeScript source code to ensure that sourcemaps have actual source that they reference. 

For local development, we need to generate sourcemaps and point them at `src`directories.  

## Steps to Reproduce

For distribution packages,

1. download a package from NPM and look at it's content
2. it'll be missing .map files

For local development,

1. Build project locally
2. dist will be missing .map files

**Comment by adminy** [comment]
still an issue with vite.
