### ISSUE TITLE
Make GitHub icon in the header customizable (GitLab etc)

### ISSUE THREAD

**Issue by emmaindal** [spotify/backstage#2797]
Currently, the GitHub icon will always be a GitHub icon even if you use GitLab for example. This Icon should change depending on where your repo is located. 

Investigate if Material UI's icon library has other icons that can be used for this or a more neutral icon that can be used every time. 

![Screen Shot 2020-10-08 at 11 55 41 AM](https://user-images.githubusercontent.com/25153114/95443771-48a03700-095d-11eb-9391-7918e6310200.png)

**Comment by erictnilsson** [comment]
I'd like to take a look at this! Could you assign me to the issue? :)

**Comment by emmaindal** [comment]
@erictnilsson Nice! Thanks 😄 will assign to you!

**Comment by erictnilsson** [comment]
Hey!
So, apart from Github, there aren't any other source control/repo icons within the Material UI's icon library. I've sampled a few general ones below that are somewhat descriptive of the SC/repo location? Not sure. One is for `code`, one is for `cloud`, one is for `folder`, and one is for `storage`: 
<img width="1215" alt="Screenshot 2020-10-08 at 20 22 03" src="https://user-images.githubusercontent.com/16206098/95499911-42827880-09a6-11eb-8902-ad1eb128f71f.png">
<img width="1216" alt="Screenshot 2020-10-08 at 20 23 28" src="https://user-images.githubusercontent.com/16206098/95499915-457d6900-09a6-11eb-82e4-5141e730a1ab.png">
<img width="1216" alt="Screenshot 2020-10-08 at 20 25 34" src="https://user-images.githubusercontent.com/16206098/95499918-4615ff80-09a6-11eb-899e-440938b1fca3.png">
<img width="1216" alt="Screenshot 2020-10-08 at 20 27 11" src="https://user-images.githubusercontent.com/16206098/95499921-46ae9600-09a6-11eb-8970-2af6cef38754.png">

I'm not 100% sold on either of them, I'd much rather have a proper source control icon like this one: 
<img width="378" alt="Screenshot 2020-10-08 at 20 33 28" src="https://user-images.githubusercontent.com/16206098/95499832-2979c780-09a6-11eb-91eb-9d0e8c0a47da.png">
but unfortunately it's not a Material icon.

What do you think @emmaindal? :)

**Comment by erictnilsson** [comment]
I guess if we go with putting a .svg as an asset we might as well get the logos for Azure, Gitlab, and Bitbucket from their press kits and do the same thing. However I'm not at all sure what licensing problems that might entail :P

**Comment by emmaindal** [comment]
Hey @erictnilsson wow thank you so much for putting this together! I like the `code` one though! Let's see if we can get some input from @katz95 or maybe @nikek on this 😄

**Comment by emmaindal** [comment]
Alright @erictnilsson I don't want to block you on this so let's go with the `code` icon for all now and we will see if we can put together icon designs for the different source code providers we support!

**Comment by emmaindal** [comment]
unless my friends over at @spotify/techdocs-core have any other suggestions? 🎉

**Comment by hooloovooo** [comment]
Agreed. Just going with the `code` icon for now seems like a good enough solution for now.

**Comment by erictnilsson** [comment]
Cool! I've linked a pull request now :)

**Comment by emmaindal** [comment]
closed by: #2895
