### ISSUE TITLE
Add deployment documentation with examples

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#282]
May depend on #283 .

Primarily we want to have a DEPLOYMENT.md file that outlines some basic deployment options.

Pick a primary very simple example means of deployment, for example GitHub pages. This will make it easy for integrators to get up and running.

**Comment by alaiacano** [comment]
👋 I was able to deploy to Heroku with these small changes: https://github.com/alaiacano/backstage/commit/abe9aab7f95b779dacfeba6ee96ef69c7afca177

**Comment by Rugvip** [comment]
@alaiacano Nice, do you wanna submit a PR with those changes? 😄

Would be awesome if you want to write up a tiny guide to how you set it up on Heroku as well :grin:

**Comment by stefanalund** [comment]
Fixed in https://github.com/spotify/backstage/pull/379

**Comment by stefanalund** [comment]
Closed in https://github.com/spotify/backstage/pull/379
