### ISSUE TITLE
Entering YAML-null values when creating a component breaks the component registration

### ISSUE THREAD

**Issue by erictnilsson** [spotify/backstage#2832]
## Summary
When creating a new component from one of the available templates, the user can insert whitespace, `null`, and `~` for the `owner` field and the `description` field. This breaks the registration of the component from the `component-info.yaml` file since the three values are interpreted as null in YAML which throws an error in the catalog. This results in the component being published to the repo but not registered in the catalog; when attempting to registering it manually an error occurs. 

Creating a component with whitespace for the `description` and `owner`:
<img width="1195" alt="Screenshot 2020-10-08 at 20 44 41" src="https://user-images.githubusercontent.com/16206098/95584049-5af1a200-0a3d-11eb-820a-8916cb5db66f.png">
The generated `component-info.yaml`:
<img width="642" alt="Screenshot 2020-10-08 at 20 51 47" src="https://user-images.githubusercontent.com/16206098/95584071-65ac3700-0a3d-11eb-8391-12a3f98df7cf.png">
The error thrown when manually registering the component: 
<img width="676" alt="Screenshot 2020-10-08 at 20 51 14" src="https://user-images.githubusercontent.com/16206098/95584081-6b098180-0a3d-11eb-94d4-f545f832622e.png">

## Expected Behavior
The form should probably not allow the user to enter  whitespace, `null`, and `~` in the `description` field and the `owner` field, just like the form validates the `storePath` field.

## Current Behavior
The form allows the three null-values and the component fails to register to the catalog after creating and publishing the component. 

## Possible Solution
To solve it, I think that we can set a `format` for the owner and the description in the component's template.yaml. Then, we can inject a customFormat in TemplatePage.tsx that contains a RegEx filtering any inputs that are whitespace, `null`, or `~`.  

## Steps to Reproduce
1. Navigate to /create/ and pick any component template. 
2. Set the description and/or the owner to whitespace, `null`, or `~`.
3. Create the component. 
4. Wait for it to complete, see results. 
5. (optional) try to register the newly-created component at `/register-component`, see error. 

## Context
Error from catalog when it tries to register the faulty `component-info.yaml`:
<img width="947" alt="Screenshot 2020-10-09 at 14 54 22" src="https://user-images.githubusercontent.com/16206098/95585438-84133200-0a3f-11eb-9bce-315b1a1997ef.png">

## Your Environment
- NodeJS Version (v12): v12.18.4
- Operating System and Version: macOS catalina version 10.15.4
- Browser Information: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by erictnilsson** [comment]
If you think my proposed solution is the way to go, I can have a pull-request ready ASAP. Either way, I'd love to be assigned to the issue and resolve it :)

**Comment by Rugvip** [comment]
@erictnilsson I think adding validation as part of JSONSchema makes sense: https://json-schema.org/draft/2019-09/json-schema-validation.html

**Comment by erictnilsson** [comment]
> @erictnilsson I think adding validation as part of JSONSchema makes sense: https://json-schema.org/draft/2019-09/json-schema-validation.html

**Comment by erictnilsson** [comment]
Cool, I'll look into it :)

**Comment by freben** [comment]
I would expect our code to generate a yaml file that is valid for any input in the text boxes. Even if the input was the string `~`, I would expect the generated file to contain `"~"` (note the quotes coercing it to a string).

The problem here is cookiecutter blindly making a file without knowing its format right? You mention `format`, doesn't cookiecutter have the ability to quote/escape the things it injects?

**Comment by freben** [comment]
Should we insert jsonify for these fields in the template? https://cookiecutter.readthedocs.io/en/latest/advanced/template_extensions.html#jsonify-extension

**Comment by Rugvip** [comment]
@freben I was just assuming that the template yaml was generated from data, but maybe that's not the case and it cookie cuts. Should definitely do that too, as in generating the entity yamls using `YAML.stringify`-equivalent thing imo. Or just in some other way making sure the values get inserted correctly.

Two separate issues though, one is the upfront validation and the other is correctly inserting the values into the yaml. Both should be fixed

**Comment by freben** [comment]
If we escape properly, there are no invalid values :)

I would argue that having a cookiecutter yaml file with 

```yaml
field: {{ value }}
```

is an actual bug that has to be fixed - you can inject absolutely anything there that breaks both parsing and structure. And the proper way to do it as a template author would be to add `| jsonify` to it imo

**Comment by Rugvip** [comment]
@freben @erictnilsson  was thinking about the more general template values case btw, for example ensuring that the GitHub slug has a `/` in it

**Comment by freben** [comment]
Yep there's definitely room for proper validation as well!

**Comment by erictnilsson** [comment]
Right. Recap just so to make sure I'm understanding you correctly: 

1. We should `jsonify` relevant fields in the cookiecutter yaml-files so that the values are enclosed with "". 

2. We can also validate the relevant fields like we do with _Github slug_ so that the user cannot insert whitespace, `~` or `null`? For that you mentioned adding validation as part of JSONschema @Rugvip ; am I correct in interpreting your approach as directly using `pattern` in the template.yaml-file like so:
<img width="502" alt="Screenshot 2020-10-13 at 17 01 46" src="https://user-images.githubusercontent.com/16206098/95879206-606d2600-0d76-11eb-91b8-c3cd027d9b0b.png">

instead of using format which I proposed as a possible solution, like this: 
<img width="502" alt="Screenshot 2020-10-13 at 17 01 13" src="https://user-images.githubusercontent.com/16206098/95879230-67943400-0d76-11eb-9bd9-861c6116ff8d.png">

Because it's easier to handle the error-message prompted to the user using a `format` since the error that's printed is something like _".description must follow format "Cannot be a YAML-null""_. Whereas for the `pattern`, the printed error becomes this: 
<img width="1181" alt="Screenshot 2020-10-13 at 16 18 33" src="https://user-images.githubusercontent.com/16206098/95879285-7a0e6d80-0d76-11eb-8199-c13db03799a1.png">

I'd love to hear your thoughts @freben @Rugvip !

**Comment by freben** [comment]
For 2, I'm hoping we should NOT worry about ~ etc since if we jsonify properly, they aren't a problem. Validation should be for domain specific things, not to avoid yaml problems. So yep, schema checking that something is on the form `\w+/\w+` is fine but because it's the domain syntax, not because it saves the yaml file :) may still need escaping/quoting after domain validation

**Comment by erictnilsson** [comment]
I see! That makes a lot of sense. But then I don't see a reason to add any more validation than what is already present; `required` already takes care of _something_ needing to be entered, right?

**Comment by freben** [comment]
Not sure! I'd have to double check :) And for the user's sake it's really nice with rich feedback telling them not "doesn't match regex" but rather "this has to be an X and an Y separated by slash, and you need to be owner of Y" etc etc :)

**Comment by freben** [comment]
@erictnilsson Looping back, is the remaining validation something you would like to contribute or should we close this ticket for now and put future improvements as a separate ticket when we get to it?

**Comment by erictnilsson** [comment]
@freben I think we can close this one :)

**Comment by Rugvip** [comment]
Alright, let's pick up the schema validation bit as part of future scafoddler work!
