### ISSUE TITLE
Using PostgreSQL for development causes error

### ISSUE THREAD

**Issue by taras** [spotify/backstage#2835]
https://github.com/spotify/backstage/commit/28793b502cdeb048b12a28c96834da3fff940c31 was failing to start backend server in development. This might have been overlooked if you're using PostgreSQL in development.

## Expected Behavior

Should be able to use Backstage in development with PostgreSQL.

## Current Behavior

![image](https://user-images.githubusercontent.com/74687/95594162-9168f600-0a18-11eb-98ef-c50e0e576e60.png)

## Possible Solution

@Rugvip suggested that it might be "related to the recent DB schema changes". 

## Steps to Reproduce

1. Configure your local development instance to use PostgreSQL
2. Run `yarn start-backend` 
3. 💥 

## Context

I was using PostgreSQL for development but switched to sqlite for now.

**Comment by freben** [comment]
Trying the following:

- `docker run -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:latest`
- connect with pssh and `create database backstage_plugin_catalog;`
- in `app-config.local.yaml`, set the config as below
- on latest master, do `yarn start-backend`

```yaml
backend:
  database:
    client: pg
    connection:
      host: localhost
      user: postgres
      password: postgres
```

The backend starts up successfully and starts populating it with entities and can be queried for them.

Are you sure the database instance was empty beforehand? Seems like the `entities_search` table had a very large `value`. This is obviously something we should fix - it doesn't make sense to even store values that large at all! I'll look into that immediately.

**Comment by taras** [comment]
Ok, let me try it again. I'll create better reproduction instructions.

**Comment by Remyapraveen** [comment]
Hi, My Backstage App has trouble connecting to the Backend, PostgreSQL DB and building a Docker Image.. Receiving this error message or the other every time..  "Backend failed to start up, Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: connect ECONNREFUSED 127.0.0.1:5432" 
Have tried many different connection Parameters. But no luck.. 
Also the deployment to Heroku seems impossible even with SQLite DB too. Its been hard work setting up this. Any suggestions or insights would be very helpful and highly appreciated

**Comment by taras** [comment]
@Remyapraveen it sounds like you have a db connection problem which needs to be troubleshooted. You can try #support channel in Discord or message me directly in Discord.

**Comment by Remyapraveen** [comment]
Hi Taras, Sure shall connect with you in Discord. Did try to uninstall everything and start over again. A couple of things seems working. Shall keep you posted.

**Comment by taras** [comment]
@Remyapraveen I just helped someone troubleshoot a similar problem. If you're getting ECONNREFUSED, that means that your Backstage is not able to connect to the host. I'm guessing that your Postgres is not actually running on 127.0.0.1:5432. Instead, it's running on some host. Where are you trying to run your Backstage?

**Comment by Remyapraveen** [comment]
![Screenshot (277)](https://user-images.githubusercontent.com/93478132/177899892-0d53d701-5f21-416f-8c1b-c84771717079.png)
While I was reinstalling postgres, I had received this message, but then once after I restarted, this one was fine, and was allowed to make the basic installation setup. Now when I am trying on Ubuntu, it shows my postgres 12.11 is running. But still facing some other issues to check the status or so.
