### ISSUE TITLE
Build and test only changed packages

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#285]
Make it so that `yarn build`/`test` at the project root only runs it for packages that are changed/affected.

Preferably, `yarn start` should be smart enough to only rebuild what's necessary on startup, and also when the repo changes (e.g. checking out an entirely separate branch).

Probably make use of the lerna `since` flag as used in CI/CD.

**Comment by mateusmarquezini** [comment]
Hi @Rugvip !

After making this change, `yarn build/ test ` should look for the plugin folder changed or newer yet?

Currently, the `yarn test` is running the entire folder, considering plugins folders.

**Comment by Rugvip** [comment]
@mateusmarquezini Yeah something like that, thinking it makes sense to do some hash-based caching but not sure. Ideally the caching should work with CI as well.

**Comment by mateusmarquezini** [comment]
@Rugvip lerna flag `--since master` does the trick, but I'm trying to understand why it's ignoring plugin folders 😅.

Can you assign this issue to me, please? Thx!

**Comment by Rugvip** [comment]
Sure, thanks!
