### ISSUE TITLE
[RFC] Update packages to address vulnerabilities reported by yarn audit

### ISSUE THREAD

**Issue by renvrant** [spotify/backstage#2884]
Running `yarn audit` on the repo at present currently reports ~100 issues, most of them duplicated. 

## Current Behavior

```
100 vulnerabilities found - Packages audited: 3113
Severity: 17 Low | 77 High | 6 Critical
```

## Possible Solution

Many could be eliminated by upgrading lerna and cli/webpack.
It might also be good to have audit reporting vulnerabilities as a part of CI builds to keep the problem visible, if that isn't already being done.

## Steps to Reproduce

Run `yarn audit` on the project.

**Comment by Rugvip** [comment]
We're relying on GitHub's dependabot alerts for this atm. Would you say yarn adit provides adittional value?

**Comment by renvrant** [comment]
@Rugvip I think they serve different purposes, as audit is just reporting. It could still be useful to integrate for visibility you might be missing. For instance, dependabot seems to have opened a PR for webpack which will address the critical vulnerability, but not for lerna.

**Comment by Rugvip** [comment]
@renvrant Dependabot does auditing too, but you need write access to the repo to see them. There may be other reasons it's not opening PRs though, like no available versions that fixes the vulnerability yet.

**Comment by andrewthauer** [comment]
I did noticed there is a dependabot PR for webpack 5 which may resolve some of the underlying audit issues - https://github.com/spotify/backstage/pull/2871. It's failing CI though.

**Comment by freben** [comment]
@renvrant We talked a bit about this and since we have a system in place (the dependabot checks, and keeping track of reports in GitHub), we are considering closing this ticket. Does that sound sensible?

**Comment by stefanalund** [comment]
Feel free to reopen if you don't agree.
