### ISSUE TITLE
[WANTED]: Lead Backstage Developer

### ISSUE THREAD

**Issue by ericsmithfboston** [spotify/backstage#2885]
We are in the initial stages of creating a developer portal / console based on Backstage and are looking for someone to help lead the effort.  The role would include opportunities to contribute back to the main Backstage project while focused on delivering features for our internal portal.
 
If you are interested in learning more about the role, please contact me at "eric.smith at homesite.com".  

 (Permanent remote work welcomed)
 
Apologies for the noise otherwise.

**Comment by dtuite** [comment]
@ericsmithfboston Just sent you an email. Looking forward to chatting.

**Comment by stefanalund** [comment]
Seems like you’ve made a connection, so closing this now. Posting a message in one our Discord channels is another option to find people. Good luck with your project!
