### ISSUE TITLE
Tests in core should be written in TypeScript

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#2891]
We don't enforce this across all packages at all, but for core it's nice to have the tests written in TypeScript. It provides an additional layer of checking that the types are correct.

The following files are currently JS:

- [ ] packages/core/src/components/Link/Link.test.jsx
- [ ] packages/core/src/components/Button/Button.test.jsx
- [ ] packages/core/src/components/ProgressBars/Gauge.test.jsx
- [ ] packages/core/src/components/Lifecycle/Lifecycle.test.jsx
- [ ] packages/core/src/components/ProgressBars/GaugeCard.test.jsx
- [ ] packages/core/src/components/HorizontalScrollGrid/HorizontalScrollGrid.test.jsx
- [ ] packages/core/src/components/StructuredMetadataTable/StructuredMetadataTable.test.jsx

**Comment by JoelLau** [comment]
hi, is this available for anyone to contribute to?

**Comment by Rugvip** [comment]
@JoelLau sorry, samiramkr is already working on it

**Comment by JoelLau** [comment]
@Rugvip oh yeah sure, that's what I was wondering haha. thnks for the quick response anyways!
