### ISSUE TITLE
Scaffolder backend- provide base url for creating apps in Enterprise GitHub

### ISSUE THREAD

**Issue by SuganJoe** [spotify/backstage#2906]
## Feature Suggestion

To support creating app repos in Enterprise Github, we may want to add  **base url** as environment variable explicitly under  scaffolder in app-config.yaml (similar to gitlab).

## Possible Implementation
1. Add an environment variable for **base url** for scaffolder Github 

2. use the same while instantiating **githubClient** , can keep this as optional input param.
      const githubBaseUrl = githubConfig.getString('baseUrl');
      const githubToken = githubConfig.getString('token');
      const githubClient = new Octokit({ auth: githubToken, baseUrl: githubBaseUrl });  

## Context
While creating app repo in Enterprise GitHub from backstage, current implementation fails at publish stage with "bad credentials" error. Making the above changes will fix the issue.

**Comment by SuganJoe** [comment]
@stefanalund I have little change which I would like to contribute back to backstage, what is the procedure to start doing it ?

**Comment by freben** [comment]
@SuganJoe If it's small and uncontroversial, just throw a PR our way. Otherwise feel free to discuss on our Discord if you have some questions first.
