### ISSUE TITLE
Move Catalog REST API filters into their own query parameter

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#2910]
## Feature Suggestion

All query parameters are treated as filters when querying the catalog right now, implemented [here](https://github.com/spotify/backstage/blob/7ff2f1c0f0c63b8be5712a56569b83743b79f980/plugins/catalog-backend/src/service/router.ts#L128). We should move filters into a dedicated query parameter such as `?filter=` or `?q=` in order to make space for things like pagination and sorting parameters.

## Possible Implementation

Either move in the filters mostly as is, something like `?filter=metadata.name=my-component&filter=kind=component`. Or encode the same data in something like JSON so that we can evolve it a bit easier in the future: `?filter={"metadata":{"name":"my-component"},"kind":"component"}`

## Context

Settling a reasonably stable version of the catalog API, which we're able to evolve over time.

Also a previous discussion on Discord: https://discordapp.com/channels/687207715902193673/687207715902193679/759482223388393473

**Comment by mahmoodhosseini** [comment]
I'd like to work on this issue.

**Comment by Rugvip** [comment]
@mahmoodhosseini Thanks!

I think it's best if we start with agreeing on the new format for the filters. Do you have a suggestion for what it could look like? One of the possible implementations or something different?

**Comment by freben** [comment]
I vote `?filter=a=b&filter=c=d`. Am not fond of the json syntax in a query string, if we want le ultra advanced filter syntax trees and stuff in the future, we can add a new `query` param exclusively for that at a later time.

**Comment by Rugvip** [comment]
Should we go with this? https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/

**Comment by freben** [comment]
I think you need to clarify that last one with an example :)

Supporting just `=` first and then adding `!=` later sounds fine.

What did you mean that the key of the query params should be?

I do not think we should change the current semantics right? Where `a=1&a=2&b=3` means `a is either 1 or 2, and b is 3`

**Comment by Rugvip** [comment]
> I do not think we should change the current semantics right? Where `a=1&a=2&b=3` means `a is either 1 or 2, and b is 3`

Whether we'd want to express this as `filter=a=1,a=2&filter=b=2` or `filter=a=1,b=3&filter=a=2,b=3`

...

Or `filter={a:{$in:[1,2]},b:3}` 😏

**Comment by freben** [comment]
or as `filter=a=1,a=2,b=2`.

But I'm not sure about introducing the use of commas. Do we wanna go there? My original goal was to use pure and simple query params, and then in the future introduce a more advanced thing if it became necessary (and that one may even be a POST with a big json blob or whatever, sure it could be encoded in a GET as well, but essentially it would be another future extension)

**Comment by Rugvip** [comment]
@freben I want to go with something that at the very least lets us add basic AND/OR nesting,  such as the one above. Either now or in a future non-breaking change

**Comment by freben** [comment]
IN (as a special case of OR) + AND was pretty powerful to get started with I thought; it let me express pretty much everything I wanted from the start. And trivial to type out and do simple work with, rather than struggling to get the escaping right for a json blob in bash with curly braces that want to get expanded etc. :) Mm we can always add one more as a non-breaking either way.

**Comment by freben** [comment]
Let's set a decision on this one.

- Query parameter name: `filter`
- If no filter is specified, all items are returned.
- Each `filter` parameter is a comma separated list of `a=b` pairs, effectively with an AND between them. For example, `filter=a=1,b=2` means "a equals 1, and b equals 2".
- If a single `filter` contains a repeated key, it represents an IN. For example, "filter=a=1,a=2,b=3" means "a equals either 1 or 2, and b equals 3".
- If more than one `filter` parameter is specified, there is effectively an OR between those groups. For example, `?filter=a=1&filter=b=2` means "either a equals 1, or b equals 2"

@Rugvip i think that would be the most powerful and flexible query structure we could express without going full elasticsearch, and it wouldn't be overly hard to implement either. Does that makes sense? It's pretty much a union of our ideas too

**Comment by freben** [comment]
@mahmoodhosseini would you be up for implementing the above if it gets the thumbs up?

**Comment by freben** [comment]
it would essentially amount to

- for each `filter`, add an `.orWhere(fn)`
- inside that `fn`, for each unique key, add a nested `this.andWhereIn` or `this.andWhere` depending on if there were multiple possible values for that key

**Comment by Rugvip** [comment]
@freben yep, +1 for OR-ing filters and AND-ing pairs.

Agree that this pattern overall should take us really far, and it's possible to implement something like a JSON query in a backwards compatible way easily if needed.

A fun one btw, how do you filter for an entity such as `component:default/my-weird,entity-name`? ._.

We do need something for arrays and existence too, and then that should hopefully cover everything

Thinking that given the following in the DB:

```yaml
apiVersion: v1
kind: Component
metadata:
  name: foo
  namespace: bar
  annotations:
    my-annotation: datadatadatadatadatadata
relations:
  - type: owner
    target: user:org/user1
  - type: dependency
    target: resource:bar/foo-db
```

We'd be able to match that with all of these:

#### Regular filter with `foo && bar`

`filter=metadata.name=foo,metadata.namespace=bar`

#### Filter by existence of field

`filter=metadata.annotations.my-annotation`

#### When combining pairs for array items, they must all match a single item

`filter=relations.type=owner,relations.target=user:org/user1`

#### This would NOT match

`filter=relations.type=owner,relations.type=dependency`

#### But you can ofc express the intended query with multiple filters

`filter=relations.type=owner&filter=relations.type=dependency`

**Comment by freben** [comment]
Yes but, for the case of relations, they would probably be on the form `filter=relations.owner=user:org/user1` (with the same semantics for existence, where you leave out the equals sign and value).

Oh and to add - we should still be supporting `*` and `%` as glob markers

**Comment by Rugvip** [comment]
@freben yeah it's nice but unfortunate that we need special logic for that. If we go with that I think we just don't handle the general case of arrays at all?

We may want to make sure we're able to query future additional fields in relations tho, but we're a bit locked in if we say that `relations.x` always refers to the type field.

**Comment by freben** [comment]
Arrays aren't handled at that level (the query engine) - it's handled in the code that generates the entities_search table entries. So the array handling is orthogonal to this issue.

**Comment by freben** [comment]
And extra fields in relations will probably be `relations.owner.type=x` for example, but again, that's up to the entities_search generation code, not the filtering query engine

**Comment by freben** [comment]
@mahmoodhosseini Is this something that you still want to implement?

**Comment by mahmoodhosseini** [comment]
@freben, @Rugvip, sorry for the late response. I had quite a bit of stuff come up, and I really dropped the ball. Even though I'd like to work on this issue, I don't think I can commit. I've been enjoying contributing to backstage and hope to contribute more in the future. Thanks.

**Comment by benjdlambert** [comment]
@mahmoodhosseini hey!

It's no problem at all, hope to see you around in the future!
