### ISSUE TITLE
"Company Radar" section on tech-radar page flowing out of HTML

### ISSUE THREAD

**Issue by abhishekjakhar** [spotify/backstage#2919]
## Expected Behavior

The section with title "Company Radar" should scroll horizontally inside the container instead of flowing out of the parent element.

<img width="960" alt="tech-radar-fix" src="https://user-images.githubusercontent.com/19193724/96169812-57c84b80-0f40-11eb-9b32-5ac0d9f58eea.png">

## Current Behavior

The section with title "Company Radar" is flowing out of it's parent element.

<img width="960" alt="tech-radar-bug" src="https://user-images.githubusercontent.com/19193724/96169845-644ca400-0f40-11eb-804e-052a9b4bd78b.png">
<img width="960" alt="tech-radar-bug-overflow" src="https://user-images.githubusercontent.com/19193724/96169856-6adb1b80-0f40-11eb-9d69-1d42121eb385.png">

## Possible Solution

Give `overflow-x: scroll` CSS property to the parent element of section with title "Company Radar" on tech-radar page

## Steps to Reproduce

1. Go to this route http://localhost:3000/tech-radar 

## Context

I was setting up the project project locally for making open source contributions, while going through the project I saw this issue.

- NodeJS Version (v12): V14.13.1
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina 10.15.7 (19H2)
- Browser Information: Google Chrome Version 86.0.4240.80

**Comment by freben** [comment]
@abhishekjakhar Yep, it's not very responsive right now. Nice well presented bug report! Would you like to get assigned to try to fix it?

**Comment by abhishekjakhar** [comment]
> @abhishekjakhar Yep, it's not very responsive right now. Nice well presented bug report! Would you like to get assigned to try to fix it?

I would love to raise the PR

**Comment by freben** [comment]
Assigned!

**Comment by abhishekjakhar** [comment]
@freben I have raised the PR https://github.com/spotify/backstage/pull/2928

**Comment by freben** [comment]
Thank you!
