### ISSUE TITLE
Add GitHub auth

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#292]
Waiting for #366

**Comment by sladyn98** [comment]
@Rugvip I could take a shot at this, any pointers to get started ?

**Comment by Rugvip** [comment]
@sladyn98 Awesome! Our long-term idea is to use http://www.passportjs.org/ for an auth backend, and lift out a popup-based auth strategy that we're using internally. It's similar to https://github.com/jaredhanson/passport-facebook/issues/188, but the page loaded at the redirect url inside the popup is just a script that posts the auth response to the parent page and then closes itself. Something like this:

``` html
<html><body><script>
window.opener.postMessage({ accessToken, scope }, origin);
window.close();
</script></body></html>
```

Got any thoughts on this approach? :grin:

For now we're thinking that a simple auth dialog where you paste a personal access token from https://github.com/settings/tokens is enough though. To save ppl the headache of spinning up an auth backend and setting up an OAuth app. What do you think? Can also pop by Discord to discuss it 😄

**Comment by Rugvip** [comment]
#326 relates to this and how plugins would make use of a GHE auth API.

**Comment by toonsevrin** [comment]
OAuth app is definitely superior to copy pasting a token: 

The UX for the developers is better (+ better security) as you won't have to copy-paste your token over and over (except if you are storing the token in some permanent storage like the localstorage but that may not be the best idea).

**Comment by sladyn98** [comment]
@Rugvip I guess having an OAuth app seems to be more preferable, and plus it is relatively easier to setup. https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

**Comment by stefanalund** [comment]
Addressed in #354

**Comment by Rugvip** [comment]
@sladyn98 Yeah OAuth is miles better, pasting a token is just a stop-gap solution.

**Comment by sladyn98** [comment]
IS this issue completed or still up for grabs ?

**Comment by stefanalund** [comment]
@sladyn98 I believe we still need to make a decision on the backend part before we can make meaningful progress on this issue https://github.com/spotify/backstage/issues/366

**Comment by sladyn98** [comment]
No worries, take your time.
