### ISSUE TITLE
CLI test should be refactored to use mock-fs instead of temporary files

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#2926]
## Expected Behavior

We should use `mock-fs` when testing file-system operations instead of working with actual files.

## Current Behavior

Many tests in the CLI use temporary directories and copy around existing files during testing. This ends up in more fragile and slower tests.

## Possible Solution

Refactor!

## Context

Master build failures in one of the tests: https://github.com/spotify/backstage/runs/1263991815?check_suite_focus=true

**Comment by ayshiff** [comment]
Can I work on this @Rugvip ?

**Comment by Rugvip** [comment]
@ayshiff yes, thank you!
