### ISSUE TITLE
TechDocs: Ensure security of dependencies by doing a checksum after downloads

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#2931]
In our [techdocs-container](https://github.com/spotify/backstage/blob/master/packages/techdocs-container/Dockerfile) docker image, we have [PlantUML](https://github.com/spotify/backstage/blob/master/packages/techdocs-container/Dockerfile#L20) as a dependency. We download the jar file and then execute it to install.

As a security measure, we should verify the checksum for its integrity after downloading and before executing. To fix this issue, update the Dockerfile accordingly.

The sha1 sum of plantuml version 1.2020.16 is `c789ace48347c43073232b1458badc5810c01fe8`. Please confirm and correct if I am wrong.

**Comment by themousepotato** [comment]
@OrkoHunter I think this should be closed by #3029

**Comment by OrkoHunter** [comment]
Aah yes. Thank you so much @themousepotato. 💯
