### ISSUE TITLE
Broken build step on macOS

### ISSUE THREAD

**Issue by mplesec** [spotify/backstage#2935]
## Expected Behavior

Running the backend's build step outputs bundle without any errors.

## Current Behavior

Encountered an issue when trying to run the backend. Followed the instructions here: https://backstage.io/docs/getting-started/create-an-app

Running `npx @backstage/create-app` works fine, no errors. Same with running `yarn start`.

However when starting the backend it throws:
```
% yarn workspace backend start
yarn workspace v1.22.4
yarn run v1.22.4
$ backstage-cli backend:dev
Build succeeded
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '../build/Debug/nodegit.node'
```

I've noticed that the `npx @backstage/create-app` command doesn't run the `yarn build` step like in the instructions.
Running that command throws the following error:
```
throw new Error('esbuild: Failed to install correctly');
```

## Possible Solution

It seems the culprit is the `esbuild` package. When installing it on macOS the output binary is just this:
```
% cat node_modules/esbuild/bin/esbuild
#!/usr/bin/env node
throw new Error(`esbuild: Failed to install correctly`);
```

Issue on their repo: https://github.com/evanw/esbuild/issues/462, in the meantime it might make sense to switch to using the wasm binary they provide: https://www.npmjs.com/package/esbuild-wasm

## Steps to Reproduce

See above

## Context

Cannot run backend.

## Your Environment

- NodeJS Version (v12): 12.18.3
- Operating System and Version (e.g. Ubuntu 14.04): macOS 10.15.7 (19H2)
- Browser Information: N/A

**Comment by mplesec** [comment]
Found the issue. Occurs if npm or yarn config has `ignore-scripts` set to `true` since the `esbuild` package runs a post-install script.

Solved with running `npm config set ignore-scripts false`.

**Comment by freben** [comment]
Aha! Great that you managed to find it yourself. Thanks for checking back in. Maybe we should add this to our docs.

**Comment by mplesec** [comment]
Added this to docs: https://github.com/spotify/backstage/pull/2954
