### ISSUE TITLE
Unregister entity UI seems to be broken when there are no entities

### ISSUE THREAD

**Issue by abhishekjakhar** [spotify/backstage#2939]
If we don't get any entities from the api/catalog/entities API, in that case we get an empty array. Now, in the UnregisterEntityDialog.tsx when we try to unregister entity we don't have any entity but still we show the UI which displays the list of entities, which seems to be broken. This results in `<li></li>` with a bullet but no text content inside it.

This is happening because we are making the following check in our UnregisterEntityDialog component 
`{entities ? JSX : null}`, here entities will evaluate to true even if the array is empty because Boolean([]) is true. Instead we should check for length of the array.

## Expected Behavior

We should not show the UI which shows the list of entities because that results in li with only a bullet and nothing else after that. 

## Current Behavior

<img width="960" alt="no-entities-bug" src="https://user-images.githubusercontent.com/19193724/96272993-71bf6800-0fec-11eb-8a5c-1358fdd9dc2e.png">

## Possible Solution

We can check the length of array instead checking the existence of array.

## Steps to Reproduce

1. Go to http://localhost:3000/catalog/Component/default:playback-order/ci-cd
2. Select the menu with three dots from top right.
3. Select "Unregister entity" from dropdown.
4. You will see the li with bullet but no content inside li because there are no entities in entities array.

## Context

I am looking to contribute to open-source community and I find this project very interesting.

## Your Environment

- NodeJS Version (v12): v14.13.1
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina 10.15.7 (19H2)
- Browser Information: Version 86.0.4240.80 (Official Build) (x86_64)

**Comment by freben** [comment]
I see it doesn't even list itself either 😬

So you wanna tackle this? 😀

**Comment by abhishekjakhar** [comment]
> I see it doesn't even list itself either 😬
> 
> So you wanna tackle this? 😀

I would love to raise a PR for this

**Comment by freben** [comment]
Done.
