### ISSUE TITLE
warnings related to act inside test cases of packages/core

### ISSUE THREAD

**Issue by abhishekjakhar** [spotify/backstage#2952]
When we run the test cases of core using JEST watch mode, all of the test pass successfully but a warning is coming up in almost all of the test cases, which says

```
    console.error
      Warning: An update to Provider inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in Provider

```

This is happening because we are calling some function directly which itself is calling a state updater and there's nothing that react-testing-library can expose for us to make sure that this is going to be wrapped inside of act. So, we will have to wrap it inside of act manually.

## Expected Behavior

The warnings should not come in the console when running all tests using JEST watch mode.

## Current Behavior

<img width="960" alt="test-cases-warnings" src="https://user-images.githubusercontent.com/19193724/96359908-88bda180-1135-11eb-868c-29514c5b430b.png">

## Possible Solution

We have already created a method in **test-utils/appWrappers.tsx** called **renderInTestApp**, which calls **renderWithEffects** which wraps the result inside the **act** function provided by **react-dom/test-utils**. If we will use **renderInTestApp** it will take care of everything for us.

## Steps to Reproduce

1. Go inside **core** directory
2. Run **yarn test**
3. The test will run in JEST watch mode
4. Press **a** to run all tests.

## Context

I am looking to do open source contributions and I find this project very interesting.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by abhishekjakhar** [comment]
I would love to pick this up

**Comment by stefanalund** [comment]
Thanks! I’ve assigned you.
