### ISSUE TITLE
catalog-model: create an example mini-org with groups and users

### ISSUE THREAD

**Issue by freben** [spotify/backstage#2963]
Add a (single) yaml example file, that holds a number of users that belong to a number of groups, in a little hierarhy. This should also be added to the static locations in a newly created Backstage app.

This will serve as an example for how one could make a batch export with actual org data in a similar fashion.

**Comment by dtuite** [comment]
@stefanalund We would like to pick this up as a way to onboard @punkle please

**Comment by freben** [comment]
Gladly! Hm I can't set him as an assignee though

**Comment by stefanalund** [comment]
(It's not possible to assign someone that's not in the thread)

**Comment by punkle** [comment]
Hey @stefanalund @freben, does this comment help?

**Comment by stefanalund** [comment]
Hey @punkle yeah it does :D Welcome and thanks for picking this up!
