### ISSUE TITLE
Small visual fixes for "Not just adopted, embraced" section in "The Spotify Story"

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#297]
1. Replace the background SVG of all the dots with a complete one - right now it seems like there's two half 'hella dots' SVGs fused together, which results in a lil glitch on the screen. 
<img width="1026" alt="Screenshot 2020-03-17 at 1 41 54 PM" src="https://user-images.githubusercontent.com/61153904/76857121-14481a80-6855-11ea-9727-1eec4223ed2a.png">

2. The top of this section should be the same background color as the background color behind the quotation. There shouldn't be stark contrast.
**Currently:** <img width="1438" alt="Screenshot 2020-03-17 at 1 40 43 PM" src="https://user-images.githubusercontent.com/61153904/76857038-e95dc680-6854-11ea-903d-03d47b868652.png">

**Ideally:** 
<img width="1023" alt="Screenshot 2020-03-17 at 1 43 04 PM" src="https://user-images.githubusercontent.com/61153904/76857241-52ddd500-6855-11ea-8c15-53b5678a931b.png">

3. There should be the copy "A look at the numbers" above the little cards that show the stats
<img width="810" alt="Screenshot 2020-03-17 at 1 43 08 PM" src="https://user-images.githubusercontent.com/61153904/76857225-4b1e3080-6855-11ea-8597-5ff6f140e4a9.png">

**Comment by Rugvip** [comment]
Moved to https://github.com/spotify/backstage-microsite/issues/107
