### ISSUE TITLE
About card Techdocs link not working

### ISSUE THREAD

**Issue by dtuite** [spotify/backstage#2975]
The "View Techdocs" link in the About Card on the Overview Tab doesn't work.

See here for a demo: https://demo.roadie.so/catalog/Component/default:sample-service-1

Using the Tab to view techdocs works as expected.

## Expected Behavior

I should be taken to the techdocs tab for the entity.

## Current Behavior

I see a blank page.

## Possible Solution

Fix the URL

**Comment by freben** [comment]
related: https://github.com/spotify/backstage/commit/ae499a55ff7a1c7d2edf7f6b8ac3feeb37ee0e6d#diff-45102fe18f442f04f49982603c544c903a6d22e86289ec922cb2c93b8796a89eR51
