### ISSUE TITLE
TechDocs Backend: Read GHE token from configuration instead of environment variables

### ISSUE THREAD

**Issue by roflc0pter** [spotify/backstage#2991]
**(I was not sure if this should be considered as a bug)**

For some reason, the access token that is used to while cloning the repo is read from the environment variables instead of from the configuration reader.
https://github.com/spotify/backstage/blob/b46863b88b933b79ec74af2550a0b4d6e473a9a2/plugins/techdocs-backend/src/helpers.ts#L130

## Possible Implementation
Pass config reader as an additional parameter and read the token from there.

## Context
I was trying to enable TechDocs with GHE setup.

**Comment by emmaindal** [comment]
Hi @roflc0pter Thanks for opening this issue, there is an open [PR]( https://github.com/spotify/backstage/pull/2992/files) that will use the ConfigReader instead of reading the token from the environment variables. I'll review that PR closer tomorrow but might solve this issue.
