### ISSUE TITLE
Remove "default" in component name 

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#3011]
## Feature Suggestion

If the namespace of the component is "default", it should not have to be shown. It adds complexity and forces the user, unnecessarily, to understand some of the underlying model.

![Screenshot 2020-10-21 at 07 55 00](https://user-images.githubusercontent.com/190856/96678841-cce9b580-1372-11eb-95da-0d47e1e92b4d.png)

## Context

We should strive to limit complexity as much as possible.

**Comment by rajreet** [comment]
I would like to work on the issue. Can You give more details?

**Comment by stefanalund** [comment]
Thanks @rajreet. Not sure if I have more context than what I added in the ticket. I think you can conditionally check for "default" and remove it, while keeping other namespaces.

**Comment by dlavrenuek** [comment]
I would like to contribute and since one is still unassigned I created https://github.com/spotify/backstage/pull/3028
