### ISSUE TITLE
Backstage should work without a GitHub access token

### ISSUE THREAD

**Issue by dtuite** [spotify/backstage#3024]
Non-GitHub users (GitLab, Bitbucket etc.) should be given the option to use backstage without a dummy `GITHUB_TOKEN` in their environment variables.

There are at least two places where I can see it is required:

 1. Backstage fails to boot in production mode without a `GITHUB_TOKEN` set.
 2. The helm charts don't allow the user to deploy backstage without a `GITHUB_TOKEN` with a dummy value.

**Comment by Rugvip** [comment]
Gonna close this as a duplicate of #2867, commented there instead. Protest if you don't agree :grin:

**Comment by dtuite** [comment]
@Rugvip Feels like the null value idea would handle this case 👍
