### ISSUE TITLE
Add Settings Button to Side Nav

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#3027]
Would love if someone could add a 'Settings' button to the side nav, right underneath 'Create.'

![settings-nav](https://user-images.githubusercontent.com/61153904/96768971-c3963280-13de-11eb-8806-cc9389d9e338.png)

**Comment by stefanalund** [comment]
@katz95 Wouldn't it make more sense to put the Settings at the bottom part of the panel? I'm thinking above the user icon. Feels like this is a common enough pattern:

![Screenshot 2020-10-22 at 07 56 18](https://user-images.githubusercontent.com/190856/96830682-1eaa4280-143c-11eb-809c-f8fcf062e7bf.png)

**Comment by harshilparmar** [comment]
Can I do this ?

**Comment by stefanalund** [comment]
@harshilparmar sure! I've assigned you. Thanks 💯

**Comment by katz95** [comment]
@stefanalund ooh good point, that works!

**Comment by craicoverflow** [comment]
The user icon is a direct link to `/settings`, which is the `SettingsPage` component. Why is there a need for an additional Settings link?

**Comment by harshilparmar** [comment]
@katz95 @stefanalund Already showing me
![setting1](https://user-images.githubusercontent.com/45915468/97070179-f9f8cb00-15f3-11eb-9aee-abac722e7656.PNG)

My question is how can I access setting component because it already showing as a popup.
(suggestion) : This looks great. Do you still want to make extra setting icon ?

**Comment by stefanalund** [comment]
@harshilparmar that’s the old UI. Please make sure you’ve pulled the latest version. 

The reason we wanted to introduce a specific Settings menu item (link) was that it is not obvious that the use icon hides a settings screen.

**Comment by harshilparmar** [comment]
@stefanalund Sorry for late,but can you please assign someone else for this issue.I am quite busy in another work it might take long time.

**Comment by freben** [comment]
Would assign @mvarrieur but I can't, probably because of not being in the thread yet

**Comment by mvarrieur** [comment]
> Would assign @mvarrieur but I can't, probably because of not being in the thread yet

Thanks sorry I didn't see this was already assigned originally.

**Comment by mvarrieur** [comment]
> Would assign @mvarrieur but I can't, probably because of not being in the thread yet

Thanks sorry you should be able to assign me now!

**Comment by mvarrieur** [comment]
@freben @stefanalund  any chance of adding a `hacktoberfest-accepted` label to this issue?

It looks like the topic got dropped from the main repo so it stopped counting for credit (might want to just add it back to the main repo for a couple weeks so people still get credit and then remove it after that instead)

**Comment by Rugvip** [comment]
@mvarrieur Afaik it's opt-in per repo and that should've been moved over, not sure though. But in general issues don't count towards hacktoberfest, do they?

Will ofc try to fix if something's actually up with the hacktoberfest credit here!

**Comment by mvarrieur** [comment]
@Rugvip Yeah this repo had hacktoberfest topic on it when PR got merged but then I assume it got removed because October was over. More of an issue on their end than yours but it was kind of a rush job for them to add it this year I think

**Comment by mvarrieur** [comment]
@Rugvip You can give credit for a single issue by adding that `hacktoberfest-accepted` label or just having the hacktoberfest topic on the whole repo. I'm thinking it probably won't count now but figured it was worth a shot to ask as unfortunately I ended up not getting credit because the 14 days period hadn't finished counting down yet

**Comment by mvarrieur** [comment]
> You can give credit for a single issue by adding that `hacktoberfest-accepted` label or just having the hacktoberfest topic on the whole repo. I'm thinking it probably won't count now but figured it was worth a shot to ask as unfortunately I ended up not getting credit because the 14 days period hadn't finished counting down yet

I might be wrong and the label might need to be on the PR instead of the issue
