### ISSUE TITLE
Yaml Descriptor Format of Catalog Entities policy validator

### ISSUE THREAD

**Issue by javigomez** [spotify/backstage#3040]
I was creating a policy for a repo and getting this misterious error:
<img width="965" alt="misteriouserror" src="https://user-images.githubusercontent.com/1375475/96864754-32b86900-1469-11eb-8ee1-688c15e233eb.png">

I knew something was wrong in my yaml, but what? At the end it was just that I forgot the `spec.lifecycle [required]`.

But the error didn't help me to find the root cause of the problem.

## Feature Suggestion
My feature request is to provide a way to get insightful information when the yaml doesn't fulfill the policy either by:
- Improve the errors reported when you try to import an invalid yaml, so it specifies where are the violations. For my example it could be: `EntityPolicyProcessor: missing required lifecycle spec` 
- create a tool for validating the yaml before sending it. Something like what TravisCI does for its yaml configuration files: https://github.com/travis-ci/travis.rb#lint

## Possible Implementation

see previous point.

**Comment by benjdlambert** [comment]
Hey @javigomez! thanks for reporting this! Would you like to contribute this? 🥇

**Comment by freben** [comment]
One improvement to this is being made here #3038

It would be interesting to see how much better your particular error message would be after that one is merged.

**Comment by erictnilsson** [comment]
#3038 makes the error a bit more descriptive:
<img width="645" alt="Screenshot 2020-10-22 at 21 58 38" src="https://user-images.githubusercontent.com/16206098/96924440-f14cab80-14b2-11eb-87fe-829c7276886b.png">

**Comment by erictnilsson** [comment]
This is what the error looks like with #3038 : 
<img width="645" alt="Screenshot 2020-10-22 at 21 58 38" src="https://user-images.githubusercontent.com/16206098/96928392-c9f8dd00-14b8-11eb-98fe-92c2f40d85b0.png">

**Comment by benjdlambert** [comment]
Hey @javigomez, seen as #3038 has been merged, do you think we could close this issue?

**Comment by javigomez** [comment]
Indeed. Thanks all, that was amazingly fast ❤️
