### ISSUE TITLE
feat: Yarn version update

### ISSUE THREAD

**Issue by lewtakm** [spotify/backstage#3048]
## Feature Suggestion

I suggest updating version of the Yarn package installed in the project to the latest version. Last update was made 7 months ago. Outdated version of Yarn cause warning in console. Fix is simple and I believe new minor versions of yarn would not break anything so it should be not that hard to implement.

## Possible Implementation

Updating yarn version inside project is quite easy. Simple command will do the job:

`yarn set version latest`

Then two files will be generated:

- **.yarnrc**
- **yarn-1.22.5.js**

that should be committed into repository. 

## Context

While we use yarn commands on console we got warning like this one:

![image](https://user-images.githubusercontent.com/36006588/96907869-1bdf3a00-149c-11eb-829f-0d2a1b570b6a.png)

so upgrading yarn version would remove this warning.

**Comment by Rugvip** [comment]
We've avoided bumping the yarn version to not grow the repo size too much. There haven't (last time I checked) been any worthwhile updates, and the size on disk is ~6MB. A specific fix we've been waiting for is for `yarn postpack` scripts to be called, but afaik that's not released yet.

I don't think there's any compelling reason to upgrade to v1.22.5, no security fixes, and yarn pack fix in .5 shouldn't affect us much either. Would be nice to disable the warning though 😅
