### ISSUE TITLE
Tech Radar Owner/Lifecycle

### ISSUE THREAD

**Issue by althafh** [spotify/backstage#3059]
## Feature Suggestion
Currently the tech-radar plugin has a hardcoded owner and lifecycle to Spotify and Beta respectively. 

## Possible Implementation

We can either remove it completely unless we want to show the Group owning the contents of the radar. However it's not an entity itself.

Any other suggestions on what to do with it?

**Comment by stefanalund** [comment]
@althafh I think it should be removed actually. Do you want to give it a go?

**Comment by althafh** [comment]
Definitely. Will put out a PR :)

**Comment by stefanalund** [comment]
🙏
