### ISSUE TITLE
Sonarcloud metrics integration

### ISSUE THREAD

**Issue by jlind23** [spotify/backstage#3063]
Purpose here will be to add sonarcloud as a plugin in order to retrieve metrics from sonarcloud.io such as code coverage or code maintenability.

## Possible Implementation
https://sonarcloud.io/web_api apis are available it needs only a user token or a service account token.

**Comment by andrewthauer** [comment]
I think it would be good to support the on premise (non cloud) version as well.

**Comment by jlind23** [comment]
Wonderful, API Paths and authentication method are both the same https://docs.sonarqube.org/latest/extend/web-api/

**Comment by stefanalund** [comment]
Great! @jlind23 should I assign you or do you want me to add [help wanted] labels?

**Comment by jlind23** [comment]
You can add help wanted as I am off for few days/weeks. Thanks for being here @stefanalund

**Comment by stefanalund** [comment]
@jlind23 done! Thanks for suggesting this.

**Comment by goober** [comment]
Could be of interest to see if there are some synergy with the security insights plugin. https://github.com/spotify/backstage/pull/3046

**Comment by dtuite** [comment]
We have a call set up at 2pm UTC time on Tuesday 27th to talk about what a SonarQube plugin would look like and what it should do. Email me at david@roadie.io if you would like to join.

**Comment by benjdlambert** [comment]
@dtuite I'd be happy to join as an interested party from the @spotify/backstage-core side - just sent you an email

**Comment by Fox32** [comment]
We already have this internally and could contribute it

**Comment by dtuite** [comment]
That looks awesome @Fox32. If you'd open source that there would be no need for us to replicate it.

**Comment by Fox32** [comment]
I created a ticket on our board 🙂

**Comment by dtuite** [comment]
@Fox32 This makes me wonder how many proprietary Backstage plugins are out in the wild already. There could be a lot of useful stuff out there that teams just haven't gotten around to open sourcing. It's can be a high friction process to open source even the smallest piece of code in some companies.

**Comment by Fox32** [comment]
We also have a plugin for Fossa (@dhenneke will create an issue for that) and DefectDojo. The later is something I would probably expect to be integrated into a security insights plugin, instead of having it separately. And I'm not sure if the way we use DefectDojo is useful for other companies.

**Comment by dhenneke** [comment]
I created the PR for our SonarQube / SonarCloud plugin https://github.com/spotify/backstage/pull/3160.

We only tested it with SonarCloud since we don't use SonarQube. I hope that we added all needed configurations to configure it against a SonarQube installation. Feel free to do some tests against your instance and report whether it works or not 😄.

**Comment by andrewthauer** [comment]
> We only tested it with SonarCloud since we don't use SonarQube. I hope that we added all needed configurations to configure it against a SonarQube installation. Feel free to do some tests against your instance and report whether it works or not 😄.

🎉 😄 - I will find some time to pull this down and try it against our on prem version of `SonarQube`!

**Comment by andrewthauer** [comment]
@dhenneke - Amazing, works great with SonarQube as well!

**Comment by stevieg27** [comment]
> We also have a plugin for Fossa (@dhenneke will create an issue for that, see #3094) and DefectDojo. The later is something I would probably expect to be integrated into a security insights plugin, instead of having it separately. And I'm not sure if the way we use DefectDojo is useful for other companies.

Do you still use defectdojo plugin for the backstage?
> 
> We also have two small ones:
> 
> * And a simple one that shows GitHub releases, but that one is a bit different from the one in the github-insights as it also shows a list of the releases inside Backstage instead of jumping to GitHub.
> * One that allows to pass a longer description to a component (similar to [Show a README in a component page #2071](https://github.com/backstage/backstage/issues/2071), but not loading from GitHub, but static inside the entity)
