### ISSUE TITLE
No value for Use Typescript in table while creating react component

### ISSUE THREAD

**Issue by abhishekjakhar** [spotify/backstage#3073]
When we create a new React App Template by clicking on Create Component button and choosing Create React App Template, we get option to opt in for typescript. Now, for example we opt in for typescript and move forward, in the last step of Stepper you will see a Review and create step which contains a table telling all of the details which we have mentioned in steps before. Here you will see that nothing is coming in front of **Use Typescript**.

## Expected Behavior

We should see 'Yes' or 'No' in front of the Use Typescript, or something in those lines.

## Current Behavior

<img width="960" alt="current-behaviour" src="https://user-images.githubusercontent.com/19193724/97065994-21896c80-15cf-11eb-858b-983c327c32d3.png">

## Possible Solution

Right now the value of Use Typescript is a boolean(true/false), which I think table is not able to render properly, we could check if the value is true then show 'Yes' and if it is false we can show 'No'.

## Steps to Reproduce

1. Go to http://localhost:3000/catalog
2. Click on **CREATE COMPONENT** button 
3. Choose **Create React App Template** template
4. Fill in template parameters and while doing this you could select or deselect **Use Typescript**
5. Go to last step of stepper, you will see a table with all the key value pairs, but there is no value in front of Use Typescript

## Context

I am looking to do open source contribution and I find this project very interesting.

## Your Environment

- NodeJS Version (v12): v14.13.1
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina 10.15.7
- Browser Information: Version 86.0.4240.111

**Comment by giulianovarriale** [comment]
Can I take that one?

**Comment by benjdlambert** [comment]
@abhishekjakhar thanks for the report! yep this should definitely not be blank! I think a solution would either be serializing this to ✅/❌ or Y/N would be great. @giulianovarriale - thanks for the interest, but I think that @abhishekjakhar said that he wanted to contribute in the original issue, so is this something that you would want to fix @abhishekjakhar?

**Comment by abhishekjakhar** [comment]
@benjdlambert Yes, I wanted to pick this up. But, I am happy to let @giulianovarriale tackle this.

**Comment by giulianovarriale** [comment]
I'm sorry @abhishekjakhar, I didn't notice you wanted to pick it up.
If you really want to work on it, please let me know.

**Comment by abhishekjakhar** [comment]
> I'm sorry @abhishekjakhar, I didn't notice you wanted to pick it up.
> 
> If you really want to work on it, please let me know. 

Hey, that's fine. I will work on something else. Feel free to work on this. 😊🙂

**Comment by freben** [comment]
Assigned to @giulianovarriale then :)

**Comment by giulianovarriale** [comment]
@freben @benjdlambert I was checking the status of my contributions on hacktoberfest and it says the repository is ineligible. That's really weird since I found your repository by looking for the hacktoberfest label. Do you know why that's happening?
 
**Ineligible Repository**
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by abhishekjakhar** [comment]
> @freben @benjdlambert I was checking the status of my contributions on hacktoberfest and it says this repository is ineligible. That's really weird since I found your repository by looking for the hacktoberfest label. Do you know why that's happening?
> 
> **Ineligible Repository**
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

@giulianovarriale there was transition from Spotify/backstage to backstage/backstage, maybe that's why you are facing some issue, because I was able to complete the Hacktoberfest challenge.

**Comment by giulianovarriale** [comment]
@abhishekjakhar It was being taken into account before. Suddenly, it is not anymore. Is there something the code owners could do? Maybe adding a hacktoberfest-accepted label on my PR?

**Comment by abhishekjakhar** [comment]
> @abhishekjakhar It was being taken into account before. Suddenly, it is not anymore. Is there something the repository owners could do? Maybe adding a hacktoberfest-accepted label on my PR?

No label was added on my PR, the label is already there on backstage repo. I wonder why it is showing error for you.
