### ISSUE TITLE
Some errors in Run Templater stage are not correctly represented in the JobStatusModal since logger fails to log the error

### ISSUE THREAD

**Issue by erictnilsson** [spotify/backstage#3077]
When creating a new component using the CRA template, if the Run Templater stage throws an error, the modal is not updated accordingly. The Run Templater stage's status gets stuck at "STARTED" (blue color) when it should be "FAILED" (red color).  
<img width="555" alt="Screenshot 2020-10-24 at 11 10 30" src="https://user-images.githubusercontent.com/16206098/97084372-bd8a9680-1616-11eb-9695-9582b2e9eaef.png">

When I debugged it, I found that in `processor.ts`, the error is caught as expected in [processor.ts line 119](https://github.com/spotify/backstage/blob/f72b512649f3edc2d62a4207efac7214b8476e7a/plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts#L119). However, logger.error() in that catch-block throws its own exception, namely _"[ERR_STREAM_WRITE_AFTER_END]: write after end"_ which is consequently caught at [line 134](https://github.com/spotify/backstage/blob/f72b512649f3edc2d62a4207efac7214b8476e7a/plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts#L134). Since stage.status is set after the logger throws a new error, it's never reflected in the GUI that the stage failed. 

I've tried to find out where/why the logger is prematurely closed but to no avail. To make matters more complicated, the issue doesn't seem to be consistent for all errors. For example, when I create a component without Docker running (which also breaks the Run Templater stage with _"ECONNREFUSED"_) it doesn't happen. 

## Expected Behavior
- The Run Templater stage should get marked as "FAILED", making the sidebar color red. 
- The logger should not fail to log the error. 

## Current Behavior
- The Run Templater stage gets stuck on "STARTED", making the sidebar color blue, even it it failed. 
- The logger throws _"[ERR_STREAM_WRITE_AFTER_END]: write after end"_.

## Possible Solution
- A quick work-around which doesn't solve the logger-issue is just to set the stage's status before logging the error.
- For the logger ending prematurely, I don't know!

## Steps to Reproduce
1. navigate to `/create/create-react-app-template`
2. For the component-Id field, enter a name with capital letters. 
3. Go through the rest of the form and press "Create".
4. Wait for the Run Templater stage to break.
5. See error. 

My setup: notice the invalid Component ID
<img width="1185" alt="Screenshot 2020-10-24 at 11 13 47" src="https://user-images.githubusercontent.com/16206098/97084184-7a7bf380-1615-11eb-81aa-cc450a9822f1.png">

## Context
[Error caught in processor.ts line 119: ](https://github.com/spotify/backstage/blob/f72b512649f3edc2d62a4207efac7214b8476e7a/plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts#L119)

![Screenshot 2020-10-24 at 16 28 05](https://user-images.githubusercontent.com/16206098/97084289-49e88980-1616-11eb-8aa5-9bc9ee38a4f4.png)

[Error caught in processor.ts line 134: ](https://github.com/spotify/backstage/blob/f72b512649f3edc2d62a4207efac7214b8476e7a/plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts#L134)

![Screenshot 2020-10-24 at 16 27 34](https://user-images.githubusercontent.com/16206098/97084309-65ec2b00-1616-11eb-89b4-fa8a8acbc5fb.png)

## Your Environment
NodeJS Version (v12): v12.18.4
Operating System and Version: macOS catalina version 10.15.4
Browser Information: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by benjdlambert** [comment]
Do you wanna take a stab at this too @erictnilsson? 

>A quick work-around which doesn't solve the logger-issue is just to set the stage's status before logging the error.

Seems reasonable 👍

**Comment by erictnilsson** [comment]
Sure thing! 🙂
