### ISSUE TITLE
Component Id/name is not validated in the CRA template

### ISSUE THREAD

**Issue by erictnilsson** [spotify/backstage#3078]
The user is able to enter a component ID that breaks the templater. The field descriptions states that only lowercase, URL-safe characters are allowed but it's not validated accordingly. 
The field's description:
<img width="380" alt="Screenshot 2020-10-24 at 16 48 32" src="https://user-images.githubusercontent.com/16206098/97084660-f3c91580-1618-11eb-8c45-9ab22ded6f52.png">

What I'm allowed to enter: (notice the component Id/name starting with a capital letter)
<img width="1185" alt="Screenshot 2020-10-24 at 11 13 47" src="https://user-images.githubusercontent.com/16206098/97084665-fc215080-1618-11eb-8788-4b216ae62de7.png">

The error: (_"Cannot create a project named "Abba" because of npm naming restrictions: name can no longer contain capital letters. Please choose a different project name"_)
<img width="555" alt="Screenshot 2020-10-24 at 11 10 30" src="https://user-images.githubusercontent.com/16206098/97084674-08a5a900-1619-11eb-8c85-abd8c3bb69de.png">

## Expected Behavior
I expect not to be allowed to enter an invalid component Id/name with a message telling me why.  

## Current Behavior
I can enter uppercase, url-invalid strings for the component Id/name. 

## Possible Solution
See #3067 and #2832 as they're very much related issues. 

## Steps to Reproduce

1. navigate to /create/create-react-app-template
2. For the component-Id field, enter a name with capital letters.
3. Go through the rest of the form and press "Create".
4. Wait for the Run Templater stage to break.

## Your Environment

- NodeJS Version (v12): v12.18.4
- Operating System and Version: macOS catalina version 10.15.4
- Browser Information: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by Marvin9** [comment]
Can we use this package for validation? https://www.npmjs.com/package/validate-npm-package-name

**Comment by benjdlambert** [comment]
I think we could probably just update the `json-schema` to add validation for this rule instead.

**Comment by benjdlambert** [comment]
https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/

**Comment by erictnilsson** [comment]
Can you assign me to the issue @benjdlambert? I'm working on a solution using json-schema 🙂

**Comment by benjdlambert** [comment]
Sure!

**Comment by erictnilsson** [comment]
Closing this via #3114
