### ISSUE TITLE
Circle CI plugin requesting from wrong project

### ISSUE THREAD

**Issue by dtuite** [spotify/backstage#3079]
I have a project which lives in CircleCI at `https://app.circleci.com/pipelines/github/RoadieHQ/sample-service`.

The annotation for the component that uses this build pipeline is [here](https://github.com/RoadieHQ/sample-service/blob/master/catalog-info-2.yaml).

```
  annotations:
    circleci.com/project-slug: RoadieHQ/sample-service
    rollbar.com/project-slug: roadie/sample-project
```

I have an auth token configured in `CIRCLECI_AUTH_TOKEN` (this backstage instance is running on kubernetes)

```
» kubectl -n demo exec backstage-backend -- printenv | grep CIRCLE
CIRCLECI_AUTH_TOKEN=[redacted]
```

When I visit [the component in Backstage](https://demo.roadie.so/catalog/Component/default:sample-service-2/ci-cd), I get a "Request failed with status code 404".

The request to fetch the builds from Circle CI (via the proxy), looks like this:

```
https://demo.roadie.so/api/proxy/circleci/api/project/bitbucket/sample-service/undefined?limit=5&offset=0&circle-token=
```

It seems to be assuming that this component is hosted on Bitbucket, which is wrong. Also, it shouldn't expect the token to be in the client side request.

Totally willing to accept that I've done something wrong when setting this up of course.

**Comment by andrewthauer** [comment]
@dtuite - I believe the circleci annotation should be prefixed with 'github/roadiehq/'. My guess is bitbucket is the fallback which is probably not desired and should error instead maybe.

**Comment by dtuite** [comment]
@andrewthauer Thanks. That solved the problem!
