### ISSUE TITLE
Standalone plugin repository don't pass TSC check.

### ISSUE THREAD

**Issue by lewtakm** [spotify/backstage#3107]
## Expected Behavior
While developing standalone plugin that is placed outside Backstage repository due to recent changes command:
```yarn tsc``` should type check and pass.
It seems that Backstage-core package taken directly from NPM was not updated correctly. 

## Current Behavior
``yarn tsc``` command produces following error:
![rO4JpVu](https://user-images.githubusercontent.com/36006588/97207517-69201c00-17ba-11eb-8602-e705bb78f67c.png)

Just to make it clear, all Backstage packages are up-to-date in package.json (0.1.1-alpha.25). I also deleted yarn.lock file to get fresh dep. 

## Possible Solution

Update Backstage Core npm package. 

## Steps to Reproduce

1. Clone repository: https://github.com/RoadieHQ/backstage-plugin-github-pull-requests to any folder (not plugins)

1. Run ```yarn install```
2. Run ```yarn tsc```

## Context

Builds a package fails. 
Up to date code is located at this repository: https://github.com/RoadieHQ/backstage-plugin-github-pull-requests
## Your Environment

- NodeJS Version (v12): v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 Pro (v: 10.0.18363)
- Browser Information: Not relevant

**Comment by Rugvip** [comment]
That was changed in https://github.com/spotify/backstage/pull/2739, and it's not released yet. It was merged 10 days ago, last release was 14 days ago.

We'll looking at a release within 2 days, but there're some things to iron out first

**Comment by lewtakm** [comment]
> That was changed in #2739, and it's not released yet. It was merged 10 days ago, last release was 14 days ago.
> 
> We'll looking at a release within 2 days, but there're some things to iron out first

Oh thanks, I was sure that those changes was included in v. 25. Let's wait then :)
