### ISSUE TITLE
CatalogBuilder.addProcessor is not working

### ISSUE THREAD

**Issue by andrewthauer** [spotify/backstage#3130]
The `CatalogBuilder.addProcessor ` does not seem to be working as expected, based on the description of the method.

## Expected Behavior

A custom `CatalogProcessor` will be added to the existing list of processors

## Current Behavior

Using `builder.addProcessor` seems to be a noop.

## Possible Solution

- Set the  `processorsReplace` flag when `addProcessor` is called and also populate the `processor` array with the default values
- Add test cases for `addProcessor`

## Steps to Reproduce

Add a custom `CatalogProcessor` in the `packages/backend/src/plugins/catalog.ts` file. The `build` method will add the processor but not use the custom one.

## Context

The `replaceProcessors` works, but it would be more useful to use the `addProcessor`

**Comment by freben** [comment]
Oh, ouch. Setting `processorsReplace` during `add` would not be the right fix. I see the bug, I'll fix it right away.

**Comment by andrewthauer** [comment]
> Oh, ouch. Setting `processorsReplace` during `add` would not be the right fix. I see the bug, I'll fix it right away.

Yep, replaceProcessors works so all good for now!
