### ISSUE TITLE
Create GitHub Templates regarding bugs/features

### ISSUE THREAD

**Issue by tarcinil** [spotify/backstage#316]
As the project is adopted and matures, there will be a need to standardize on the inputs for features and bugs.  

This will allow maintainers to have data that they deem necessary to determining the scope of a feature, or the difficulty of resolving a bug.

https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by Rugvip** [comment]
Yep, think this will help everyone involved :grin:

Do you know of any good examples? I kinda like https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE

**Comment by tarcinil** [comment]
I've liked these but I also work in these repos (bias).

https://github.com/sensu/sensu-go/tree/master/.github/ISSUE_TEMPLATE
https://github.com/sensu/web/tree/master/.github/ISSUE_TEMPLATE

**Comment by freben** [comment]
Would you like to make a PR and add at least bug and feature e.g. from sensu? Then we can have the team check them out and suggest tweaks.

**Comment by tarcinil** [comment]
I will work on them tonight.
