### ISSUE TITLE
Cleanup: GridBlockWithButton from microsite

### ISSUE THREAD

**Issue by abhishekjakhar** [spotify/backstage#3176]
## Cleanup

The GridBlockWithButton component is defined in microsite but it is not getting used anywhere, should we remove it?

### Screenshot

<img width="640" alt="grid-block-with-button" src="https://user-images.githubusercontent.com/19193724/97691503-74c65800-1ac4-11eb-9084-350e39bb7192.png">

## Context

I am working on the migration of microsite from Docusaurus V1 to Docusaurus V2, while doing the migration I saw that GridBlockWithButton is not getting used anywhere.

**Comment by OrkoHunter** [comment]
Sure! It doesn't look being used anywhere currently to me too.

**Comment by abhishekjakhar** [comment]
Should I go ahead and remove it?

**Comment by OrkoHunter** [comment]
Yes. :)
