### ISSUE TITLE
Zombie serve process

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#321]
Running into port 3000 conflicts occasionally, only to discover a background serve process that wasn't killed properly. Need to track down and kill all zombies.

**Comment by paladium** [comment]
Hello, @Rugvip how can I recreate this issue?

**Comment by freben** [comment]
I don't think we're 100% sure yet - it has happened on a couple occasions for several of us but I think it will be part of this ticket to figure out where and why.

**Comment by Rugvip** [comment]
I don't know xP I would imagine it's to do with the watch-deps command and how it handles the child process.

Created this issue so that we can start gathering information, but no concrete task other than trying to reproduce it : /

**Comment by paladium** [comment]
I had a similar problem a few times but with other projects, not sure why that happens. I am using Hyper terminal, sometimes when the tab is closed the process might not be properly killed

**Comment by Rugvip** [comment]
Yeah that sounds plausible, I'm seeing it in iTerm2/zsh

**Comment by stefanalund** [comment]
I've experience this in Hyper as well.

**Comment by mateusmarquezini** [comment]
I've also experienced this issue using the native OS terminal. I'm using Ubuntu 18.04.4 LTS.

**Comment by O5ten** [comment]
Seen this happen a couple times on WSL (Ubuntu & bash) too.
