### ISSUE TITLE
RFC: Feedback on API concept

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#339]
Creating this issue to gather feedback on the API concept introduced in https://github.com/spotify/backstage/pull/251 and https://github.com/spotify/backstage/pull/326.

Anything goes, questions about purpose, ideas, clarifying things, naming, alternatives, etc.

Starting out with providing a few answers:

### Why was this created in the first place?

In the Spotify internal Backstage we added the concept as a way to make it easier to write tests, and to wrangle the growing complexity of the dependency graph between different app-wide features.

### What is the purpose of the API concept?

Apart from what's mentioned above, it's now also provides a way to decouple plugins from the APIs that they consume. A plugin can for example depend on an error reporting API, and it is up to the app that uses the plugin to provide an implementation of the API.

### Would every app have to write their own API implementations?

The `backstage/core`, or possibly a separate package, would ship a set of default implementations for all APIs. Apps can choose to use these directly, build upon them, or replace them.

### How does the API concept help with testing?

The `backstage/core` package would include mocks for all core API definitions. They should provide sane defaults for all behaviour and stay out of the way, but also provide additional methods for testing error/edge cases.

For example, any component consuming a core API in a way where we don't want to do any further testing of the API would simply do something like

```tsx
const rendered = render(wrapInTestApp(<MyComponent />))
```

While for example the error api mock could provide methods for ensuring that errors have been reported, something like

```tsx
const errorApi = testRegistry.get(errorApiRef) as MockErrorApi;

const rendered = render(wrapInTestApp(<MyComponent />))

expect(errorApi.reportedErrors.length).toBe(1);
```

### Are the API definitions limited only to the ones listed in backstage/core?

For now it would be the only supported way, but we want to support externally defined APIs, and APIs defined and consumed within a single plugin.

**Comment by toonsevrin** [comment]
I've said this before but if you want to go take your security to the next level (this could fe be done in a v2 rewrite of Backstage), you should make each API and plugin live within it's own javascript namespace. This is typically done by leveraging the _same-origin policy_ of browsers (eg. through iframes).

**More practically speaking:**

Your dns server forwards all traffic from `*.backstage.cronus.com` to the Backstage server. The backstage server will serve the core application from `core.backstageorigin.com`. Plugins would be served from `<plugin>.plugin.backstageorigin.com`.

Let's say we have an authenticator API, it would be loaded in the browser under an iframe with `src="https://auth.plugin.backstageorigin.com"`. Now all the authentication internals (and the cookies+storage) are completely isolated from the other plugins. The only communication that is permitted is communication through `window/postMessage`.

Take this a step further and you can require plugins to declare a manifest file with the plugins they want to communicate with (this should be done anyways for dependency management), now the core can enforce that only plugins that need to communicate with eachother can communicate with eachother.


**Note: This is how my ideal backstage world would look like. I assume there are not sufficient resources for an implementation like this for now, hence 'v2'.**

**Comment by Rugvip** [comment]
@toonsevrin Yeah I think the declaration of dependencies in a manifest is something to explore as a part of the API concept. it will be needed in some capacity so that whoever creates a backstage app knows what APIs have to be implemented based on what plugins are being used.

Regarding separated origins I'm not so sure tbh, I think leaning towards read-only interface with destructive actions in a secure context has a better security/UX/DX tradeoff.

**Comment by Rugvip** [comment]
I have have a naming-help request related to this API concept! We've tried some different terminology, like "services", "factories", "libraries", but APIs is short and matches the concept, so it's what we've gone with for now.

The request is to find a word to describe these APIs though, as saying simply "Backstage API" is a bit confusing, as in what kind of API are we talking about? So looking for a word to place before/between "Backstage" and "API", to be able to refer to for example the existing error API as a "&lt;blank&gt; API". Or talk about "Backstage &lt;blank&gt; APIs".

Some ideas: "frontend", "plugin", "integration", "provided", "app"
Or a bit more abstract: "fuse", "axial", "edge", "perimeter"

**Comment by soapraj** [comment]
I like 'Backstage Plugin APIs' for plugin concerns and 'Backstage App APIs' for app concerns. 

Ex: Would error API be only used by plugins or the app can also use it to push error messages to the user? What I am getting here is can APIs be distinguished by usage or there will be overlaps?

**Comment by wesleyyee** [comment]
+1 to `Backstage Plugin APIs`

**Comment by Rugvip** [comment]
@soapraj @wesleyyee I think usage of APIs would really extend everywhere, including apps, plugins, and shared components, so yeah there would be overlap. [this](https://github.com/spotify/backstage/blob/2327cd121a903c6fa96b456abec142a95f5e8de0/packages/core/src/components/CopyTextButton/CopyTextButton.tsx#L65) being an example of that

Thing that worries me about prefixing with "plugin" or "app" is that it would be confused with `createPlugin` and `createApp` etc.

Still don't have anything better than "plugin APIs" though :p

"Backstage Global API", "Backstage Universal API"? 😅

**Comment by wesleyyee** [comment]
I also like `Provider` or `Utility`

**Comment by Rugvip** [comment]
Yeah "Utility API" isn't bad. It gets a bit weird when you talk about something like the "Lighthouse Utility API", but I don't think we'll find a name that fits perfectly with every use-case.

"Provide(r/d) API" gets tricky because of the clashes with React context imo.

**Comment by Rugvip** [comment]
Another option that I think covers a couple more use-cases is "Service APIs". Might help people coming from Angular as well, as they're similar and used in the same way as angular services.

**Comment by Rugvip** [comment]
Discussed the naming a bit further today and settled for trying out "Utility APIs". Service APIs is too easy to confuse with the "service" component entity type, and we want to keep these Utility APIs limited to only things that you access using the `useApi` hook. With that separation in mind, "Plugin APIs" or "App APIs" would be too easy to mix up with `createPlugin`, `createApp` and friends.
