### ISSUE TITLE
Add deployment secret management

### ISSUE THREAD

**Issue by tarcinil** [spotify/backstage#342]
While I see that there is a way to maintain secrets inside of the `secrets.env` file, I know some enterprises do not like having plain-text passwords on the filesystem, this integration could prevent a security finding.

Possible Library: https://www.npmjs.com/package/node-vault

**Comment by Rugvip** [comment]
`secrets.env` was a hacky short-term solution and not something we plan to use in the future :grin:

Would you be alright with renaming this issue to cover all options for secret handling and discussing the general topic?

**Comment by tarcinil** [comment]
👍 Sounds good to me

**Comment by Rugvip** [comment]
We will try to keep deployment configuration out of scope for now. The artifact produced by this repo would be docker images with secrets communicated though env/files.

Let's revisit this if we see a need to keep deployment configurations in this repo that doesn't just serve as examples.
