### ISSUE TITLE
Add Azure (AAD) auth

### ISSUE THREAD

**Issue by toonsevrin** [spotify/backstage#348]

**Comment by Rugvip** [comment]
Waiting for #366 to be determined before we move on with this issue

**Comment by ContrarianChris** [comment]
So, I've taken a first stab at adding Azure AD as an OIDC auth provider for Sign In. 
I've opened #1990 as draft as I have hit some issues and looking for some help resolving them, and feedback on what I've done so far.

**Comment by ContrarianChris** [comment]
I've abandoned #1990 as I was getting nowhere with `passport-azure-ad` (it didn't conform to passport.js anyways).

I switched to using `passport-microsoft` and everything is now all good 👍
#2056 is the working implementation.
