### ISSUE TITLE
Feature flags

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#358]
## Feature Suggestion

Make it possible to hide functionality behind a **feature flag**. Example from Spotify internal:

<img width="818" alt="Screenshot 2020-03-22 at 22 32 23" src="https://user-images.githubusercontent.com/190856/77261197-182cd000-6c8d-11ea-9514-c7089585f8a1.png">

## Possible Implementation

Example code:
```
import FeatureFlags from 'shared/apis/featureFlags/featureFlags';

registerFeatureFlag('my-feature');

if (FeatureFlags.getItem('my-feature')) {
  // Do something you don't want everyone to see.
}
```

**Comment by bih** [comment]
I'd like to take this one in my spare time :D

**Comment by stefanalund** [comment]
@bih given that you are the biggest feature flagger in the biz, this makes sense 😆

Would you like me to Assign you?
