### ISSUE TITLE
Investigate auth backend alternatives

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#366]
We want to look into using different auth backends to implement auth.

Alternatives so far:
- [passport.js](http://www.passportjs.org/)
- Custom [auth proxy](https://auth0.com/docs/connections/calling-an-external-idp-api?_ga=2.196088745.421680458.1585145744-1766963120.1584905237#from-the-frontend) for [auth0](https://auth0.com/)
- [dex](https://github.com/dexidp/dex)

Couple of questions to clear up for each alternative:

- [ ] Does it allow us to get authenticate a user?
- [ ] Does it let the user authorize actions on their behalf (OAuth)?
- [ ] What reusable client-side packages are there?
- [ ] How do different auth providers differ from each other, and how does it impact the client-side API?
- [ ] Can we used the popup-based auth currently used internally? Requires:
  * [ ] Custom html response
  * [ ] Custom nonce-cookie handling
  * [ ] Custom oauth state forwarding
  * [ ] Redirect-url generation for redirect response

**Comment by toonsevrin** [comment]
Fyi: Passport.js has allows for auth0 authentication, there is no point in implementing auth0 natively afaik :)

**Comment by Rugvip** [comment]
@toonsevrin yeah we would need to have something like that for auth0 anyway. I think we can rule out using auth0 directly as there's no way to get access tokens for the IdPs without a backend, which is something we will want https://auth0.com/docs/connections/calling-an-external-idp-api

**Comment by Rugvip** [comment]
Adding back auth0 as an option, but making it clear that it would require us to build a proxy for getting access token. More on that [here](https://auth0.com/docs/connections/calling-an-external-idp-api?_ga=2.196088745.421680458.1585145744-1766963120.1584905237#from-the-frontend).

It does give us some more flexibility wrt backend language/frameworks, and should end up being a slimmer implementation compared to using passport as well.

**Comment by stefanalund** [comment]
ArgoCD uses this https://github.com/dexidp/dex -- maybe worth looking into as well.

**Comment by Rugvip** [comment]
@stefanalund agreed, added to the list

**Comment by freben** [comment]
Decided on passport for initial main auth library.
