### ISSUE TITLE
List examples of other OSS apps with pluggable client-side auth architectures

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#370]
For gathering ideas and inspiration for how we want to design the auth API.

Some things that we want to look for:
- OpenID vs OAuth handling
- OAuth providers in npm packages
- Projects that use a common API for all OAuth providers
- Client-side implementations, server-side is discussed in #366

**Comment by soapraj** [comment]
https://marmelab.com/react-admin/

**Comment by Rugvip** [comment]
What I gathered from react-admin so far:

An interface like this one is used to define authentication providers:

```
const authProvider = {
    login: params => Promise.resolve(),
    logout: params => Promise.resolve(),
    checkAuth: params => Promise.resolve(),
    checkError: error => Promise.resolve(),
    getPermissions: params => Promise.resolve(),
};
```

^ from https://marmelab.com/react-admin/Authentication.html

The interface is similar to the one we have internally, although it's split into more methods. Biggest difference is that ours is centered around getting an OAuth access token with the correct scopes, while that is handled as a side-effect in react admin.

It seems like auth is mostly centered around password-based flows, and the authorization parts bit are more direct but could probably be adopted to fit OAuth: https://marmelab.com/react-admin/Authorization.html

SO question about using react-admin with OIDC: https://stackoverflow.com/questions/54763687/react-admin-with-openid-connect

**Comment by freben** [comment]
Initial API has been settled and implemented.
