### ISSUE TITLE
Proposal: Everything not related to UI/plugin management should be a plugin

### ISSUE THREAD

**Issue by toonsevrin** [spotify/backstage#374]
I believe that separating all behavior (eg. settings, authentication...) not related to the core of backstage (plugin management) should be separated in their own plugins.

These plugins would of course still ship by default, so the UX is identical. The development overhead is minimal as well.

Pro's: 
- **No patching required** when companies want to disable a feature: They can simply use the plugin management system (which I assume will come) to disable the features they don't like
- **Cleaner code:** The core modules remain small and easy to understand.
- **Backstage becomes it's own customer:** As the core developers will have to actively use the plugin system, they will quickly detect lacking features in it and hopefully add these. I'll provide an example below.

Cons:
- **More boilerplate:** You'll have some boilerplate as each feature becomes it's own module
- **Dependency management**: Eg. a lot of plugins may rely on the auth plugin. What if this is disabled? This is a nice example of _"backstage becomes it's own customer"_. Dependency management should be a feature of the plugin management system.
- **"Now I have to write all these subsystems as if they were APIs/libraries"**: I can hardly call this a con tbh.

Looking forward to your thoughts on this.

**Comment by freben** [comment]
Thank you for this discussion piece!

It is indeed our goal to have a sufficient and practical level of separation/modularity. We are currently drafting several of the API surfaces, including auth (as linked to), and you'll see these arrive in the coming weeks. While we may not go for an ultra-micro-package approach, we probably do not want a kitchen sink core either.

As this is being fleshed out, you may see some things land in overly central places, e.g. things unexpectedly being put into core or even app, and then transition out into a plugin later when the patterns emerge.

Do please call us out if you feel that something is out of place though, in case we haven't considered that particular thing yet or similar.

**Comment by toonsevrin** [comment]
Thanks for the response, @freben. I can totally see how micro-packaging can cause friction in many cases. The most important aspect is that features which certain clients may not need can be disabled.

**Comment by Rugvip** [comment]
Would say this issue is related to #339, as it covers inter-plugin dependencies as well

**Comment by stefanalund** [comment]
With very few exceptions, this is what we are doing. Consider this ticket "done".
