### ISSUE TITLE
No HTTPS for storybook deployment

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#382]
We can't serve both `backstage.io` and `storybook.backstage.io` with GitHub Pages over HTTPS, since GitHub doesn't support mixing apex and subdomains. The issue is being discussed [here](https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/td-p/7116) .

For now we will probably just stick to only HTTP, and keep track of the issue. Other alternatives would be to switch hosting, merge the storybook build into the microsite to expose as `backstage.io/storybook`, or use the default github domain.

GitHub Docs: https://help.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#https-errors

**Comment by bih** [comment]
Have you thought about setting up [Cloudflare](https://www.cloudflare.com/) as I know they do HTTPS support with GitHub Pages through proxying?

**Comment by bih** [comment]
But probably for obvious reasons of reducing the number of points of failure, the simpler the "stack" the better. Maybe a vanilla GH pages URL might suffice.

**Comment by Rugvip** [comment]
Yeah thinking it's not a catastrophe to serve storybook over http, and that we can wait for a fix from GitHub. There's even a workaround where you can rotate the cname of the apex domain to let GitHub generate cert that will then stay in place, but you need to do it every 3 months.

**Comment by riginoommen** [comment]
I am looking for this currently i am trying to deploy this on heroku 

Fork is here - https://github.com/riginoommen/backstage

**Comment by stefanalund** [comment]
@riginoommen nice! I assigned you for now.

**Comment by riginoommen** [comment]
This will be the herouku URL i am trying with deployment - https://backstagerigin.herokuapp.com/

**Comment by OrkoHunter** [comment]
@Rugvip Odd that GitHub has marked the discussion as "Solved" long time ago https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/m-p/7202#M495

@riginoommen I see that you were trying to use Heroku for deployment. I gave it a try myself for #535. Apparently Heroku has some complications with the time it takes to build backstage. [Here is my comment](https://github.com/spotify/backstage/issues/535#issuecomment-612640512) with a summary of the problems I faced and a [log of discussions in discord](https://discordapp.com/channels/687207715902193673/687235481154617364/698869133571522582). Let me know if you have any thoughts. 🙇

**Comment by stefanalund** [comment]
Storybook has been moved to https://backstage.io/storybook and therefore has HTTPS support.
