### ISSUE TITLE
Create "Designing for Backstage" Document

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#385]
We're super excited to be designing in the open. In the coming weeks, we'll be refining our process of how we (Backstage designers at Spotify) collaboratively work with internal and external contributors to design a better DX for teams all over the world.

The 'Designing for Backstage' doc will ideally cover some of these bases:
1. Design principles - what does Backstage uphold when it comes to building rad DX?
2. Design practice - how do we work? how can you work with us?
3. Resources and assets - where to access design guidelines, etc.
4. More to come! This will be an iterative doc - we're happy to take input from the community to see what you all need.

Example (flows for how we might all work together):
<img width="2061" alt="Open source design flow" src="https://user-images.githubusercontent.com/61153904/77538112-77622e80-6e9f-11ea-8074-4e0fb9a5319f.png">

**Comment by stefanalund** [comment]
Isn’t this one done?
