### ISSUE TITLE
Get rid of opacity in the wave svgs

### ISSUE THREAD

**Issue by soapraj** [spotify/backstage#393]
Recalculate the gradient colors to account for opacity.

**Comment by stefanalund** [comment]
@soapraj can you provide a screenshot or some more details? It's a bit vague :)

**Comment by freben** [comment]
is it a matter of just taking the image from the design, and using the color picker to pick out the colors at the top and bottom of each wave? :)

**Comment by Rugvip** [comment]
I don't think so, because the gradients extend beyond the edges of the box.

I think what we wanna do is take the background color and mix it with opacity% of the gradient color on each end, and then make the gradients opaque.

**Comment by Rugvip** [comment]
@otakarhyps Thanks for having a look! The colors are defined in [packages/core/src/layout/Page/PageThemeProvider.ts](https://github.com/spotify/backstage/blob/master/packages/core/src/layout/Page/PageThemeProvider.ts), and the SVGs themselves are inlined in [packages/core/src/layout/Header/Waves.tsx](https://github.com/spotify/backstage/blob/master/packages/core/src/layout/Header/Waves.tsx).

It's probably best to hold off on this issue for now though, as there's some work in #1232 to change the gradients. Might actually be worth dealing with this issue in that work if you want @benjaminr?

**Comment by benjaminr** [comment]
Sure, @Rugvip, happy to include this work in the same PR.

So you want the inline stopOpacity out of waves.tsx SVG definitions and mixing into the PageThemeProvider gradient specs for the various page header themes?

**Comment by Rugvip** [comment]
@benjaminr The original goal here was actually to get rid of opacity all together, as it makes re-using the page theme colors a bit weird, and trickier to define your own page themes. I'm not sure if that makes sense with the new design or not. Gonna ask in that issue.

**Comment by stefanalund** [comment]
@katz95 should this still be open?

**Comment by nikek** [comment]
This doesn't apply anymore as we changed the shapes to be gradients from white to transparent. Effectively removing the colors out of the shapes so that only the background needs a color/color-gradient. Simplifies the implementation and lets you mix and match any background color with any shape.
