### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by drsounds** [spotify/backstage#395]
## Feature Suggestion
Support Dark Mode on browsers

## Possible Implementation
Using CSS3 directives

**Comment by Rugvip** [comment]
Without having dug in to this at all I would assume that material-ui themes can help out here

**Comment by freben** [comment]
https://material-ui.com/customization/palette/#dark-mode

**Comment by stefanalund** [comment]
I know this is something at least Spotify developers would be really happy about :)

**Comment by drsounds** [comment]
I made a PR #398 with a solution for this

**Comment by drsounds** [comment]
Hi, I have made a commit today and yesterday on my PR #398 but it seems it haven't got any review yet.

**Comment by stefanalund** [comment]
@drsounds thanks a lot for those. We are discussing how to introduce dark mode across the system. It has implications on all plugin developers and we want to make sure we have thought this through properly before we merge your PR. I hope you are ok with this taking a bit longer than normal. 🙏

**Comment by drsounds** [comment]
Great,

Does that mean I will have to make further changes to comply with the decisions you take on dark mode implementations?

**Comment by drsounds** [comment]
I created a new PR #430 for dark mode because the old was messed up. But it doesn't build on CLI Test due some kind of weird node error, but everything works on my computer, look in the comments of the PR

**Comment by Rugvip** [comment]
@drsounds hoping to solve the build issues with #438

**Comment by drsounds** [comment]
Ok so when this is fixed, I will have to make a new PR or can you merge the current one when reviewed pass?

**Comment by Rugvip** [comment]
@drsounds Best would be to update the existing PR. Afaik you should have a sync button on the PR, otherwise there's https://stackoverflow.com/questions/53199291/github-how-to-keep-your-forked-repo-in-sync-with-the-original-while-updating-t

**Comment by drsounds** [comment]
There is no syc button and I tried out the instructions on StavkOverflow but it fails anyway

**Comment by drsounds** [comment]
Ive now made some fixes and now the CLI passed so could you have a look?

**Comment by drsounds** [comment]
I now see you have merged my commits! Yeah!

My question, is there some kind of CONTRIBUTORS list I can add my name (Buddhalow) to?

**Comment by stefanalund** [comment]
We really appreciate your contribution @drsounds -- but we have not (yet) set up a page like that. Will of course include you if we do!

**Comment by drsounds** [comment]
Hi, I see you you announced the completion of the first milestone and there was a link to Contributors at github, but my profile is missing. I see there are other non Spotify employees listed there

**Comment by Rugvip** [comment]
@drsounds Looks like you used an email address that isn't registered on your GitHub account when you made the commits. https://github.com/spotify/backstage/pull/430/commits

If you add that email to your account I think you'll show up!

**Comment by drsounds** [comment]
I added email but it didnt work...

**Comment by Rugvip** [comment]
@drsounds it did, you're in the list
