### ISSUE TITLE
Adding "Information Card" component to Storybook

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#400]
Would love if someone could help create this "Information Card" component to add to our Storybook (storybook.backstage.io)! 🙏

**Usage**
The information card is one of the most basic UX components that will exist in Backstage. Its purpose is to provide informational content to users. There's the option of adding a footer that includes a link to another page/site/etc. There's also the option of adding a subhead to the header.

![Information Card](https://user-images.githubusercontent.com/61153904/77760121-2b95bd80-7036-11ea-8a56-290418f2df88.png)

**Specs**
![Information Card Specs](https://user-images.githubusercontent.com/61153904/77760781-3866e100-7037-11ea-9e72-88d1d74c53df.png)

Let me know if you have any questions!!

**Comment by stefanalund** [comment]
@mateusmarquezini you seem to enjoy these kinds of challenges 😜

**Comment by mateusmarquezini** [comment]
> @mateusmarquezini you seem to enjoy these kinds of challenges

haha yeah, in fact! Feel free to assign this issue to me! :smile:

**Comment by stefanalund** [comment]
Closer in #400
