### ISSUE TITLE
Adding "Pivot Card" component to Storybook

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#401]
Would love if someone could help create this "Pivot Card" component to add to our Storybook (storybook.backstage.io)! 🙏

**Usage**
The pivot card is one of the most basic UX components that will exist in Backstage. Its purpose is to provide informational content to users, while also giving them the option to interact with the dropdown under the header and switch contexts. There's the option of adding a footer that includes a link to another page/site/etc.

![Pivot Card](https://user-images.githubusercontent.com/61153904/77761523-803a3800-7038-11ea-8cb1-ab17e8081315.png)

**Specs**
![Pivot Card Specs](https://user-images.githubusercontent.com/61153904/77761530-83352880-7038-11ea-8fcf-da9e78497a6d.png)

**Comment by Rugvip** [comment]
What's the difference between this and #400?

**Comment by mateusmarquezini** [comment]
> What's the difference between this and #400?

it seems the dropdown under the header, no?

**Comment by Rugvip** [comment]
> > What's the difference between this and #400?
> 
> it seems the dropdown under the header, no?

Not clear to me if that is the only difference though, since that could probably just be put as a feature in the InfoCard.

@katz95 is this new or is there some example of this internally?

**Comment by freben** [comment]
Agreed. I would make sense for the InfoCard to support subtitles anyway, whether a dropdown or plain text.

**Comment by katz95** [comment]
hi!! i like that idea of putting it as a feature! there's a couple of variations of this info card as well (aside from the pivot version). they were designed by Ed + Seth I believe and are included in our Backstage internal design system! included screenshots of them below. 

would it be more helpful for you all if i created separate issues for these different 'features' of the card? or if i just lumped them all together haha?

<img width="979" alt="Screenshot 2020-03-30 at 9 44 36 AM" src="https://user-images.githubusercontent.com/61153904/77887569-19509500-726b-11ea-8975-8d06bd1aa1d5.png">

<img width="486" alt="Screenshot 2020-03-30 at 9 44 42 AM" src="https://user-images.githubusercontent.com/61153904/77887567-181f6800-726b-11ea-9fdc-b7af3645b396.png">

**Comment by stefanalund** [comment]
@katz95 I would create separate issues for those. Also, I think we can skip the Pagination Card for now since it makes most sense when combined with a data [grid component](https://github.com/spotify/backstage/issues/161). Pretty sure this card is not in used internally either.

**Comment by stefanalund** [comment]
I'm in favour of closing this issue @katz95 until we know the Pivot Card is useful. WDYT?

**Comment by katz95** [comment]
Sure, I'm okay with that!
