### ISSUE TITLE
Core components should we written in typescript

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#407]
The following components need porting to typescript with hooks:

- [x] `layout/ContentHeader`, #425
- [x] `layout/ErrorBoundary` (class component), #426
- [x] `layout/Header`, #408
- [x] `layout/Header/Waves`, #419
- [x] `layout/HeaderActionMenu`, #425
- [x] `layout/HeaderLabel`, #425
- [ ] ~~`layout/HeaderLabel/OwnerHeaderLabel`~~ (removed)
- [x] `layout/InfoCard`
- [x] `layout/InfoCard/BottomLink`

**Comment by Rugvip** [comment]
Only InfoCard that isn't WIP, so can assign this issue if anyone wants to look at that.

**Comment by hooloovooo** [comment]
> Only InfoCard that isn't WIP, so can assign this issue if anyone wants to look at that.

I can take on InfoCard. :)

**Comment by Rugvip** [comment]
@hooloovooo thanks!

**Comment by stefanalund** [comment]
Done. Thanks all that helped!
