### ISSUE TITLE
Investigate auth0 setup

### ISSUE THREAD

**Issue by soapraj** [spotify/backstage#413]
Investigate how authentication for a backstage app be handled using Auth0 https://auth0.com/docs/

**Comment by Rugvip** [comment]
Need to clear up the questions from #366:

- [x] Does it allow us to get authenticate a user? Yes
- [x] Does it let the user authorize actions on their behalf (OAuth)? Yes, with a custom proxy that

TBD:
- [ ] What reusable client-side packages are there?
- [ ] How do different auth providers differ from each other, and how does it impact the client-side API?
- [ ] Can we used the popup-based auth currently used internally? Requires:
  * [ ] Custom html response
  * [ ] Custom nonce-cookie handling
  * [ ] Custom oauth state forwarding
  * [ ] Redirect-url generation for redirect response

**Comment by freben** [comment]
Settled for passport for now.

**Comment by taras** [comment]
@Rugvip is there an example repo that's using Auth0 provider?

**Comment by Rugvip** [comment]
@taras not that I'm aware of. Best bet would be to ask on Discord and perhaps see if any of the authors of the provider are around
