### ISSUE TITLE
feat(yarn): install as a local dependency

### ISSUE THREAD

**Issue by ericis** [spotify/backstage#416]
## Feature Suggestion

Install `yarn` as a local dependency, instead of assuming to install it globally. This will also guarantee that engineers are using the same version.

## Possible Implementation

`npm i yarn -D`

## Context

Why is yarn actually required? Setup instructions require the installation of yarn globally via the yarn installer while also requiring the user to install NodeJS. Would it be better to have them just install Node and then use the npm yarn dev dependency?

**Comment by Rugvip** [comment]
I'll 1-up this! We're shipping the entire yarn implementation in the repo, see [.yarnrc](https://github.com/spotify/backstage/blob/0692663f9f96842c997cf00852da15b400aa0451/.yarnrc) and [.yarn/releases](https://github.com/spotify/backstage/blob/0692663f9f96842c997cf00852da15b400aa0451/.yarn/releases).

See https://classic.yarnpkg.com/en/docs/cli/policies/

**Comment by Rugvip** [comment]
@ericis Do you agree what I mentioned solves the problem you highlighted?

**Comment by Rugvip** [comment]
#441 is an example of how we would bump the current yarn version

Closing this for now, please let so know if we missed something.

**Comment by ericis** [comment]
No @Rugvip it really doesn't quite solve it. The project is using an extension of yarn to lock the version of yarn, which still requires a global installation of yarn, which shouldn't be required.

Since engineers have to have NodeJS, I was suggesting that this project install yarn as a development dependency using `npm i yarn -D` (adding it to the `./package.json`).

**Goals:**
- eliminate yarn as a global dependency
- lock yarn version for all engineers (immutable tool consistency)

I'll submit a PR.

**Comment by Rugvip** [comment]
@ericis ok, happy to review the PR, some things are easier to explain with code :grin:

**Comment by ericis** [comment]
The suggested fixes are provided in PR #468
