### ISSUE TITLE
Add `yarn clean` clean, which cleans up all build output

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#427]
## Feature Suggestion

Add a `yarn clean` command to the root package and any package with build output

## Possible Implementation

Clean command that deletes the build output. I think we could rely on a single dependency in the root package for the remove command, such as rimraf.

## Context

Should be useful for troubleshooting build issues and when working on the CLI build tooling.

**Comment by NetPenguins** [comment]
Hey there, wanting to get started on contributing to your project here. So I know we can call rimraf inside of root/package.json and direct that to node_modules which should cover all bases. Am I understanding this correctly?

**Comment by Rugvip** [comment]
Discussion ongoing in #524, should I assign this to you @NetPenguins?

**Comment by OrkoHunter** [comment]
We can close this issue, since https://github.com/spotify/backstage/pull/524 is merged! 🚀

**Comment by stefanalund** [comment]
Closed in #524
