### ISSUE TITLE
Remove build step from Dockerfile

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#443]
## Feature Suggestion

Remove the initial build step in the Dockerfile and depend on that being run on the host.

## Possible Implementation

Remove the first step in the multistage build, copy contents from app build output instead.

## Context

Running the build inside the docker is pretty finicky. There are a lot of individual files to copy in and it makes the build pretty fragile. It is also ridiculously slow as yarn install has to do everything from scratch. I think it makes more sense to simply remove the first step and rely on the app to be bundled on the host before building the container.

I'm usually prefer having everything in a single Dockerfile, but in this case I don't think it makes much sense. Latest related issue is #436

**Comment by paulpach** [comment]
I'll take it, PR coming soon.

**Comment by Rugvip** [comment]
@paulpach Thanks, but hold up! This is already in review: #446

Dunno why GitHub didn't pick up the link, guess it has to be in the original PR body?

**Comment by Rugvip** [comment]
Fixed by #446
