### ISSUE TITLE
Document how to contribute to Storybook

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#448]
## Feature Suggestion

Document how to contribute to Storybook as well as how to run it locally.

## Possible Implementation

A new Markdown file in `/docs` linked to from the main Documentation section in the README.

## Context

Having good documentation will increase the likelihood of someone helping to create and maintain components.

**Comment by stefanalund** [comment]
@katz95 @mateusmarquezini FYI

**Comment by stefanalund** [comment]
@mikqi

**Comment by mateusmarquezini** [comment]
> @katz95 @mateusmarquezini FYI

Feel free to assign it to me if you want! 🥳
