### ISSUE TITLE
Change Storybook background color (behind the components)

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#450]
Would love if someone could modify the background color behind the Information Card component in Storybook (and future components as well) to the current background color in Backstage, which is #F9F9F9. Currently my eyes are strugging a bit to see the component, haha! Let me know if that's even possible. 🙏

<img width="481" alt="Screenshot 2020-04-02 at 1 59 30 PM" src="https://user-images.githubusercontent.com/61153904/78246891-2fb85400-74ea-11ea-9aa5-09c57f2808b7.png">

<img width="906" alt="Screenshot 2020-04-02 at 2 00 46 PM" src="https://user-images.githubusercontent.com/61153904/78247006-5e362f00-74ea-11ea-8c4e-197865af3575.png">

**Comment by hmartinez69** [comment]
@katz95 @stefanalund  : PR #458 for this issue

**Comment by stefanalund** [comment]
Closed in #458
