### ISSUE TITLE
Tests fail for App if imported plugins are exported on the same line

### ISSUE THREAD

**Issue by marcuseide** [spotify/backstage#451]
## Expected Behavior

Plugins are being exported to the App In `app/src/plugins.ts`.
A plugin should be able to be exported with an import on the same line using ES6 syntax without test failing.
```js
export { default as HomePagePlugin } from '@backstage/plugin-home-page';
export { default as WelcomePlugin } from '@backstage/plugin-welcome';
```

## Current Behavior

Currently, plugins are first imported, then exported:
```js
import { default as HomePagePlugin } from '@backstage/plugin-home-page';
import { default as WelcomePlugin } from '@backstage/plugin-welcome';
export { HomePagePlugin, WelcomePlugin };
```

Otherwise, `App.test.js` will fail with:

```bash
 yarn run v1.22.1
$ backstage-cli test
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Plugin 'undefined' is already registered

      33 |         for (const p of plugin) {
      34 |             if (this.plugins.has(p)) {
    > 35 |                 throw new Error(`Plugin '${p}' is already registered`);
         |                       ^
      36 |             }
      37 |             this.plugins.add(p);
      38 |         }

      at AppBuilder.Object.<anonymous>.AppBuilder.registerPlugin (../../core/dist/cjs/api/app/AppBuilder.js:35:23)
      at Object.<anonymous> (App.tsx:46:19)
      at Object.<anonymous> (App.test.tsx:19:1)

  console.warn ../../node_modules/react/cjs/react.development.js:315
    Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        23.981s
Ran all test suites.

Command 'web-scripts' exited with code 1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The reason for the above error is that the exports in `plugins.ts` is being imported as `undefined` which then gets registered in the App, which cannot handle two plugins with the same name.

## Possible Solution

Look into why this is happening for tests only. Possibly a `jest` setting somewhere?

## Steps to Reproduce (for bugs)

1. Change the import/export statement in `plugins.ts`
2. Run `yarn test` in `packages/app`

## Your Environment

* NodeJS Version (v12):
* Operating System and Version (e.g. Ubuntu 14.04):
* Browser Information:

**Comment by braulio-balanza** [comment]
@marcuseide it might have something to do with the order of imports and exports. I printed the value of the variable plugins in App.tsx and gave me this: 
```
console.log src/App.tsx:1271
    { HomePagePlugin: undefined, WelcomePlugin: undefined }
```
it is being imported from plugins.ts before they have any value. I don't know if that was what you were referring to.

**Comment by freben** [comment]
@braulio-balanza Right, that's the symptom we were seeing - question is why, and why only in tests, and what to do about it.

**Comment by soapraj** [comment]
I tried repro-ing this issue with a similar setup with react-script, jest and ts [here](https://github.com/soapraj/jest-exp)

The exports seem to work and I can see that the plugins object is a valid one

```
plugins ==> {
  SamplePlugin: [Function: SamplePlugin],
  FooPlugin: [Function: FooPlugin]
}
```

If I change the lines in plugins.ts  to
```
export * as HomePagePlugin from '@backstage/plugin-home-page';
export * as WelcomePlugin from '@backstage/plugin-welcome';
```

then the plugins object in App.tsx looks like this
```
    plugins ==> {
      HomePagePlugin: {
        config: { id: 'home-page', register: [Function: register] },
        default: Plugin { config: [Object] }
      },
      WelcomePlugin: {
        config: { id: 'welcome', register: [Function: register] },
        default: Plugin { config: [Object] }
      }
    }
```

**Comment by soapraj** [comment]
This issue is no longer valid after https://github.com/spotify/backstage/pull/526

**Comment by Rugvip** [comment]
@soapraj oh yeah good point :grin:

We should update the logic in `create-plugin` and close this. We still have the issue of forwarding of default exports not working in tests though I guess, so probably open an issue detailing that instead.

**Comment by braulio-balanza** [comment]
Actually, after alpha.4 I can't replicate the error anymore.
