### ISSUE TITLE
Avoid PR rebuild after text edit

### ISSUE THREAD

**Issue by ericis** [spotify/backstage#469]
Simply editing the text of a PR causes Actions to kick-off CI and tests.

## Expected Behavior

Editing text of a PR would not initiate Actions. *Unless the actions are verifying something about the comment, but then they don't need to run the entire pipeline.

## Current Behavior

[see above]

## Possible Solution

Is this possible? Is it possible to ignore something like "pull_request edited"?

## Steps to Reproduce (for bugs)

1. Edit the text for an open PR that already completed CI and test actions
2. Watch them run again

## Context

Actions are unnecessary here.

## Your Environment

n/a (GitHub)

**Comment by Rugvip** [comment]
Yeah that makes little sense, good catch!

Fixed in #470
