### ISSUE TITLE
Dynamic load apps without recompiling

### ISSUE THREAD

**Issue by drsounds** [spotify/backstage#471]
It should be possible to dynamic load apps without recompiling and also be able to support apps in other frameworks than just React.js. There is a suggestion for that on your discord from a company who are interested in Backstage but uses Vue.js
## Possible Implementation

New JS Import API that works in modern browser

**Comment by freben** [comment]
This sounds like two separate issues.

Embedding vue in react is possible using e.g. [vuera](https://github.com/akxcv/vuera), but it's of course not optimal. The core of Backstage is and will remain react + mui based.
