### ISSUE TITLE
COPY failed: stat /var/lib/docker/...packages/app/build: no such file or directory

### ISSUE THREAD

**Issue by dpinol** [spotify/backstage#479]
Hi,
```docker build``` fails on my machine (docker 19.03.8, ubuntu Ubuntu 19.10)
```
docker build . -t spotify/backstage
Sending build context to Docker daemon  9.893MB
Step 1/6 : FROM nginx:mainline
mainline: Pulling from library/nginx
c499e6d256d6: Pull complete 
74cda408e262: Pull complete 
ffadbd415ab7: Pull complete 
Digest: sha256:282530fcb7cd19f3848c7b611043f82ae4be3781cb00105a1d593d7e6286b596
Status: Downloaded newer image for nginx:mainline
 ---> ed21b7a8aee9
Step 2/6 : COPY packages/app/build /usr/share/nginx/html
COPY failed: stat /var/lib/docker/tmp/docker-builder052570233/packages/app/build: no such file or directory
```
## Expected Behavior
No error

## Current Behavior
COPY failed: stat /var/lib/docker/tmp/docker-builder052570233/packages/app/build: no such file or directory

## Steps to Reproduce (for bugs)
```
git clone git@github.com:spotify/backstage.git
docker build . -t spotify/backstage
```

## Your Environment
* NodeJS Version (v12): v12.16.1
* Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 19.10
* Browser Information: not using it

**Comment by freben** [comment]
Sounds like you didn't build the project first. The canonical way of building it is `yarn docker-build`, would you mind trying that?

**Comment by dpinol** [comment]
it worked thanks!
