### ISSUE TITLE
[cli] pass `backstage-cli test` command line arguments to `web-scripts test`

### ISSUE THREAD

**Issue by fastfrwrd** [spotify/backstage#488]
## Feature Suggestion
When I run `yarn test Intro` on the lighthouse plugin, I hope to have the behavior to web-scripts, which passes all of the arguments that web-scripts doesn't interact with directly onto Jest, meaning that I filter to just run the test I meant to run. Today, it seems to swallow that stuff.

**Comment by Rugvip** [comment]
👍 , we haven't quite figured out the model for the cli commands args/help, but I imagine we can already settle on only jest for tests and forward all args.
