### ISSUE TITLE
[plugin-lighthouse] automatically poll for updates on RUNNING audits

### ISSUE THREAD

**Issue by fastfrwrd** [spotify/backstage#522]
## Feature Suggestion

When an audit is running in the application, I want to see updates without having to manually refresh. This would mean that we could have the Create Audit redirect go to the AuditView without it feeling too weird.

## Possible Implementation

- when an audit is found to be running, create an effect which keeps requesting it
- maybe restructure the data in the plugin to use a top-level reducer with a context, and move to a flux-y architecture

## Context

- as a user of the plugin, I should see updates to running audits as they happen in a realtime manner.

**Comment by braulio-balanza** [comment]
I could try and hack this one, any pointers to get started?

**Comment by freben** [comment]
I'm not the maker of the ticket, but something like a useInterval that refetches every so often if anything is in progress, would probably be a good start

 https://github.com/streamich/react-use/blob/master/docs/useInterval.md

**Comment by braulio-balanza** [comment]
Ok, I'll give it a shot

**Comment by stefanalund** [comment]
Great @braulio-balanza I assigned you!

**Comment by stefanalund** [comment]
Fixed in https://github.com/spotify/backstage/pull/623
