### ISSUE TITLE
npx @backstage/cli create-app fails: describe is not defined

### ISSUE THREAD

**Issue by codypenta** [spotify/backstage#525]
Following the getting started blog here: https://github.com/spotify/backstage/blob/master/docs/getting-started/create-an-app.md

`npx @backstage/cli create-app`

The command fails to create a new app and throws a 'describe is not defined error`

## Expected Behavior

npx @backstage/cli create-app should bootstrap new app

## Current Behavior

npx @backstage/cli create-app fails to create new app mid-way and throws:

ReferenceError: describe is not defined

I cloned the repo and ran the same command internally which got a more verbose error message

```bash
lerna ERR! yarn run build stderr:
/Users/me/js/apps/frontstage/frontstage/node_modules/@backstage/cli/dist/index.js:14
describe('dummy', () => {
^


ReferenceError: describe is not defined
    at Object.<anonymous> (/Users/me/js/apps/frontstage/frontstage/node_modules/@backstage/cli/dist/index.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/me/js/apps/frontstage/frontstage/node_modules/@backstage/cli/bin/backstage-cli:61:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
error Command failed with exit code 1.
```

## Possible Solution

It seems like the CLI and/or Lerna doesn't like this file:

https://github.com/spotify/backstage/blob/master/packages/cli/src/index.test.ts

## Steps to Reproduce (for bugs)

1. npx @backstage/cli create-app

## Your Environment

* NodeJS Version (v12): v12.16.1
* Operating System and Version (e.g. Ubuntu 14.04): MacOS (Catalina)
* Browser Information: N/A

**Comment by braulio-balanza** [comment]
The error seems to be in the /node_modules/@backstage//cli/dist/index.js. It is using a "describe" function when it is not a test file, and eslint is not ignoring /dist. Delete it and that error wont come up. However, the build command still doesn't run because eslint is looking for the legal notice on top of every file.

**Comment by Rugvip** [comment]
Some fixes in #527 and #528, and I believe we need #526 merged too.

Really need #495 in place 😅. `create-app` is still very new and things are moving fast, no things will keep breaking until the test is in place.

**Comment by braulio-balanza** [comment]
I am still getting the same errors. ```yarn install``` installs a version of @backstage/cli that does not reflect the merges. The problem also seems to be in the npm package registry. [You can check it here.](https://npm.runkit.com/%40backstage%2Fcli)
![Screenshot from 2020-04-09 13-25-50](https://user-images.githubusercontent.com/62359443/78928239-e3c75b00-7a65-11ea-821a-b392ed4007ab.png)
 Probably updating the npm package will reflect the mergers and fix the issues.

**Comment by Rugvip** [comment]
@braulio-balanza yeah it needs a new release. The version is master isn't fully working though so I think we could hold off a bit.

**Comment by felipebragazup** [comment]
same problem here
