### ISSUE TITLE
Localhost fails on Safari

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#531]
Safari:
<img width="1552" alt="Screenshot 2020-04-11 at 15 39 18" src="https://user-images.githubusercontent.com/190856/79045312-b7990f00-7c0a-11ea-80b7-c03c52d47c34.png">

Chrome:
<img width="1552" alt="Screenshot 2020-04-11 at 15 39 10" src="https://user-images.githubusercontent.com/190856/79045317-bbc52c80-7c0a-11ea-886c-2c8a7a03b7c9.png">

## Current Behavior

<img width="631" alt="Screenshot 2020-04-11 at 15 40 55" src="https://user-images.githubusercontent.com/190856/79045339-dac3be80-7c0a-11ea-8709-0039a4644f71.png">

## Steps to Reproduce (for bugs)

Run `yarn start` on Safari.
## Your Environment

<img width="396" alt="Screenshot 2020-04-11 at 15 41 53" src="https://user-images.githubusercontent.com/190856/79045364-fcbd4100-7c0a-11ea-91df-0c8ae380dccc.png">

* NodeJS Version (v12):
* Operating System and Version (e.g. Ubuntu 14.04):
* Browser Information:

**Comment by freben** [comment]
@drsounds

**Comment by freben** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList

Does not inherit from EventTarget on safari, may have to use addListener there instead of addEventListener

**Comment by OrkoHunter** [comment]
Hi @freben @stefanalund @drsounds, I've created https://github.com/spotify/backstage/pull/534 for this issue. 🙏
