### ISSUE TITLE
Deploy app for a new Pull Requests for quality assurance

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#535]
## Feature Suggestion

When Pull Requests make breaking changes (UI, build, etc.), screenshots are a good way to help reviewers merge PR with confidence. (We already have this.)

However, for build fixes like https://github.com/spotify/backstage/pull/534, it will be nice to have the branch deployed somewhere on web and the reviewers can visit the link and test the changes!

## Possible Implementation

Heroku can be used for this. They call it ["Review apps"](https://devcenter.heroku.com/articles/github-integration-review-apps). When a PR is created, the pipeline triggers, and a new app is created for the feature branch e.g. https://backstage-pr-xxx.herokuapp.com

## Context

Making it easy for reviewers to accept breaking changes.

**Comment by OrkoHunter** [comment]
If this feature makes sense, I volunteer to help! 🙋‍♂️

**Comment by stefanalund** [comment]
@OrkoHunter that would be great. We have a similar thing internally at Spotify and it is indexed very useful. I’m assigning you. Thanks 🙏

**Comment by OrkoHunter** [comment]
Awesome! Great to know. Let me get started on a personal heroku pipeline and I'll configure it for my fork.

Later, we can create the "official" heroku pipeline for this repository. 🙏

**Comment by OrkoHunter** [comment]
Hi @Rugvip ! Huge thanks to you for helping me on discord with this. To summarize the current situation -

As long as we use `yarn start` or `backstage-cli app:serve` to start the app on Heroku, we are going to get a boot time out on Heroku because of `backstage-cli`'s [cache management](https://github.com/spotify/backstage/blob/a6167ce02a59520734b83e3fc0bad4297938b9c0/packages/cli/src/commands/build-cache/index.ts#L27-L51). Since most probably, Heroku does not track files in git, `backstage-cli` is going to do rollup build for all the packages, and exceed the 60 seconds time limit.

Some of the solutions/alternatives that I can think of -

* Skip `backstage-cli` and directly serve the static content somehow, to bypass cache check logic. (?) Not sure if it would work.
* Update cache checks to work in a non-git repo as well. (Probably too much work)
* Look for some other way to host which does not have a timeout limit.

**Comment by OrkoHunter** [comment]
https://tugboat.qa looks like a good alternative! Especially made for this problem.

<img width="2048" alt="Screen Shot 2020-04-13 at 1 21 17" src="https://user-images.githubusercontent.com/8065913/79074052-2074aa00-7d25-11ea-8ebb-12bc1d6a8983.png">

**Comment by OrkoHunter** [comment]
Azure pipelines might also be an alternative.

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops

**Comment by Rugvip** [comment]
@OrkoHunter np! Just to be clear tho, the cache management doesn't add any time to the build, it just speeds up subsequent builds. Building without the cache would take just as long time.

**Comment by freben** [comment]
Right, if we could take actual app build output produced by the review build, and  serve that statically, we'd be golden - correct?

**Comment by OrkoHunter** [comment]
@freben Yes, agreed!
@Rugvip Thanks!

**Comment by OrkoHunter** [comment]
If we were to serve static content, let me give Netlify a try, which builds static pages from PRs. It's very similar to GitHub pages.
https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

**Comment by OrkoHunter** [comment]
Wohoo! Netlify worked great!

Here is the build for the master branch on my fork - https://backstage-spotify-orkohunter.netlify.com/
And here is [the deployment](https://5e9474dd557c5b0008ad2a57--backstage-spotify-orkohunter.netlify.com/) for new Pull Request https://github.com/OrkoHunter/backstage/pull/5

**Comment by OrkoHunter** [comment]
It might be better to use GitHub actions to trigger Netlify deployment.

@stefanalund @Rugvip @freben Let me know your thoughts. 🙇

**Comment by OrkoHunter** [comment]
This is the configuration file https://github.com/OrkoHunter/backstage/blob/master/netlify.toml
```toml
# Filename: netlify.toml

[build]
  command = "yarn bundle"
  publish = "packages/app/build"

[build.environment]
  NODE_VERSION = "12"
```

**Comment by freben** [comment]
I haven't read up on what features these things  offer. But I was hoping that it would be possible to just add a step at the end of the review build workflow that zips up the already finished dist folder and calls it a deployment :) If that doesn't make any sense, feel free to ignore :)

**Comment by OrkoHunter** [comment]
> that zips up the already finished dist folder and calls it a deployment

Oh. In my understanding, this will then allow the reviewers to download the zip and run the website locally. Hmm, I'm not so sure how helpful it will be. We can also checkout anyone's git branch and build it locally.

So, I believe having Netlify to deploy preview apps for our PRs would be a good thing. (Bonus: We also get a master branch deployment for people to see a quick demo).

Today, I noticed that [Storybookjs also uses Netlify deploy previews for PRs](https://github.com/storybookjs/storybook/pull/10411/checks?check_run_id=584451261). I hope adding Netlify to the repository is not much of an intrusion. But, I will leave this for @spotify/backstage-core to decide. 🙇

**Comment by OrkoHunter** [comment]
I'll close this ticket since Netlify has been integrated with the repository and can be used to see PR deploys. Related #593.

**Comment by q0rban** [comment]
Hi friends!

Glad to hear Netlify got you going! 

If you're interested in giving Tugboat a spin, I'd love to help out. Among other things, Tugboat has visual diffs built-in, shell access to all services right from your browser, and preview snapshots called Base Previews that speed up your builds tremendously. If you're interested, you can hop into our [Slack](https://launchpass.com/tugboatqa) or shoot me an email at james@tugboat.qa.

I know this is all probably 'too little, too late,' so… here's a Tub and Goat:

# 🛀 🐐
