### ISSUE TITLE
Show code in Storybook

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#536]
Other Storybooks show the example code next to the demo. It would be nice if ours did that as well. Example: https://react.carbondesignsystem.com/?path=/story/codesnippet--multi-line

<img width="1552" alt="Screenshot 2020-04-12 at 15 34 50" src="https://user-images.githubusercontent.com/190856/79070064-643ec380-7cd3-11ea-9b64-5960f704f9cd.png">

**Comment by OrkoHunter** [comment]
Hi @stefanalund ! Looks like a good feature.

Let me get an understanding on how Storybook implemented and I'll get started. ✨
