### ISSUE TITLE
Support dark/light mode in Storybook

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#543]
## Feature Suggestion

Make it possible to toggle dark/light mode inside Storybook. This will allow for easier verification that components behave correctly in both themes. 

## Possible Implementation

https://medium.com/encode/setting-up-storybook-with-material-ui-and-styled-components-5bdacb6db866

**Comment by OrkoHunter** [comment]
Thanks for creating the issue @stefanalund and the medium article. Let me start the implementation.

This storybook documentation is helpful too https://storybook.js.org/docs/configurations/theming/

**Comment by stefanalund** [comment]
Thanks for looking into this @OrkoHunter -- I assigned you to the Issue.

**Comment by OrkoHunter** [comment]
Thanks @stefanalund !
