### ISSUE TITLE
Matching the width of the Tabbed Card Component to the Information Card Component in Storybook

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#564]
Currently the [Tabbed Card ](http://storybook.backstage.io/?path=/story/tabbed-card--default) spans the whole width of the stage. It would be rad if it could match the width of the Information Card (seen below).

<img width="892" alt="Screenshot 2020-04-16 at 9 38 22 AM" src="https://user-images.githubusercontent.com/61153904/79428234-2806ae00-7fc6-11ea-83f7-87ecf85d0b51.png">

**Comment by OrkoHunter** [comment]
I was looking at the Storybook to find the discrepancy between the components, but later realized it was fixed in https://github.com/spotify/backstage/pull/565 😅

**Comment by Rugvip** [comment]
@OrkoHunter ah right, slight issue with the reference syntax in the PR xP

**Comment by OrkoHunter** [comment]
Honestly, GitHub could do a lot more than just looking for `Closes` in the description 😂
