### ISSUE TITLE
Edit Style of Table Component

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#569]
## 🗒 General 

It would be amazing if someone could update the [sortable table component ](http://storybook.backstage.io/?path=/story/sortable-table--default) styles!

## 💻 Usage

The sortable table is a robust way to view a lot of categorized information at once. By giving users the power to modify their views of the inputs, they can comprehend the data in a much easier way. 

### Default state
![Default](https://user-images.githubusercontent.com/61153904/79459521-b0e80e80-7ff3-11ea-8e18-bf930720e7f0.png)

### Hover
![Hover](https://user-images.githubusercontent.com/61153904/79459520-b04f7800-7ff3-11ea-939e-dc3c6af55a56.png)

### Active
![Focus](https://user-images.githubusercontent.com/61153904/79459518-afb6e180-7ff3-11ea-9c10-eecae691fcf5.png)

## 📐 Specs

![Specs](https://user-images.githubusercontent.com/61153904/79471173-8c476300-8002-11ea-9b91-185d6558e8c0.png)

### Rules
1. Text input columns are always left aligned for easier read. The sort arrow icon will go to the right of the column header.  _Caveat: this can be adjusted for different languages._
2. Numerical input columns are always right aligned for easier read. The sort arrow icon will go to the left of the column header.

### Example
<img width="251" alt="Screenshot 2020-04-16 at 4 38 25 PM" src="https://user-images.githubusercontent.com/61153904/79469634-b730b780-8000-11ea-99c1-94c896d06409.png">

## 🔮 Future

- Status
- Additional types of input

**Comment by stefanalund** [comment]
I wonder if we should hold off on these changes in the existing SortableTable since we want to replace that one with a more feature-rich default table/grid component https://github.com/spotify/backstage/issues/161 -- @hooloovooo is looking into that issue.

**Comment by tharun208** [comment]
@stefanalund ,I like to work on this issue !

**Comment by stefanalund** [comment]
@tharun208 thanks a lot for offering, but the plan is that this stylistic change will be included in this work https://github.com/spotify/backstage/pull/600

I think there will be additional issues created for improving that one as it lands. @hooloovooo can you please makes sure to ping @tharun208 on any such issue? Thanks
