### ISSUE TITLE
Create better Storybook example for TrendLine

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#573]
Our Storybook should show a more typical Story example of a TrendLine. A good example is how it is used in the [Lighthouse plugin](https://github.com/spotify/backstage/tree/master/plugins/lighthouse):

<img width="1125" alt="lead" src="https://user-images.githubusercontent.com/190856/79538713-29e37680-8085-11ea-80c7-d547b6a7d9ed.png">

## Feature Suggestion

Add additional story in `TrendLine.stories.tsx` that wraps it in a `SortableTable`.

**Comment by OrkoHunter** [comment]
@stefanalund Please see https://github.com/spotify/backstage/pull/611 🙏
