### ISSUE TITLE
Setup a process for Architecture Decision Records (ADR)

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#574]
Context https://labs.spotify.com/2020/04/14/when-should-i-write-an-architecture-decision-record/

Ping @jomaxx -- author of ^

## Feature Suggestion

Store architectural decisions somewhere in the repo.

**Comment by eywoon** [comment]
I'd like to take this one up 😀

**Comment by stefanalund** [comment]
Thanks @eywoon -- I assigned you!
