### ISSUE TITLE
Packages should use dependencies instead of peerDependencies

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#584]
## Expected Behavior

We were hoping that peerDependencies could be used as a way to signal which dependencies should be shared with other packages. Even to the point where we inline the regular dependencies during the rollup build.

## Current Behavior

Peer dependencies don't work well with yarn workspaces, transitive dependencies in the workspace don't propagate properly. For example, if a plugin has a peer dependency on react and the app depends on the plugin, yarn will complain about a missing peer dependency, even if the app depends on react.

## Possible Solution

Skip using peerDependencies for now, make all packages just use dependencies instead. They pretty much behave the same anyway atm.

## Context

Initially brought up in #576, and partially fixed in #581.

**Comment by ruairitobrien** [comment]
I can take this one on 👍

**Comment by Rugvip** [comment]
Fixed by #586
