### ISSUE TITLE
Change the background color in Storybook to comply with dark/light mode

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#602]
## Feature Suggestion

Change the background of Storybook to comply with dark/light mode.

![image for github](https://user-images.githubusercontent.com/8065913/79735415-3856ba00-8333-11ea-8246-72b090ac0afc.png)

## Possible Implementation

From @Rugvip, we can probably add a decorator that wraps every page with a themed background.
The current dark/light mode wraps only the components with the theme.

## Context

Dark/Light mode was added for components in Storybook in https://github.com/spotify/backstage/pull/599.

**Comment by stefanalund** [comment]
Fixed in #634
