### ISSUE TITLE
Convert StructuredMetadataTable to TypeScript

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#607]
## Feature Suggestion

This component should be converted from JS -> TS:

https://github.com/spotify/backstage/tree/master/packages/core/src/components/StructuredMetadataTable

## Context

We want all components and APIs to be in TypeScript.

**Comment by braulio-balanza** [comment]
So I submitted a pull request that addresses this issue #656. I didn't see this issue was already assigned, which is completely my mistake and I apologize for it. Would it be fine if we use the pull request I made as a draft for this issue? @stefanalund @soapraj

**Comment by stefanalund** [comment]
No worries @braulio-balanza -- I know for a fact that @soapraj has other stuff to do as well, I'm sure he won't mind 💯 Thanks for the awesome work!

**Comment by stefanalund** [comment]
Closed in #656
