### ISSUE TITLE
Use @internal namespace for private packages

### ISSUE THREAD

**Issue by freben** [spotify/backstage#615]
As part of clarifying what is part of the open source offering and what is examples or private code, we should signal these differences using package names/namespaces.

Suggested solution:

* Let all public, published packages retain their `@backstage` namespace. 
* ~~Change all private packages in the open source project (`plugins/home-page`, `plugins/welcome`) to be under an `@internal` namespace~~
* Change the create-app template accordingly
* For future additions to the create-app template, such as a placeholder package for internal-only shared components or so, make sure that that also gets the `@internal`+private treatment
* Offer an option in the create-plugin script to configure the new plugin as `@internal` (and private) upfront, or as `@spotify`.
* Update documentation accordingly, where appropriate

**Comment by watcher00090** [comment]
Hi, I'm a little new to backstage and want to contribute, I was wondering, what would the point of the second to last bullet be?

**Comment by freben** [comment]
@watcher00090 Hi, we were reviewing old issues and realised that we had somehow completely missed responding to your comment - sorry about that. Is this something you would still want to look into? 

To answer your question, the second point actually no longer applies since home-page is gone and welcome is published.
