### ISSUE TITLE
Plugin Route

### ISSUE THREAD

**Issue by o0Djeen0o** [spotify/backstage#616]
Hi,

If I understand correctly, a Plugin registers its own route with the React Component to be used, something like : 
` router.registerRoute('/myRoute', MyComponent);`

However, it is in the final application that plugins are imported and routes mapped:

```
<SidebarPage>
    <Sidebar>
      <SidebarLogo />
      <SidebarSpacer />
      <SidebarDivider />
      <SidebarItem icon={AccountCircle} to="/myRoute" text="MyComponent" />
      <SidebarDivider />
      <SidebarSpace />
      <ToggleThemeSidebarItem />
    </Sidebar>
    {children}
  </SidebarPage>
```

So why the route is not defined by app instead of the Plugin ? If my application is working in a given path, let's say `http://localhost:3000/my/application/ui`, I would like to have my plugin added in this inner route, `http://localhost:3000/my/application/ui/myRoute`, and not `http://localhost:3000/myRoute`.

Maybe I'm missing some information here. Could you help?

## Feature Suggestion

Allow a plugin to be registered within an inner (not known by the plugin) route, depending of the application landscape.

## Possible Implementation

Router could be configured by the final application to add a prefix path.

**Comment by Rugvip** [comment]
@o0Djeen0o Thanks for reporting! What do you think about https://github.com/spotify/backstage/issues/418 as a solution?

**Comment by o0Djeen0o** [comment]
Hello @Rugvip,

Sorry, I missed this RFC. I've checked the proposal and I think that it would resolve elegantly my issue ! Thanks!

**Comment by stefanalund** [comment]
Tracked in #418
