### ISSUE TITLE
packages/cli: Rollup caching is not used on Windows for yarn start/build

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#618]
## Expected Behavior

The issue is only for Windows.

After running `yarn build` and `yarn start` for the first time, the successive `yarn start` should use the rollup build cache.

## Current Behavior

The rollup caches are not being used. The error says `[build-cache] input directory is dirty, skipping cache`.

Thus, it takes ~4 minutes to run `yarn start` each time after making any change. This significantly slows down development.

<img width="863" alt="Screen Shot 2020-04-22 at 22 40 33" src="https://user-images.githubusercontent.com/8065913/79989835-47806800-84eb-11ea-89c8-972d814dec1c.png">

## Possible Solution

Modify/Update the logic to check for caches in the cli package. https://github.com/spotify/backstage/tree/master/packages/cli/src/lib/buildCache

## Steps to Reproduce

1. Run `yarn start` on a Windows machine.
2. Close, and then do `yarn start` again.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Windows Server 2019 (on AWS)
- Browser Information: (Not relevant, but IE).

**Comment by OrkoHunter** [comment]
cc @Rugvip, I noticed this while debugging for #613.

**Comment by Rugvip** [comment]
@OrkoHunter Thanks! I'd guess that this check is failing: https://github.com/spotify/backstage/blob/5b34072863fcaa23153b05560a25e10e83e66247/packages/cli/src/lib/buildCache/cache.ts#L88. Could be that that command doesn't fly on windows.

**Comment by OrkoHunter** [comment]
Yes, I agree. In the command `git diff --quiet HEAD -- ${quotedInputPaths.join(' ')}`, my guess is that the path after `--` is not properly formatted for Windows.

**Comment by Rugvip** [comment]
nvm, seems to be working just fine on Windows in latest master!
