### ISSUE TITLE
Dynamic imports don't work

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#630]
## Expected Behavior

It should be possible to use dynamic imports, i.e. `import('my-module').then(module => ...)`

## Current Behavior

Rollup doesn't seem to generate correct output for import statements. It ends up removing the import function with this:

```
() => new Promise(function (resolve) { resolve(_interopNamespace(require('my-module'))); })
```

## Possible Solution

Changing the rollup output format to 'module' seems to produce correct code. We might want to switch to that and make sure it works with the rest of the build.

## Steps to Reproduce

Try to use a dynamic import in a plugin.

## Context

Dynamic imports is a huge part of keeping initial page load fast, it's best to have it working early on so that all plugins can use it.

**Comment by OrkoHunter** [comment]
This also requires an update to `tsconfig.json`.
```json
  "compilerOptions": {
    "module": "esnext"
  }
```
Build error without updating tsconfig, for a new plugin which has dynamic import:
```
src/index.ts:19:1 - error TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'esnext', 'commonjs', 'amd', 'system', or 'umd'.
```
