### ISSUE TITLE
Yarn start: Missing notice header error in plugin.ts

### ISSUE THREAD

**Issue by dev0zz** [spotify/backstage#640]
I can't start the application

![backstage error](https://user-images.githubusercontent.com/44142517/80209078-ab14ad80-8631-11ea-8a0c-1ea7ddc49003.png)

**Comment by stefanalund** [comment]
@dev0zz what environment are you on? It works on Mac for me.

**Comment by Rugvip** [comment]
Thanks for reporting! Fix is being worked on, but I'm closing this as it's a duplicate of #613

**Comment by dev0zz** [comment]
> @dev0zz what environment are you on? It works on Mac for me.

i am working on Windows
