### ISSUE TITLE
HorizontalScrollGrid broken in dark mode

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#666]
## Expected Behavior

A natural "dark" shadow be used.

## Current Behavior

<img width="1094" alt="Screenshot 2020-04-28 at 07 28 56" src="https://user-images.githubusercontent.com/190856/80450583-1ad0b400-8922-11ea-83cb-0d7657a3d6bb.png">

## Possible Solution

Switch to darker pattern.

**Comment by shmidt-i** [comment]
Can take this one for starters!

**Comment by stefanalund** [comment]
Thank @shmidt-i I assigned you!

**Comment by stefanalund** [comment]
Fixed in https://github.com/spotify/backstage/pull/668
