### ISSUE TITLE
[Plugin] CircleCI

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#667]
## Summary

Show a list of builds in CircleCI and allow users to drill down to get more information. Some inspiration may be found from our internal CI view:

![Screenshot 2020-04-28 at 09 34 00](https://user-images.githubusercontent.com/190856/80459970-735c7d00-8933-11ea-8951-5a4adc3d51a2.png)

![image3](https://user-images.githubusercontent.com/190856/80459458-b23e0300-8932-11ea-88ed-c7d5d021b272.png)

## Project website (if applicable)

https://circleci.com/docs/api/

## Context

A CI view is one of the essential and most used plugins inside Spotify. As an example, our CI environment adds deep links into Backstage in the Pull Request view(s) in GitHub. From there engineers can drill down further and follow the status of PRs as they make their way into production.

**Comment by leomindez** [comment]
Should I create a plugin into [https://github.com/spotify/backstage/tree/master/plugins](plugins) section?

**Comment by stefanalund** [comment]
> Should I create a plugin into https://github.com/spotify/backstage/tree/master/plugins section?

@leomindez yes - that's the preferred approach for plugins that should be open sourced.

I know for a fact that @shmidt-i has started looking into building this plugin. Would you be interested in working on a different CI plugin:

https://github.com/spotify/backstage/issues/673
https://github.com/spotify/backstage/issues/674

**Comment by shmidt-i** [comment]
@Nek and me are working on this

**Comment by Nek** [comment]
work started!
