### ISSUE TITLE
[Plugin] Jenkins

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#673]
## Summary

Show a list of builds in [Jenkins](https://www.jenkins.io/) and allow users to drill down to get more information. 

Some inspiration may be found from our internal CI view:

![Screenshot 2020-04-28 at 09 34 00](https://user-images.githubusercontent.com/190856/80459970-735c7d00-8933-11ea-8951-5a4adc3d51a2.png)

![image3](https://user-images.githubusercontent.com/190856/80459458-b23e0300-8932-11ea-88ed-c7d5d021b272.png)

## Project website (if applicable)

https://wiki.jenkins.io/display/JENKINS/Remote+access+API

## Context

A CI view is one of the essential and most used plugins inside Spotify. As an example, our CI environment adds deep links into Backstage in the Pull Request view(s) in GitHub. From there engineers can drill down further and follow the status of PRs as they make their way into production.

**Comment by splisson-altair** [comment]
I'm interested working on this.

**Comment by stefanalund** [comment]
@splisson-altair excellent! I've assigned it to you. Let us know on [Discord](https://discord.com/invite/EBHEGzX) if you need any help.

**Comment by littlethoughts** [comment]
I started looking into this, but was held up by CORS policies. Do you want to look at this together @splisson-altair ?

**Comment by stefanalund** [comment]
I suggest looking at the [CircleCI plugin](https://github.com/spotify/backstage/tree/master/plugins/circleci) as well. @shmidt-i or @Nek can help answer questions about it.

**Comment by freben** [comment]
Maybe proxying through the backend (`packages/backend` is the example implementation) is applicable here? By making a `plugins/jenkins-backend` that exposes a frontend friendly API.

**Comment by splisson** [comment]
@stefanalund please assign to my personal account instead, thanks

@freben yes that s what I'm wondering. looking into circle-ci plugin it seems the proxying is integrated in the plugin via api. Is that a backend also ? (just not separate?) @shmidt-i @Nek ? I'm thinking of using the same pattern and use jenkins npm package on the server side.

**Comment by splisson** [comment]
> I started looking into this, but was held up by CORS policies. Do you want to look at this together @splisson-altair ?

yes. I'm exploring circle-ci plugin to see gif the same pattern can be used for Jenkins. Ping me on discord when available to discuss.

**Comment by stefanalund** [comment]
Lot's of companies are interested in a Jenkins plugin. Is there any update on this? Thanks

**Comment by splisson** [comment]
> Lot's of companies are interested in a Jenkins plugin. Is there any update on this? Thanks

Unfortunately I did not get enough time to work much on this. I have some initial code following the circle example. I'll try to push a branch so people can collaborate on this, sounds good?

**Comment by stefanalund** [comment]
@splisson thanks for the update! Creating a Draft pull request would be awesome 💯

**Comment by littlethoughts** [comment]
It seems that a lot of plugins will need to have a proxy backend and different kinds of authorization. Jenkins uses basic auth for example.
Are there any plans to have a generic proxy backend that can be used by all "frontend" plugins?
Otherwise it would be necessary to duplicate something like @freben wrote in the sentry-backend plugin.
Same question for authorization, is there a generic way to store credentials per user?

**Comment by Rugvip** [comment]
@littlethoughts we haven't properly started exploring proxying in the backend yet, but it's something that's been discussed quite a bit and we have a couple of ideas. We most likely want to allow for a couple of different models depending on how much logic there needs to be around managing identities and access in the proxy layer. Most likely we'd also provide some utilities for the most common proxy use-cases as part of the `backend-common` package.

Right now there's no built-in method to store credentials per user in a backend-plugin. The model that does already exist is accessing credentials on the client-side and passing them on to any backend, there's a bit more info about that here: https://github.com/spotify/backstage/blob/master/docs/auth/overview.md#accessing-third-party-services

For Jenkins I think the simples solution would be to look at something like https://plugins.jenkins.io/oic-auth/. With that you can already now hook it up to an ID Token supplied by the `IdentityApi`, and it's gonna be the most future-proof and lowest maintenance method.

In case you want to experiment (it's all very WIP), we just merged a PR with an early implementation of the `IdentityApi`: https://github.com/spotify/backstage/pull/1320
With that you can for example grab an ID Token for the user using `useApi(identityApiRef).getIdToken()` inside a react component. We'll be adding some more configuration around specifying the issuer and audience of the ID token, but for now you can assume it's Google or whatever custom token you paste in the Custom SignIn option.

**Comment by timja** [comment]
I've created a PR for this https://github.com/spotify/backstage/pull/1802, would love feedback on it.

Thanks!

**Comment by stefanalund** [comment]
Closed in https://github.com/spotify/backstage/pull/1802 🎉🎉🎉🎉🎉🎉🎉🎉

Thanks @timja and @dtuite 👏
