### ISSUE TITLE
[Plugin] Travis CI

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#674]
## Summary

Show a list of builds in [Travis CI](https://travis-ci.org/) and allow users to drill down to get more information. 

Some inspiration may be found from our internal CI view:

![Screenshot 2020-04-28 at 09 34 00](https://user-images.githubusercontent.com/190856/80459970-735c7d00-8933-11ea-8951-5a4adc3d51a2.png)

![image3](https://user-images.githubusercontent.com/190856/80459458-b23e0300-8932-11ea-88ed-c7d5d021b272.png)

## Project website (if applicable)

https://docs.travis-ci.com/

## Context

A CI view is one of the essential and most used plugins inside Spotify. As an example, our CI environment adds deep links into Backstage in the Pull Request view(s) in GitHub. From there engineers can drill down further and follow the status of PRs as they make their way into production.

**Comment by stefanalund** [comment]
@dtuite you are working on this, correct?

**Comment by dtuite** [comment]
Yes. Code is here: https://github.com/RoadieHQ/backstage-plugin-travis-ci It installs into Backstage just like any other plugin.

[Here is a live demo.](https://backstage-demo.roadie.io/travis-ci)

![Screenshot 2020-08-09 at 20 18 43](https://user-images.githubusercontent.com/562403/89773801-866b1580-dafc-11ea-819a-bf138b325f93.png)

**Comment by dtuite** [comment]
@stefanalund Corresponding PR: https://github.com/spotify/backstage/pull/1892
