### ISSUE TITLE
The Getting Started page links to a private/non-existent docker image

### ISSUE THREAD

**Issue by JoeStead** [spotify/backstage#677]
The instructions linked here: https://github.com/spotify/backstage/blob/master/docs/getting-started/development-environment.md#L30 point to a docker image that isn't publicly available, and cannot be pulled/run.

## Expected Behavior
The docker image should be accessible and run as described.

## Current Behavior
When not logged in, docker will have an error:
`docker: Error response from daemon: pull access denied for spotify/backstage, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

## Possible Solution
Make the image public/publish the image to dockerhum

## Steps to Reproduce
Run dockerpull on a machine that isn't logged in to dockerhub

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by OrkoHunter** [comment]
> `pull access denied for spotify/backstage`

Hi @JoeStead ! I believe the `spotify/backstage` image is supposed to be created locally using `yarn docker-build` command and then we can run it using `docker run`.

[`yarn docker-build`](https://github.com/spotify/backstage/blob/a92f662d88347a912391b6a6d13dc7d64e3230b5/package.json#L16) bundles the package and creates an image using `docker-build` and creates the `spotify/backstage` tag. The `docker run` is then able to find the image.

Can you please try again and let us know if it still does not work? Thank you!

**Comment by JoeStead** [comment]
Ahh sorry, completely missed the first step trying to rush trying it out. You're right
