### ISSUE TITLE
[CLI] Speed up plugin:build

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#678]
## Feature Suggestion

We're currently using [rollup-plugin-typescript2](https://github.com/spotify/backstage/blob/a92f662d88347a912391b6a6d13dc7d64e3230b5/packages/cli/src/commands/plugin/rollup.config.ts#L47), is really slow. Benchmarking shows that by far the majority of time is spent in this plugin using build, and using `tsc` directly is about 3 times faster.

## Possible Implementation

Try out https://github.com/rollup/plugins/tree/master/packages/sucrase for stripping types. This will leave us without any type definitions though, and one solution to that issue could be to run a separate `tsc` process to generate types in parallel. For watch mode we would need to hook into the (rollup watch events)[https://github.com/spotify/backstage/blob/a92f662d88347a912391b6a6d13dc7d64e3230b5/packages/cli/src/commands/plugin/build.ts#L67] and spawn the `tsc` process. There are some possible issues with this approach though. Since types are not output in sync with JS, watch consumers could run into type issues, or we might end up triggering a second unwanted refresh when the type build completes.

## Context

The `plugin:build` command is too slow for development right now. `backstage/core` takes ~1min to build or start up in watch mode.

This is intended to become less of an issue for plugins and separate backstage apps over time, since the plan is to rely more on `plugin:serve` to serve and watch the plugin code itself, and using packaged versions of `@backstage/core` etc. We still want `plugin:build` to be faster though, or we might need to consider switching to alternative modes of wiring things up for dev.

A bit of extra context around the current architecture of separate builds for all packages is that we currently have a single build internally, and it's quite slow in a number of ways. It's slow to start up the app, which is something we're intending to solve with the separated builds and `plugin:serve`. Typescript completion in editors is also pretty slow, and the goal is to improve that by using type declarations from build output rather than source files.

**Comment by wesleyyee** [comment]
@Rugvip Sucrase looks nice! Had some clarifying questions.

When is it absolutely important to run type checking? 
Is it important to run tsc on every sucrase run in dev mode? Would it be used for generating typings to be used by editors?

One thought is could we add a `plugin:dev` for running the plugins in dev mode that would use sucrase and reserve `plugin:build` for proper builds with type checking via  rollup-plugin-typescript2?

**Comment by Rugvip** [comment]
@wesleyyee I'd say the type checking part of it isn't important at all, we can definitely just run tsc separately, probably as part of the lint step. With the current build setup the type definition generation is important though, as you won't get proper autocompletion in editors without it, even during dev.

**Comment by Rugvip** [comment]
Supersede by #834
