### ISSUE TITLE
Document the different backend use cases 

### ISSUE THREAD

**Issue by freben** [spotify/backstage#694]
Write documentation about how to consume backing services from Backstage.

Outline the difference between (1) just frontend plugin talking directly to a service, (2) frontend talking via the Backstage proxy to a service, (3) frontend with accompanying Backstage backend part. Give guidance on when to choose which one.

**Comment by stefanalund** [comment]
@freben questions are popping up about this. Could you please pick up this issue?

**Comment by freben** [comment]
Working on it!
