### ISSUE TITLE
[CLI] Flaky E2E Test

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#708]
## Expected Behavior

CLI E2E tests should not sometimes fail and have to be retriggered.

## Current Behavior

CLI E2E test sometimes fail to find the expected text on the page being loaded, even though there's nothing wrong with the PR. The test then has to be retriggered to pass.

## Possible Solution

Allow for 3 attempts to [`visit()`](https://github.com/spotify/backstage/blob/3b2aeae05a508f6253808ec118dafd2421362449/packages/cli/e2e-test/helpers.js#L104) and [check for content](https://github.com/spotify/backstage/blob/3b2aeae05a508f6253808ec118dafd2421362449/packages/cli/e2e-test/helpers.js#L121) on the page.

## Steps to Reproduce

`-`

## Context

Failed run: https://github.com/spotify/backstage/runs/619867498?check_suite_focus=true

## Your Environment

GitHub Actions

**Comment by OrkoHunter** [comment]
Hi @Rugvip ! I am trying to understand this issue. I checked the [build error log](https://github.com/spotify/backstage/runs/619867498?check_suite_focus=true) that you have referenced. It is not very clear to me why the assertion failed.

<img width="1114" alt="Screen Shot 2020-05-05 at 3 01 59" src="https://user-images.githubusercontent.com/8065913/80997775-caef7100-8e7c-11ea-83f2-a40d5ec81cd1.png">

I want to clarify your Possible solution.

> Allow for 3 attempts to [visit()](https://github.com/spotify/backstage/blob/3b2aeae05a508f6253808ec118dafd2421362449/packages/cli/e2e-test/helpers.js#L104)

I can see that the `maxAttempts` is set to 240. And if there are any load errors in `visit()`, more attempts are made. 240 seems like too many number of attempts. Is that why you want to reduce it to 3?

> [check for content](https://github.com/spotify/backstage/blob/3b2aeae05a508f6253808ec118dafd2421362449/packages/cli/e2e-test/helpers.js#L121) on the page.

Do you mean to replace `browser.assert.evaluate` with [`browser.assert.text`](https://github.com/assaf/zombie#asserttextselection-expected-message) perhaps? Thank you!

**Comment by Rugvip** [comment]
@OrkoHunter The current retry loop with 240 tries is for waiting for the page to be ready. Basically a `yarn start` process is started, and then this loop waits for it to be ready to serve the page. Once the `visit()` call succeeds, the expected text has to be in the page, and that is where I think we should add some more retries.

So instead of `1: wait for page to be ready` -> `2: check if text is present`, where # 1 can try up to 240 times, and # 2 only once. We'd want to switch to `1: wait for page to be ready` -> `2: wait for text to be present`, where # 2 tries up to 3 times.

Then if you can get the `browser.assert.text` to work as well that's fine :grin:

**Comment by OrkoHunter** [comment]
Thank you for the detailed explanation @Rugvip ! ✨ I created #720.
