### ISSUE TITLE
[CI] Storybook build should fail if warnings are emitted

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#718]
## Feature Suggestion

Storybook warnings should fail on [this step](https://github.com/spotify/backstage/blob/1063279b4a2411f8fbda175793d4c30047fb231f/.github/workflows/frontend.yml#L66) in CI if there are warnings during the storybook build.  See #713 for an example of an error.

## Possible Implementation

Either there's support in the storybook CLI, or we might need to add something in the [webpack config](https://github.com/spotify/backstage/blob/1063279b4a2411f8fbda175793d4c30047fb231f/packages/storybook/.storybook/main.js#L14) when `process.env.CI` is set.

## Context

TS isolated modules needs treatment in storybook but not in the rollup build, causing issues like the one fixed by #713.

**Comment by OrkoHunter** [comment]
I created #721 for this. I do have a questio. Do we want to fail the CI on _all_ Storybook webpack build warnings?

Along with the TypeScript `type` export issue like #713, there are 3 other warnings we have to address.

1.
```
    AssetsOverSizeLimitWarning: asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets:
      vendors~main.3052b000bb004f483dbf.bundle.js (2.19 MiB)
        at /Users/himanshu/workspace/spotify/backstage/node_modules/@storybook/react/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:95:7
```

2.
```
    EntrypointsOverSizeLimitWarning: entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (2.39 MiB)
          runtime~main.3052b000bb004f483dbf.bundle.js
          vendors~main.3052b000bb004f483dbf.bundle.js
          main.3052b000bb004f483dbf.bundle.js

        at /Users/himanshu/workspace/spotify/backstage/node_modules/@storybook/react/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:100:7
```

3.
```
    NoAsyncChunksWarning: webpack performance recommendations:
    You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/
        at /Users/himanshu/workspace/spotify/backstage/node_modules/@storybook/react/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:113:21
```

Should we ignore these three warnings?

**Comment by OrkoHunter** [comment]
Let me go ahead and ignore `AssetsOverSizeLimitWarning`, `EntrypointsOverSizeLimitWarning` and `NoAsyncChunksWarning` for now in #721.
