### ISSUE TITLE
Load Scaffolder Templates from the Catalog API

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#725]
In the /create workflow (see below) available templates should be loaded from the server. Today they are statically assigned, and do not work.

![Screenshot 2020-05-06 at 08 03 32](https://user-images.githubusercontent.com/190856/81142490-1898d600-8f70-11ea-8a54-314d7c8fe590.png)

## Feature Suggestion

This should work in a similar way as demonstrated in this video: https://www.youtube.com/watch?v=U1iwe3L5pzc

**Comment by benjdlambert** [comment]
Consider how we can add these templates into the Service Catalog as `kind: 'Template'`?

Maybe calling the service catalog here could be a better solution rather than listing from the `scaffolder-backed`

**Comment by benjdlambert** [comment]
Now #1301 is merged, there will be mock templates that are poplulated into the Catalog.

Now we should be able to list these in a nice view.
