### ISSUE TITLE
[Templates] Add template for Spring Boot service

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#726]
## Feature Suggestion

It should be possible to scaffold a new **Spring Boot** backend service through Backstage.

![Screenshot 2020-05-06 at 08 09 17](https://user-images.githubusercontent.com/190856/81142839-f2276a80-8f70-11ea-8d13-f4e6c7a666f8.png)

## Possible Implementation

Add a new "template" and load it from the server.

## Context

Demo of this is available at https://www.youtube.com/watch?v=U1iwe3L5pzc

**Comment by benjdlambert** [comment]
Should this template be in the milestone @stefanalund?

**Comment by stefanalund** [comment]
@benjdlambert nah, not really needed I think. But since we are targeting micro service management as the first end-2-end use-case, it does still makes sense add a "service" template.

**Comment by stefanalund** [comment]
Done!
