### ISSUE TITLE
Import assets in the plugins/app

### ISSUE THREAD

**Issue by shmidt-i** [spotify/backstage#766]
If you want to import any assets, e.g. svg/png images, videos, etc, typescript will raise an error, such as: 
```
Cannot find module '../../assets/logo.png'. ts(2307)
```

Can be fixed by introducing ambient module declaration:

```
declare module '*.png'
```
in some `.d.ts` file and then add it through `tsconfig.json`.
But maybe there is a more general way of dealing with this.

Just to clarify, not a runtime issue, webpack that is bundling the app/plugin does its job just fine, it is only Typescript, who gives an error.

**Comment by Rugvip** [comment]
There's a declaration file already, but it doesn't seem to get picked up: https://github.com/spotify/backstage/blob/master/packages/cli/src/commands/plugin/assets.d.ts
