### ISSUE TITLE
inventory backend: register / unregister components

### ISSUE THREAD

**Issue by freben** [spotify/backstage#770]
Add the API endpoints to register and unregister references to component files in a version control system. This will be a completely separate set of endpoints, not related to the components etc.

Suggestion:
- `POST /locations` to add a new location
- `GET /locations` to list all locations
- `GET /locations/:id` to get a specific location by uuid
- `PUT /locations/:id` to change a specific location

Locations are stored in the database in a separate table.

POST request body:
```
{
  "type": "github",
  "spec": {
    "url": "https://github.com/org/repo/descriptor.yaml"
  }
}
```

PUT request body:
```
{
  "id": "944b5af2-01bc-4af6-b5c2-db7ef1a878d1",  // optional, but if present, must match existing
  "type": "github",
  "spec": {
    "url": "https://github.com/org/repo/descriptor.yaml"
  }
}
```

GET response body:
```
{
  "id": "944b5af2-01bc-4af6-b5c2-db7ef1a878d1",
  "type": "github",
  "spec": {
    "url": "https://github.com/org/repo/descriptor.yaml"
  },
  "status": {
    // references to actual things that are generated from this location (components etc)
    // current status of ability to refresh from the location
    // details of errors - could not read, could read but not parse, not permitted, ... etc
  }
}
```

**Comment by sharadpattanshetti** [comment]
Really interested for these APIs.
