### ISSUE TITLE
catalog frontend: component item page

### ISSUE THREAD

**Issue by freben** [spotify/backstage#774]
Implement the skeleton of a page that shows the basic data pertaining to a component with a given ID

**Comment by adaszyn** [comment]
I'll tackle that! 🚀

**Comment by stefanalund** [comment]
This page should include an "Unregister" button: https://github.com/spotify/backstage/issues/776

**Comment by stefanalund** [comment]
Fixed in https://github.com/spotify/backstage/pull/866
