### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#778]
Hello! Would appreciate if someone could update the logo in the side nav to our new logo! I've attached a ZIP of the SVG. Thank you!

[04 Icon_Teal.svg.zip](https://github.com/spotify/backstage/files/4600015/04.Icon_Teal.svg.zip)

**Comment by cheepo2109** [comment]
Hey @katz95!
Current UX expands whole word on hover.
So I should update only B part and then on expansion Logo stays same + "backstage"?
Should I update favicon too?
<img width="742" alt="CleanShot 2020-05-09 at 21 40 05@2x" src="https://user-images.githubusercontent.com/5988617/81478228-cb518880-923d-11ea-983c-28f876b152d4.png">

<img width="723" alt="CleanShot 2020-05-09 at 21 40 15@2x" src="https://user-images.githubusercontent.com/5988617/81478226-c8569800-923d-11ea-941f-eac443d60230.png">

**Comment by katz95** [comment]
Hi @cheepo2109! Thanks for responding, and great question! 🙏

When the side bar is minimized, it should just show the B part of the logo. When it's expanded, it should show the full logo, which I've attached to this comment. 😄 

And if you could update the favicon, that would be rad too! You can use the teal 'B' icon for the favicon when it's on dark tabs, and you can use the black 'B' icon (attached to this comment) for the favicon when it's on light tabs.

Thank you!


[03 Logo_Teal.svg.zip](https://github.com/spotify/backstage/files/4608208/03.Logo_Teal.svg.zip)

[06 Icon_Black.svg.zip](https://github.com/spotify/backstage/files/4608218/06.Icon_Black.svg.zip)

**Comment by katz95** [comment]
A reference example of what we were able to do with the favicon for the microsite! 🥳 

https://github.com/spotify/backstage-microsite/pull/163
