### ISSUE TITLE
RFC: Onboarding should be easy

### ISSUE THREAD

**Issue by dtuite** [spotify/backstage#782]
Simple, fast onboarding will help companies to uptake Backstage and get value from it quickly.

# The problem

Imagine an engineer or product manager in a company who really believes in Backstage and understands the value it could bring to their organization. They want to get their company using it but Backstage requires metadata to be embedded in the Git repos of the various services and data models which the company uses. This lone engineer or PM can fill out the metadata for their own services but they can't fill out the metadata for all of the services in their company, or even a significant subset of them.

This high-touch onboarding process makes Backstage difficult to adopt, even inside companies which can see the value of using it. I'm creating this GitHub issue to theorize about improvements.

# Potential solutions

Here are a few ideas to get started. This is more brainstorming than implementation level solutionizing.

 1. Develop an agent which can sit in a Kubernetes cluster (or other infrastructure - eg. attach to serverless workloads) and push metadata about the services running there to Backstage APIs (something [like this does](https://github.com/larderdev/kubewise) perhaps - Disclaimer: I wrote it).
 2. Develop tools which can automatically open pull requests against GitHub repos inside an organization to populate them with a (likely empty) metadata YAML file. The values would need to be filled out by the owners of the team but at least the initial structure would be there. Tools which can migrate existing metadata files which are in place for competing internal systems should also be considered.
 3. Make microservice sample applications which respond on an API endpoint with their metadata. Perhaps it would be possible to work with projects like micro/micro on this.
 4. ...??

## Context

The full power of Backstage is unlocked within an organization when there is a high level of data-completeness and correctness.

I am making a number of assumptions when opening this PR

 1. The desired metadata collection process involves ingesting metadata from git repos as described in #454 
 2. There is a desire for the ability to detect service metadata by connecting to an API on each service instance over the network (perhaps this is better left to service registries?)

**Comment by dtuite** [comment]
_Complete_ onboarding will likely never be a 5 minute job of course. Backstage just touches too many parts of the infra for that to be possible. 

That is ok. The point is to reduce the "time to wow" as much as possible for the person who is installing Backstage for the first time. You want them to be able to run a few commands then turn to the person beside them (assuming we are all COVID free and back in the office here!) and say "holy sh*t look at this". This will make it much easier for Backstage to spread virally within the company so that everyone starts using it.

**Comment by stefanalund** [comment]
Great topic. Adding on to it:

While meeting various companies interested in Backstage it is clear that many already have _some kind of_ inventory of their software (`yaml` files that are scraped and exposed through an API, databases, spreadsheets, etc).

For this category of customers it should be possible to keep their existing solution, and write a small "shim" that integrates their solution with an API that Backstage provides.

The same pattern is valid for the [Identify](https://github.com/spotify/backstage/milestone/12) service.

**Comment by mbruggmann** [comment]
To add one more thing to this: We can also rely on known APIs in combination with a little configuration to provide functionality out of the box. For example, I think it should eventually be possible to:

* Discover and index all services running in Kubernetes/Heroku/Lambda/...
* Get all builds from Tekton/CircleCI/Travis/Jenkins/...
* Query all databases, pub/sub topics, and other interesting resources from GCP/AWS/Azure...

This comes down a bit to how we model the catalog, and if you need a source code repository for a component/resource/api to exist or not.

**Comment by brunopereiraelven** [comment]
Hi there, coming from a managed services/consulting background I can affirm that most companies have messy Cloud accounts and a high enough employee turnover to make things hard in the beginning.

I believe that Cloud scanners + other background discovery tools that can help import things in a Service/Resource Catalog is very helpful. Without proper tagging and metadata, it can be difficult to know what to environments, applications/products and teams each resource belong.

Scanning things and registering stuff in the Service Catalog is a great first step and then asking for teams to review untagged resources makes it much easier during onboarding.

Regarding Cloud resources, a great way of doing that is using Cloud SDKs + some other tools helpful tools like [ScoutSuite](https://github.com/nccgroup/ScoutSuite).

**Comment by freben** [comment]
@brunopereiraelven Agreed. Internally at Spotify, we leverage Backstage to gently automatically poke at people about various kinds of misconfiguration, through information boxes and color choices etc. One such example is if the owner you have set for your component does not abide by certain business rules. We have found that this can be rather effective actually, in terms of engagement/outcome, without being actually disruptive. So if we could auto-mass-import, and then put relevant and actionable information about missing pieces in front of people that care, experience suggests that they will want to reconfigure their thing, and things will improve gradually at a steady pace.

**Comment by stefanalund** [comment]
What @aexvir and friends are doing might be interesting to look at https://github.com/kiwicom/the-zoo/pull/306

**Comment by dtuite** [comment]
I'll close this now because it's really old and can be superseeded by the more specific suggestion in https://github.com/spotify/backstage/issues/2801
