### ISSUE TITLE
[Plugin] Sentry

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#823]
## Summary

A plugin that shows the most important alerts from [Sentry](https://sentry.io/). 

## Project website (if applicable)

https://docs.sentry.io/

## Context

UX patterns can probably be reused from this CircleCI plugin: https://github.com/spotify/backstage/pull/748.

**Comment by adaszyn** [comment]
Hey @stefanalund, I'll try to tackle this 🙂
