### ISSUE TITLE
Want more customizability with themes

### ISSUE THREAD

**Issue by timurista** [spotify/backstage#828]
## Feature Suggestion

We want to be able to load custom material UI themes including custom fonts (Gotham etc.), and custom colors and title for backstage. 

Also, It'd be ideal if the header could be configured (using material App should be able to allow for the header to be swappable. We want to show custom colors and Roku name in the header.

## Possible Implementation

backstage/packages/theme/src/index.ts
There should be a way to load a theme for export like this;
```themes.ts
export rokuTheme from './rokuTheme';
```
allow for the theme to be selectable from a list. And settable to local storage.
```
import theme from 'themes'
const themeKeys = Object.keys(themes)
...
themeKeys.map(theme => <List>...onClick={theme => onSelectTheme(theme)}... />
onSelectTheme(theme => localStorage.set('theme', theme))
```
And update the ThemeContext function from:
```function toggleTheme() {```
to
```
function setTheme(themeName) {```
```

and allow for overrides of the default theme:
```
    default:
     const defaultTheme = localStorage.get('defaultTheme')
      if (!window.matchMedia) {
        backstageTheme = defaultTheme;
        break;
      }
      backstageTheme = defaultTheme;
```

## Context

We want to add Roku Branding including themes, styling, and colors to the backstage app without having to write custom css and components.

**Comment by Rugvip** [comment]
We've already designed for this with the theme package and type. It's possible to provide your own theme in the app, and you can use [createTheme](https://github.com/spotify/backstage/blob/e399a3f8d0e38973e98b7182c584839dbd13a81f/packages/theme/src/baseTheme.ts#L208) from the `@backstage/theme` package to create your own theme using a palette, or creating your completely custom theme by using the lower level functions.

The piece that's a bit wonky atm is the theme switcher in the app. Ideally that'd be an API or component in core that gets reused in the app, but right now the entire implementation is shipped with the example app.

If you scaffold your own app you'd replace the theme that is being imported [here](https://github.com/spotify/backstage/blob/e399a3f8d0e38973e98b7182c584839dbd13a81f/packages/cli/templates/default-app/packages/app/src/App.tsx#L3) with your own.

**Comment by timurista** [comment]
createTheme doesn't seem to let me use custom fonts... unless I am missing somehting.

**Comment by Rugvip** [comment]
Yep, but `createThemeOptions` and `createThemeOverrides` are exported, so you can use those to create your own theme with the same overrides.

**Comment by Rugvip** [comment]
Agreed! Going far back in the history of this project we experimented with some ideas of how common parts of a plugin page like the header could be replaced at the app level.

Some stuff here: https://github.com/spotify/backstage/blob/00f1d9d8e89dbe2f98f9756971ff0086946ed4d0/frontend/packages/core/src/components/DefaultEntityPage/DefaultEntityPage.tsx#L15
And here: https://github.com/spotify/backstage/blob/4d58971e2b5e604335bb9473c637eeccedcc08b1/frontend/packages/core/src/api/entityView/EntityPageBuilder.tsx#L8

We'll likely revisit that or something similar at some point, exactly for this kind of use-case.

**Comment by Rugvip** [comment]
Alright if I close this issue as I think the original question is resolved?

**Comment by timurista** [comment]
Yes, thanks. However, being able to use the switcher for multiple themes is something we would like.

**Comment by stefanalund** [comment]
@Rugvip I would suggest making this more clear in our docs before closing the issue.

**Comment by Rugvip** [comment]
Fix the the configurability issues in the app in https://github.com/spotify/backstage/pull/876
