### ISSUE TITLE
Remove nested card in Status component

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#830]
There's a nested card within the status component - if we could remove that so it's just one card, that would be rad! 🙏 

http://storybook.backstage.io/?path=/story/status--default

### Currently 
<img width="633" alt="Screenshot 2020-05-12 at 4 13 52 PM" src="https://user-images.githubusercontent.com/61153904/81703290-abec7280-946c-11ea-96b5-f81a336f611b.png">

### Ideally
<img width="479" alt="Screenshot 2020-05-12 at 4 21 24 PM" src="https://user-images.githubusercontent.com/61153904/81703285-aa22af00-946c-11ea-9503-2a44d6398c86.png">

**Comment by cheepo2109** [comment]
Done and Merged ✅

**Comment by stefanalund** [comment]
Closed via #832
