### ISSUE TITLE
[RFC] New Build Setup

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#834]
## Context

The current build setup ranges from pretty slow, for example bundling, to extremely slow, looking at ~1min core package builds. There's plenty of space for improvement, but it's been unclear exactly what build setups would be best, especially given that we want a setup that scales to much larger projects than this is right now.

To figure out the options for different parts of the builds setups and what tradeoffs we'd actually been making, I've been doing a bunch of benchmarks in this project: [Rugvip/ts-build-bench](https://github.com/Rugvip/ts-build-bench).

## Benchmarking Outcome

The benchmarking was divided into 3 major categories, VSCode performance, bundle/build speed, and type checking speed. For a more in-depth explanation, see the [ts-build-bench README](https://github.com/Rugvip/ts-build-bench/blob/master/README.md).

The outcome of the VSCode benchmarking was that there's not much to do, just point straight to src files for development.

The bundling benchmarks showed that even for a very large project, new transpilers like [esbuild](https://github.com/evanw/esbuild) and [sucrase](https://github.com/alangpierce/sucrase) provide enough performance that it's possible to transpile an entire project from TypeScript source files in one go, and still provide a good development experience. Transpilers like `ts-loader` and `babel-loader` are not really quick enough for a good development experience, babel being the one we use in our large internal project right now. If we have to use either of those it'd likely be best to keep the separate builds of each package that we have right now.

For building individual packages with rollup, esbuild and sucrase both provide a huge performance boost over what we're using right now. I also found that esbuild also produces code that is much quicker for webpack to process compared to sucrase.

The outcome of the type checking was that [TypeScript project references](https://www.typescriptlang.org/docs/handbook/project-references.html) can provide a big speedup for setups that require separate TypeScript configurations for each package. But, by far the quickest method, and the only reasonable one for a huge project, is to use a top-level tsconfig that lints the entire project, basically pointing to every `src/` directory of every package. The downside of this top-level approach is that declaration files end up in a separate directory and need to be moved to their respective packages before publishing.

## New Suggested Setup

Based on the outcome of the benchmarking and reading up on various tools, I'm suggesting the following changes:

1. Point all `types` fields in `package.json` to `src/index.ts`, published packages still point to `dist/index.d.ts`.
1. Switch `plugin:build` to use rollup with esbuild plugin, but only use build for publishing packages. Minify output as well, if it works. No need to support watch mode either.
1. Switch `plugin:serve` and `app:serve` to both use a common custom webpack config. Use sucrase-loader as it has react-hot-loader support, and have esbuild-loader as a fallback in case sucrase-loader doesn't work out. Use the same loader for both development and production.
1. Skip type-checking in all build steps, and rely on editors and `tsc` instead. Start using a single top-level tsconfig for linting, use incremental mode and an `outDir` that is cached in CI. Use [rollup-plugin-dts](https://www.npmjs.com/package/rollup-plugin-dts) or whatever other `.d.ts` bundling tool is good to build a single `.d.ts` file for each package. If they don't work well, just copy `.d.ts` files from the common output dir to each package before publishing.

## Reasoning

Some thoughs and constraints explaining the above choices:

1. We don't accept an average of 1-2 minutes of waiting to start up a dev server, if it's that slow we need to find other solutions.
1. Production builds should be relatively quick, no more than a few minutes including minification.
1. The build setup should support hundreds of plugins. This project will grow much larger, and we want to use the same setup for our internal version of Backstage as well.
1. We want to keep webpack because it has excellent bundle splitting strategies that keeps the initial page load very quick.
1. It is better to use the same transilers for development and production builds. I don't think we want to use for example sucrase for development but babel for production builds.
1. We're targetting modern and up-to-date browsers, so transpilation is mostly a matter of removing types and transforming JSX.
1. Users of backstage that want to target older browsers can set up a custom webpack build for that purpose.
1. The project is still in alpha so we can choose a build strategy and if it doesn't work out, switch.

**Comment by freben** [comment]
Will a single tsconfig and a top-level driven approach affect the setup where we mix frontend and backend packages in the same repo?

Will we need to make special cases for those that prefer to make plugins entirely in js instead of ts?

**Comment by Rugvip** [comment]
@freben overall the benchmarks are made to help guide decision, making it more clear what kind of performance tradeoffs we'd be making. So if a top-level config approach doesn't work, that's too bad and we have to go with something else :grin:

I think it should work though, as long as the config is kept the same. The impact is really that `compilerOptions` in package tsconfigs will be ignored for type checking. Using js should still be fine, and using different module output configurations should also be fine.
