### ISSUE TITLE
catalog backend: add more database tests

### ISSUE THREAD

**Issue by freben** [spotify/backstage#878]
There are [some tests](https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/src/database/Database.test.ts) for the Database class, but they should be more exhaustive. Include adding components, and test removal of locations that are in use by a component etc.

**Comment by Nek** [comment]
Parking it until new **big** changes to Database code from @freben

**Comment by freben** [comment]
This is too broad and the API is still in flux - closing, and then adding a new one if necessary once the API has stabilised
