### ISSUE TITLE
catalog backend: store location update results

### ISSUE THREAD

**Issue by freben** [spotify/backstage#883]
When the [location refresh loop](https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/src/database/DatabaseManager.ts#L33) runs, it just logs and throws away the results.

Make it so that

- Outcomes of the refresh is stored in the [database](https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/src/database/Database.ts), for every location, probably at least a timestamp and a `status` and a `message` or similar.

Outcomes should be instructive enough for a human to be able to read them and act upon them, e.g. status OK and message "DNS resolution failed, host example.com not found".

Outcomes can either be kept in a growing list so that you can see the refresh history, or just keep the last one for efficiency reasons.

Outcomes will be in a new table, with a foreign key to the location. We probably want to cascade delete outcomes when a location is deleted.

**Comment by adaszyn** [comment]
I'll take that 🙂
