### ISSUE TITLE
catalog backend: retrieve location update results

### ISSUE THREAD

**Issue by freben** [spotify/backstage#884]
Depends on #883 .

Callers of the [item catalog](https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/src/catalog/DatabaseItemsCatalog.ts) are not able to see the outcomes of recent [location refresh loop](https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/src/database/DatabaseManager.ts#L33) runs. 

Make it so that

- Outcomes become part of the response, per component, when querying the catalog. That way users can see the current status of each component.
- Outcomes become part of the response, per location, when querying the catalog.

Outcomes should be instructive enough for a human to be able to read them and act upon them, e.g. status OK and message "DNS resolution failed, host example.com not found, at timestamp X".

Outcomes can either be kept in a growing list so that you can see the refresh history, or just keep the last one for efficiency reasons.

It may be the case that when querying components you only see the last outcome, but when querying a location you see more. This is entirely optional, let's discuss.

To get the outcomes as part of the result, the [response model](https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/src/catalog/types.ts#L23) probably needs to either be extended with a field `status`, or an envelope added around the actual data, or similar.

**Comment by shmidt-i** [comment]
### Status of the entity
What is it as a concept? Should it be tied to the status of parsing/ingesting of the descriptor file, or should it be like a "Running" server/ "Deployed" docs etc?

### Stitching
Right now we discussing putting information about `location` (update result) into a `entity` response, which are technically two different types of resources, linked, but still different. 
If we have had `graphql` layer atm, I'd go for a field `updates` on the `location` response,
and `entity` would've had linked `location` and therefore access to all `updates` related to this particular `entity`. Question is - do we want to diverge from this in favor of stitching stuff in the place now (easier to consume by frontend) or keep them nice and separated, and make consumption easier later with the `graphql` or whatever we choose for BFF?

Both are open questions, would be glad to discuss it more broadly :)

**Comment by stefanalund** [comment]
> Status of the entity

Let’s skip this for now and remove it.

**Comment by shmidt-i** [comment]
I mean, `status` field was only one possible implementation and we still need to figure out a way forward with location update results

**Comment by shmidt-i** [comment]
Also, it can be a separate endpoints `/entity/:id/updates` & `/location/:id/updates` or even `/updates/location/:id` & `/updates/entity/:id`

**Comment by freben** [comment]
Or `/locations/:id` contains the current status (together with the location info itself), and `/locations/:id/history` goes back a bit.

I'm considering that the location refresh loop might perhaps insert a `backstage.io/managed-by-location: <location id>` annotation on entities it creates. Then the view could grab that and query the above endpoint to get statuses.

And that might also be how a future graphql endpoint could make the link.

**Comment by shmidt-i** [comment]
I like it, going to try it out tomorrow 👍
