### ISSUE TITLE
Pin sidebar

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#907]
## Feature Suggestion

Users should be able to "pin" the sidebar to into a statically expanded state: 

<img width="560" alt="Screenshot 2020-04-29 at 3 53 26 PM" src="https://user-images.githubusercontent.com/61153904/80604142-a1c08200-8a31-11ea-9f1f-0a6a9dc0646d.png">

Pressing it again should leave the sidebar in the default state; i.e. expanding on mouse hover and collapsing when the mouse leaves.

## Possible Implementation

Use local storage to keep user's preferences.

**Comment by adaszyn** [comment]
I'll take that! :)

**Comment by stefanalund** [comment]
Thanks @adaszyn -- ping @katz95 if you have any questions about the design aspects.

**Comment by stefanalund** [comment]
Closed in https://github.com/spotify/backstage/pull/928
