### ISSUE TITLE
Tabs (primary level navigation)

### ISSUE THREAD

**Issue by katz95** [spotify/backstage#922]
## 🗒 General

Hi! Would love if someone could help us build our primary level navigation, which comes in the form of tabs! ✨Please add this to our [Storybook](http://storybook.backstage.io/) as well.

![tabs](https://user-images.githubusercontent.com/61153904/82327275-6f75c500-99de-11ea-99e0-330d66a83981.gif)

## 💻 Usage

![Tabs](https://user-images.githubusercontent.com/61153904/82327390-9e8c3680-99de-11ea-8ed0-5c9115e8e7c3.png)

Horizontal tabs are the first level of navigation within a plugin or entity page on Backstage. First level navigation should be broader, and we recommend keeping the number of first level tabs to less than 8. However, if there are more tabs, we have designed a way for users to view additional tabs by clicking on the caret icon at the very right of the tab area.

We recommend that you follow the [usage](https://material.io/components/tabs#usage) and [interaction](https://material-ui.com/components/tabs/) guidelines for tabs that Material has listed.

## 📐 Specs
![Tabs Specs](https://user-images.githubusercontent.com/61153904/82327412-a77d0800-99de-11ea-9e0b-d5cadcbfdc31.png)

## 🔮 Future
We're currently brainstorming secondary and tertiary level navigation as well! We'll keep you all posted! 🎉

**Comment by Rugvip** [comment]
There's an existing component for horizontal scrolling that we should reuse: https://github.com/spotify/backstage/tree/master/packages/core/src/components/HorizontalScrollGrid

**Comment by shmidt-i** [comment]
I think actually this is exactly what is needed +- styling:
https://material-ui.com/components/tabs/#scrollable-tabs

**Comment by ayshiff** [comment]
Can I work on it ? 🚀

**Comment by stefanalund** [comment]
@ayshiff for sure! I've assigned you.

**Comment by shmidt-i** [comment]
Hey @ayshiff, just checking in to see if you need any help on this one?

**Comment by ayshiff** [comment]
Hey @shmidt-i ! Thank you, I'm almost done !
