### ISSUE TITLE
catalog backend: discuss/implement a pattern for handling transactions

### ISSUE THREAD

**Issue by adaszyn** [spotify/backstage#941]
With a growing catalog backend, we might consider providing a pattern for passing database transaction context to all methods interacting with a db. Ideally, each method could be executed inside or outside of a transaction.
An example where we might benefit from such pattern:

https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/src/database/DatabaseManager.ts#L88

```ts
// queries executed in the methods below should be executed in an transaction
try {
// ...
  await database.addOrUpdateComponent(dbc);
  await DatabaseManager.logUpdateSuccess(...);
} catch {}

// ...however, we might wanna execute:
await DatabaseManager.logUpdateSuccess(...);
// separately, outside of transaction

```

**Comment by freben** [comment]
Yes!

It could perhaps be as simple as

```
export class Database {
  transaction<T>((tx: TheKinexTxType) => Promise<T>);
  entities(tx: TheKinexTxType) { ... }
  otherThing(tx: TheKinexTxType) { ... }
  ...
}
```

**Comment by freben** [comment]
A pattern for this will emerge as part of #880

**Comment by stefanalund** [comment]
Is this ticket still relevant?

**Comment by freben** [comment]
We already have a lightweight version of this based on the last comment - let's close
