### ISSUE TITLE
[Plugin] Rollbar

### ISSUE THREAD

**Issue by andrewthauer** [spotify/backstage#970]
## Summary

A plugin that shows the most important alerts from [Rollbar](https://rollbar.com/).

## Project website (if applicable)

https://explorer.docs.rollbar.com/

## Context

UX patterns can probably be reused from this CircleCI plugin: #823.

**Comment by stefanalund** [comment]
Thanks for suggesting @andrewthauer. Are you planning on working on this plugin yourself or should I add a [help wanted] label?

**Comment by andrewthauer** [comment]
@stefanalund - I can take a stab at it. Although I might not get to it for a little while.

**Comment by andrewthauer** [comment]
This plugin was originally introduced in #1497 with subsequent follow up PR's. Future work will entail integration with the catalog model, etc.
