### ISSUE TITLE
Settle the MVP metadata model

### ISSUE THREAD

**Issue by freben** [spotify/backstage#983]
Before considering the catalog to be in a Minimum Lovable Product (MLP) state, we should settle on a sensible, well scoped, and useful set of metadata that users can start making use of immediately.

Regarding actual pieces of information, we can borrow some inspiration from the internal Backstage, and signals from users here on GitHub. Some candidates:

- [x] type - what possible values? - how do they affect the other fields?
- [ ] icon
- [x] description / tagline
- [ ] location / ghe - information about from whence it came
- [x] lifecycle - what possible values?
- [ ] system - and how to express entity references in general?
- [x] owner - and how does this interact with the identity effort?
- [ ] maintainers - if necessary? what would be the semantics here? do we have different types of "ownership"?
- [ ] scope or impact - e.g. whether it touches end users or is internal; whether it has financial impact or not etc
- [ ] kewords - for human-only search purposes
- [ ] tags - more strict actual classifying tags
- [ ] docs - somehow reference where to go for more information

Regarding how to store them, we need to make a judgment on where in the object model they fit best.

- in the spec
- in the metadata root
- in metadata.labels, with backstage.io namespace prefix
- in metadata.labels, without namespace prefix
- in metadata.annotations, with backstage.io namespace prefix
- in metadata.annotations, without namespace prefix

**Comment by stefanalund** [comment]
@freben we decided to skip the `tags` and `keywords` for now. As such, should we close this ticket track the remaining work somewhere else?
