### ISSUE TITLE
Implement backend fetching for component item overview page

### ISSUE THREAD

**Issue by freben** [spotify/backstage#984]
Keep the design as is, but do the fetching from an actual backend instance.

**Comment by Nek** [comment]
The frontend makes assumption that some data is available but only "name" and "description" are specced. Only "name" is required by spec.
No front-end oriented "Component" spec/types.
No "remove entity" logic.

Todo:
- unregister component (remove entity?)
- get and visualize all the extra data
- subscription to update?

**Comment by Nek** [comment]
Semantics between front-end <--> backend.
