### ISSUE TITLE
Register component integration with backend

### ISSUE THREAD

**Issue by shmidt-i** [spotify/backstage#986]
Inside the entity list view there is a button allowing you to register entity, but for now it's not connected to the backend. Also, unregister functionality isn't there. This ticket is to add both and connect it with the backend.

**Comment by stefanalund** [comment]
I think it makes sense to add a Register button on the Create page:

![Screenshot 2020-05-25 at 13 39 17](https://user-images.githubusercontent.com/190856/82809802-3b424e80-9e8d-11ea-8a17-e6875b5731e4.png)

**Comment by shmidt-i** [comment]
Show the result of registration: error/success. If success - list of registered components with links to their detailed views, if error - keep the error message informative but simple. Need adjustment in the backend, since we don't do addEntity synchronously hence not returning any info about registered entities.

**Comment by stefanalund** [comment]
@nikek @katz95 I think there is an opportunity to create a list of "successful steps" that have been executed. We could reuse that for this plugin: https://github.com/spotify/backstage/pull/1068#issuecomment-635793614
