### ISSUE TITLE
Render correct data from backend

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#987]
![image](https://user-images.githubusercontent.com/190856/82800194-8f443780-9e7b-11ea-857f-7703be1db72d.png)

**Comment by BA1RY** [comment]
@stefanalund I'd like to work on this.

**Comment by stefanalund** [comment]
@BA1RY awesome, assigning you. Please note that the backend is still in development so there might be a bit of a bumpy ride (ping @freben)

**Comment by BA1RY** [comment]
Thank you @stefanalund. I see that we are consuming data for catalog from `mock-factory-data.json`. Do I need to add temporary data to the json file for developing the frontend as the backend is still in development?

**Comment by freben** [comment]
Hey!

The backend just gained a `/catalog/entities` endpoint. If you can make the frontend view start out fetching from `http://localhost:7000/catalog/entities` and displaying their `metadata.name` property in the list, then that's a good start.

After starting the backend, it has no entities in it. What you do, is that you can add so called locations to it. They are then periodically refreshed. To add a location, do something like `curl -H "Content-Type: application/json" -d '{"type":"file","target":"/some/path"}' http://localhost:7000/catalog/locations`. Typed out on a phone, so I hope I got that right :) Replace the path with the absolute path of [one of the files here](https://github.com/spotify/backstage/tree/master/plugins/catalog-backend/fixtures) in your local repo. After Less than 10 seconds the entities endpoint should start returning the contents of that file.

Like alund said, this may be a bit bumpy since things are a bit raw the following couple days as the interfaces mature, but don't hesitate to ask if things are unclear. I left for the day now but I'll keep an eye out and will try to lay some more groundwork tomorrow for this if you're blocked.

**Comment by freben** [comment]
Oh to make `yarn start` work in `packages/backend`, you currently have to give it three env variables on the command line. I don't have them at hand right now, sorry about that. If you figure them out (just give them dummy values), great. Otherwise I'll make sure to help make this easier tomorrow.

**Comment by BA1RY** [comment]
Thank you @freben . I really appreciate it. Could you please provide more details on how to make `yarn start` work? I wasn't able to figure out the environment variables.

**Comment by BA1RY** [comment]
@freben Just to clarify, backend data is being served over GraphQL and queries need to be made accordingly. Please correct me if I'm wrong.

**Comment by freben** [comment]
Not yet. The GraphQL aggregator will not be made until a bit later, when the underlying features are stabilized.

I made a [pull request](https://github.com/spotify/backstage/pull/1007) for updating the backend README to reflect the current reality.

**Comment by BA1RY** [comment]
@stefanalund I have a question. Do you want me to get data from backend for `catalog` like how it's been implemented in `sentry` or should I make changes to existing `mock-factory.ts` file to make fetch requests to backend?

**Comment by stefanalund** [comment]
@BA1RY I think @freben is better positioned to answer whether it is worth mocking the data for now or actually call out to the catalog-backend.

**Comment by BA1RY** [comment]
@stefanalund Understood.
@freben I have a few queries.
1. Like you instructed, I was able to get the backend running. Each api response item is in this format.
`{
    "apiVersion": "backstage.io/v1beta1",
    "kind": "Component",
    "metadata": {
      "uid": "aafab2c1-b35a-4150-8104-245dd711d9ef",
      "etag": "ZjlhMzQ2OWUtM2ZjNy00ZDUyLTg2YzctODFjOGYyNjE1YTBj",
      "generation": 1,
      "name": "component1"
    },
    "spec": {
      "type": "service"
    }
  }
` 
Which of the above data do we need to extract and store in frontend (Example: name, uid) and in what format?

2. Do you want me to get data from backend for `catalog` like how it's been implemented in `sentry` or should I make changes to existing `mock-factory.ts` file to make fetch requests to backend?

3. There are three functions `getAllComponents(), getComponentByName(name: string), removeComponentByName(name: string)` in `ComponentFactory` interface inside
 `data/component.ts`. How do you want me to handle the last two functions? I'm confused about this.

**Comment by freben** [comment]
Yeah feel free to mirror sentry for now with the API_HOST env as a basis. We are about to settle how we want to handle config being passed to plugins later in this milestone, but that's not done yet.

For some basics about the entity format, see the type declarations [here](https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/src/ingestion/types.ts), and some context [here](https://github.com/spotify/backstage/issues/767).

We haven't fleshed out all the fields yet, but you have at least `kind` and `metadata.name` that you want for the views.

Don't worry about the existing ComponentFactory stuff, it should be thrown away. Just having the word "Component" in there is misleading. The overarching term is "entity". The catalog contains entities. Some of those entities are of the `kind` "Component".

Make some new API to replace it, maybe named `CatalogApi`. We will want to make that a core API later, but you may skip that step for now. It would probably have a method `entities` and a method `entity`.

The first can take some optional filters. If you like, you can skip that step for the first PR.

The second needs three parameters, all strings: `kind`, `name`, and `namespace`. The first two may be for example "Component" and "my-component-1". The last one will always be the string "default" currently.

These will end up reaching [these backend endpoints](https://github.com/spotify/backstage/blob/master/plugins/catalog-backend/src/service/router.ts#L43).

**Comment by benjdlambert** [comment]
Hey @BA1RY,

After a chat internally this morning, @spotify/backstage-core will take ownership of this feature.
It's part of the release we're working on right now, but please feel free to pick up something else!

Thanks for your help!

**Comment by BA1RY** [comment]
Sure @benjdlambert :smiley:

**Comment by benjdlambert** [comment]
This issue overlaps a lot with implementation from #978 

Will postpone a some of this work like hooking up the filters until PR's #1043 and #1047 get merged.

**Comment by soapraj** [comment]
Closing this as remaining work is in #990
