### ISSUE TITLE
catalog switcher

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#988]
This should probably be a reusable component (it exists in Backstage internal):

![image](https://user-images.githubusercontent.com/190856/82800308-c6b2e400-9e7b-11ea-81c3-3ea6d8c56cc4.png)

**Comment by benjdlambert** [comment]
I will make #1000 close this issue, and then we can maybe create another ticket similar to #984 which is to implement the backend fetching of all these items and what the relative queries should be to the entities search service in #772. 

Does that make sense @alund?
