### ISSUE TITLE
Add subtitle support to Table

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#991]
Current Table component only supports a `title`. Add support for subtitle:

![image](https://user-images.githubusercontent.com/190856/82801083-05956980-9e7d-11ea-8e26-134fab76af79.png)

This should include a Storybook entry.

**Comment by ayshiff** [comment]
I would like to work on it 👍

**Comment by stefanalund** [comment]
@ayshiff thanks! I have Assigned you.
