### ISSUE TITLE
Page title not correct in /create

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#996]
## Expected Behavior

Should reflect current title.

## Current Behavior

Includes [object Object] stringification. 

![Screenshot 2020-05-25 at 14 15 35](https://user-images.githubusercontent.com/190856/82811960-3e8c0900-9e92-11ea-8528-8faab3b343d3.png)

## Steps to Reproduce

Go to /create

## Context

This most likely have to do with Helmet not being configured correctly.

**Comment by govindgoel** [comment]
@stefanalund  I would like to work on this.

**Comment by stefanalund** [comment]
Thanks @govindgoel -- you are Assigned now!

**Comment by govindgoel** [comment]
@stefanalund  This issue is happening due to the use of <Lifecycle alpha shorthand /> to display the alpha image after the title text.

**Comment by govindgoel** [comment]
@stefanalund This issue is due to the Lifecycle component ```<Lifecycle alpha shorthand />```  as the Page Title is unable to parse it.

**Comment by stefanalund** [comment]
@govindgoel thanks, that's interesting. Do you know if this can be fixed without removing the Alpha label?

**Comment by shmidt-i** [comment]
Something like this should do:
https://github.com/spotify/backstage/blob/88561490d41fce5fabaa596359bfb443c4a82f4d/plugins/circleci/src/components/Layout/Layout.tsx#L24

**Comment by govindgoel** [comment]
Thanks for the suggestion @shmidt-i
